# TinyDisasterVQA — minimal teacher ablation notebook

This notebook does only what we need for the new T1–T6 teacher ablation:

1. mount Drive and pull the GitHub repo,
2. unpack FloodNet-VQA,
3. run preprocessing for cap5 and cap10,
4. run sanity tests, including `03_test_teacher_ablation.py`,
5. only after that, run full T1–T6 teacher training.

Run cells top to bottom until the smoke tests pass. Then run the full training cell.

In [ ]:
from google.colab import drive, userdata
from pathlib import Path
import os
import subprocess

drive.mount("/content/drive")

# Edit these only if needed.
GITHUB_REPO = "jacobinsilico/TinyDisasterVQA"
BRANCH = "submission"
REPO_DIR = Path("/content/TinyDisasterVQA")

try:
    GITHUB_TOKEN = userdata.get("GITHUB_TOKEN")
except Exception:
    GITHUB_TOKEN = None

if GITHUB_TOKEN:
    CLONE_URL = f"https://x-access-token:{GITHUB_TOKEN}@github.com/{GITHUB_REPO}.git"
else:
    CLONE_URL = f"https://github.com/{GITHUB_REPO}.git"

print("Repo:", GITHUB_REPO)
print("Branch:", BRANCH)
print("Repo dir:", REPO_DIR)
print("Token available:", bool(GITHUB_TOKEN))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Repo: jacobinsilico/TinyDisasterVQA
Branch: submission
Repo dir: /content/TinyDisasterVQA
Token available: True

In [ ]:
if REPO_DIR.exists():
    print("Repo already exists. Fetching and pulling...")
    subprocess.run(["git", "-C", str(REPO_DIR), "fetch", "origin"], check=True)
    subprocess.run(["git", "-C", str(REPO_DIR), "checkout", BRANCH], check=True)
    subprocess.run(["git", "-C", str(REPO_DIR), "pull", "origin", BRANCH], check=True)
else:
    print("Cloning repo...")
    subprocess.run(["git", "clone", "--branch", BRANCH, CLONE_URL, str(REPO_DIR)], check=True)

os.environ["PYTHONPATH"] = f"{REPO_DIR / 'src'}:" + os.environ.get("PYTHONPATH", "")

print()
subprocess.run(["git", "-C", str(REPO_DIR), "status", "--short"], check=True)
subprocess.run(["git", "-C", str(REPO_DIR), "rev-parse", "--abbrev-ref", "HEAD"], check=True)
subprocess.run(["git", "-C", str(REPO_DIR), "log", "-1", "--oneline"], check=True)
print("PYTHONPATH =", os.environ["PYTHONPATH"])

Cloning repo...

PYTHONPATH = /content/TinyDisasterVQA/src:/env/python

In [ ]:
%cd /content/TinyDisasterVQA
!nvidia-smi
!python --version
!pip install -q pandas pillow tqdm matplotlib torch torchvision

/content/TinyDisasterVQA
Tue Jun  9 20:28:23 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   53C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
Python 3.12.13

## Dataset setup

This expects the archive used in the previous notebook:

```text
/content/drive/MyDrive/floodnet-data.tar
```

After extraction, the repo should contain:

```text
dataset/data/
dataset/images/
```

In [ ]:
%%bash
set -e

cd /content/TinyDisasterVQA

rm -rf dataset
mkdir -p dataset

tar -xf /content/drive/MyDrive/floodnet-data.tar -C dataset

# Normalize old archive layout if it extracts as dataset/floodnet-data/{data,images}.
if [ -d dataset/floodnet-data ]; then
  rm -rf dataset/data dataset/images
  mv dataset/floodnet-data/data dataset/
  mv dataset/floodnet-data/images dataset/
  rm -rf dataset/floodnet-data
fi

echo "Dataset directories:"
find dataset -maxdepth 3 -type d | sort

test -f dataset/data/train_annotations.json
test -f dataset/data/valid_annotations.json
test -f dataset/data/test_annotations.json
test -d dataset/images/train_images
test -d dataset/images/valid_images
test -d dataset/images/test_images

echo "Dataset setup OK."

Dataset directories:
dataset
dataset/data
dataset/images
dataset/images/test_images
dataset/images/train_images
dataset/images/valid_images
Dataset setup OK.

## Preprocess cap5 and cap10

This regenerates the clean T1–T6 inputs:

- `outputs/training_data_cap5`
- `outputs/training_data_cap10`
- `outputs/answer_space_cap5`
- `outputs/answer_space_cap10`

In [ ]:
%%bash
set -e

cd /content/TinyDisasterVQA
export PYTHONPATH=/content/TinyDisasterVQA/src:$PYTHONPATH

python scripts/01_explore_dataset.py --dataset-root dataset --count-cap 5  --output-dir outputs/exploration_cap5
python scripts/01_explore_dataset.py --dataset-root dataset --count-cap 10 --output-dir outputs/exploration_cap10

python scripts/02_build_manifest.py --dataset-root dataset --count-cap 5 --output-dir outputs/processed_cap5
python scripts/03_build_answer_space.py --manifest outputs/processed_cap5/floodnet_manifest.csv --output-dir outputs/answer_space_cap5
python scripts/04_prepare_training_data.py \
  --manifest outputs/processed_cap5/floodnet_manifest.csv \
  --word-to-token outputs/processed_cap5/word_to_token.json \
  --answer-space outputs/answer_space_cap5/answer_space.json \
  --dataset-root dataset \
  --output-dir outputs/training_data_cap5

python scripts/02_build_manifest.py --dataset-root dataset --count-cap 10 --output-dir outputs/processed_cap10
python scripts/03_build_answer_space.py --manifest outputs/processed_cap10/floodnet_manifest.csv --output-dir outputs/answer_space_cap10
python scripts/04_prepare_training_data.py \
  --manifest outputs/processed_cap10/floodnet_manifest.csv \
  --word-to-token outputs/processed_cap10/word_to_token.json \
  --answer-space outputs/answer_space_cap10/answer_space.json \
  --dataset-root dataset \
  --output-dir outputs/training_data_cap10

================================================================================
TinyDisasterVQA / FloodNet-VQA Dataset Exploration
================================================================================
Dataset root: /content/TinyDisasterVQA/dataset
Output dir:   /content/TinyDisasterVQA/outputs/exploration_cap5
Count cap:    5+

TinyDisasterVQA / FloodNet-VQA Dataset Exploration
================================================================================
Dataset root: /content/TinyDisasterVQA/dataset
Total QA samples: 9537
Total unique images: 2188
Total unique question templates: 31
Total unique question types: 7
Total unique answers: 49
Question vocabulary size from word_to_token.json: 49
Answer class count from class_to_label.json: 51

Split stats:
split  num_qa_samples  num_unique_images  num_unique_questions  num_unique_question_types  num_unique_answers  num_missing_images
 test            1833                411                    31                          7                  36                   0
train            5898               1364                    31                          7                  43                   0
valid            1806                413                    31                          7                  39                   0

Question type counts:
                     question_type  count  percentage
        Road_Condition_Recognition   2578   27.031561
Entire_Image_Condition_Recognition   2188   22.942225
                  Complex_Counting   1015   10.642760
                Density_Estimation    939    9.845863
    Building_Condition_Recognition    939    9.845863
                   Risk_Assessment    939    9.845863
                   Simple_Counting    939    9.845863

Top 20 answers:
answer_norm  count  percentage
         no   2239   23.476984
        yes   2029   21.275034
non flooded   2028   21.264549
       high    363    3.806228
          1    335    3.512635
    flooded    330    3.460208
          3    324    3.397295
   moderate    292    3.061759
          4    290    3.040789
        low    284    2.977876
          2    271    2.841564
          5    138    1.446996
          6    105    1.100975
          7     62    0.650100
          8     40    0.419419
         16     39    0.408934
         13     35    0.366992
         14     30    0.314564
         17     24    0.251651
         11     24    0.251651

Counting summary:
Counting QA samples: 1954
Counting labels unseen in valid vs train: ['26', '32', '38', '39', '40']
Counting labels unseen in test vs train: ['26', '39', '51']

Image split overlap:
split_a split_b  num_overlapping_images example_overlapping_images
  train   valid                       0
  train    test                       0
  valid    test                       0

Missing images:
Total missing image references: 0

Majority baselines:
                         baseline  valid_accuracy  test_accuracy
  global_majority_train_answer=no        0.248062       0.231315
majority_answer_per_question_type        0.404208       0.405892


Done. Wrote exploration outputs to: outputs/exploration_cap5
================================================================================
TinyDisasterVQA / FloodNet-VQA Dataset Exploration
================================================================================
Dataset root: /content/TinyDisasterVQA/dataset
Output dir:   /content/TinyDisasterVQA/outputs/exploration_cap10
Count cap:    10+

TinyDisasterVQA / FloodNet-VQA Dataset Exploration
================================================================================
Dataset root: /content/TinyDisasterVQA/dataset
Total QA samples: 9537
Total unique images: 2188
Total unique question templates: 31
Total unique question types: 7
Total unique answers: 49
Question vocabulary size from word_to_token.json: 49
Answer class count from class_to_label.json: 51

Split stats:
split  num_qa_samples  num_unique_images  num_unique_questions  num_unique_question_types  num_unique_answers  num_missing_images
 test            1833                411                    31                          7                  36                   0
train            5898               1364                    31                          7                  43                   0
valid            1806                413                    31                          7                  39                   0

Question type counts:
                     question_type  count  percentage
        Road_Condition_Recognition   2578   27.031561
Entire_Image_Condition_Recognition   2188   22.942225
                  Complex_Counting   1015   10.642760
                Density_Estimation    939    9.845863
    Building_Condition_Recognition    939    9.845863
                   Risk_Assessment    939    9.845863
                   Simple_Counting    939    9.845863

Top 20 answers:
answer_norm  count  percentage
         no   2239   23.476984
        yes   2029   21.275034
non flooded   2028   21.264549
       high    363    3.806228
          1    335    3.512635
    flooded    330    3.460208
          3    324    3.397295
   moderate    292    3.061759
          4    290    3.040789
        low    284    2.977876
          2    271    2.841564
          5    138    1.446996
          6    105    1.100975
          7     62    0.650100
          8     40    0.419419
         16     39    0.408934
         13     35    0.366992
         14     30    0.314564
         17     24    0.251651
         11     24    0.251651

Counting summary:
Counting QA samples: 1954
Counting labels unseen in valid vs train: ['26', '32', '38', '39', '40']
Counting labels unseen in test vs train: ['26', '39', '51']

Image split overlap:
split_a split_b  num_overlapping_images example_overlapping_images
  train   valid                       0
  train    test                       0
  valid    test                       0

Missing images:
Total missing image references: 0

Majority baselines:
                         baseline  valid_accuracy  test_accuracy
  global_majority_train_answer=no        0.248062       0.231315
majority_answer_per_question_type        0.404208       0.405892


Done. Wrote exploration outputs to: outputs/exploration_cap10
================================================================================
TinyDisasterVQA / Build FloodNet Manifest
================================================================================
Dataset root: /content/TinyDisasterVQA/dataset
Output dir:   /content/TinyDisasterVQA/outputs/processed_cap5
Count cap:    5+

TinyDisasterVQA / FloodNet Manifest Summary
================================================================================
Dataset root: /content/TinyDisasterVQA/dataset
Manifest CSV: outputs/processed_cap5/floodnet_manifest.csv
Manifest JSONL: outputs/processed_cap5/floodnet_manifest.jsonl

Task formulation:
  single_head_edge_global
  count_cap: 5+
  edge_global_classes: 14

Total samples: 9537
Unique images: 2188
Question templates: 31
Original answer classes used in data: 49
Original answer classes in class_to_label.json: 51

Split stats:
split  num_samples  num_images  num_question_templates  num_original_answers  num_edge_classes
 test         1833         411                      31                    36                14
train         5898        1364                      31                    43                14
valid         1806         413                      31                    39                14

Edge heads:
split edge_head  count
 test    binary    820
 test condition    447
 test     count    383
 test   density    183
train    binary   2634
train condition   1480
train     count   1204
train   density    580
valid    binary    814
valid condition    449
valid     count    367
valid   density    176

Edge class counts:
split            edge_class  edge_global_label  count
 test             binary:no                  0    424
 test            binary:yes                  1    396
 test     condition:flooded                  2     65
 test       condition:mixed                  3      6
 test condition:non_flooded                  4    376
 test           density:low                  5     61
 test      density:moderate                  6     45
 test          density:high                  7     77
 test               count:1                  8     75
 test               count:2                  9     55
 test               count:3                 10     53
 test               count:4                 11     44
 test               count:5                 12     31
 test              count:5+                 13    125
train             binary:no                  0   1367
train            binary:yes                  1   1267
train     condition:flooded                  2    201
train       condition:mixed                  3      6
train condition:non_flooded                  4   1273
train           density:low                  5    165
train      density:moderate                  6    195
train          density:high                  7    220
train               count:1                  8    184
train               count:2                  9    165
train               count:3                 10    220
train               count:4                 11    190
train               count:5                 12     82
train              count:5+                 13    363
valid             binary:no                  0    448
valid            binary:yes                  1    366
valid     condition:flooded                  2     64
valid       condition:mixed                  3      6
valid condition:non_flooded                  4    379
valid           density:low                  5     58
valid      density:moderate                  6     52
valid          density:high                  7     66
valid               count:1                  8     76
valid               count:2                  9     51
valid               count:3                 10     51
valid               count:4                 11     56
valid               count:5                 12     25
valid              count:5+                 13    108

Head label maps:
{
  "binary": {
    "no": 0,
    "yes": 1
  },
  "condition": {
    "flooded": 0,
    "mixed": 1,
    "non_flooded": 2
  },
  "count": {
    "1": 0,
    "2": 1,
    "3": 2,
    "4": 3,
    "5": 4,
    "5+": 5
  },
  "density": {
    "high": 2,
    "low": 0,
    "moderate": 1
  }
}

Edge class to label:
{
  "binary:no": 0,
  "binary:yes": 1,
  "condition:flooded": 2,
  "condition:mixed": 3,
  "condition:non_flooded": 4,
  "count:1": 8,
  "count:2": 9,
  "count:3": 10,
  "count:4": 11,
  "count:5": 12,
  "count:5+": 13,
  "density:high": 7,
  "density:low": 5,
  "density:moderate": 6
}

Original labels unseen in valid compared to train:
['26', '32', '38', '39', '40']

Original labels unseen in test compared to train:
['26', '39', '51']

Edge classes unseen in valid compared to train:
[]

Edge classes unseen in test compared to train:
[]

Count capped counts:
split edge_answer  edge_global_label  count
 test           1                  8     75
 test           2                  9     55
 test           3                 10     53
 test           4                 11     44
 test           5                 12     31
 test          5+                 13    125
train           1                  8    184
train           2                  9    165
train           3                 10    220
train           4                 11    190
train           5                 12     82
train          5+                 13    363
valid           1                  8     76
valid           2                  9     51
valid           3                 10     51
valid           4                 11     56
valid           5                 12     25
valid          5+                 13    108

Done. Wrote manifest outputs to: outputs/processed_cap5
================================================================================
TinyDisasterVQA / Build Answer Space
================================================================================
Manifest:   /content/TinyDisasterVQA/outputs/processed_cap5/floodnet_manifest.csv
Output dir: /content/TinyDisasterVQA/outputs/answer_space_cap5
Weights:    inverse_sqrt

TinyDisasterVQA / Answer Space Summary
================================================================================
Manifest: outputs/processed_cap5/floodnet_manifest.csv
Total samples: 9537

Task formulation:
  single_head_edge_global
  count_cap: 5+
  edge_global_classes: 14

Original global answer space:
  Classes used in manifest: 49
  Valid unseen answers vs train: ['26', '32', '38', '39', '40']
  Test unseen answers vs train:  ['26', '39', '51']

Edge global answer space:
  Classes: 14
  Valid unseen classes vs train: []
  Test unseen classes vs train:  []

Edge global classes:
  00: binary:no                 train_count=1367  weight=0.3070
  01: binary:yes                train_count=1267  weight=0.3189
  02: condition:flooded         train_count=201   weight=0.8007
  03: condition:mixed           train_count=6     weight=4.6343
  04: condition:non_flooded     train_count=1273  weight=0.3182
  05: density:low               train_count=165   weight=0.8837
  06: density:moderate          train_count=195   weight=0.8129
  07: density:high              train_count=220   weight=0.7653
  08: count:1                   train_count=184   weight=0.8369
  09: count:2                   train_count=165   weight=0.8837
  10: count:3                   train_count=220   weight=0.7653
  11: count:4                   train_count=190   weight=0.8235
  12: count:5                   train_count=82    weight=1.2536
  13: count:5+                  train_count=363   weight=0.5958

Edge heads:
  binary       train_count=2634
  condition    train_count=1480
  count        train_count=1204
  density      train_count=580

Local labels by edge head:
  binary: 2 classes
    00: no           train_count=1367
    01: yes          train_count=1267
  condition: 3 classes
    00: flooded      train_count=201
    01: mixed        train_count=6
    02: non_flooded  train_count=1273
  density: 3 classes
    00: low          train_count=165
    01: moderate     train_count=195
    02: high         train_count=220
  count: 6 classes
    00: 1            train_count=184
    01: 2            train_count=165
    02: 3            train_count=220
    03: 4            train_count=190
    04: 5            train_count=82
    05: 5+           train_count=363

Recommended:
  Use edge_global as the main teacher/student/deployment target.
  Use class_weights_edge_global_by_label.json for weighted CE ablation.
  Use edge_head/target_edge_head only for diagnostics or count auxiliary loss.

Done. Wrote answer-space outputs to: outputs/answer_space_cap5
================================================================================
TinyDisasterVQA / Prepare Training Data
================================================================================
Manifest:         /content/TinyDisasterVQA/outputs/processed_cap5/floodnet_manifest.csv
Word-to-token:    /content/TinyDisasterVQA/outputs/processed_cap5/word_to_token.json
Answer space:     /content/TinyDisasterVQA/outputs/answer_space_cap5/answer_space.json
Dataset root:     /content/TinyDisasterVQA/dataset
Output dir:       /content/TinyDisasterVQA/outputs/training_data_cap5
Max question len: 11

TinyDisasterVQA / Training Data Summary
================================================================================
Task formulation:
  target_formulation: single_head_edge_global
  main target: target_edge_global
  count_cap: 5+
  num_edge_global_classes: 14

Total samples: 9537
Train samples: 5898
Valid samples: 1806
Test samples:  1833

Question templates: 31
Vocabulary size with PAD=0: 50
UNK id: 1
PAD id: 0
Max observed question length: 11
Fixed max question length: 11
Questions longer than max length: 0
OOV token count: 0

Head distribution:
split edge_head  count
 test    binary    820
 test condition    447
 test     count    383
 test   density    183
train    binary   2634
train condition   1480
train     count   1204
train   density    580
valid    binary    814
valid condition    449
valid     count    367
valid   density    176

Target counts:
split            edge_class  target_edge_global  count
 test             binary:no                   0    424
 test            binary:yes                   1    396
 test     condition:flooded                   2     65
 test       condition:mixed                   3      6
 test condition:non_flooded                   4    376
 test           density:low                   5     61
 test      density:moderate                   6     45
 test          density:high                   7     77
 test               count:1                   8     75
 test               count:2                   9     55
 test               count:3                  10     53
 test               count:4                  11     44
 test               count:5                  12     31
 test              count:5+                  13    125
train             binary:no                   0   1367
train            binary:yes                   1   1267
train     condition:flooded                   2    201
train       condition:mixed                   3      6
train condition:non_flooded                   4   1273
train           density:low                   5    165
train      density:moderate                   6    195
train          density:high                   7    220
train               count:1                   8    184
train               count:2                   9    165
train               count:3                  10    220
train               count:4                  11    190
train               count:5                  12     82
train              count:5+                  13    363
valid             binary:no                   0    448
valid            binary:yes                   1    366
valid     condition:flooded                   2     64
valid       condition:mixed                   3      6
valid condition:non_flooded                   4    379
valid           density:low                   5     58
valid      density:moderate                   6     52
valid          density:high                   7     66
valid               count:1                   8     76
valid               count:2                   9     51
valid               count:3                  10     51
valid               count:4                  11     56
valid               count:5                  12     25
valid              count:5+                  13    108

Outputs:
  outputs/training_data_cap5/train.csv
  outputs/training_data_cap5/valid.csv
  outputs/training_data_cap5/test.csv
  outputs/training_data_cap5/metadata.json
  outputs/training_data_cap5/target_counts.csv
  outputs/training_data_cap5/head_distribution.csv
  outputs/training_data_cap5/question_template_distribution.csv

Done. Wrote training data to: outputs/training_data_cap5
================================================================================
TinyDisasterVQA / Build FloodNet Manifest
================================================================================
Dataset root: /content/TinyDisasterVQA/dataset
Output dir:   /content/TinyDisasterVQA/outputs/processed_cap10
Count cap:    10+

TinyDisasterVQA / FloodNet Manifest Summary
================================================================================
Dataset root: /content/TinyDisasterVQA/dataset
Manifest CSV: outputs/processed_cap10/floodnet_manifest.csv
Manifest JSONL: outputs/processed_cap10/floodnet_manifest.jsonl

Task formulation:
  single_head_edge_global
  count_cap: 10+
  edge_global_classes: 19

Total samples: 9537
Unique images: 2188
Question templates: 31
Original answer classes used in data: 49

## Sanity tests

Run these before any full teacher training.

In [ ]:
%%bash
set -e

cd /content/TinyDisasterVQA
export PYTHONPATH=/content/TinyDisasterVQA/src:$PYTHONPATH

python testing/01_test_dataloader.py --data-dir outputs/training_data_cap5
python testing/01_test_dataloader.py --data-dir outputs/training_data_cap10

python testing/02_test_teacher_forward.py --data-dir outputs/training_data_cap5
python testing/02_test_teacher_forward.py --data-dir outputs/training_data_cap10 --modes lstm template

================================================================================
TinyDisasterVQA / Dataloader sanity check
================================================================================
Data dir:      /content/TinyDisasterVQA/outputs/training_data_cap5
Train CSV:     outputs/training_data_cap5/train.csv
Valid CSV:     outputs/training_data_cap5/valid.csv
Test CSV:      outputs/training_data_cap5/test.csv
Dataset root:  /content/TinyDisasterVQA/dataset
Target modes:  ['edge_global', 'edge_multihead', 'original']


================================================================================
Checking target_mode=edge_global / train
================================================================================
Batch summary
============================================================
image:                (8, 3, 224, 224)
question_tokens:      (8, 11)
question_length:      (8,)
question_template_id: (8,)
head_id:              (8,)
target:               (8,)

example image_id:     9875.JPG
example question:     Is the area mostly flooded?
example question type:Entire_Image_Condition_Recognition
example edge head:    binary
example answer:       no
example target:       0

Tensor checks:
  image dtype:                 torch.float32
  image shape:                 (8, 3, 224, 224)
  image min/max:               -2.118 / 2.640
  question_tokens dtype:       torch.int64
  question_tokens shape:       (8, 11)
  question_template_id dtype:  torch.int64
  target dtype:                torch.int64
  unique head_ids:             [0, 1, 2]
  unique targets:              [0, 1, 2, 5]

First 5 samples:
  [0] image_id=9875.JPG | head=binary | target=0 | edge_global=0 | edge_head=0 | original=48 | answer=no | q=Is the area mostly flooded?
  [1] image_id=10827.JPG | head=binary | target=1 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is the area mostly non flooded
  [2] image_id=7789.JPG | head=density | target=5 | edge_global=5 | edge_head=0 | original=46 | answer=low | q=How dense the area is?
  [3] image_id=7573.JPG | head=binary | target=0 | edge_global=0 | edge_head=0 | original=48 | answer=no | q=Is the entire road non flooded?
  [4] image_id=10819.JPG | head=binary | target=0 | edge_global=0 | edge_head=0 | original=48 | answer=no | q=Is the area mostly flooded?

================================================================================
Checking target_mode=edge_global / valid
================================================================================
Batch summary
============================================================
image:                (8, 3, 224, 224)
question_tokens:      (8, 11)
question_length:      (8,)
question_template_id: (8,)
head_id:              (8,)
target:               (8,)

example image_id:     10169.JPG
example question:     How many buildings can be recognized as non flooded?
example question type:Complex_Counting
example edge head:    count
example answer:       4
example target:       11

Tensor checks:
  image dtype:                 torch.float32
  image shape:                 (8, 3, 224, 224)
  image min/max:               -2.118 / 2.640
  question_tokens dtype:       torch.int64
  question_tokens shape:       (8, 11)
  question_template_id dtype:  torch.int64
  target dtype:                torch.int64
  unique head_ids:             [0, 1, 2, 3]
  unique targets:              [0, 1, 4, 6, 11]

First 5 samples:
  [0] image_id=10169.JPG | head=count | target=11 | edge_global=11 | edge_head=3 | original=30 | answer=4 | q=How many buildings can be recognized as non flooded?
  [1] image_id=10169.JPG | head=binary | target=1 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is the entire road non flooded?
  [2] image_id=10169.JPG | head=condition | target=4 | edge_global=4 | edge_head=2 | original=49 | answer=non flooded | q=What is the condition of the road in this image?
  [3] image_id=10169.JPG | head=condition | target=4 | edge_global=4 | edge_head=2 | original=49 | answer=non flooded | q=What is the overall condition of the given image?
  [4] image_id=10169.JPG | head=density | target=6 | edge_global=6 | edge_head=1 | original=47 | answer=moderate | q=What is the level of density in this image?

================================================================================
Checking target_mode=edge_global / test
================================================================================
Batch summary
============================================================
image:                (8, 3, 224, 224)
question_tokens:      (8, 11)
question_length:      (8,)
question_template_id: (8,)
head_id:              (8,)
target:               (8,)

example image_id:     10163.JPG
example question:     Is the area mostly non flooded
example question type:Entire_Image_Condition_Recognition
example edge head:    binary
example answer:       yes
example target:       1

Tensor checks:
  image dtype:                 torch.float32
  image shape:                 (8, 3, 224, 224)
  image min/max:               -2.118 / 2.640
  question_tokens dtype:       torch.int64
  question_tokens shape:       (8, 11)
  question_template_id dtype:  torch.int64
  target dtype:                torch.int64
  unique head_ids:             [0, 1, 2, 3]
  unique targets:              [0, 1, 4, 7, 13]

First 5 samples:
  [0] image_id=10163.JPG | head=binary | target=1 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is the area mostly non flooded
  [1] image_id=10164.JPG | head=condition | target=4 | edge_global=4 | edge_head=2 | original=49 | answer=non flooded | q=what is the current state of the area?
  [2] image_id=10174.JPG | head=binary | target=1 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is the entire road non flooded?
  [3] image_id=10174.JPG | head=density | target=7 | edge_global=7 | edge_head=2 | original=45 | answer=high | q=What is the level of density in this image?
  [4] image_id=10174.JPG | head=binary | target=1 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is there any non flooded building?

================================================================================
Checking target_mode=edge_multihead / train
================================================================================
Batch summary
============================================================
image:                (8, 3, 224, 224)
question_tokens:      (8, 11)
question_length:      (8,)
question_template_id: (8,)
head_id:              (8,)
target:               (8,)

example image_id:     7072.JPG
example question:     Is the entire road non flooded?
example question type:Road_Condition_Recognition
example edge head:    binary
example answer:       yes
example target:       1

Tensor checks:
  image dtype:                 torch.float32
  image shape:                 (8, 3, 224, 224)
  image min/max:               -2.118 / 2.640
  question_tokens dtype:       torch.int64
  question_tokens shape:       (8, 11)
  question_template_id dtype:  torch.int64
  target dtype:                torch.int64
  unique head_ids:             [0, 1, 3]
  unique targets:              [0, 1, 2, 5]

First 5 samples:
  [0] image_id=7072.JPG | head=binary | target=1 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is the entire road non flooded?
  [1] image_id=7521.JPG | head=binary | target=1 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is there any flooded building?
  [2] image_id=6707.JPG | head=binary | target=0 | edge_global=0 | edge_head=0 | original=48 | answer=no | q=Is the road easily accesible?
  [3] image_id=8392.JPG | head=condition | target=2 | edge_global=4 | edge_head=2 | original=49 | answer=non flooded | q=what is the current state of the area?
  [4] image_id=8516.JPG | head=condition | target=2 | edge_global=4 | edge_head=2 | original=49 | answer=non flooded | q=what is the current state of the area?

================================================================================
Checking target_mode=edge_multihead / valid
================================================================================
Batch summary
============================================================
image:                (8, 3, 224, 224)
question_tokens:      (8, 11)
question_length:      (8,)
question_template_id: (8,)
head_id:              (8,)
target:               (8,)

example image_id:     10169.JPG
example question:     How many buildings can be recognized as non flooded?
example question type:Complex_Counting
example edge head:    count
example answer:       4
example target:       3

Tensor checks:
  image dtype:                 torch.float32
  image shape:                 (8, 3, 224, 224)
  image min/max:               -2.118 / 2.640
  question_tokens dtype:       torch.int64
  question_tokens shape:       (8, 11)
  question_template_id dtype:  torch.int64
  target dtype:                torch.int64
  unique head_ids:             [0, 1, 2, 3]
  unique targets:              [0, 1, 2, 3]

First 5 samples:
  [0] image_id=10169.JPG | head=count | target=3 | edge_global=11 | edge_head=3 | original=30 | answer=4 | q=How many buildings can be recognized as non flooded?
  [1] image_id=10169.JPG | head=binary | target=1 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is the entire road non flooded?
  [2] image_id=10169.JPG | head=condition | target=2 | edge_global=4 | edge_head=2 | original=49 | answer=non flooded | q=What is the condition of the road in this image?
  [3] image_id=10169.JPG | head=condition | target=2 | edge_global=4 | edge_head=2 | original=49 | answer=non flooded | q=What is the overall condition of the given image?
  [4] image_id=10169.JPG | head=density | target=1 | edge_global=6 | edge_head=1 | original=47 | answer=moderate | q=What is the level of density in this image?

================================================================================
Checking target_mode=edge_multihead / test
================================================================================
Batch summary
============================================================
image:                (8, 3, 224, 224)
question_tokens:      (8, 11)
question_length:      (8,)
question_template_id: (8,)
head_id:              (8,)
target:               (8,)

example image_id:     10163.JPG
example question:     Is the area mostly non flooded
example question type:Entire_Image_Condition_Recognition
example edge head:    binary
example answer:       yes
example target:       1

Tensor checks:
  image dtype:                 torch.float32
  image shape:                 (8, 3, 224, 224)
  image min/max:               -2.118 / 2.640
  question_tokens dtype:       torch.int64
  question_tokens shape:       (8, 11)
  question_template_id dtype:  torch.int64
  target dtype:                torch.int64
  unique head_ids:             [0, 1, 2, 3]
  unique targets:              [0, 1, 2, 5]

First 5 samples:
  [0] image_id=10163.JPG | head=binary | target=1 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is the area mostly non flooded
  [1] image_id=10164.JPG | head=condition | target=2 | edge_global=4 | edge_head=2 | original=49 | answer=non flooded | q=what is the current state of the area?
  [2] image_id=10174.JPG | head=binary | target=1 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is the entire road non flooded?
  [3] image_id=10174.JPG | head=density | target=2 | edge_global=7 | edge_head=2 | original=45 | answer=high | q=What is the level of density in this image?
  [4] image_id=10174.JPG | head=binary | target=1 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is there any non flooded building?

================================================================================
Checking target_mode=original / train
================================================================================
Batch summary
============================================================
image:                (8, 3, 224, 224)
question_tokens:      (8, 11)
question_length:      (8,)
question_template_id: (8,)
head_id:              (8,)
target:               (8,)

example image_id:     6492.JPG
example question:     What is the total number of building?
example question type:Simple_Counting
example edge head:    count
example answer:       2
example target:       11

Tensor checks:
  image dtype:                 torch.float32
  image shape:                 (8, 3, 224, 224)
  image min/max:               -2.118 / 2.640
  question_tokens dtype:       torch.int64
  question_tokens shape:       (8, 11)
  question_template_id dtype:  torch.int64
  target dtype:                torch.int64
  unique head_ids:             [0, 1, 2, 3]
  unique targets:              [0, 11, 45, 48, 49, 50]

First 5 samples:
  [0] image_id=6492.JPG | head=count | target=11 | edge_global=9 | edge_head=1 | original=11 | answer=2 | q=What is the total number of building?
  [1] image_id=7612.JPG | head=binary | target=48 | edge_global=0 | edge_head=0 | original=48 | answer=no | q=Do the rescuers need to take immediate actions?
  [2] image_id=6559.JPG | head=binary | target=48 | edge_global=0 | edge_head=0 | original=48 | answer=no | q=Is this area need immediate help?
  [3] image_id=6928.JPG | head=count | target=0 | edge_global=8 | edge_head=0 | original=0 | answer=1 | q=What is the total number of non flooded building?
  [4] image_id=7520.JPG | head=binary | target=50 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is the entire road flooded?

================================================================================
Checking target_mode=original / valid
================================================================================
Batch summary
============================================================
image:                (8, 3, 224, 224)
question_tokens:      (8, 11)
question_length:      (8,)
question_template_id: (8,)
head_id:              (8,)
target:               (8,)

example image_id:     10169.JPG
example question:     How many buildings can be recognized as non flooded?
example question type:Complex_Counting
example edge head:    count
example answer:       4
example target:       30

Tensor checks:
  image dtype:                 torch.float32
  image shape:                 (8, 3, 224, 224)
  image min/max:               -2.118 / 2.640
  question_tokens dtype:       torch.int64
  question_tokens shape:       (8, 11)
  question_template_id dtype:  torch.int64
  target dtype:                torch.int64
  unique head_ids:             [0, 1, 2, 3]
  unique targets:              [30, 47, 48, 49, 50]

First 5 samples:
  [0] image_id=10169.JPG | head=count | target=30 | edge_global=11 | edge_head=3 | original=30 | answer=4 | q=How many buildings can be recognized as non flooded?
  [1] image_id=10169.JPG | head=binary | target=50 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is the entire road non flooded?
  [2] image_id=10169.JPG | head=condition | target=49 | edge_global=4 | edge_head=2 | original=49 | answer=non flooded | q=What is the condition of the road in this image?
  [3] image_id=10169.JPG | head=condition | target=49 | edge_global=4 | edge_head=2 | original=49 | answer=non flooded | q=What is the overall condition of the given image?
  [4] image_id=10169.JPG | head=density | target=47 | edge_global=6 | edge_head=1 | original=47 | answer=moderate | q=What is the level of density in this image?

================================================================================
Checking target_mode=original / test
================================================================================
Batch summary
============================================================
image:                (8, 3, 224, 224)
question_tokens:      (8, 11)
question_length:      (8,)
question_template_id: (8,)
head_id:              (8,)
target:               (8,)

example image_id:     10163.JPG
example question:     Is the area mostly non flooded
example question type:Entire_Image_Condition_Recognition
example edge head:    binary
example answer:       yes
example target:       50

Tensor checks:
  image dtype:                 torch.float32
  image shape:                 (8, 3, 224, 224)
  image min/max:               -2.118 / 2.640
  question_tokens dtype:       torch.int64
  question_tokens shape:       (8, 11)
  question_template_id dtype:  torch.int64
  target dtype:                torch.int64
  unique head_ids:             [0, 1, 2, 3]
  unique targets:              [39, 45, 48, 49, 50]

First 5 samples:
  [0] image_id=10163.JPG | head=binary | target=50 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is the area mostly non flooded
  [1] image_id=10164.JPG | head=condition | target=49 | edge_global=4 | edge_head=2 | original=49 | answer=non flooded | q=what is the current state of the area?
  [2] image_id=10174.JPG | head=binary | target=50 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is the entire road non flooded?
  [3] image_id=10174.JPG | head=density | target=45 | edge_global=7 | edge_head=2 | original=45 | answer=high | q=What is the level of density in this image?
  [4] image_id=10174.JPG | head=binary | target=50 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is there any non flooded building?

================================================================================
Dataloader sanity check passed.
================================================================================
================================================================================
TinyDisasterVQA / Dataloader sanity check
================================================================================
Data dir:      /content/TinyDisasterVQA/outputs/training_data_cap10
Train CSV:     outputs/training_data_cap10/train.csv
Valid CSV:     outputs/training_data_cap10/valid.csv
Test CSV:      outputs/training_data_cap10/test.csv
Dataset root:  /content/TinyDisasterVQA/dataset
Target modes:  ['edge_global', 'edge_multihead', 'original']


================================================================================
Checking target_mode=edge_global / train
================================================================================
Batch summary
============================================================
image:                (8, 3, 224, 224)
question_tokens:      (8, 11)
question_length:      (8,)
question_template_id: (8,)
head_id:              (8,)
target:               (8,)

example image_id:     8403.JPG
example question:     Is there any non flooded building?
example question type:Building_Condition_Recognition
example edge head:    binary
example answer:       yes
example target:       1

Tensor checks:
  image dtype:                 torch.float32
  image shape:                 (8, 3, 224, 224)
  image min/max:               -2.118 / 2.640
  question_tokens dtype:       torch.int64
  question_tokens shape:       (8, 11)
  question_template_id dtype:  torch.int64
  target dtype:                torch.int64
  unique head_ids:             [0, 1, 3]
  unique targets:              [0, 1, 2, 4, 11]

First 5 samples:
  [0] image_id=8403.JPG | head=binary | target=1 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is there any non flooded building?
  [1] image_id=8984.JPG | head=condition | target=4 | edge_global=4 | edge_head=2 | original=49 | answer=non flooded | q=What is the condition of road?
  [2] image_id=7998.JPG | head=condition | target=4 | edge_global=4 | edge_head=2 | original=49 | answer=non flooded | q=What is the condition of road?
  [3] image_id=6935.JPG | head=binary | target=1 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is there any non flooded building?
  [4] image_id=6531.JPG | head=binary | target=0 | edge_global=0 | edge_head=0 | original=48 | answer=no | q=Is there any flooded building?


## T1–T6 one-epoch smoke test

This runs `testing/03_test_teacher_ablation.py` on Colab instead of locally.  
It uses `--no-pretrained` by default inside the script, so this tests the training code paths without wasting time on full teacher training.

In [ ]:
%%bash
set -euo pipefail

cd /content/TinyDisasterVQA
export PYTHONPATH=/content/TinyDisasterVQA/src:${PYTHONPATH:-}

SMOKE_DIR=/content/drive/MyDrive/TinyDisasterVQA/testing_teacher_ablation
mkdir -p "$SMOKE_DIR"

# Clean previous smoke-test runs only
find "$SMOKE_DIR" -maxdepth 1 -type d -name "smoke_T*" -exec rm -rf {} +

python testing/03_test_teacher_ablation.py \
  --runs-dir "$SMOKE_DIR" \
  --epochs 1 \
  --batch-size 8 \
  --eval-batch-size 8 \
  --num-workers 2

================================================================================
TinyDisasterVQA / Train Teacher
================================================================================
Run dir:          /content/drive/MyDrive/TinyDisasterVQA/testing_teacher_ablation/smoke_T1_cap10_lstm_ce
Device:           cuda
Backbone:         convnext_tiny
Pretrained:       False
Question encoder: lstm
Loss mode:        ce
Count aux weight: 0.0
AMP:              True
Image size:       224
Batch size:       8
Eval batch:       8
Augment train:    False
Epochs:           1
LR:               0.0001
Weight decay:     0.0001
Freeze image:     False
Count cap:        10
Num classes:      19
Count classes:    11
Count head id:    3

Model summary
================================================================================
Class:             TeacherVQA
Total params:      28,882,803
Trainable params:  28,882,803
FP32 param size:   110.18 MB
Int8 param size:   28205.9 KB
Image backbone:    convnext_tiny
Pretrained:        False
Image feature dim: 768
Question encoder:  lstm
Question dim:      256
Num classes:       19
Count aux:         False


================================================================================
Epoch 1/1
================================================================================
Epoch 001 | step 0001/0738 | loss=3.0002 | main=3.0002 | aux=0.0000 | acc=0.0000 | binary=0.000 | condition=0.000 | count=0.000 | time=23.7s
Epoch 001 | step 0738/0738 | loss=1.3368 | main=1.3368 | aux=0.0000 | acc=0.5370 | binary=0.637 | condition=0.792 | count=0.144 | density=0.248 | time=1.6min

train overall: acc=0.5370 (3167/5898)
train macro acc: 0.2101
train by edge head:
  binary       acc=0.6371 (1678/2634)
  condition    acc=0.7919 (1172/1480)
  count        acc=0.1437 (173/1204)
  density      acc=0.2483 (144/580)
train by question type:
  Building_Condition_Recognition           acc=0.6103 (354/580)
  Complex_Counting                         acc=0.1410 (88/624)
  Density_Estimation                       acc=0.2483 (144/580)
  Entire_Image_Condition_Recognition       acc=0.7485 (1021/1364)
  Risk_Assessment                          acc=0.6397 (371/580)
  Road_Condition_Recognition               acc=0.6943 (1104/1590)
  Simple_Counting                          acc=0.1466 (85/580)

valid overall: acc=0.7320 (1322/1806)
valid macro acc: 0.3979
valid by edge head:
  binary       acc=0.8317 (677/814)
  condition    acc=0.9443 (424/449)
  count        acc=0.3488 (128/367)
  density      acc=0.5284 (93/176)
valid by question type:
  Building_Condition_Recognition           acc=0.8295 (146/176)
  Complex_Counting                         acc=0.3455 (66/191)
  Density_Estimation                       acc=0.5284 (93/176)
  Entire_Image_Condition_Recognition       acc=0.9201 (380/413)
  Risk_Assessment                          acc=0.7784 (137/176)
  Road_Condition_Recognition               acc=0.8795 (438/498)
  Simple_Counting                          acc=0.3523 (62/176)

Epoch 1 done | train_acc=0.5370 | valid_acc=0.7320 | best_valid_acc=0.7320 at epoch 1 | IMPROVED

================================================================================
Evaluating best checkpoint on test set
================================================================================

test overall: acc=0.7272 (1333/1833)
test macro acc: 0.3536
test by edge head:
  binary       acc=0.8476 (695/820)
  condition    acc=0.9620 (430/447)
  count        acc=0.2846 (109/383)
  density      acc=0.5410 (99/183)
test by question type:
  Building_Condition_Recognition           acc=0.8525 (156/183)
  Complex_Counting                         acc=0.2750 (55/200)
  Density_Estimation                       acc=0.5410 (99/183)
  Entire_Image_Condition_Recognition       acc=0.9343 (384/411)
  Risk_Assessment                          acc=0.8197 (150/183)
  Road_Condition_Recognition               acc=0.8878 (435/490)
  Simple_Counting                          acc=0.2951 (54/183)

================================================================================
Training complete
================================================================================
Run dir:          /content/drive/MyDrive/TinyDisasterVQA/testing_teacher_ablation/smoke_T1_cap10_lstm_ce
Best valid acc:   0.7320
Best epoch:       1
Test acc:         0.7272
Total time:       2.2min
================================================================================
TinyDisasterVQA / Train Teacher
================================================================================
Run dir:          /content/drive/MyDrive/TinyDisasterVQA/testing_teacher_ablation/smoke_T2_cap5_lstm_ce
Device:           cuda
Backbone:         convnext_tiny
Pretrained:       False
Question encoder: lstm
Loss mode:        ce
Count aux weight: 0.0
AMP:              True
Image size:       224
Batch size:       8
Eval batch:       8
Augment train:    False
Epochs:           1
LR:               0.0001
Weight decay:     0.0001
Freeze image:     False
Count cap:        5
Num classes:      14
Count classes:    6
Count head id:    3

Model summary
================================================================================
Class:             TeacherVQA
Total params:      28,881,518
Trainable params:  28,881,518
FP32 param size:   110.17 MB
Int8 param size:   28204.6 KB
Image backbone:    convnext_tiny
Pretrained:        False
Image feature dim: 768
Question encoder:  lstm
Question dim:      256
Num classes:       14
Count aux:         False


================================================================================
Epoch 1/1
================================================================================
Epoch 001 | step 0001/0738 | loss=2.6545 | main=2.6545 | aux=0.0000 | acc=0.0000 | binary=0.000 | condition=0.000 | count=0.000 | time=25.0s
Epoch 001 | step 0738/0738 | loss=1.2755 | main=1.2755 | aux=0.0000 | acc=0.5370 | binary=0.623 | condition=0.785 | count=0.208 | density=0.197 | time=1.6min

train overall: acc=0.5370 (3167/5898)
train macro acc: 0.2637
train by edge head:
  binary       acc=0.6226 (1640/2634)
  condition    acc=0.7851 (1162/1480)
  count        acc=0.2085 (251/1204)
  density      acc=0.1966 (114/580)
train by question type:
  Building_Condition_Recognition           acc=0.5966 (346/580)
  Complex_Counting                         acc=0.1859 (116/624)
  Density_Estimation                       acc=0.1966 (114/580)
  Entire_Image_Condition_Recognition       acc=0.7155 (976/1364)
  Risk_Assessment                          acc=0.6638 (385/580)
  Road_Condition_Recognition               acc=0.6887 (1095/1590)
  Simple_Counting                          acc=0.2328 (135/580)

valid overall: acc=0.7182 (1297/1806)
valid macro acc: 0.4698
valid by edge head:
  binary       acc=0.8280 (674/814)
  condition    acc=0.9154 (411/449)
  count        acc=0.3351 (123/367)
  density      acc=0.5057 (89/176)
valid by question type:
  Building_Condition_Recognition           acc=0.8182 (144/176)
  Complex_Counting                         acc=0.3194 (61/191)
  Density_Estimation                       acc=0.5057 (89/176)
  Entire_Image_Condition_Recognition       acc=0.9056 (374/413)
  Risk_Assessment                          acc=0.7727 (136/176)
  Road_Condition_Recognition               acc=0.8655 (431/498)
  Simple_Counting                          acc=0.3523 (62/176)

Epoch 1 done | train_acc=0.5370 | valid_acc=0.7182 | best_valid_acc=0.7182 at epoch 1 | IMPROVED

================================================================================
Evaluating best checkpoint on test set
================================================================================

test overall: acc=0.7229 (1325/1833)
test macro acc: 0.4664
test by edge head:
  binary       acc=0.8366 (686/820)
  condition    acc=0.9418 (421/447)
  count        acc=0.3473 (133/383)
  density      acc=0.4645 (85/183)
test by question type:
  Building_Condition_Recognition           acc=0.8306 (152/183)
  Complex_Counting                         acc=0.3300 (66/200)
  Density_Estimation                       acc=0.4645 (85/183)
  Entire_Image_Condition_Recognition       acc=0.9270 (381/411)
  Risk_Assessment                          acc=0.7923 (145/183)
  Road_Condition_Recognition               acc=0.8755 (429/490)
  Simple_Counting                          acc=0.3661 (67/183)

================================================================================
Training complete
================================================================================
Run dir:          /content/drive/MyDrive/TinyDisasterVQA/testing_teacher_ablation/smoke_T2_cap5_lstm_ce
Best valid acc:   0.7182
Best epoch:       1
Test acc:         0.7229
Total time:       2.2min
================================================================================
TinyDisasterVQA / Train Teacher
================================================================================
Run dir:          /content/drive/MyDrive/TinyDisasterVQA/testing_teacher_ablation/smoke_T3_cap10_template_ce
Device:           cuda
Backbone:         convnext_tiny
Pretrained:       False
Question encoder: template
Loss mode:        ce
Count aux weight: 0.0
AMP:              True
Image size:       224
Batch size:       8
Eval batch:       8
Augment train:    False
Epochs:           1
LR:               0.0001
Weight decay:     0.0001
Freeze image:     False
Count cap:        10
Num classes:      19
Count classes:    11
Count head id:    3

Model summary
================================================================================
Class:             TeacherVQA
Total params:      28,419,571
Trainable params:  28,419,571
FP32 param size:   108.41 MB
Int8 param size:   27753.5 KB
Image backbone:    convnext_tiny
Pretrained:        False
Image feature dim: 768
Question encoder:  template
Question dim:      128
Num classes:       19
Count aux:         False


================================================================================
Epoch 1/1
================================================================================
Epoch 001 | step 0001/0738 | loss=2.9243 | main=2.9243 | aux=0.0000 | acc=0.0000 | binary=0.000 | condition=0.000 | count=0.000 | time=24.4s
Epoch 001 | step 0738/0738 | loss=1.4398 | main=1.4398 | aux=0.0000 | acc=0.5626 | binary=0.751 | condition=0.753 | count=0.077 | density=0.228 | time=1.6min

train overall: acc=0.5626 (3318/5898)
train macro acc: 0.1910
train by edge head:
  binary       acc=0.7509 (1978/2634)
  condition    acc=0.7534 (1115/1480)
  count        acc=0.0772 (93/1204)
  density      acc=0.2276 (132/580)
train by question type:
  Building_Condition_Recognition           acc=0.6966 (404/580)
  Complex_Counting                         acc=0.0801 (50/624)
  Density_Estimation                       acc=0.2276 (132/580)
  Entire_Image_Condition_Recognition       acc=0.7837 (1069/1364)
  Risk_Assessment                          acc=0.7534 (437/580)
  Road_Condition_Recognition               acc=0.7440 (1183/1590)
  Simple_Counting                          acc=0.0741 (43/580)

valid overall: acc=0.7475 (1350/1806)
valid macro acc: 0.3855
valid by edge head:
  binary       acc=0.8796 (716/814)
  condition    acc=0.9332 (419/449)
  count        acc=0.3569 (131/367)
  density      acc=0.4773 (84/176)
valid by question type:
  Building_Condition_Recognition           acc=0.8636 (152/176)
  Complex_Counting                         acc=0.3351 (64/191)
  Density_Estimation                       acc=0.4773 (84/176)
  Entire_Image_Condition_Recognition       acc=0.9346 (386/413)
  Risk_Assessment                          acc=0.8920 (157/176)
  Road_Condition_Recognition               acc=0.8835 (440/498)
  Simple_Counting                          acc=0.3807 (67/176)

Epoch 1 done | train_acc=0.5626 | valid_acc=0.7475 | best_valid_acc=0.7475 at epoch 1 | IMPROVED

================================================================================
Evaluating best checkpoint on test set
================================================================================

test overall: acc=0.7540 (1382/1833)
test macro acc: 0.3625
test by edge head:
  binary       acc=0.8988 (737/820)
  condition    acc=0.9620 (430/447)
  count        acc=0.3211 (123/383)
  density      acc=0.5027 (92/183)
test by question type:
  Building_Condition_Recognition           acc=0.9016 (165/183)
  Complex_Counting                         acc=0.2750 (55/200)
  Density_Estimation                       acc=0.5027 (92/183)
  Entire_Image_Condition_Recognition       acc=0.9440 (388/411)
  Risk_Assessment                          acc=0.9126 (167/183)
  Road_Condition_Recognition               acc=0.9122 (447/490)
  Simple_Counting                          acc=0.3716 (68/183)

================================================================================
Training complete
================================================================================
Run dir:          /content/drive/MyDrive/TinyDisasterVQA/testing_teacher_ablation/smoke_T3_cap10_template_ce
Best valid acc:   0.7475
Best epoch:       1
Test acc:         0.7540
Total time:       2.1min
================================================================================
TinyDisasterVQA / Train Teacher
================================================================================
Run dir:          /content/drive/MyDrive/TinyDisasterVQA/testing_teacher_ablation/smoke_T4_cap5_template_ce
Device:           cuda
Backbone:         convnext_tiny
Pretrained:       False
Question encoder: template
Loss mode:        ce
Count aux weight: 0.0
AMP:              True
Image size:       224
Batch size:       8
Eval batch:       8
Augment train:    False
Epochs:           1
LR:               0.0001
Weight decay:     0.0001
Freeze image:     False
Count cap:        5
Num classes:      14
Count classes:    6
Count head id:    3

Model summary
================================================================================
Class:             TeacherVQA
Total params:      28,418,286
Trainable params:  28,418,286
FP32 param size:   108.41 MB
Int8 param size:   27752.2 KB
Image backbone:    convnext_tiny
Pretrained:        False
Image feature dim: 768
Question encoder:  template
Question dim:      128
Num classes:       14
Count aux:         False


================================================================================
Epoch 1/1
================================================================================
Epoch 001 | step 0001/0738 | loss=2.6370 | main=2.6370 | aux=0.0000 | acc=0.1250 | binary=0.167 | condition=0.000 | density=0.000 | time=23.4s
Epoch 001 | step 0738/0738 | loss=1.3421 | main=1.3421 | aux=0.0000 | acc=0.5687 | binary=0.722 | condition=0.777 | count=0.137 | density=0.236 | time=1.6min

train overall: acc=0.5687 (3354/5898)
train macro acc: 0.2659
train by edge head:
  binary       acc=0.7221 (1902/2634)
  condition    acc=0.7770 (1150/1480)
  count        acc=0.1370 (165/1204)
  density      acc=0.2362 (137/580)
train by question type:
  Building_Condition_Recognition           acc=0.7069 (410/580)
  Complex_Counting                         acc=0.1106 (69/624)
  Density_Estimation                       acc=0.2362 (137/580)
  Entire_Image_Condition_Recognition       acc=0.7852 (1071/1364)
  Risk_Assessment                          acc=0.6741 (391/580)
  Road_Condition_Recognition               acc=0.7421 (1180/1590)
  Simple_Counting                          acc=0.1655 (96/580)

valid overall: acc=0.7386 (1334/1806)
valid macro acc: 0.4599
valid by edge head:
  binary       acc=0.8722 (710/814)
  condition    acc=0.9176 (412/449)
  count        acc=0.3433 (126/367)
  density      acc=0.4886 (86/176)
valid by question type:
  Building_Condition_Recognition           acc=0.8580 (151/176)
  Complex_Counting                         acc=0.3246 (62/191)
  Density_Estimation                       acc=0.4886 (86/176)
  Entire_Image_Condition_Recognition       acc=0.9201 (380/413)
  Risk_Assessment                          acc=0.8580 (151/176)
  Road_Condition_Recognition               acc=0.8835 (440/498)
  Simple_Counting                          acc=0.3636 (64/176)

Epoch 1 done | train_acc=0.5687 | valid_acc=0.7386 | best_valid_acc=0.7386 at epoch 1 | IMPROVED

================================================================================
Evaluating best checkpoint on test set
================================================================================

test overall: acc=0.7414 (1359/1833)
test macro acc: 0.4509
test by edge head:
  binary       acc=0.8817 (723/820)
  condition    acc=0.9239 (413/447)
  count        acc=0.3446 (132/383)
  density      acc=0.4973 (91/183)
test by question type:
  Building_Condition_Recognition           acc=0.8798 (161/183)
  Complex_Counting                         acc=0.3250 (65/200)
  Density_Estimation                       acc=0.4973 (91/183)
  Entire_Image_Condition_Recognition       acc=0.9319 (383/411)
  Risk_Assessment                          acc=0.8852 (162/183)
  Road_Condition_Recognition               acc=0.8776 (430/490)
  Simple_Counting                          acc=0.3661 (67/183)

================================================================================
Training complete
================================================================================
Run dir:          /content/drive/MyDrive/TinyDisasterVQA/testing_teacher_ablation/smoke_T4_cap5_template_ce
Best valid acc:   0.7386
Best epoch:       1
Test acc:         0.7414
Total time:       2.1min
================================================================================
TinyDisasterVQA / Train Teacher
================================================================================
Run dir:          /content/drive/MyDrive/TinyDisasterVQA/testing_teacher_ablation/smoke_T5_cap5_template_weighted_ce
Device:           cuda
Backbone:         convnext_tiny
Pretrained:       False
Question encoder: template
Loss mode:        weighted_ce
Count aux weight: 0.0
AMP:              True
Image size:       224
Batch size:       8
Eval batch:       8
Augment train:    False
Epochs:           1
LR:               0.0001
Weight decay:     0.0001
Freeze image:     False
Count cap:        5
Num classes:      14
Count classes:    6
Count head id:    3

Model summary
================================================================================
Class:             TeacherVQA
Total params:      28,418,286
Trainable params:  28,418,286
FP32 param size:   108.41 MB
Int8 param size:   27752.2 KB
Image backbone:    convnext_tiny
Pretrained:        False
Image feature dim: 768
Question encoder:  template
Question dim:      128
Num classes:       14
Count aux:         False

Using edge_global class weights:
[0.3070286810398102, 0.3189149796962738, 0.8006914258003235, 4.634336948394775, 0.3181625306606293, 0.883733332157135, 0.8129164576530457, 0.7653355598449707, 0.8368628621101379, 0.883733332157135, 0.7653355598449707, 0.8235432505607605, 1.2535922527313232, 0.5958129167556763]

================================================================================
Epoch 1/1
================================================================================
Epoch 001 | step 0001/0738 | loss=2.6587 | main=2.6587 | aux=0.0000 | acc=0.1250 | binary=0.167 | condition=0.000 | density=0.000 | time=23.1s
Epoch 001 | step 0738/0738 | loss=1.7644 | main=1.7644 | aux=0.0000 | acc=0.5404 | binary=0.674 | condition=0.746 | count=0.133 | density=0.253 | time=1.6min

train overall: acc=0.5404 (3187/5898)
train macro acc: 0.2663
train by edge head:
  binary       acc=0.6743 (1776/2634)
  condition    acc=0.7459 (1104/1480)
  count        acc=0.1329 (160/1204)
  density      acc=0.2534 (147/580)
train by question type:
  Building_Condition_Recognition           acc=0.6500 (377/580)
  Complex_Counting                         acc=0.1090 (68/624)

In [ ]:
from pathlib import Path
import json
import pandas as pd

base = Path("/content/drive/MyDrive/TinyDisasterVQA/testing_teacher_ablation")
rows = []

for summary_path in sorted(base.glob("*/final_summary.json")):
    with summary_path.open("r") as f:
        row = json.load(f)
    row["run_name"] = summary_path.parent.name
    rows.append(row)

df = pd.DataFrame(rows)
display(df[[
    "run_name",
    "count_cap",
    "question_encoder",
    "loss_mode",
    "best_valid_acc",
    "test_acc",
    "best_epoch",
]] if len(df) else df)

,run_name,count_cap,question_encoder,loss_mode,best_valid_acc,test_acc,best_epoch
0,smoke_T1_cap10_lstm_ce,10,lstm,ce,0.732004,0.727223,1
1,smoke_T2_cap5_lstm_ce,5,lstm,ce,0.718162,0.722859,1
2,smoke_T3_cap10_template_ce,10,template,ce,0.747508,0.753955,1
3,smoke_T4_cap5_template_ce,5,template,ce,0.738649,0.741408,1
4,smoke_T5_cap5_template_weighted_ce,5,template,weighted_ce,0.719823,0.725586,1
5,smoke_T6_cap5_template_count_aux,5,template,count_aux,0.711517,0.724495,1

# Stop here first

If all cells above pass, the pipeline is structurally fine.  
Only then run the full T1–T6 teacher training cell below.

## Full T1–T6 teacher training

This writes runs directly to Drive:

```text
/content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6
```

Default full setting:

- ConvNeXt-Tiny
- 224×224
- pretrained ImageNet weights
- 30 epochs
- early stopping patience 5
- batch size 64

T1: cap10 + LSTM + CE

In [ ]:
%cd /content/TinyDisasterVQA
%env PYTHONPATH=/content/TinyDisasterVQA/src
%env PYTHONUNBUFFERED=1

!mkdir -p /content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6

!python -u scripts/05_train_teacher.py \
  --dataset-root dataset \
  --runs-dir /content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6 \
  --backbone convnext_tiny \
  --image-size 224 \
  --epochs 30 \
  --batch-size 64 \
  --eval-batch-size 64 \
  --num-workers 2 \
  --early-stopping-patience 5 \
  --early-stopping-min-delta 0.001 \
  --log-interval 5 \
  --pretrained \
  --train-csv outputs/training_data_cap10/train.csv \
  --valid-csv outputs/training_data_cap10/valid.csv \
  --test-csv outputs/training_data_cap10/test.csv \
  --metadata outputs/training_data_cap10/metadata.json \
  --class-weights outputs/answer_space_cap10/class_weights_edge_global_by_label.json \
  --run-name T1_cap10_lstm_ce \
  --question-encoder lstm \
  --loss-mode ce

/content/TinyDisasterVQA
env: PYTHONPATH=/content/TinyDisasterVQA/src
env: PYTHONUNBUFFERED=1
================================================================================
TinyDisasterVQA / Train Teacher
================================================================================
Run dir:          /content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6/T1_cap10_lstm_ce
Device:           cuda
Backbone:         convnext_tiny
Pretrained:       True
Question encoder: lstm
Loss mode:        ce
Count aux weight: 0.0
AMP:              True
Image size:       224
Batch size:       64
Eval batch:       64
Augment train:    True
Epochs:           30
LR:               0.0001
Weight decay:     0.0001
Freeze image:     False
Count cap:        10
Num classes:      19
Count classes:    11
Count head id:    3

Model summary
================================================================================
Class:             TeacherVQA
Total params:      28,882,803
Trainable params:  28,882,803
FP32 param size:   110.18 MB
Int8 param size:   28205.9 KB
Image backbone:    convnext_tiny
Pretrained:        True
Image feature dim: 768
Question encoder:  lstm
Question dim:      256
Num classes:       19
Count aux:         False


================================================================================
Epoch 1/30
================================================================================
Epoch 001 | step 0001/0093 | loss=2.9606 | main=2.9606 | aux=0.0000 | acc=0.0000 | binary=0.000 | condition=0.000 | count=0.000 | density=0.000 | time=34.5s
Epoch 001 | step 0005/0093 | loss=2.9090 | main=2.9090 | aux=0.0000 | acc=0.0875 | binary=0.152 | condition=0.071 | count=0.018 | density=0.000 | time=35.8s
Epoch 001 | step 0010/0093 | loss=2.8141 | main=2.8141 | aux=0.0000 | acc=0.1703 | binary=0.288 | condition=0.156 | count=0.008 | density=0.000 | time=37.4s
Epoch 001 | step 0015/0093 | loss=2.7148 | main=2.7148 | aux=0.0000 | acc=0.1979 | binary=0.369 | condition=0.129 | count=0.005 | density=0.000 | time=39.0s
Epoch 001 | step 0020/0093 | loss=2.6170 | main=2.6170 | aux=0.0000 | acc=0.2188 | binary=0.410 | condition=0.123 | count=0.004 | density=0.000 | time=40.7s
Epoch 001 | step 0025/0093 | loss=2.5501 | main=2.5501 | aux=0.0000 | acc=0.2263 | binary=0.432 | condition=0.124 | count=0.003 | density=0.000 | time=42.3s
Epoch 001 | step 0030/0093 | loss=2.4990 | main=2.4990 | aux=0.0000 | acc=0.2354 | binary=0.422 | condition=0.183 | count=0.003 | density=0.000 | time=44.1s
Epoch 001 | step 0035/0093 | loss=2.4512 | main=2.4512 | aux=0.0000 | acc=0.2433 | binary=0.406 | condition=0.241 | count=0.002 | density=0.000 | time=45.9s
Epoch 001 | step 0040/0093 | loss=2.4219 | main=2.4219 | aux=0.0000 | acc=0.2441 | binary=0.397 | condition=0.270 | count=0.002 | density=0.000 | time=47.7s
Epoch 001 | step 0045/0093 | loss=2.3888 | main=2.3888 | aux=0.0000 | acc=0.2497 | binary=0.389 | condition=0.301 | count=0.002 | density=0.000 | time=49.4s
Epoch 001 | step 0050/0093 | loss=2.3592 | main=2.3592 | aux=0.0000 | acc=0.2531 | binary=0.390 | condition=0.310 | count=0.002 | density=0.000 | time=51.1s
Epoch 001 | step 0055/0093 | loss=2.3371 | main=2.3371 | aux=0.0000 | acc=0.2577 | binary=0.400 | condition=0.314 | count=0.001 | density=0.000 | time=52.9s
Epoch 001 | step 0060/0093 | loss=2.3096 | main=2.3096 | aux=0.0000 | acc=0.2685 | binary=0.404 | condition=0.352 | count=0.003 | density=0.000 | time=54.7s
Epoch 001 | step 0065/0093 | loss=2.2761 | main=2.2761 | aux=0.0000 | acc=0.2776 | binary=0.400 | condition=0.390 | count=0.006 | density=0.000 | time=56.4s
Epoch 001 | step 0070/0093 | loss=2.2400 | main=2.2400 | aux=0.0000 | acc=0.2897 | binary=0.407 | condition=0.423 | count=0.007 | density=0.000 | time=58.2s
Epoch 001 | step 0075/0093 | loss=2.2105 | main=2.2105 | aux=0.0000 | acc=0.2985 | binary=0.414 | condition=0.448 | count=0.007 | density=0.000 | time=1.0min
Epoch 001 | step 0080/0093 | loss=2.1773 | main=2.1773 | aux=0.0000 | acc=0.3094 | binary=0.421 | condition=0.476 | count=0.009 | density=0.000 | time=1.0min
Epoch 001 | step 0085/0093 | loss=2.1437 | main=2.1437 | aux=0.0000 | acc=0.3206 | binary=0.431 | condition=0.499 | count=0.013 | density=0.006 | time=1.1min
Epoch 001 | step 0090/0093 | loss=2.1097 | main=2.1097 | aux=0.0000 | acc=0.3304 | binary=0.438 | condition=0.519 | count=0.015 | density=0.009 | time=1.1min
Epoch 001 | step 0093/0093 | loss=2.0961 | main=2.0961 | aux=0.0000 | acc=0.3345 | binary=0.443 | condition=0.528 | count=0.017 | density=0.009 | time=1.5min

train overall: acc=0.3345 (1973/5898)
train macro acc: 0.0864
train by edge head:
  binary       acc=0.4427 (1166/2634)
  condition    acc=0.5277 (781/1480)
  count        acc=0.0174 (21/1204)
  density      acc=0.0086 (5/580)
train by question type:
  Building_Condition_Recognition           acc=0.4328 (251/580)
  Complex_Counting                         acc=0.0144 (9/624)
  Density_Estimation                       acc=0.0086 (5/580)
  Entire_Image_Condition_Recognition       acc=0.4890 (667/1364)
  Risk_Assessment                          acc=0.6345 (368/580)
  Road_Condition_Recognition               acc=0.4157 (661/1590)
  Simple_Counting                          acc=0.0207 (12/580)

valid overall: acc=0.5637 (1018/1806)
valid macro acc: 0.2069
valid by edge head:
  binary       acc=0.6769 (551/814)
  condition    acc=0.8909 (400/449)
  count        acc=0.1471 (54/367)
  density      acc=0.0739 (13/176)
valid by question type:
  Building_Condition_Recognition           acc=0.5000 (88/176)
  Complex_Counting                         acc=0.1099 (21/191)
  Density_Estimation                       acc=0.0739 (13/176)
  Entire_Image_Condition_Recognition       acc=0.8329 (344/413)
  Risk_Assessment                          acc=0.9886 (174/176)
  Road_Condition_Recognition               acc=0.6928 (345/498)
  Simple_Counting                          acc=0.1875 (33/176)

Epoch 1 done | train_acc=0.3345 | valid_acc=0.5637 | best_valid_acc=0.5637 at epoch 1 | IMPROVED

================================================================================
Epoch 2/30
================================================================================
Epoch 002 | step 0001/0093 | loss=1.2864 | main=1.2864 | aux=0.0000 | acc=0.5469 | binary=0.680 | condition=0.857 | count=0.000 | density=0.000 | time=0.7s
Epoch 002 | step 0005/0093 | loss=1.4034 | main=1.4034 | aux=0.0000 | acc=0.5437 | binary=0.707 | condition=0.880 | count=0.045 | density=0.031 | time=2.1s
Epoch 002 | step 0010/0093 | loss=1.4004 | main=1.4004 | aux=0.0000 | acc=0.5359 | binary=0.688 | condition=0.863 | count=0.068 | density=0.026 | time=3.8s
Epoch 002 | step 0015/0093 | loss=1.3810 | main=1.3810 | aux=0.0000 | acc=0.5292 | binary=0.655 | condition=0.879 | count=0.107 | density=0.020 | time=5.6s
Epoch 002 | step 0020/0093 | loss=1.3397 | main=1.3397 | aux=0.0000 | acc=0.5461 | binary=0.672 | condition=0.899 | count=0.105 | density=0.023 | time=7.4s
Epoch 002 | step 0025/0093 | loss=1.3428 | main=1.3428 | aux=0.0000 | acc=0.5350 | binary=0.651 | condition=0.907 | count=0.100 | density=0.045 | time=9.4s
Epoch 002 | step 0030/0093 | loss=1.3149 | main=1.3149 | aux=0.0000 | acc=0.5318 | binary=0.635 | condition=0.912 | count=0.100 | density=0.048 | time=11.5s
Epoch 002 | step 0035/0093 | loss=1.2875 | main=1.2875 | aux=0.0000 | acc=0.5388 | binary=0.634 | condition=0.924 | count=0.122 | density=0.042 | time=13.3s
Epoch 002 | step 0040/0093 | loss=1.2579 | main=1.2579 | aux=0.0000 | acc=0.5461 | binary=0.638 | condition=0.929 | count=0.120 | density=0.050 | time=15.0s
Epoch 002 | step 0045/0093 | loss=1.2467 | main=1.2467 | aux=0.0000 | acc=0.5503 | binary=0.641 | condition=0.931 | count=0.122 | density=0.049 | time=16.8s
Epoch 002 | step 0050/0093 | loss=1.2278 | main=1.2278 | aux=0.0000 | acc=0.5544 | binary=0.643 | condition=0.938 | count=0.127 | density=0.056 | time=18.5s
Epoch 002 | step 0055/0093 | loss=1.2075 | main=1.2075 | aux=0.0000 | acc=0.5616 | binary=0.653 | condition=0.940 | count=0.137 | density=0.060 | time=20.2s
Epoch 002 | step 0060/0093 | loss=1.1920 | main=1.1920 | aux=0.0000 | acc=0.5695 | binary=0.658 | condition=0.943 | count=0.153 | density=0.091 | time=22.0s
Epoch 002 | step 0065/0093 | loss=1.1751 | main=1.1751 | aux=0.0000 | acc=0.5776 | binary=0.667 | condition=0.944 | count=0.162 | density=0.114 | time=23.9s
Epoch 002 | step 0070/0093 | loss=1.1571 | main=1.1571 | aux=0.0000 | acc=0.5846 | binary=0.675 | condition=0.947 | count=0.166 | density=0.133 | time=25.7s
Epoch 002 | step 0075/0093 | loss=1.1377 | main=1.1377 | aux=0.0000 | acc=0.5940 | binary=0.682 | condition=0.950 | count=0.175 | density=0.154 | time=27.4s
Epoch 002 | step 0080/0093 | loss=1.1215 | main=1.1215 | aux=0.0000 | acc=0.6016 | binary=0.687 | condition=0.952 | count=0.186 | density=0.167 | time=29.1s
Epoch 002 | step 0085/0093 | loss=1.1073 | main=1.1073 | aux=0.0000 | acc=0.6101 | binary=0.696 | condition=0.952 | count=0.202 | density=0.187 | time=30.8s
Epoch 002 | step 0090/0093 | loss=1.0913 | main=1.0913 | aux=0.0000 | acc=0.6167 | binary=0.706 | condition=0.952 | count=0.207 | density=0.201 | time=32.5s
Epoch 002 | step 0093/0093 | loss=1.0855 | main=1.0855 | aux=0.0000 | acc=0.6192 | binary=0.708 | condition=0.953 | count=0.213 | density=0.207 | time=33.2s

train overall: acc=0.6192 (3652/5898)
train macro acc: 0.2609
train by edge head:
  binary       acc=0.7084 (1866/2634)
  condition    acc=0.9527 (1410/1480)
  count        acc=0.2126 (256/1204)
  density      acc=0.2069 (120/580)
train by question type:
  Building_Condition_Recognition           acc=0.6759 (392/580)
  Complex_Counting                         acc=0.2035 (127/624)
  Density_Estimation                       acc=0.2069 (120/580)
  Entire_Image_Condition_Recognition       acc=0.8343 (1138/1364)
  Risk_Assessment                          acc=0.8552 (496/580)
  Road_Condition_Recognition               acc=0.7862 (1250/1590)
  Simple_Counting                          acc=0.2224 (129/580)

valid overall: acc=0.7663 (1384/1806)
valid macro acc: 0.4492
valid by edge head:
  binary       acc=0.8428 (686/814)
  condition    acc=0.9555 (429/449)
  count        acc=0.4932 (181/367)
  density      acc=0.5000 (88/176)
valid by question type:
  Building_Condition_Recognition           acc=0.8807 (155/176)
  Complex_Counting                         acc=0.4607 (88/191)
  Density_Estimation                       acc=0.5000 (88/176)
  Entire_Image_Condition_Recognition       acc=0.9225 (381/413)
  Risk_Assessment                          acc=0.7841 (138/176)
  Road_Condition_Recognition               acc=0.8855 (441/498)
  Simple_Counting                          acc=0.5284 (93/176)

Epoch 2 done | train_acc=0.6192 | valid_acc=0.7663 | best_valid_acc=0.7663 at epoch 2 | IMPROVED

================================================================================
Epoch 3/30
================================================================================
Epoch 003 | step 0001/0093 | loss=0.6016 | main=0.6016 | aux=0.0000 | acc=0.8281 | binary=0.808 | condition=1.000 | count=0.571 | density=0.625 | time=0.7s
Epoch 003 | step 0005/0093 | loss=0.6775 | main=0.6775 | aux=0.0000 | acc=0.7812 | binary=0.831 | condition=0.988 | count=0.407 | density=0.545 | time=2.1s
Epoch 003 | step 0010/0093 | loss=0.7233 | main=0.7233 | aux=0.0000 | acc=0.7688 | binary=0.849 | condition=0.987 | count=0.419 | density=0.537 | time=3.7s
Epoch 003 | step 0015/0093 | loss=0.7139 | main=0.7139 | aux=0.0000 | acc=0.7719 | binary=0.853 | condition=0.972 | count=0.431 | density=0.529 | time=5.3s
Epoch 003 | step 0020/0093 | loss=0.6997 | main=0.6997 | aux=0.0000 | acc=0.7766 | binary=0.867 | condition=0.972 | count=0.421 | density=0.559 | time=6.9s
Epoch 003 | step 0025/0093 | loss=0.6917 | main=0.6917 | aux=0.0000 | acc=0.7800 | binary=0.869 | condition=0.972 | count=0.412 | density=0.614 | time=8.7s
Epoch 003 | step 0030/0093 | loss=0.6881 | main=0.6881 | aux=0.0000 | acc=0.7766 | binary=0.865 | condition=0.975 | count=0.404 | density=0.615 | time=10.6s
Epoch 003 | step 0035/0093 | loss=0.6776 | main=0.6776 | aux=0.0000 | acc=0.7781 | binary=0.871 | condition=0.975 | count=0.399 | density=0.611 | time=12.6s
Epoch 003 | step 0040/0093 | loss=0.6702 | main=0.6702 | aux=0.0000 | acc=0.7801 | binary=0.876 | condition=0.975 | count=0.412 | density=0.592 | time=14.3s
Epoch 003 | step 0045/0093 | loss=0.6649 | main=0.6649 | aux=0.0000 | acc=0.7826 | binary=0.878 | condition=0.969 | count=0.422 | density=0.595 | time=16.0s
Epoch 003 | step 0050/0093 | loss=0.6547 | main=0.6547 | aux=0.0000 | acc=0.7859 | binary=0.879 | condition=0.970 | count=0.423 | density=0.612 | time=17.8s
Epoch 003 | step 0055/0093 | loss=0.6509 | main=0.6509 | aux=0.0000 | acc=0.7875 | binary=0.878 | condition=0.971 | count=0.431 | density=0.634 | time=19.6s
Epoch 003 | step 0060/0093 | loss=0.6470 | main=0.6470 | aux=0.0000 | acc=0.7888 | binary=0.880 | condition=0.969 | count=0.435 | density=0.646 | time=21.3s
Epoch 003 | step 0065/0093 | loss=0.6412 | main=0.6412 | aux=0.0000 | acc=0.7909 | binary=0.883 | condition=0.969 | count=0.435 | density=0.647 | time=23.2s
Epoch 003 | step 0070/0093 | loss=0.6345 | main=0.6345 | aux=0.0000 | acc=0.7917 | binary=0.883 | condition=0.970 | count=0.437 | density=0.654 | time=25.3s
Epoch 003 | step 0075/0093 | loss=0.6327 | main=0.6327 | aux=0.0000 | acc=0.7931 | binary=0.884 | condition=0.969 | count=0.442 | density=0.654 | time=27.4s
Epoch 003 | step 0080/0093 | loss=0.6232 | main=0.6232 | aux=0.0000 | acc=0.7965 | binary=0.886 | condition=0.970 | count=0.443 | density=0.673 | time=29.1s
Epoch 003 | step 0085/0093 | loss=0.6145 | main=0.6145 | aux=0.0000 | acc=0.7993 | binary=0.888 | condition=0.970 | count=0.447 | density=0.683 | time=30.9s
Epoch 003 | step 0090/0093 | loss=0.6073 | main=0.6073 | aux=0.0000 | acc=0.8007 | binary=0.892 | condition=0.971 | count=0.446 | density=0.686 | time=32.6s
Epoch 003 | step 0093/0093 | loss=0.6061 | main=0.6061 | aux=0.0000 | acc=0.8011 | binary=0.893 | condition=0.970 | count=0.447 | density=0.688 | time=33.3s

train overall: acc=0.8011 (4725/5898)
train macro acc: 0.4451
train by edge head:
  binary       acc=0.8933 (2353/2634)
  condition    acc=0.9696 (1435/1480)
  count        acc=0.4468 (538/1204)
  density      acc=0.6879 (399/580)
train by question type:
  Building_Condition_Recognition           acc=0.8845 (513/580)
  Complex_Counting                         acc=0.4215 (263/624)
  Density_Estimation                       acc=0.6879 (399/580)
  Entire_Image_Condition_Recognition       acc=0.9428 (1286/1364)
  Risk_Assessment                          acc=0.9017 (523/580)
  Road_Condition_Recognition               acc=0.9220 (1466/1590)
  Simple_Counting                          acc=0.4741 (275/580)

valid overall: acc=0.8378 (1513/1806)
valid macro acc: 0.5348
valid by edge head:
  binary       acc=0.9214 (750/814)
  condition    acc=0.9733 (437/449)
  count        acc=0.4877 (179/367)
  density      acc=0.8352 (147/176)
valid by question type:
  Building_Condition_Recognition           acc=0.9034 (159/176)
  Complex_Counting                         acc=0.4660 (89/191)
  Density_Estimation                       acc=0.8352 (147/176)
  Entire_Image_Condition_Recognition       acc=0.9637 (398/413)
  Risk_Assessment                          acc=0.9773 (172/176)
  Road_Condition_Recognition               acc=0.9197 (458/498)
  Simple_Counting                          acc=0.5114 (90/176)

Epoch 3 done | train_acc=0.8011 | valid_acc=0.8378 | best_valid_acc=0.8378 at epoch 3 | IMPROVED

================================================================================
Epoch 4/30
================================================================================
Epoch 004 | step 0001/0093 | loss=0.3391 | main=0.3391 | aux=0.0000 | acc=0.9062 | binary=1.000 | condition=1.000 | count=0.455 | density=1.000 | time=0.7s
Epoch 004 | step 0005/0093 | loss=0.4375 | main=0.4375 | aux=0.0000 | acc=0.8438 | binary=0.960 | condition=0.955 | count=0.439 | density=0.892 | time=2.0s
Epoch 004 | step 0010/0093 | loss=0.4244 | main=0.4244 | aux=0.0000 | acc=0.8500 | binary=0.951 | condition=0.972 | count=0.417 | density=0.905 | time=3.7s
Epoch 004 | step 0015/0093 | loss=0.4471 | main=0.4471 | aux=0.0000 | acc=0.8448 | binary=0.959 | condition=0.968 | count=0.424 | density=0.876 | time=5.4s
Epoch 004 | step 0020/0093 | loss=0.4366 | main=0.4366 | aux=0.0000 | acc=0.8500 | binary=0.959 | condition=0.974 | count=0.457 | density=0.839 | time=7.0s
Epoch 004 | step 0025/0093 | loss=0.4450 | main=0.4450 | aux=0.0000 | acc=0.8488 | binary=0.958 | condition=0.976 | count=0.463 | density=0.837 | time=8.8s
Epoch 004 | step 0030/0093 | loss=0.4301 | main=0.4301 | aux=0.0000 | acc=0.8589 | binary=0.961 | condition=0.978 | count=0.497 | density=0.858 | time=10.6s
Epoch 004 | step 0035/0093 | loss=0.4376 | main=0.4376 | aux=0.0000 | acc=0.8554 | binary=0.954 | condition=0.976 | count=0.500 | density=0.858 | time=12.7s
Epoch 004 | step 0040/0093 | loss=0.4369 | main=0.4369 | aux=0.0000 | acc=0.8555 | binary=0.953 | condition=0.979 | count=0.498 | density=0.868 | time=14.5s
Epoch 004 | step 0045/0093 | loss=0.4414 | main=0.4414 | aux=0.0000 | acc=0.8528 | binary=0.951 | condition=0.980 | count=0.494 | density=0.864 | time=16.3s
Epoch 004 | step 0050/0093 | loss=0.4304 | main=0.4304 | aux=0.0000 | acc=0.8572 | binary=0.955 | condition=0.979 | count=0.503 | density=0.863 | time=18.0s
Epoch 004 | step 0055/0093 | loss=0.4304 | main=0.4304 | aux=0.0000 | acc=0.8571 | binary=0.955 | condition=0.980 | count=0.505 | density=0.857 | time=19.8s
Epoch 004 | step 0060/0093 | loss=0.4305 | main=0.4305 | aux=0.0000 | acc=0.8557 | binary=0.958 | condition=0.977 | count=0.502 | density=0.855 | time=21.6s
Epoch 004 | step 0065/0093 | loss=0.4268 | main=0.4268 | aux=0.0000 | acc=0.8567 | binary=0.960 | condition=0.977 | count=0.500 | density=0.860 | time=23.4s
Epoch 004 | step 0070/0093 | loss=0.4244 | main=0.4244 | aux=0.0000 | acc=0.8583 | binary=0.959 | condition=0.977 | count=0.499 | density=0.868 | time=25.5s
Epoch 004 | step 0075/0093 | loss=0.4148 | main=0.4148 | aux=0.0000 | acc=0.8615 | binary=0.960 | condition=0.978 | count=0.504 | density=0.873 | time=27.5s
Epoch 004 | step 0080/0093 | loss=0.4124 | main=0.4124 | aux=0.0000 | acc=0.8629 | binary=0.961 | condition=0.978 | count=0.508 | density=0.872 | time=29.4s
Epoch 004 | step 0085/0093 | loss=0.4061 | main=0.4061 | aux=0.0000 | acc=0.8645 | binary=0.962 | condition=0.979 | count=0.511 | density=0.870 | time=31.2s
Epoch 004 | step 0090/0093 | loss=0.4023 | main=0.4023 | aux=0.0000 | acc=0.8649 | binary=0.962 | condition=0.980 | count=0.508 | density=0.878 | time=32.9s
Epoch 004 | step 0093/0093 | loss=0.3991 | main=0.3991 | aux=0.0000 | acc=0.8659 | binary=0.962 | condition=0.980 | count=0.508 | density=0.879 | time=33.6s

train overall: acc=0.8659 (5107/5898)
train macro acc: 0.5213
train by edge head:
  binary       acc=0.9624 (2535/2634)
  condition    acc=0.9797 (1450/1480)
  count        acc=0.5083 (612/1204)
  density      acc=0.8793 (510/580)
train by question type:
  Building_Condition_Recognition           acc=0.9431 (547/580)
  Complex_Counting                         acc=0.4920 (307/624)
  Density_Estimation                       acc=0.8793 (510/580)
  Entire_Image_Condition_Recognition       acc=0.9751 (1330/1364)
  Risk_Assessment                          acc=0.9707 (563/580)
  Road_Condition_Recognition               acc=0.9717 (1545/1590)
  Simple_Counting                          acc=0.5259 (305/580)

valid overall: acc=0.8859 (1600/1806)
valid macro acc: 0.5992
valid by edge head:
  binary       acc=0.9717 (791/814)
  condition    acc=0.9755 (438/449)
  count        acc=0.6131 (225/367)
  density      acc=0.8295 (146/176)
valid by question type:
  Building_Condition_Recognition           acc=0.9375 (165/176)

T2: cap5 + LSTM + CE

In [ ]:
%cd /content/TinyDisasterVQA
%env PYTHONPATH=/content/TinyDisasterVQA/src
%env PYTHONUNBUFFERED=1

!python -u scripts/05_train_teacher.py \
  --dataset-root dataset \
  --runs-dir /content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6 \
  --backbone convnext_tiny \
  --image-size 224 \
  --epochs 30 \
  --batch-size 64 \
  --eval-batch-size 64 \
  --num-workers 2 \
  --early-stopping-patience 5 \
  --early-stopping-min-delta 0.001 \
  --log-interval 5 \
  --pretrained \
  --train-csv outputs/training_data_cap5/train.csv \
  --valid-csv outputs/training_data_cap5/valid.csv \
  --test-csv outputs/training_data_cap5/test.csv \
  --metadata outputs/training_data_cap5/metadata.json \
  --class-weights outputs/answer_space_cap5/class_weights_edge_global_by_label.json \
  --run-name T2_cap5_lstm_ce \
  --question-encoder lstm \
  --loss-mode ce

/content/TinyDisasterVQA
env: PYTHONPATH=/content/TinyDisasterVQA/src
env: PYTHONUNBUFFERED=1
================================================================================
TinyDisasterVQA / Train Teacher
================================================================================
Run dir:          /content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6/T2_cap5_lstm_ce
Device:           cuda
Backbone:         convnext_tiny
Pretrained:       True
Question encoder: lstm
Loss mode:        ce
Count aux weight: 0.0
AMP:              True
Image size:       224
Batch size:       64
Eval batch:       64
Augment train:    True
Epochs:           30
LR:               0.0001
Weight decay:     0.0001
Freeze image:     False
Count cap:        5
Num classes:      14
Count classes:    6
Count head id:    3

Model summary
================================================================================
Class:             TeacherVQA
Total params:      28,881,518
Trainable params:  28,881,518
FP32 param size:   110.17 MB
Int8 param size:   28204.6 KB
Image backbone:    convnext_tiny
Pretrained:        True
Image feature dim: 768
Question encoder:  lstm
Question dim:      256
Num classes:       14
Count aux:         False


================================================================================
Epoch 1/30
================================================================================
Epoch 001 | step 0001/0093 | loss=2.6338 | main=2.6338 | aux=0.0000 | acc=0.0312 | binary=0.000 | condition=0.100 | count=0.000 | density=0.000 | time=33.8s
Epoch 001 | step 0005/0093 | loss=2.6059 | main=2.6059 | aux=0.0000 | acc=0.1313 | binary=0.137 | condition=0.268 | count=0.025 | density=0.030 | time=35.1s
Epoch 001 | step 0010/0093 | loss=2.5342 | main=2.5342 | aux=0.0000 | acc=0.1922 | binary=0.240 | condition=0.340 | count=0.014 | density=0.016 | time=36.9s
Epoch 001 | step 0015/0093 | loss=2.4728 | main=2.4728 | aux=0.0000 | acc=0.2240 | binary=0.304 | condition=0.365 | count=0.010 | density=0.010 | time=38.7s
Epoch 001 | step 0020/0093 | loss=2.4048 | main=2.4048 | aux=0.0000 | acc=0.2375 | binary=0.326 | condition=0.376 | count=0.007 | density=0.008 | time=40.5s
Epoch 001 | step 0025/0093 | loss=2.3588 | main=2.3588 | aux=0.0000 | acc=0.2400 | binary=0.341 | condition=0.356 | count=0.006 | density=0.006 | time=42.4s
Epoch 001 | step 0030/0093 | loss=2.3147 | main=2.3147 | aux=0.0000 | acc=0.2458 | binary=0.358 | condition=0.347 | count=0.005 | density=0.005 | time=44.2s
Epoch 001 | step 0035/0093 | loss=2.2764 | main=2.2764 | aux=0.0000 | acc=0.2549 | binary=0.371 | condition=0.356 | count=0.004 | density=0.004 | time=46.0s
Epoch 001 | step 0040/0093 | loss=2.2415 | main=2.2415 | aux=0.0000 | acc=0.2664 | binary=0.367 | condition=0.405 | count=0.004 | density=0.004 | time=47.8s
Epoch 001 | step 0045/0093 | loss=2.2151 | main=2.2151 | aux=0.0000 | acc=0.2774 | binary=0.374 | condition=0.437 | count=0.005 | density=0.003 | time=49.6s
Epoch 001 | step 0050/0093 | loss=2.1926 | main=2.1926 | aux=0.0000 | acc=0.2756 | binary=0.370 | condition=0.441 | count=0.005 | density=0.003 | time=51.5s
Epoch 001 | step 0055/0093 | loss=2.1615 | main=2.1615 | aux=0.0000 | acc=0.2835 | binary=0.381 | condition=0.447 | count=0.007 | density=0.003 | time=53.4s
Epoch 001 | step 0060/0093 | loss=2.1366 | main=2.1366 | aux=0.0000 | acc=0.2927 | binary=0.392 | condition=0.462 | count=0.013 | density=0.003 | time=55.3s
Epoch 001 | step 0065/0093 | loss=2.1106 | main=2.1106 | aux=0.0000 | acc=0.3072 | binary=0.405 | condition=0.490 | count=0.020 | density=0.002 | time=57.2s
Epoch 001 | step 0070/0093 | loss=2.0780 | main=2.0780 | aux=0.0000 | acc=0.3210 | binary=0.414 | condition=0.522 | count=0.025 | density=0.002 | time=58.9s
Epoch 001 | step 0075/0093 | loss=2.0542 | main=2.0542 | aux=0.0000 | acc=0.3285 | binary=0.420 | condition=0.533 | count=0.037 | density=0.004 | time=1.0min
Epoch 001 | step 0080/0093 | loss=2.0261 | main=2.0261 | aux=0.0000 | acc=0.3395 | binary=0.429 | condition=0.554 | count=0.042 | density=0.004 | time=1.0min
Epoch 001 | step 0085/0093 | loss=1.9963 | main=1.9963 | aux=0.0000 | acc=0.3513 | binary=0.443 | condition=0.574 | count=0.046 | density=0.004 | time=1.1min
Epoch 001 | step 0090/0093 | loss=1.9664 | main=1.9664 | aux=0.0000 | acc=0.3602 | binary=0.449 | condition=0.591 | count=0.056 | density=0.004 | time=1.1min
Epoch 001 | step 0093/0093 | loss=1.9500 | main=1.9500 | aux=0.0000 | acc=0.3644 | binary=0.454 | condition=0.597 | count=0.056 | density=0.003 | time=1.5min

train overall: acc=0.3644 (2149/5898)
train macro acc: 0.1285
train by edge head:
  binary       acc=0.4537 (1195/2634)
  condition    acc=0.5973 (884/1480)
  count        acc=0.0565 (68/1204)
  density      acc=0.0034 (2/580)
train by question type:
  Building_Condition_Recognition           acc=0.4793 (278/580)
  Complex_Counting                         acc=0.0337 (21/624)
  Density_Estimation                       acc=0.0034 (2/580)
  Entire_Image_Condition_Recognition       acc=0.5264 (718/1364)
  Risk_Assessment                          acc=0.5707 (331/580)
  Road_Condition_Recognition               acc=0.4730 (752/1590)
  Simple_Counting                          acc=0.0810 (47/580)

valid overall: acc=0.5393 (974/1806)
valid macro acc: 0.2051
valid by edge head:
  binary       acc=0.6523 (531/814)
  condition    acc=0.8419 (378/449)
  count        acc=0.1771 (65/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.5114 (90/176)
  Complex_Counting                         acc=0.1361 (26/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.7845 (324/413)
  Risk_Assessment                          acc=0.9773 (172/176)
  Road_Condition_Recognition               acc=0.6486 (323/498)
  Simple_Counting                          acc=0.2216 (39/176)

Epoch 1 done | train_acc=0.3644 | valid_acc=0.5393 | best_valid_acc=0.5393 at epoch 1 | IMPROVED

================================================================================
Epoch 2/30
================================================================================
Epoch 002 | step 0001/0093 | loss=1.7271 | main=1.7271 | aux=0.0000 | acc=0.3594 | binary=0.448 | condition=0.692 | count=0.000 | density=0.143 | time=0.7s
Epoch 002 | step 0005/0093 | loss=1.3677 | main=1.3677 | aux=0.0000 | acc=0.5094 | binary=0.619 | condition=0.850 | count=0.047 | density=0.034 | time=2.2s
Epoch 002 | step 0010/0093 | loss=1.2855 | main=1.2855 | aux=0.0000 | acc=0.5266 | binary=0.603 | condition=0.838 | count=0.129 | density=0.038 | time=4.0s
Epoch 002 | step 0015/0093 | loss=1.2194 | main=1.2194 | aux=0.0000 | acc=0.5490 | binary=0.613 | condition=0.879 | count=0.145 | density=0.025 | time=5.8s
Epoch 002 | step 0020/0093 | loss=1.2127 | main=1.2127 | aux=0.0000 | acc=0.5516 | binary=0.614 | condition=0.896 | count=0.161 | density=0.018 | time=7.5s
Epoch 002 | step 0025/0093 | loss=1.2127 | main=1.2127 | aux=0.0000 | acc=0.5575 | binary=0.623 | condition=0.906 | count=0.175 | density=0.035 | time=9.3s
Epoch 002 | step 0030/0093 | loss=1.1940 | main=1.1940 | aux=0.0000 | acc=0.5578 | binary=0.619 | condition=0.912 | count=0.177 | density=0.035 | time=11.2s
Epoch 002 | step 0035/0093 | loss=1.1850 | main=1.1850 | aux=0.0000 | acc=0.5598 | binary=0.617 | condition=0.916 | count=0.191 | density=0.039 | time=13.1s
Epoch 002 | step 0040/0093 | loss=1.1713 | main=1.1713 | aux=0.0000 | acc=0.5617 | binary=0.621 | condition=0.922 | count=0.199 | density=0.038 | time=14.9s
Epoch 002 | step 0045/0093 | loss=1.1491 | main=1.1491 | aux=0.0000 | acc=0.5670 | binary=0.620 | condition=0.930 | count=0.209 | density=0.048 | time=16.7s
Epoch 002 | step 0050/0093 | loss=1.1414 | main=1.1414 | aux=0.0000 | acc=0.5719 | binary=0.630 | condition=0.932 | count=0.220 | density=0.065 | time=18.7s
Epoch 002 | step 0055/0093 | loss=1.1207 | main=1.1207 | aux=0.0000 | acc=0.5776 | binary=0.631 | condition=0.934 | count=0.241 | density=0.072 | time=20.6s
Epoch 002 | step 0060/0093 | loss=1.1123 | main=1.1123 | aux=0.0000 | acc=0.5794 | binary=0.633 | condition=0.935 | count=0.244 | density=0.087 | time=22.4s
Epoch 002 | step 0065/0093 | loss=1.0916 | main=1.0916 | aux=0.0000 | acc=0.5856 | binary=0.633 | condition=0.938 | count=0.253 | density=0.111 | time=24.2s
Epoch 002 | step 0070/0093 | loss=1.0809 | main=1.0809 | aux=0.0000 | acc=0.5871 | binary=0.631 | condition=0.938 | count=0.263 | density=0.118 | time=26.0s
Epoch 002 | step 0075/0093 | loss=1.0660 | main=1.0660 | aux=0.0000 | acc=0.5942 | binary=0.641 | condition=0.940 | count=0.279 | density=0.120 | time=27.8s
Epoch 002 | step 0080/0093 | loss=1.0501 | main=1.0501 | aux=0.0000 | acc=0.6018 | binary=0.648 | condition=0.943 | count=0.287 | density=0.137 | time=29.5s
Epoch 002 | step 0085/0093 | loss=1.0374 | main=1.0374 | aux=0.0000 | acc=0.6077 | binary=0.654 | condition=0.944 | count=0.297 | density=0.162 | time=31.2s
Epoch 002 | step 0090/0093 | loss=1.0253 | main=1.0253 | aux=0.0000 | acc=0.6137 | binary=0.664 | condition=0.945 | count=0.304 | density=0.172 | time=33.0s
Epoch 002 | step 0093/0093 | loss=1.0227 | main=1.0227 | aux=0.0000 | acc=0.6153 | binary=0.667 | condition=0.945 | count=0.308 | density=0.178 | time=33.8s

train overall: acc=0.6153 (3629/5898)
train macro acc: 0.3385
train by edge head:
  binary       acc=0.6667 (1756/2634)
  condition    acc=0.9453 (1399/1480)
  count        acc=0.3081 (371/1204)
  density      acc=0.1776 (103/580)
train by question type:
  Building_Condition_Recognition           acc=0.5983 (347/580)
  Complex_Counting                         acc=0.2821 (176/624)
  Density_Estimation                       acc=0.1776 (103/580)
  Entire_Image_Condition_Recognition       acc=0.8094 (1104/1364)
  Risk_Assessment                          acc=0.8155 (473/580)
  Road_Condition_Recognition               acc=0.7742 (1231/1590)
  Simple_Counting                          acc=0.3362 (195/580)

valid overall: acc=0.8156 (1473/1806)
valid macro acc: 0.5587
valid by edge head:
  binary       acc=0.9128 (743/814)
  condition    acc=0.9555 (429/449)
  count        acc=0.5640 (207/367)
  density      acc=0.5341 (94/176)
valid by question type:
  Building_Condition_Recognition           acc=0.8807 (155/176)
  Complex_Counting                         acc=0.5550 (106/191)
  Density_Estimation                       acc=0.5341 (94/176)
  Entire_Image_Condition_Recognition       acc=0.9540 (394/413)
  Risk_Assessment                          acc=0.9773 (172/176)
  Road_Condition_Recognition               acc=0.9056 (451/498)
  Simple_Counting                          acc=0.5739 (101/176)

Epoch 2 done | train_acc=0.6153 | valid_acc=0.8156 | best_valid_acc=0.8156 at epoch 2 | IMPROVED

================================================================================
Epoch 3/30
================================================================================
Epoch 003 | step 0001/0093 | loss=0.6770 | main=0.6770 | aux=0.0000 | acc=0.7969 | binary=0.880 | condition=0.909 | count=0.538 | density=0.500 | time=0.7s
Epoch 003 | step 0005/0093 | loss=0.6771 | main=0.6771 | aux=0.0000 | acc=0.8031 | binary=0.904 | condition=0.935 | count=0.554 | density=0.423 | time=2.1s
Epoch 003 | step 0010/0093 | loss=0.6999 | main=0.6999 | aux=0.0000 | acc=0.7766 | binary=0.870 | condition=0.953 | count=0.557 | density=0.367 | time=3.9s
Epoch 003 | step 0015/0093 | loss=0.7051 | main=0.7051 | aux=0.0000 | acc=0.7792 | binary=0.856 | condition=0.962 | count=0.553 | density=0.457 | time=5.7s
Epoch 003 | step 0020/0093 | loss=0.6996 | main=0.6996 | aux=0.0000 | acc=0.7750 | binary=0.845 | condition=0.958 | count=0.542 | density=0.496 | time=7.3s
Epoch 003 | step 0025/0093 | loss=0.6883 | main=0.6883 | aux=0.0000 | acc=0.7806 | binary=0.850 | condition=0.958 | count=0.533 | density=0.547 | time=8.9s
Epoch 003 | step 0030/0093 | loss=0.6672 | main=0.6672 | aux=0.0000 | acc=0.7865 | binary=0.847 | condition=0.960 | count=0.542 | density=0.572 | time=10.6s
Epoch 003 | step 0035/0093 | loss=0.6502 | main=0.6502 | aux=0.0000 | acc=0.7920 | binary=0.845 | condition=0.964 | count=0.550 | density=0.598 | time=12.3s
Epoch 003 | step 0040/0093 | loss=0.6535 | main=0.6535 | aux=0.0000 | acc=0.7871 | binary=0.840 | condition=0.963 | count=0.547 | density=0.602 | time=14.0s
Epoch 003 | step 0045/0093 | loss=0.6450 | main=0.6450 | aux=0.0000 | acc=0.7892 | binary=0.846 | condition=0.965 | count=0.540 | density=0.605 | time=15.7s
Epoch 003 | step 0050/0093 | loss=0.6261 | main=0.6261 | aux=0.0000 | acc=0.7963 | binary=0.853 | condition=0.967 | count=0.549 | density=0.615 | time=17.6s
Epoch 003 | step 0055/0093 | loss=0.6206 | main=0.6206 | aux=0.0000 | acc=0.7972 | binary=0.853 | condition=0.964 | count=0.558 | density=0.615 | time=19.6s
Epoch 003 | step 0060/0093 | loss=0.6089 | main=0.6089 | aux=0.0000 | acc=0.8016 | binary=0.859 | condition=0.964 | count=0.559 | density=0.631 | time=21.6s
Epoch 003 | step 0065/0093 | loss=0.5924 | main=0.5924 | aux=0.0000 | acc=0.8075 | binary=0.862 | condition=0.965 | count=0.566 | density=0.650 | time=23.4s
Epoch 003 | step 0070/0093 | loss=0.5819 | main=0.5819 | aux=0.0000 | acc=0.8107 | binary=0.864 | condition=0.966 | count=0.570 | density=0.669 | time=25.1s
Epoch 003 | step 0075/0093 | loss=0.5757 | main=0.5757 | aux=0.0000 | acc=0.8121 | binary=0.867 | condition=0.965 | count=0.566 | density=0.679 | time=26.8s
Epoch 003 | step 0080/0093 | loss=0.5747 | main=0.5747 | aux=0.0000 | acc=0.8141 | binary=0.869 | condition=0.966 | count=0.572 | density=0.678 | time=28.6s
Epoch 003 | step 0085/0093 | loss=0.5696 | main=0.5696 | aux=0.0000 | acc=0.8160 | binary=0.871 | condition=0.967 | count=0.566 | density=0.690 | time=30.3s
Epoch 003 | step 0090/0093 | loss=0.5638 | main=0.5638 | aux=0.0000 | acc=0.8179 | binary=0.875 | condition=0.968 | count=0.566 | density=0.696 | time=32.0s
Epoch 003 | step 0093/0093 | loss=0.5624 | main=0.5624 | aux=0.0000 | acc=0.8172 | binary=0.875 | condition=0.966 | count=0.565 | density=0.700 | time=32.7s

train overall: acc=0.8172 (4820/5898)
train macro acc: 0.5980
train by edge head:
  binary       acc=0.8747 (2304/2634)
  condition    acc=0.9662 (1430/1480)
  count        acc=0.5648 (680/1204)
  density      acc=0.7000 (406/580)
train by question type:
  Building_Condition_Recognition           acc=0.8517 (494/580)
  Complex_Counting                         acc=0.5417 (338/624)
  Density_Estimation                       acc=0.7000 (406/580)
  Entire_Image_Condition_Recognition       acc=0.9355 (1276/1364)
  Risk_Assessment                          acc=0.9000 (522/580)
  Road_Condition_Recognition               acc=0.9069 (1442/1590)
  Simple_Counting                          acc=0.5897 (342/580)

valid overall: acc=0.8588 (1551/1806)
valid macro acc: 0.6523
valid by edge head:
  binary       acc=0.9214 (750/814)
  condition    acc=0.9755 (438/449)
  count        acc=0.5886 (216/367)
  density      acc=0.8352 (147/176)
valid by question type:
  Building_Condition_Recognition           acc=0.9034 (159/176)
  Complex_Counting                         acc=0.5812 (111/191)
  Density_Estimation                       acc=0.8352 (147/176)
  Entire_Image_Condition_Recognition       acc=0.9637 (398/413)
  Risk_Assessment                          acc=0.9886 (174/176)
  Road_Condition_Recognition               acc=0.9177 (457/498)
  Simple_Counting                          acc=0.5966 (105/176)

Epoch 3 done | train_acc=0.8172 | valid_acc=0.8588 | best_valid_acc=0.8588 at epoch 3 | IMPROVED

================================================================================
Epoch 4/30
================================================================================
Epoch 004 | step 0001/0093 | loss=0.3938 | main=0.3938 | aux=0.0000 | acc=0.8281 | binary=0.893 | condition=1.000 | count=0.500 | density=0.889 | time=0.7s
Epoch 004 | step 0005/0093 | loss=0.4318 | main=0.4318 | aux=0.0000 | acc=0.8531 | binary=0.918 | condition=1.000 | count=0.556 | density=0.914 | time=2.0s
Epoch 004 | step 0010/0093 | loss=0.3975 | main=0.3975 | aux=0.0000 | acc=0.8656 | binary=0.913 | condition=1.000 | count=0.599 | density=0.934 | time=3.7s
Epoch 004 | step 0015/0093 | loss=0.3978 | main=0.3978 | aux=0.0000 | acc=0.8667 | binary=0.921 | condition=1.000 | count=0.611 | density=0.864 | time=5.6s
Epoch 004 | step 0020/0093 | loss=0.3806 | main=0.3806 | aux=0.0000 | acc=0.8750 | binary=0.932 | condition=0.997 | count=0.615 | density=0.876 | time=7.4s
Epoch 004 | step 0025/0093 | loss=0.3750 | main=0.3750 | aux=0.0000 | acc=0.8800 | binary=0.936 | condition=0.995 | count=0.617 | density=0.895 | time=9.0s
Epoch 004 | step 0030/0093 | loss=0.3673 | main=0.3673 | aux=0.0000 | acc=0.8807 | binary=0.936 | condition=0.996 | count=0.616 | density=0.890 | time=10.8s
Epoch 004 | step 0035/0093 | loss=0.3668 | main=0.3668 | aux=0.0000 | acc=0.8772 | binary=0.933 | condition=0.994 | count=0.617 | density=0.884 | time=12.5s
Epoch 004 | step 0040/0093 | loss=0.3651 | main=0.3651 | aux=0.0000 | acc=0.8758 | binary=0.931 | condition=0.992 | count=0.608 | density=0.883 | time=14.3s
Epoch 004 | step 0045/0093 | loss=0.3579 | main=0.3579 | aux=0.0000 | acc=0.8823 | binary=0.934 | condition=0.990 | count=0.629 | density=0.891 | time=16.0s
Epoch 004 | step 0050/0093 | loss=0.3598 | main=0.3598 | aux=0.0000 | acc=0.8794 | binary=0.935 | condition=0.989 | count=0.625 | density=0.873 | time=17.8s
Epoch 004 | step 0055/0093 | loss=0.3524 | main=0.3524 | aux=0.0000 | acc=0.8821 | binary=0.937 | condition=0.987 | count=0.632 | density=0.878 | time=19.8s
Epoch 004 | step 0060/0093 | loss=0.3523 | main=0.3523 | aux=0.0000 | acc=0.8812 | binary=0.939 | condition=0.988 | count=0.628 | density=0.878 | time=21.9s
Epoch 004 | step 0065/0093 | loss=0.3499 | main=0.3499 | aux=0.0000 | acc=0.8837 | binary=0.942 | condition=0.986 | count=0.632 | density=0.883 | time=23.8s
Epoch 004 | step 0070/0093 | loss=0.3476 | main=0.3476 | aux=0.0000 | acc=0.8848 | binary=0.944 | condition=0.987 | count=0.635 | density=0.886 | time=25.6s
Epoch 004 | step 0075/0093 | loss=0.3404 | main=0.3404 | aux=0.0000 | acc=0.8875 | binary=0.945 | condition=0.987 | count=0.641 | density=0.890 | time=27.3s
Epoch 004 | step 0080/0093 | loss=0.3351 | main=0.3351 | aux=0.0000 | acc=0.8895 | binary=0.948 | condition=0.988 | count=0.644 | density=0.889 | time=29.1s
Epoch 004 | step 0085/0093 | loss=0.3356 | main=0.3356 | aux=0.0000 | acc=0.8893 | binary=0.949 | condition=0.988 | count=0.643 | density=0.879 | time=30.8s
Epoch 004 | step 0090/0093 | loss=0.3335 | main=0.3335 | aux=0.0000 | acc=0.8901 | binary=0.952 | condition=0.987 | count=0.644 | density=0.877 | time=32.5s
Epoch 004 | step 0093/0093 | loss=0.3316 | main=0.3316 | aux=0.0000 | acc=0.8906 | binary=0.953 | condition=0.987 | count=0.644 | density=0.876 | time=33.2s

train overall: acc=0.8906 (5253/5898)
train macro acc: 0.6932
train by edge head:
  binary       acc=0.9525 (2509/2634)
  condition    acc=0.9872 (1461/1480)
  count        acc=0.6437 (775/1204)
  density      acc=0.8759 (508/580)
train by question type:
  Building_Condition_Recognition           acc=0.9310 (540/580)
  Complex_Counting                         acc=0.6394 (399/624)
  Density_Estimation                       acc=0.8759 (508/580)
  Entire_Image_Condition_Recognition       acc=0.9692 (1322/1364)
  Risk_Assessment                          acc=0.9707 (563/580)
  Road_Condition_Recognition               acc=0.9717 (1545/1590)
  Simple_Counting                          acc=0.6483 (376/580)

valid overall: acc=0.8926 (1612/1806)
valid macro acc: 0.6758
valid by edge head:
  binary       acc=0.9717 (791/814)
  condition    acc=0.9777 (439/449)
  count        acc=0.6621 (243/367)
  density      acc=0.7898 (139/176)
valid by question type:
  Building_Condition_Recognition           acc=0.9375 (165/176)

T3:

In [ ]:
%cd /content/TinyDisasterVQA
%env PYTHONPATH=/content/TinyDisasterVQA/src
%env PYTHONUNBUFFERED=1

!python -u scripts/05_train_teacher.py \
  --dataset-root dataset \
  --runs-dir /content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6 \
  --backbone convnext_tiny \
  --image-size 224 \
  --epochs 30 \
  --batch-size 64 \
  --eval-batch-size 64 \
  --num-workers 2 \
  --early-stopping-patience 5 \
  --early-stopping-min-delta 0.001 \
  --log-interval 5 \
  --pretrained \
  --train-csv outputs/training_data_cap10/train.csv \
  --valid-csv outputs/training_data_cap10/valid.csv \
  --test-csv outputs/training_data_cap10/test.csv \
  --metadata outputs/training_data_cap10/metadata.json \
  --class-weights outputs/answer_space_cap10/class_weights_edge_global_by_label.json \
  --run-name T3_cap10_template_ce \
  --question-encoder template \
  --loss-mode ce

/content/TinyDisasterVQA
env: PYTHONPATH=/content/TinyDisasterVQA/src
env: PYTHONUNBUFFERED=1
================================================================================
TinyDisasterVQA / Train Teacher
================================================================================
Run dir:          /content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6/T3_cap10_template_ce
Device:           cuda
Backbone:         convnext_tiny
Pretrained:       True
Question encoder: template
Loss mode:        ce
Count aux weight: 0.0
AMP:              True
Image size:       224
Batch size:       64
Eval batch:       64
Augment train:    True
Epochs:           30
LR:               0.0001
Weight decay:     0.0001
Freeze image:     False
Count cap:        10
Num classes:      19
Count classes:    11
Count head id:    3

Model summary
================================================================================
Class:             TeacherVQA
Total params:      28,419,571
Trainable params:  28,419,571
FP32 param size:   108.41 MB
Int8 param size:   27753.5 KB
Image backbone:    convnext_tiny
Pretrained:        True
Image feature dim: 768
Question encoder:  template
Question dim:      128
Num classes:       19
Count aux:         False


================================================================================
Epoch 1/30
================================================================================
Epoch 001 | step 0001/0093 | loss=2.9517 | main=2.9517 | aux=0.0000 | acc=0.0312 | binary=0.074 | condition=0.000 | count=0.000 | density=0.000 | time=33.5s
Epoch 001 | step 0005/0093 | loss=2.8597 | main=2.8597 | aux=0.0000 | acc=0.1531 | binary=0.298 | condition=0.015 | count=0.000 | density=0.000 | time=35.0s
Epoch 001 | step 0010/0093 | loss=2.7519 | main=2.7519 | aux=0.0000 | acc=0.2031 | binary=0.401 | condition=0.030 | count=0.000 | density=0.000 | time=36.8s
Epoch 001 | step 0015/0093 | loss=2.6378 | main=2.6378 | aux=0.0000 | acc=0.2208 | binary=0.450 | condition=0.040 | count=0.000 | density=0.000 | time=38.5s
Epoch 001 | step 0020/0093 | loss=2.5287 | main=2.5287 | aux=0.0000 | acc=0.2422 | binary=0.471 | condition=0.089 | count=0.000 | density=0.000 | time=40.3s
Epoch 001 | step 0025/0093 | loss=2.4618 | main=2.4618 | aux=0.0000 | acc=0.2550 | binary=0.493 | condition=0.115 | count=0.000 | density=0.000 | time=42.1s
Epoch 001 | step 0030/0093 | loss=2.4231 | main=2.4231 | aux=0.0000 | acc=0.2729 | binary=0.506 | condition=0.178 | count=0.000 | density=0.000 | time=43.9s
Epoch 001 | step 0035/0093 | loss=2.3704 | main=2.3704 | aux=0.0000 | acc=0.2911 | binary=0.514 | condition=0.238 | count=0.000 | density=0.000 | time=45.8s
Epoch 001 | step 0040/0093 | loss=2.3210 | main=2.3210 | aux=0.0000 | acc=0.3074 | binary=0.528 | condition=0.278 | count=0.000 | density=0.000 | time=47.6s
Epoch 001 | step 0045/0093 | loss=2.2803 | main=2.2803 | aux=0.0000 | acc=0.3219 | binary=0.540 | condition=0.321 | count=0.000 | density=0.000 | time=49.5s
Epoch 001 | step 0050/0093 | loss=2.2354 | main=2.2354 | aux=0.0000 | acc=0.3369 | binary=0.545 | condition=0.374 | count=0.002 | density=0.000 | time=51.3s
Epoch 001 | step 0055/0093 | loss=2.2002 | main=2.2002 | aux=0.0000 | acc=0.3480 | binary=0.546 | condition=0.423 | count=0.003 | density=0.000 | time=53.1s
Epoch 001 | step 0060/0093 | loss=2.1742 | main=2.1742 | aux=0.0000 | acc=0.3576 | binary=0.561 | condition=0.435 | count=0.011 | density=0.000 | time=54.9s
Epoch 001 | step 0065/0093 | loss=2.1385 | main=2.1385 | aux=0.0000 | acc=0.3714 | binary=0.573 | condition=0.469 | count=0.015 | density=0.000 | time=56.6s
Epoch 001 | step 0070/0093 | loss=2.1017 | main=2.1017 | aux=0.0000 | acc=0.3855 | binary=0.586 | condition=0.501 | count=0.015 | density=0.000 | time=58.3s
Epoch 001 | step 0075/0093 | loss=2.0639 | main=2.0639 | aux=0.0000 | acc=0.3998 | binary=0.595 | condition=0.532 | count=0.020 | density=0.000 | time=1.0min
Epoch 001 | step 0080/0093 | loss=2.0234 | main=2.0234 | aux=0.0000 | acc=0.4135 | binary=0.608 | condition=0.556 | count=0.020 | density=0.000 | time=1.0min
Epoch 001 | step 0085/0093 | loss=1.9917 | main=1.9917 | aux=0.0000 | acc=0.4243 | binary=0.620 | condition=0.578 | count=0.020 | density=0.000 | time=1.1min
Epoch 001 | step 0090/0093 | loss=1.9608 | main=1.9608 | aux=0.0000 | acc=0.4354 | binary=0.632 | condition=0.595 | count=0.021 | density=0.000 | time=1.1min
Epoch 001 | step 0093/0093 | loss=1.9456 | main=1.9456 | aux=0.0000 | acc=0.4396 | binary=0.635 | condition=0.605 | count=0.021 | density=0.000 | time=1.5min

train overall: acc=0.4396 (2593/5898)
train macro acc: 0.1132
train by edge head:
  binary       acc=0.6352 (1673/2634)
  condition    acc=0.6047 (895/1480)
  count        acc=0.0208 (25/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.5776 (335/580)
  Complex_Counting                         acc=0.0208 (13/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.6356 (867/1364)
  Risk_Assessment                          acc=0.6845 (397/580)
  Road_Condition_Recognition               acc=0.6094 (969/1590)
  Simple_Counting                          acc=0.0207 (12/580)

valid overall: acc=0.6080 (1098/1806)
valid macro acc: 0.1915
valid by edge head:
  binary       acc=0.8292 (675/814)
  condition    acc=0.8820 (396/449)
  count        acc=0.0736 (27/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.8182 (144/176)
  Complex_Counting                         acc=0.0366 (7/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.8789 (363/413)
  Risk_Assessment                          acc=0.7841 (138/176)
  Road_Condition_Recognition               acc=0.8554 (426/498)
  Simple_Counting                          acc=0.1136 (20/176)

Epoch 1 done | train_acc=0.4396 | valid_acc=0.6080 | best_valid_acc=0.6080 at epoch 1 | IMPROVED

================================================================================
Epoch 2/30
================================================================================
Epoch 002 | step 0001/0093 | loss=1.3863 | main=1.3863 | aux=0.0000 | acc=0.5781 | binary=0.742 | condition=1.000 | count=0.077 | density=0.000 | time=0.8s
Epoch 002 | step 0005/0093 | loss=1.3168 | main=1.3168 | aux=0.0000 | acc=0.6188 | binary=0.850 | condition=0.913 | count=0.065 | density=0.028 | time=2.1s
Epoch 002 | step 0010/0093 | loss=1.3238 | main=1.3238 | aux=0.0000 | acc=0.6328 | binary=0.891 | condition=0.902 | count=0.096 | density=0.128 | time=3.8s
Epoch 002 | step 0015/0093 | loss=1.2735 | main=1.2735 | aux=0.0000 | acc=0.6490 | binary=0.870 | condition=0.918 | count=0.114 | density=0.157 | time=5.5s
Epoch 002 | step 0020/0093 | loss=1.2881 | main=1.2881 | aux=0.0000 | acc=0.6492 | binary=0.874 | condition=0.920 | count=0.121 | density=0.157 | time=7.3s
Epoch 002 | step 0025/0093 | loss=1.2738 | main=1.2738 | aux=0.0000 | acc=0.6519 | binary=0.863 | condition=0.928 | count=0.107 | density=0.198 | time=9.1s
Epoch 002 | step 0030/0093 | loss=1.2616 | main=1.2616 | aux=0.0000 | acc=0.6536 | binary=0.859 | condition=0.938 | count=0.103 | density=0.224 | time=11.1s
Epoch 002 | step 0035/0093 | loss=1.2362 | main=1.2362 | aux=0.0000 | acc=0.6513 | binary=0.848 | condition=0.937 | count=0.097 | density=0.235 | time=13.2s
Epoch 002 | step 0040/0093 | loss=1.2207 | main=1.2207 | aux=0.0000 | acc=0.6570 | binary=0.854 | condition=0.939 | count=0.108 | density=0.261 | time=15.2s
Epoch 002 | step 0045/0093 | loss=1.2061 | main=1.2061 | aux=0.0000 | acc=0.6580 | binary=0.852 | condition=0.943 | count=0.107 | density=0.275 | time=17.0s
Epoch 002 | step 0050/0093 | loss=1.1738 | main=1.1738 | aux=0.0000 | acc=0.6647 | binary=0.850 | condition=0.948 | count=0.121 | density=0.289 | time=18.8s
Epoch 002 | step 0055/0093 | loss=1.1488 | main=1.1488 | aux=0.0000 | acc=0.6733 | binary=0.856 | condition=0.950 | count=0.137 | density=0.305 | time=20.6s
Epoch 002 | step 0060/0093 | loss=1.1330 | main=1.1330 | aux=0.0000 | acc=0.6786 | binary=0.857 | condition=0.953 | count=0.147 | density=0.323 | time=22.4s
Epoch 002 | step 0065/0093 | loss=1.1170 | main=1.1170 | aux=0.0000 | acc=0.6832 | binary=0.860 | condition=0.955 | count=0.157 | density=0.337 | time=24.2s
Epoch 002 | step 0070/0093 | loss=1.0960 | main=1.0960 | aux=0.0000 | acc=0.6891 | binary=0.861 | condition=0.955 | count=0.167 | density=0.348 | time=26.0s
Epoch 002 | step 0075/0093 | loss=1.0849 | main=1.0849 | aux=0.0000 | acc=0.6908 | binary=0.861 | condition=0.950 | count=0.169 | density=0.372 | time=27.9s
Epoch 002 | step 0080/0093 | loss=1.0734 | main=1.0734 | aux=0.0000 | acc=0.6937 | binary=0.860 | condition=0.948 | count=0.175 | density=0.384 | time=29.7s
Epoch 002 | step 0085/0093 | loss=1.0552 | main=1.0552 | aux=0.0000 | acc=0.6996 | binary=0.862 | condition=0.949 | count=0.177 | density=0.406 | time=31.4s
Epoch 002 | step 0090/0093 | loss=1.0466 | main=1.0466 | aux=0.0000 | acc=0.7012 | binary=0.862 | condition=0.951 | count=0.179 | density=0.420 | time=33.1s
Epoch 002 | step 0093/0093 | loss=1.0376 | main=1.0376 | aux=0.0000 | acc=0.7040 | binary=0.862 | condition=0.952 | count=0.187 | density=0.426 | time=33.8s

train overall: acc=0.7040 (4152/5898)
train macro acc: 0.3035
train by edge head:
  binary       acc=0.8622 (2271/2634)
  condition    acc=0.9520 (1409/1480)
  count        acc=0.1869 (225/1204)
  density      acc=0.4259 (247/580)
train by question type:
  Building_Condition_Recognition           acc=0.8603 (499/580)
  Complex_Counting                         acc=0.1442 (90/624)
  Density_Estimation                       acc=0.4259 (247/580)
  Entire_Image_Condition_Recognition       acc=0.9238 (1260/1364)
  Risk_Assessment                          acc=0.8552 (496/580)
  Road_Condition_Recognition               acc=0.8962 (1425/1590)
  Simple_Counting                          acc=0.2328 (135/580)

valid overall: acc=0.7890 (1425/1806)
valid macro acc: 0.4950
valid by edge head:
  binary       acc=0.8280 (674/814)
  condition    acc=0.9577 (430/449)
  count        acc=0.4986 (183/367)
  density      acc=0.7841 (138/176)
valid by question type:
  Building_Condition_Recognition           acc=0.8182 (144/176)
  Complex_Counting                         acc=0.4764 (91/191)
  Density_Estimation                       acc=0.7841 (138/176)
  Entire_Image_Condition_Recognition       acc=0.9225 (381/413)
  Risk_Assessment                          acc=0.7784 (137/176)
  Road_Condition_Recognition               acc=0.8876 (442/498)
  Simple_Counting                          acc=0.5227 (92/176)

Epoch 2 done | train_acc=0.7040 | valid_acc=0.7890 | best_valid_acc=0.7890 at epoch 2 | IMPROVED

================================================================================
Epoch 3/30
================================================================================
Epoch 003 | step 0001/0093 | loss=0.7982 | main=0.7982 | aux=0.0000 | acc=0.7031 | binary=0.829 | condition=1.000 | count=0.083 | density=0.333 | time=0.7s
Epoch 003 | step 0005/0093 | loss=0.8280 | main=0.8280 | aux=0.0000 | acc=0.7438 | binary=0.856 | condition=0.978 | count=0.250 | density=0.571 | time=2.1s
Epoch 003 | step 0010/0093 | loss=0.8212 | main=0.8212 | aux=0.0000 | acc=0.7594 | binary=0.872 | condition=0.970 | count=0.341 | density=0.610 | time=3.7s
Epoch 003 | step 0015/0093 | loss=0.8002 | main=0.8002 | aux=0.0000 | acc=0.7729 | binary=0.886 | condition=0.964 | count=0.365 | density=0.680 | time=5.3s
Epoch 003 | step 0020/0093 | loss=0.7808 | main=0.7808 | aux=0.0000 | acc=0.7727 | binary=0.878 | condition=0.969 | count=0.363 | density=0.699 | time=7.0s
Epoch 003 | step 0025/0093 | loss=0.7630 | main=0.7630 | aux=0.0000 | acc=0.7762 | binary=0.881 | condition=0.971 | count=0.375 | density=0.694 | time=8.6s
Epoch 003 | step 0030/0093 | loss=0.7427 | main=0.7427 | aux=0.0000 | acc=0.7828 | binary=0.886 | condition=0.971 | count=0.379 | density=0.711 | time=10.2s
Epoch 003 | step 0035/0093 | loss=0.7371 | main=0.7371 | aux=0.0000 | acc=0.7808 | binary=0.884 | condition=0.970 | count=0.382 | density=0.693 | time=12.1s
Epoch 003 | step 0040/0093 | loss=0.7241 | main=0.7241 | aux=0.0000 | acc=0.7824 | binary=0.880 | condition=0.973 | count=0.388 | density=0.700 | time=14.0s
Epoch 003 | step 0045/0093 | loss=0.7136 | main=0.7136 | aux=0.0000 | acc=0.7878 | binary=0.883 | condition=0.974 | count=0.399 | density=0.701 | time=16.0s
Epoch 003 | step 0050/0093 | loss=0.7059 | main=0.7059 | aux=0.0000 | acc=0.7922 | binary=0.885 | condition=0.973 | count=0.411 | density=0.713 | time=17.7s
Epoch 003 | step 0055/0093 | loss=0.6928 | main=0.6928 | aux=0.0000 | acc=0.7969 | binary=0.887 | condition=0.974 | count=0.429 | density=0.720 | time=19.4s
Epoch 003 | step 0060/0093 | loss=0.6827 | main=0.6827 | aux=0.0000 | acc=0.8008 | binary=0.890 | condition=0.974 | count=0.436 | density=0.728 | time=21.1s
Epoch 003 | step 0065/0093 | loss=0.6717 | main=0.6717 | aux=0.0000 | acc=0.8041 | binary=0.893 | condition=0.975 | count=0.442 | density=0.726 | time=22.8s
Epoch 003 | step 0070/0093 | loss=0.6706 | main=0.6706 | aux=0.0000 | acc=0.8051 | binary=0.895 | condition=0.976 | count=0.441 | density=0.723 | time=24.5s
Epoch 003 | step 0075/0093 | loss=0.6587 | main=0.6587 | aux=0.0000 | acc=0.8081 | binary=0.899 | condition=0.975 | count=0.443 | density=0.720 | time=26.3s
Epoch 003 | step 0080/0093 | loss=0.6521 | main=0.6521 | aux=0.0000 | acc=0.8090 | binary=0.899 | condition=0.976 | count=0.439 | density=0.728 | time=28.3s
Epoch 003 | step 0085/0093 | loss=0.6494 | main=0.6494 | aux=0.0000 | acc=0.8086 | binary=0.899 | condition=0.975 | count=0.442 | density=0.732 | time=30.3s
Epoch 003 | step 0090/0093 | loss=0.6446 | main=0.6446 | aux=0.0000 | acc=0.8085 | binary=0.900 | condition=0.976 | count=0.439 | density=0.733 | time=32.0s
Epoch 003 | step 0093/0093 | loss=0.6426 | main=0.6426 | aux=0.0000 | acc=0.8093 | binary=0.899 | condition=0.976 | count=0.444 | density=0.734 | time=32.7s

train overall: acc=0.8093 (4773/5898)
train macro acc: 0.4521
train by edge head:
  binary       acc=0.8994 (2369/2634)
  condition    acc=0.9757 (1444/1480)
  count        acc=0.4435 (534/1204)
  density      acc=0.7345 (426/580)
train by question type:
  Building_Condition_Recognition           acc=0.8931 (518/580)
  Complex_Counting                         acc=0.4071 (254/624)
  Density_Estimation                       acc=0.7345 (426/580)
  Entire_Image_Condition_Recognition       acc=0.9399 (1282/1364)
  Risk_Assessment                          acc=0.9190 (533/580)
  Road_Condition_Recognition               acc=0.9308 (1480/1590)
  Simple_Counting                          acc=0.4828 (280/580)

valid overall: acc=0.8511 (1537/1806)
valid macro acc: 0.5451
valid by edge head:
  binary       acc=0.9165 (746/814)
  condition    acc=0.9733 (437/449)
  count        acc=0.5504 (202/367)
  density      acc=0.8636 (152/176)
valid by question type:
  Building_Condition_Recognition           acc=0.9148 (161/176)
  Complex_Counting                         acc=0.5288 (101/191)
  Density_Estimation                       acc=0.8636 (152/176)
  Entire_Image_Condition_Recognition       acc=0.9492 (392/413)
  Risk_Assessment                          acc=0.8409 (148/176)
  Road_Condition_Recognition               acc=0.9679 (482/498)
  Simple_Counting                          acc=0.5739 (101/176)

Epoch 3 done | train_acc=0.8093 | valid_acc=0.8511 | best_valid_acc=0.8511 at epoch 3 | IMPROVED

================================================================================
Epoch 4/30
================================================================================
Epoch 004 | step 0001/0093 | loss=0.4523 | main=0.4523 | aux=0.0000 | acc=0.9062 | binary=0.929 | condition=1.000 | count=0.700 | density=0.857 | time=1.0s
Epoch 004 | step 0005/0093 | loss=0.5494 | main=0.5494 | aux=0.0000 | acc=0.8187 | binary=0.891 | condition=1.000 | count=0.541 | density=0.735 | time=2.5s
Epoch 004 | step 0010/0093 | loss=0.5115 | main=0.5115 | aux=0.0000 | acc=0.8375 | binary=0.911 | condition=0.993 | count=0.573 | density=0.746 | time=4.1s
Epoch 004 | step 0015/0093 | loss=0.5353 | main=0.5353 | aux=0.0000 | acc=0.8354 | binary=0.909 | condition=0.987 | count=0.558 | density=0.778 | time=5.8s
Epoch 004 | step 0020/0093 | loss=0.5159 | main=0.5159 | aux=0.0000 | acc=0.8422 | binary=0.915 | condition=0.990 | count=0.553 | density=0.778 | time=7.5s
Epoch 004 | step 0025/0093 | loss=0.5134 | main=0.5134 | aux=0.0000 | acc=0.8494 | binary=0.919 | condition=0.988 | count=0.562 | density=0.809 | time=9.1s
Epoch 004 | step 0030/0093 | loss=0.5034 | main=0.5034 | aux=0.0000 | acc=0.8495 | binary=0.921 | condition=0.987 | count=0.552 | density=0.811 | time=10.9s
Epoch 004 | step 0035/0093 | loss=0.5027 | main=0.5027 | aux=0.0000 | acc=0.8509 | binary=0.925 | condition=0.986 | count=0.552 | density=0.811 | time=12.6s
Epoch 004 | step 0040/0093 | loss=0.4987 | main=0.4987 | aux=0.0000 | acc=0.8527 | binary=0.929 | condition=0.988 | count=0.550 | density=0.823 | time=14.6s
Epoch 004 | step 0045/0093 | loss=0.4956 | main=0.4956 | aux=0.0000 | acc=0.8528 | binary=0.931 | condition=0.988 | count=0.549 | density=0.818 | time=16.5s
Epoch 004 | step 0050/0093 | loss=0.4859 | main=0.4859 | aux=0.0000 | acc=0.8534 | binary=0.931 | condition=0.989 | count=0.543 | density=0.819 | time=18.4s
Epoch 004 | step 0055/0093 | loss=0.4804 | main=0.4804 | aux=0.0000 | acc=0.8520 | binary=0.929 | condition=0.988 | count=0.539 | density=0.819 | time=20.2s
Epoch 004 | step 0060/0093 | loss=0.4793 | main=0.4793 | aux=0.0000 | acc=0.8531 | binary=0.933 | condition=0.987 | count=0.539 | density=0.821 | time=21.9s
Epoch 004 | step 0065/0093 | loss=0.4803 | main=0.4803 | aux=0.0000 | acc=0.8526 | binary=0.933 | condition=0.986 | count=0.533 | density=0.820 | time=23.7s
Epoch 004 | step 0070/0093 | loss=0.4729 | main=0.4729 | aux=0.0000 | acc=0.8562 | binary=0.936 | condition=0.986 | count=0.540 | density=0.822 | time=25.4s
Epoch 004 | step 0075/0093 | loss=0.4727 | main=0.4727 | aux=0.0000 | acc=0.8579 | binary=0.937 | condition=0.985 | count=0.546 | density=0.829 | time=27.2s
Epoch 004 | step 0080/0093 | loss=0.4701 | main=0.4701 | aux=0.0000 | acc=0.8588 | binary=0.939 | condition=0.985 | count=0.546 | density=0.831 | time=29.1s
Epoch 004 | step 0085/0093 | loss=0.4677 | main=0.4677 | aux=0.0000 | acc=0.8596 | binary=0.939 | condition=0.983 | count=0.548 | density=0.831 | time=31.0s
Epoch 004 | step 0090/0093 | loss=0.4663 | main=0.4663 | aux=0.0000 | acc=0.8604 | binary=0.941 | condition=0.983 | count=0.546 | density=0.835 | time=33.0s
Epoch 004 | step 0093/0093 | loss=0.4657 | main=0.4657 | aux=0.0000 | acc=0.8603 | binary=0.940 | condition=0.983 | count=0.548 | density=0.833 | time=33.7s

train overall: acc=0.8603 (5074/5898)
train macro acc: 0.5217
train by edge head:
  binary       acc=0.9400 (2476/2634)
  condition    acc=0.9831 (1455/1480)
  count        acc=0.5482 (660/1204)
  density      acc=0.8328 (483/580)
train by question type:
  Building_Condition_Recognition           acc=0.9224 (535/580)
  Complex_Counting                         acc=0.5353 (334/624)
  Density_Estimation                       acc=0.8328 (483/580)
  Entire_Image_Condition_Recognition       acc=0.9604 (1310/1364)
  Risk_Assessment                          acc=0.9500 (551/580)
  Road_Condition_Recognition               acc=0.9654 (1535/1590)
  Simple_Counting                          acc=0.5621 (326/580)

valid overall: acc=0.8754 (1581/1806)
valid macro acc: 0.5635
valid by edge head:
  binary       acc=0.9631 (784/814)
  condition    acc=0.9800 (440/449)
  count        acc=0.5777 (212/367)
  density      acc=0.8239 (145/176)
valid by question type:

T4

In [ ]:
%cd /content/TinyDisasterVQA
%env PYTHONPATH=/content/TinyDisasterVQA/src
%env PYTHONUNBUFFERED=1

!python -u scripts/05_train_teacher.py \
  --dataset-root dataset \
  --runs-dir /content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6 \
  --backbone convnext_tiny \
  --image-size 224 \
  --epochs 30 \
  --batch-size 64 \
  --eval-batch-size 64 \
  --num-workers 2 \
  --early-stopping-patience 5 \
  --early-stopping-min-delta 0.001 \
  --log-interval 5 \
  --pretrained \
  --train-csv outputs/training_data_cap5/train.csv \
  --valid-csv outputs/training_data_cap5/valid.csv \
  --test-csv outputs/training_data_cap5/test.csv \
  --metadata outputs/training_data_cap5/metadata.json \
  --class-weights outputs/answer_space_cap5/class_weights_edge_global_by_label.json \
  --run-name T4_cap5_template_ce \
  --question-encoder template \
  --loss-mode ce

/content/TinyDisasterVQA
env: PYTHONPATH=/content/TinyDisasterVQA/src
env: PYTHONUNBUFFERED=1
================================================================================
TinyDisasterVQA / Train Teacher
================================================================================
Run dir:          /content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6/T4_cap5_template_ce
Device:           cuda
Backbone:         convnext_tiny
Pretrained:       True
Question encoder: template
Loss mode:        ce
Count aux weight: 0.0
AMP:              True
Image size:       224
Batch size:       64
Eval batch:       64
Augment train:    True
Epochs:           30
LR:               0.0001
Weight decay:     0.0001
Freeze image:     False
Count cap:        5
Num classes:      14
Count classes:    6
Count head id:    3

Model summary
================================================================================
Class:             TeacherVQA
Total params:      28,418,286
Trainable params:  28,418,286
FP32 param size:   108.41 MB
Int8 param size:   27752.2 KB
Image backbone:    convnext_tiny
Pretrained:        True
Image feature dim: 768
Question encoder:  template
Question dim:      128
Num classes:       14
Count aux:         False


================================================================================
Epoch 1/30
================================================================================
Epoch 001 | step 0001/0093 | loss=2.6385 | main=2.6385 | aux=0.0000 | acc=0.0938 | binary=0.208 | condition=0.000 | count=0.071 | density=0.000 | time=33.1s
Epoch 001 | step 0005/0093 | loss=2.5776 | main=2.5776 | aux=0.0000 | acc=0.2156 | binary=0.423 | condition=0.069 | count=0.068 | density=0.026 | time=34.5s
Epoch 001 | step 0010/0093 | loss=2.4845 | main=2.4845 | aux=0.0000 | acc=0.2625 | binary=0.493 | condition=0.175 | count=0.036 | density=0.016 | time=36.2s
Epoch 001 | step 0015/0093 | loss=2.3932 | main=2.3932 | aux=0.0000 | acc=0.2823 | binary=0.485 | condition=0.282 | count=0.024 | density=0.010 | time=38.0s
Epoch 001 | step 0020/0093 | loss=2.3154 | main=2.3154 | aux=0.0000 | acc=0.3047 | binary=0.490 | condition=0.357 | count=0.018 | density=0.008 | time=39.9s
Epoch 001 | step 0025/0093 | loss=2.2464 | main=2.2464 | aux=0.0000 | acc=0.3181 | binary=0.505 | condition=0.369 | count=0.015 | density=0.006 | time=41.7s
Epoch 001 | step 0030/0093 | loss=2.2063 | main=2.2063 | aux=0.0000 | acc=0.3286 | binary=0.527 | condition=0.376 | count=0.012 | density=0.005 | time=43.6s
Epoch 001 | step 0035/0093 | loss=2.1551 | main=2.1551 | aux=0.0000 | acc=0.3451 | binary=0.522 | condition=0.446 | count=0.011 | density=0.004 | time=45.4s
Epoch 001 | step 0040/0093 | loss=2.1368 | main=2.1368 | aux=0.0000 | acc=0.3523 | binary=0.523 | condition=0.481 | count=0.009 | density=0.004 | time=47.2s
Epoch 001 | step 0045/0093 | loss=2.0994 | main=2.0994 | aux=0.0000 | acc=0.3729 | binary=0.552 | condition=0.510 | count=0.008 | density=0.003 | time=49.1s
Epoch 001 | step 0050/0093 | loss=2.0575 | main=2.0575 | aux=0.0000 | acc=0.3859 | binary=0.564 | condition=0.534 | count=0.008 | density=0.003 | time=50.9s
Epoch 001 | step 0055/0093 | loss=2.0262 | main=2.0262 | aux=0.0000 | acc=0.3969 | binary=0.575 | condition=0.558 | count=0.008 | density=0.003 | time=52.7s
Epoch 001 | step 0060/0093 | loss=1.9933 | main=1.9933 | aux=0.0000 | acc=0.4096 | binary=0.589 | condition=0.579 | count=0.013 | density=0.003 | time=54.5s
Epoch 001 | step 0065/0093 | loss=1.9615 | main=1.9615 | aux=0.0000 | acc=0.4212 | binary=0.599 | condition=0.600 | count=0.019 | density=0.002 | time=56.4s
Epoch 001 | step 0070/0093 | loss=1.9357 | main=1.9357 | aux=0.0000 | acc=0.4288 | binary=0.610 | condition=0.616 | count=0.022 | density=0.002 | time=58.2s
Epoch 001 | step 0075/0093 | loss=1.9087 | main=1.9087 | aux=0.0000 | acc=0.4381 | binary=0.621 | condition=0.629 | count=0.030 | density=0.002 | time=59.9s
Epoch 001 | step 0080/0093 | loss=1.8777 | main=1.8777 | aux=0.0000 | acc=0.4494 | binary=0.632 | condition=0.646 | count=0.037 | density=0.002 | time=1.0min
Epoch 001 | step 0085/0093 | loss=1.8487 | main=1.8487 | aux=0.0000 | acc=0.4594 | binary=0.642 | condition=0.661 | count=0.044 | density=0.002 | time=1.1min
Epoch 001 | step 0090/0093 | loss=1.8157 | main=1.8157 | aux=0.0000 | acc=0.4710 | binary=0.657 | condition=0.676 | count=0.044 | density=0.004 | time=1.1min
Epoch 001 | step 0093/0093 | loss=1.8004 | main=1.8004 | aux=0.0000 | acc=0.4744 | binary=0.660 | condition=0.678 | count=0.045 | density=0.003 | time=1.5min

train overall: acc=0.4744 (2798/5898)
train macro acc: 0.1680
train by edge head:
  binary       acc=0.6602 (1739/2634)
  condition    acc=0.6777 (1003/1480)
  count        acc=0.0449 (54/1204)
  density      acc=0.0034 (2/580)
train by question type:
  Building_Condition_Recognition           acc=0.6086 (353/580)
  Complex_Counting                         acc=0.0385 (24/624)
  Density_Estimation                       acc=0.0034 (2/580)
  Entire_Image_Condition_Recognition       acc=0.6752 (921/1364)
  Risk_Assessment                          acc=0.7466 (433/580)
  Road_Condition_Recognition               acc=0.6509 (1035/1590)
  Simple_Counting                          acc=0.0517 (30/580)

valid overall: acc=0.6462 (1167/1806)
valid macro acc: 0.2820
valid by edge head:
  binary       acc=0.8280 (674/814)
  condition    acc=0.9220 (414/449)
  count        acc=0.2098 (77/367)
  density      acc=0.0114 (2/176)
valid by question type:
  Building_Condition_Recognition           acc=0.8182 (144/176)
  Complex_Counting                         acc=0.1937 (37/191)
  Density_Estimation                       acc=0.0114 (2/176)
  Entire_Image_Condition_Recognition       acc=0.8886 (367/413)
  Risk_Assessment                          acc=0.7784 (137/176)
  Road_Condition_Recognition               acc=0.8835 (440/498)
  Simple_Counting                          acc=0.2273 (40/176)

Epoch 1 done | train_acc=0.4744 | valid_acc=0.6462 | best_valid_acc=0.6462 at epoch 1 | IMPROVED

================================================================================
Epoch 2/30
================================================================================
Epoch 002 | step 0001/0093 | loss=1.0747 | main=1.0747 | aux=0.0000 | acc=0.6875 | binary=0.806 | condition=1.000 | count=0.250 | density=0.286 | time=0.7s
Epoch 002 | step 0005/0093 | loss=1.2586 | main=1.2586 | aux=0.0000 | acc=0.6188 | binary=0.812 | condition=0.932 | count=0.119 | density=0.114 | time=2.0s
Epoch 002 | step 0010/0093 | loss=1.1997 | main=1.1997 | aux=0.0000 | acc=0.6422 | binary=0.818 | condition=0.932 | count=0.153 | density=0.177 | time=3.7s
Epoch 002 | step 0015/0093 | loss=1.1971 | main=1.1971 | aux=0.0000 | acc=0.6479 | binary=0.838 | condition=0.927 | count=0.130 | density=0.189 | time=5.5s
Epoch 002 | step 0020/0093 | loss=1.1632 | main=1.1632 | aux=0.0000 | acc=0.6648 | binary=0.844 | condition=0.931 | count=0.154 | density=0.230 | time=7.4s
Epoch 002 | step 0025/0093 | loss=1.1384 | main=1.1384 | aux=0.0000 | acc=0.6756 | binary=0.857 | condition=0.932 | count=0.152 | density=0.245 | time=9.2s
Epoch 002 | step 0030/0093 | loss=1.1156 | main=1.1156 | aux=0.0000 | acc=0.6786 | binary=0.861 | condition=0.921 | count=0.177 | density=0.240 | time=11.0s
Epoch 002 | step 0035/0093 | loss=1.0998 | main=1.0998 | aux=0.0000 | acc=0.6830 | binary=0.864 | condition=0.925 | count=0.183 | density=0.264 | time=12.8s
Epoch 002 | step 0040/0093 | loss=1.0856 | main=1.0856 | aux=0.0000 | acc=0.6859 | binary=0.861 | condition=0.924 | count=0.198 | density=0.287 | time=14.6s
Epoch 002 | step 0045/0093 | loss=1.0644 | main=1.0644 | aux=0.0000 | acc=0.6899 | binary=0.854 | condition=0.931 | count=0.208 | density=0.308 | time=16.4s
Epoch 002 | step 0050/0093 | loss=1.0359 | main=1.0359 | aux=0.0000 | acc=0.6991 | binary=0.861 | condition=0.936 | count=0.216 | density=0.325 | time=18.2s
Epoch 002 | step 0055/0093 | loss=1.0214 | main=1.0214 | aux=0.0000 | acc=0.7040 | binary=0.861 | condition=0.939 | count=0.217 | density=0.349 | time=20.1s
Epoch 002 | step 0060/0093 | loss=1.0066 | main=1.0066 | aux=0.0000 | acc=0.7086 | binary=0.861 | condition=0.940 | count=0.231 | density=0.370 | time=21.9s
Epoch 002 | step 0065/0093 | loss=0.9924 | main=0.9924 | aux=0.0000 | acc=0.7132 | binary=0.861 | condition=0.941 | count=0.244 | density=0.390 | time=23.8s
Epoch 002 | step 0070/0093 | loss=0.9713 | main=0.9713 | aux=0.0000 | acc=0.7190 | binary=0.864 | condition=0.943 | count=0.253 | density=0.402 | time=25.5s
Epoch 002 | step 0075/0093 | loss=0.9617 | main=0.9617 | aux=0.0000 | acc=0.7231 | binary=0.867 | condition=0.944 | count=0.263 | density=0.422 | time=27.3s
Epoch 002 | step 0080/0093 | loss=0.9508 | main=0.9508 | aux=0.0000 | acc=0.7256 | binary=0.865 | condition=0.946 | count=0.274 | density=0.435 | time=29.0s
Epoch 002 | step 0085/0093 | loss=0.9369 | main=0.9369 | aux=0.0000 | acc=0.7305 | binary=0.869 | condition=0.948 | count=0.289 | density=0.443 | time=30.7s
Epoch 002 | step 0090/0093 | loss=0.9305 | main=0.9305 | aux=0.0000 | acc=0.7316 | binary=0.868 | condition=0.950 | count=0.296 | density=0.460 | time=32.5s
Epoch 002 | step 0093/0093 | loss=0.9233 | main=0.9233 | aux=0.0000 | acc=0.7328 | binary=0.867 | condition=0.950 | count=0.302 | density=0.462 | time=33.2s

train overall: acc=0.7328 (4322/5898)
train macro acc: 0.4317
train by edge head:
  binary       acc=0.8671 (2284/2634)
  condition    acc=0.9500 (1406/1480)
  count        acc=0.3023 (364/1204)
  density      acc=0.4621 (268/580)
train by question type:
  Building_Condition_Recognition           acc=0.8655 (502/580)
  Complex_Counting                         acc=0.2452 (153/624)
  Density_Estimation                       acc=0.4621 (268/580)
  Entire_Image_Condition_Recognition       acc=0.9164 (1250/1364)
  Risk_Assessment                          acc=0.8724 (506/580)
  Road_Condition_Recognition               acc=0.9006 (1432/1590)
  Simple_Counting                          acc=0.3638 (211/580)

valid overall: acc=0.8455 (1527/1806)
valid macro acc: 0.6184
valid by edge head:
  binary       acc=0.9201 (749/814)
  condition    acc=0.9688 (435/449)
  count        acc=0.5477 (201/367)
  density      acc=0.8068 (142/176)
valid by question type:
  Building_Condition_Recognition           acc=0.8977 (158/176)
  Complex_Counting                         acc=0.5340 (102/191)
  Density_Estimation                       acc=0.8068 (142/176)
  Entire_Image_Condition_Recognition       acc=0.9613 (397/413)
  Risk_Assessment                          acc=0.9886 (174/176)
  Road_Condition_Recognition               acc=0.9137 (455/498)
  Simple_Counting                          acc=0.5625 (99/176)

Epoch 2 done | train_acc=0.7328 | valid_acc=0.8455 | best_valid_acc=0.8455 at epoch 2 | IMPROVED

================================================================================
Epoch 3/30
================================================================================
Epoch 003 | step 0001/0093 | loss=0.4690 | main=0.4690 | aux=0.0000 | acc=0.8906 | binary=0.938 | condition=1.000 | count=0.714 | density=0.700 | time=0.7s
Epoch 003 | step 0005/0093 | loss=0.5530 | main=0.5530 | aux=0.0000 | acc=0.8344 | binary=0.887 | condition=1.000 | count=0.537 | density=0.684 | time=2.0s
Epoch 003 | step 0010/0093 | loss=0.5795 | main=0.5795 | aux=0.0000 | acc=0.8156 | binary=0.883 | condition=0.983 | count=0.492 | density=0.677 | time=3.6s
Epoch 003 | step 0015/0093 | loss=0.5986 | main=0.5986 | aux=0.0000 | acc=0.8219 | binary=0.890 | condition=0.980 | count=0.526 | density=0.700 | time=5.4s
Epoch 003 | step 0020/0093 | loss=0.5808 | main=0.5808 | aux=0.0000 | acc=0.8281 | binary=0.890 | condition=0.985 | count=0.523 | density=0.713 | time=7.1s
Epoch 003 | step 0025/0093 | loss=0.5891 | main=0.5891 | aux=0.0000 | acc=0.8275 | binary=0.889 | condition=0.983 | count=0.544 | density=0.714 | time=8.9s
Epoch 003 | step 0030/0093 | loss=0.5799 | main=0.5799 | aux=0.0000 | acc=0.8286 | binary=0.888 | condition=0.980 | count=0.546 | density=0.723 | time=10.6s
Epoch 003 | step 0035/0093 | loss=0.5837 | main=0.5837 | aux=0.0000 | acc=0.8286 | binary=0.887 | condition=0.976 | count=0.554 | density=0.730 | time=12.3s
Epoch 003 | step 0040/0093 | loss=0.5788 | main=0.5788 | aux=0.0000 | acc=0.8313 | binary=0.891 | condition=0.977 | count=0.554 | density=0.750 | time=14.0s
Epoch 003 | step 0045/0093 | loss=0.5675 | main=0.5675 | aux=0.0000 | acc=0.8361 | binary=0.892 | condition=0.978 | count=0.565 | density=0.756 | time=15.7s
Epoch 003 | step 0050/0093 | loss=0.5711 | main=0.5711 | aux=0.0000 | acc=0.8337 | binary=0.897 | condition=0.978 | count=0.551 | density=0.759 | time=17.4s
Epoch 003 | step 0055/0093 | loss=0.5617 | main=0.5617 | aux=0.0000 | acc=0.8372 | binary=0.900 | condition=0.977 | count=0.558 | density=0.769 | time=19.1s
Epoch 003 | step 0060/0093 | loss=0.5590 | main=0.5590 | aux=0.0000 | acc=0.8378 | binary=0.901 | condition=0.975 | count=0.558 | density=0.778 | time=21.0s
Epoch 003 | step 0065/0093 | loss=0.5532 | main=0.5532 | aux=0.0000 | acc=0.8406 | binary=0.903 | condition=0.976 | count=0.565 | density=0.780 | time=23.0s
Epoch 003 | step 0070/0093 | loss=0.5462 | main=0.5462 | aux=0.0000 | acc=0.8449 | binary=0.907 | condition=0.976 | count=0.573 | density=0.790 | time=24.8s
Epoch 003 | step 0075/0093 | loss=0.5406 | main=0.5406 | aux=0.0000 | acc=0.8450 | binary=0.909 | condition=0.977 | count=0.563 | density=0.799 | time=26.5s
Epoch 003 | step 0080/0093 | loss=0.5374 | main=0.5374 | aux=0.0000 | acc=0.8449 | binary=0.908 | condition=0.978 | count=0.560 | density=0.809 | time=28.2s
Epoch 003 | step 0085/0093 | loss=0.5291 | main=0.5291 | aux=0.0000 | acc=0.8480 | binary=0.912 | condition=0.978 | count=0.564 | density=0.817 | time=29.9s
Epoch 003 | step 0090/0093 | loss=0.5221 | main=0.5221 | aux=0.0000 | acc=0.8505 | binary=0.913 | condition=0.976 | count=0.572 | density=0.821 | time=31.5s
Epoch 003 | step 0093/0093 | loss=0.5214 | main=0.5214 | aux=0.0000 | acc=0.8503 | binary=0.912 | condition=0.977 | count=0.573 | density=0.821 | time=32.3s

train overall: acc=0.8503 (5015/5898)
train macro acc: 0.6385
train by edge head:
  binary       acc=0.9123 (2403/2634)
  condition    acc=0.9770 (1446/1480)
  count        acc=0.5731 (690/1204)
  density      acc=0.8207 (476/580)
train by question type:
  Building_Condition_Recognition           acc=0.8983 (521/580)
  Complex_Counting                         acc=0.5433 (339/624)
  Density_Estimation                       acc=0.8207 (476/580)
  Entire_Image_Condition_Recognition       acc=0.9443 (1288/1364)
  Risk_Assessment                          acc=0.9207 (534/580)
  Road_Condition_Recognition               acc=0.9472 (1506/1590)
  Simple_Counting                          acc=0.6052 (351/580)

valid overall: acc=0.8693 (1570/1806)
valid macro acc: 0.6402
valid by edge head:
  binary       acc=0.9435 (768/814)
  condition    acc=0.9755 (438/449)
  count        acc=0.6022 (221/367)
  density      acc=0.8125 (143/176)
valid by question type:
  Building_Condition_Recognition           acc=0.9034 (159/176)
  Complex_Counting                         acc=0.5916 (113/191)
  Density_Estimation                       acc=0.8125 (143/176)
  Entire_Image_Condition_Recognition       acc=0.9709 (401/413)
  Risk_Assessment                          acc=0.9034 (159/176)
  Road_Condition_Recognition               acc=0.9779 (487/498)
  Simple_Counting                          acc=0.6136 (108/176)

Epoch 3 done | train_acc=0.8503 | valid_acc=0.8693 | best_valid_acc=0.8693 at epoch 3 | IMPROVED

================================================================================
Epoch 4/30
================================================================================
Epoch 004 | step 0001/0093 | loss=0.4084 | main=0.4084 | aux=0.0000 | acc=0.8594 | binary=1.000 | condition=1.000 | count=0.500 | density=0.667 | time=0.7s
Epoch 004 | step 0005/0093 | loss=0.5124 | main=0.5124 | aux=0.0000 | acc=0.8250 | binary=0.913 | condition=0.988 | count=0.519 | density=0.750 | time=2.0s
Epoch 004 | step 0010/0093 | loss=0.4475 | main=0.4475 | aux=0.0000 | acc=0.8547 | binary=0.919 | condition=0.994 | count=0.586 | density=0.817 | time=3.7s
Epoch 004 | step 0015/0093 | loss=0.4201 | main=0.4201 | aux=0.0000 | acc=0.8677 | binary=0.925 | condition=0.996 | count=0.606 | density=0.837 | time=5.3s
Epoch 004 | step 0020/0093 | loss=0.4183 | main=0.4183 | aux=0.0000 | acc=0.8680 | binary=0.925 | condition=0.994 | count=0.610 | density=0.822 | time=7.0s
Epoch 004 | step 0025/0093 | loss=0.4026 | main=0.4026 | aux=0.0000 | acc=0.8781 | binary=0.934 | condition=0.987 | count=0.649 | density=0.824 | time=8.8s
Epoch 004 | step 0030/0093 | loss=0.3998 | main=0.3998 | aux=0.0000 | acc=0.8766 | binary=0.933 | condition=0.983 | count=0.653 | density=0.817 | time=10.7s
Epoch 004 | step 0035/0093 | loss=0.3953 | main=0.3953 | aux=0.0000 | acc=0.8781 | binary=0.929 | condition=0.985 | count=0.665 | density=0.828 | time=12.5s
Epoch 004 | step 0040/0093 | loss=0.3928 | main=0.3928 | aux=0.0000 | acc=0.8777 | binary=0.933 | condition=0.986 | count=0.650 | density=0.835 | time=14.2s
Epoch 004 | step 0045/0093 | loss=0.3867 | main=0.3867 | aux=0.0000 | acc=0.8795 | binary=0.933 | condition=0.985 | count=0.653 | density=0.842 | time=16.0s
Epoch 004 | step 0050/0093 | loss=0.3834 | main=0.3834 | aux=0.0000 | acc=0.8825 | binary=0.934 | condition=0.985 | count=0.663 | density=0.849 | time=17.7s
Epoch 004 | step 0055/0093 | loss=0.3802 | main=0.3802 | aux=0.0000 | acc=0.8824 | binary=0.935 | condition=0.986 | count=0.655 | density=0.858 | time=19.4s
Epoch 004 | step 0060/0093 | loss=0.3787 | main=0.3787 | aux=0.0000 | acc=0.8818 | binary=0.935 | condition=0.986 | count=0.654 | density=0.860 | time=21.2s
Epoch 004 | step 0065/0093 | loss=0.3756 | main=0.3756 | aux=0.0000 | acc=0.8827 | binary=0.937 | condition=0.984 | count=0.656 | density=0.857 | time=23.2s
Epoch 004 | step 0070/0093 | loss=0.3697 | main=0.3697 | aux=0.0000 | acc=0.8853 | binary=0.938 | condition=0.983 | count=0.659 | density=0.862 | time=25.2s
Epoch 004 | step 0075/0093 | loss=0.3693 | main=0.3693 | aux=0.0000 | acc=0.8860 | binary=0.939 | condition=0.981 | count=0.664 | density=0.869 | time=27.1s
Epoch 004 | step 0080/0093 | loss=0.3677 | main=0.3677 | aux=0.0000 | acc=0.8859 | binary=0.938 | condition=0.982 | count=0.659 | density=0.872 | time=28.9s
Epoch 004 | step 0085/0093 | loss=0.3616 | main=0.3616 | aux=0.0000 | acc=0.8877 | binary=0.938 | condition=0.982 | count=0.666 | density=0.876 | time=30.6s
Epoch 004 | step 0090/0093 | loss=0.3603 | main=0.3603 | aux=0.0000 | acc=0.8878 | binary=0.939 | condition=0.983 | count=0.664 | density=0.875 | time=32.3s
Epoch 004 | step 0093/0093 | loss=0.3590 | main=0.3590 | aux=0.0000 | acc=0.8886 | binary=0.940 | condition=0.983 | count=0.664 | density=0.878 | time=33.0s

train overall: acc=0.8886 (5241/5898)
train macro acc: 0.7019
train by edge head:
  binary       acc=0.9404 (2477/2634)
  condition    acc=0.9831 (1455/1480)
  count        acc=0.6645 (800/1204)
  density      acc=0.8776 (509/580)
train by question type:
  Building_Condition_Recognition           acc=0.9224 (535/580)
  Complex_Counting                         acc=0.6474 (404/624)
  Density_Estimation                       acc=0.8776 (509/580)
  Entire_Image_Condition_Recognition       acc=0.9567 (1305/1364)
  Risk_Assessment                          acc=0.9431 (547/580)
  Road_Condition_Recognition               acc=0.9717 (1545/1590)
  Simple_Counting                          acc=0.6828 (396/580)

valid overall: acc=0.8776 (1585/1806)
valid macro acc: 0.6525
valid by edge head:
  binary       acc=0.9619 (783/814)
  condition    acc=0.9777 (439/449)
  count        acc=0.6104 (224/367)
  density      acc=0.7898 (139/176)
valid by question type:

T5

In [ ]:
%cd /content/TinyDisasterVQA
%env PYTHONPATH=/content/TinyDisasterVQA/src
%env PYTHONUNBUFFERED=1

!python -u scripts/05_train_teacher.py \
  --dataset-root dataset \
  --runs-dir /content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6 \
  --backbone convnext_tiny \
  --image-size 224 \
  --epochs 30 \
  --batch-size 64 \
  --eval-batch-size 64 \
  --num-workers 2 \
  --early-stopping-patience 5 \
  --early-stopping-min-delta 0.001 \
  --log-interval 5 \
  --pretrained \
  --train-csv outputs/training_data_cap5/train.csv \
  --valid-csv outputs/training_data_cap5/valid.csv \
  --test-csv outputs/training_data_cap5/test.csv \
  --metadata outputs/training_data_cap5/metadata.json \
  --class-weights outputs/answer_space_cap5/class_weights_edge_global_by_label.json \
  --run-name T5_cap5_template_weighted_ce \
  --question-encoder template \
  --loss-mode weighted_ce

/content/TinyDisasterVQA
env: PYTHONPATH=/content/TinyDisasterVQA/src
env: PYTHONUNBUFFERED=1
================================================================================
TinyDisasterVQA / Train Teacher
================================================================================
Run dir:          /content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6/T5_cap5_template_weighted_ce
Device:           cuda
Backbone:         convnext_tiny
Pretrained:       True
Question encoder: template
Loss mode:        weighted_ce
Count aux weight: 0.0
AMP:              True
Image size:       224
Batch size:       64
Eval batch:       64
Augment train:    True
Epochs:           30
LR:               0.0001
Weight decay:     0.0001
Freeze image:     False
Count cap:        5
Num classes:      14
Count classes:    6
Count head id:    3

Model summary
================================================================================
Class:             TeacherVQA
Total params:      28,418,286
Trainable params:  28,418,286
FP32 param size:   108.41 MB
Int8 param size:   27752.2 KB
Image backbone:    convnext_tiny
Pretrained:        True
Image feature dim: 768
Question encoder:  template
Question dim:      128
Num classes:       14
Count aux:         False

Using edge_global class weights:
[0.3070286810398102, 0.3189149796962738, 0.8006914258003235, 4.634336948394775, 0.3181625306606293, 0.883733332157135, 0.8129164576530457, 0.7653355598449707, 0.8368628621101379, 0.883733332157135, 0.7653355598449707, 0.8235432505607605, 1.2535922527313232, 0.5958129167556763]

================================================================================
Epoch 1/30
================================================================================
Epoch 001 | step 0001/0093 | loss=2.6376 | main=2.6376 | aux=0.0000 | acc=0.0938 | binary=0.208 | condition=0.000 | count=0.071 | density=0.000 | time=33.4s
Epoch 001 | step 0005/0093 | loss=2.6208 | main=2.6208 | aux=0.0000 | acc=0.1625 | binary=0.299 | condition=0.042 | count=0.082 | density=0.053 | time=34.8s
Epoch 001 | step 0010/0093 | loss=2.5820 | main=2.5820 | aux=0.0000 | acc=0.2188 | binary=0.415 | condition=0.090 | count=0.071 | density=0.047 | time=36.5s
Epoch 001 | step 0015/0093 | loss=2.5446 | main=2.5446 | aux=0.0000 | acc=0.2573 | binary=0.440 | condition=0.218 | count=0.061 | density=0.031 | time=38.3s
Epoch 001 | step 0020/0093 | loss=2.5104 | main=2.5104 | aux=0.0000 | acc=0.2820 | binary=0.442 | condition=0.308 | count=0.058 | density=0.023 | time=40.2s
Epoch 001 | step 0025/0093 | loss=2.4733 | main=2.4733 | aux=0.0000 | acc=0.3038 | binary=0.462 | condition=0.352 | count=0.050 | density=0.019 | time=42.0s
Epoch 001 | step 0030/0093 | loss=2.4634 | main=2.4634 | aux=0.0000 | acc=0.3161 | binary=0.479 | condition=0.369 | count=0.054 | density=0.016 | time=43.8s
Epoch 001 | step 0035/0093 | loss=2.4281 | main=2.4281 | aux=0.0000 | acc=0.3335 | binary=0.494 | condition=0.401 | count=0.065 | density=0.013 | time=45.6s
Epoch 001 | step 0040/0093 | loss=2.4150 | main=2.4150 | aux=0.0000 | acc=0.3410 | binary=0.491 | condition=0.435 | count=0.075 | density=0.011 | time=47.4s
Epoch 001 | step 0045/0093 | loss=2.3861 | main=2.3861 | aux=0.0000 | acc=0.3528 | binary=0.485 | condition=0.484 | count=0.077 | density=0.017 | time=49.2s
Epoch 001 | step 0050/0093 | loss=2.3503 | main=2.3503 | aux=0.0000 | acc=0.3688 | binary=0.495 | condition=0.514 | count=0.089 | density=0.016 | time=51.1s
Epoch 001 | step 0055/0093 | loss=2.3285 | main=2.3285 | aux=0.0000 | acc=0.3784 | binary=0.505 | condition=0.534 | count=0.091 | density=0.017 | time=52.9s
Epoch 001 | step 0060/0093 | loss=2.3057 | main=2.3057 | aux=0.0000 | acc=0.3883 | binary=0.512 | condition=0.554 | count=0.098 | density=0.018 | time=54.8s
Epoch 001 | step 0065/0093 | loss=2.2769 | main=2.2769 | aux=0.0000 | acc=0.3998 | binary=0.520 | condition=0.580 | count=0.099 | density=0.027 | time=56.7s
Epoch 001 | step 0070/0093 | loss=2.2570 | main=2.2570 | aux=0.0000 | acc=0.4054 | binary=0.519 | condition=0.593 | count=0.108 | density=0.044 | time=58.5s
Epoch 001 | step 0075/0093 | loss=2.2357 | main=2.2357 | aux=0.0000 | acc=0.4135 | binary=0.523 | condition=0.612 | count=0.112 | density=0.059 | time=1.0min
Epoch 001 | step 0080/0093 | loss=2.2156 | main=2.2156 | aux=0.0000 | acc=0.4230 | binary=0.529 | condition=0.628 | count=0.120 | density=0.067 | time=1.0min
Epoch 001 | step 0085/0093 | loss=2.1917 | main=2.1917 | aux=0.0000 | acc=0.4325 | binary=0.541 | condition=0.633 | count=0.128 | density=0.076 | time=1.1min
Epoch 001 | step 0090/0093 | loss=2.1656 | main=2.1656 | aux=0.0000 | acc=0.4429 | binary=0.556 | condition=0.645 | count=0.128 | density=0.077 | time=1.1min
Epoch 001 | step 0093/0093 | loss=2.1513 | main=2.1513 | aux=0.0000 | acc=0.4474 | binary=0.560 | condition=0.649 | count=0.130 | density=0.083 | time=1.5min

train overall: acc=0.4474 (2639/5898)
train macro acc: 0.2064
train by edge head:
  binary       acc=0.5600 (1475/2634)
  condition    acc=0.6486 (960/1480)
  count        acc=0.1296 (156/1204)
  density      acc=0.0828 (48/580)
train by question type:
  Building_Condition_Recognition           acc=0.5379 (312/580)
  Complex_Counting                         acc=0.1314 (82/624)
  Density_Estimation                       acc=0.0828 (48/580)
  Entire_Image_Condition_Recognition       acc=0.5946 (811/1364)
  Risk_Assessment                          acc=0.6569 (381/580)
  Road_Condition_Recognition               acc=0.5855 (931/1590)
  Simple_Counting                          acc=0.1276 (74/580)

valid overall: acc=0.6999 (1264/1806)
valid macro acc: 0.4259
valid by edge head:
  binary       acc=0.7973 (649/814)
  condition    acc=0.9220 (414/449)
  count        acc=0.2807 (103/367)
  density      acc=0.5568 (98/176)
valid by question type:
  Building_Condition_Recognition           acc=0.7614 (134/176)
  Complex_Counting                         acc=0.2513 (48/191)
  Density_Estimation                       acc=0.5568 (98/176)
  Entire_Image_Condition_Recognition       acc=0.9080 (375/413)
  Risk_Assessment                          acc=0.7670 (135/176)
  Road_Condition_Recognition               acc=0.8414 (419/498)
  Simple_Counting                          acc=0.3125 (55/176)

Epoch 1 done | train_acc=0.4474 | valid_acc=0.6999 | best_valid_acc=0.6999 at epoch 1 | IMPROVED

================================================================================
Epoch 2/30
================================================================================
Epoch 002 | step 0001/0093 | loss=1.5329 | main=1.5329 | aux=0.0000 | acc=0.7500 | binary=0.806 | condition=0.929 | count=0.333 | density=0.857 | time=0.7s
Epoch 002 | step 0005/0093 | loss=1.7013 | main=1.7013 | aux=0.0000 | acc=0.6344 | binary=0.729 | condition=0.878 | count=0.254 | density=0.457 | time=2.1s
Epoch 002 | step 0010/0093 | loss=1.6200 | main=1.6200 | aux=0.0000 | acc=0.6609 | binary=0.750 | condition=0.907 | count=0.255 | density=0.516 | time=3.9s
Epoch 002 | step 0015/0093 | loss=1.6253 | main=1.6253 | aux=0.0000 | acc=0.6594 | binary=0.749 | condition=0.902 | count=0.235 | density=0.547 | time=5.8s
Epoch 002 | step 0020/0093 | loss=1.6209 | main=1.6209 | aux=0.0000 | acc=0.6742 | binary=0.750 | condition=0.899 | count=0.273 | density=0.587 | time=7.6s
Epoch 002 | step 0025/0093 | loss=1.6214 | main=1.6214 | aux=0.0000 | acc=0.6819 | binary=0.762 | condition=0.902 | count=0.266 | density=0.603 | time=9.3s
Epoch 002 | step 0030/0093 | loss=1.5822 | main=1.5822 | aux=0.0000 | acc=0.6870 | binary=0.769 | condition=0.902 | count=0.285 | density=0.585 | time=11.2s
Epoch 002 | step 0035/0093 | loss=1.5579 | main=1.5579 | aux=0.0000 | acc=0.6906 | binary=0.773 | condition=0.907 | count=0.296 | density=0.580 | time=13.0s
Epoch 002 | step 0040/0093 | loss=1.5307 | main=1.5307 | aux=0.0000 | acc=0.6973 | binary=0.768 | condition=0.913 | count=0.317 | density=0.615 | time=14.8s
Epoch 002 | step 0045/0093 | loss=1.5099 | main=1.5099 | aux=0.0000 | acc=0.6983 | binary=0.765 | condition=0.914 | count=0.324 | density=0.612 | time=16.6s
Epoch 002 | step 0050/0093 | loss=1.4819 | main=1.4819 | aux=0.0000 | acc=0.7075 | binary=0.776 | condition=0.919 | count=0.333 | density=0.613 | time=18.5s
Epoch 002 | step 0055/0093 | loss=1.4640 | main=1.4640 | aux=0.0000 | acc=0.7116 | binary=0.780 | condition=0.920 | count=0.335 | density=0.619 | time=20.4s
Epoch 002 | step 0060/0093 | loss=1.4433 | main=1.4433 | aux=0.0000 | acc=0.7164 | binary=0.784 | condition=0.921 | count=0.347 | density=0.624 | time=22.2s
Epoch 002 | step 0065/0093 | loss=1.4297 | main=1.4297 | aux=0.0000 | acc=0.7185 | binary=0.780 | condition=0.920 | count=0.356 | density=0.642 | time=24.0s
Epoch 002 | step 0070/0093 | loss=1.4003 | main=1.4003 | aux=0.0000 | acc=0.7243 | binary=0.786 | condition=0.922 | count=0.364 | density=0.644 | time=25.8s
Epoch 002 | step 0075/0093 | loss=1.3835 | main=1.3835 | aux=0.0000 | acc=0.7271 | binary=0.790 | condition=0.923 | count=0.368 | density=0.655 | time=27.6s
Epoch 002 | step 0080/0093 | loss=1.3659 | main=1.3659 | aux=0.0000 | acc=0.7279 | binary=0.788 | condition=0.926 | count=0.373 | density=0.659 | time=29.3s
Epoch 002 | step 0085/0093 | loss=1.3478 | main=1.3478 | aux=0.0000 | acc=0.7325 | binary=0.793 | condition=0.928 | count=0.385 | density=0.665 | time=31.0s
Epoch 002 | step 0090/0093 | loss=1.3405 | main=1.3405 | aux=0.0000 | acc=0.7337 | binary=0.792 | condition=0.931 | count=0.391 | density=0.675 | time=32.8s
Epoch 002 | step 0093/0093 | loss=1.3321 | main=1.3321 | aux=0.0000 | acc=0.7341 | binary=0.793 | condition=0.932 | count=0.393 | density=0.672 | time=33.6s

train overall: acc=0.7341 (4330/5898)
train macro acc: 0.5087
train by edge head:
  binary       acc=0.7927 (2088/2634)
  condition    acc=0.9318 (1379/1480)
  count        acc=0.3929 (473/1204)
  density      acc=0.6724 (390/580)
train by question type:
  Building_Condition_Recognition           acc=0.7345 (426/580)
  Complex_Counting                         acc=0.3333 (208/624)
  Density_Estimation                       acc=0.6724 (390/580)
  Entire_Image_Condition_Recognition       acc=0.8856 (1208/1364)
  Risk_Assessment                          acc=0.7810 (453/580)
  Road_Condition_Recognition               acc=0.8679 (1380/1590)
  Simple_Counting                          acc=0.4569 (265/580)

valid overall: acc=0.8189 (1479/1806)
valid macro acc: 0.6520
valid by edge head:
  binary       acc=0.8428 (686/814)
  condition    acc=0.9555 (429/449)
  count        acc=0.5913 (217/367)
  density      acc=0.8352 (147/176)
valid by question type:
  Building_Condition_Recognition           acc=0.8182 (144/176)
  Complex_Counting                         acc=0.5602 (107/191)
  Density_Estimation                       acc=0.8352 (147/176)
  Entire_Image_Condition_Recognition       acc=0.9201 (380/413)
  Risk_Assessment                          acc=0.8466 (149/176)
  Road_Condition_Recognition               acc=0.8876 (442/498)
  Simple_Counting                          acc=0.6250 (110/176)

Epoch 2 done | train_acc=0.7341 | valid_acc=0.8189 | best_valid_acc=0.8189 at epoch 2 | IMPROVED

================================================================================
Epoch 3/30
================================================================================
Epoch 003 | step 0001/0093 | loss=0.7450 | main=0.7450 | aux=0.0000 | acc=0.9219 | binary=0.938 | condition=1.000 | count=0.571 | density=1.000 | time=0.8s
Epoch 003 | step 0005/0093 | loss=0.8348 | main=0.8348 | aux=0.0000 | acc=0.8500 | binary=0.866 | condition=0.988 | count=0.556 | density=0.895 | time=2.1s
Epoch 003 | step 0010/0093 | loss=0.9171 | main=0.9171 | aux=0.0000 | acc=0.8109 | binary=0.819 | condition=0.977 | count=0.542 | density=0.831 | time=3.8s
Epoch 003 | step 0015/0093 | loss=0.9150 | main=0.9150 | aux=0.0000 | acc=0.8135 | binary=0.821 | condition=0.972 | count=0.589 | density=0.810 | time=5.6s
Epoch 003 | step 0020/0093 | loss=0.8872 | main=0.8872 | aux=0.0000 | acc=0.8180 | binary=0.821 | condition=0.977 | count=0.601 | density=0.791 | time=7.4s
Epoch 003 | step 0025/0093 | loss=0.8821 | main=0.8821 | aux=0.0000 | acc=0.8194 | binary=0.825 | condition=0.976 | count=0.613 | density=0.795 | time=9.1s
Epoch 003 | step 0030/0093 | loss=0.8589 | main=0.8589 | aux=0.0000 | acc=0.8245 | binary=0.831 | condition=0.970 | count=0.618 | density=0.812 | time=10.8s
Epoch 003 | step 0035/0093 | loss=0.8747 | main=0.8747 | aux=0.0000 | acc=0.8196 | binary=0.828 | condition=0.966 | count=0.613 | density=0.806 | time=12.5s
Epoch 003 | step 0040/0093 | loss=0.8699 | main=0.8699 | aux=0.0000 | acc=0.8187 | binary=0.827 | condition=0.963 | count=0.615 | density=0.818 | time=14.2s
Epoch 003 | step 0045/0093 | loss=0.8538 | main=0.8538 | aux=0.0000 | acc=0.8229 | binary=0.827 | condition=0.965 | count=0.625 | density=0.832 | time=16.0s
Epoch 003 | step 0050/0093 | loss=0.8695 | main=0.8695 | aux=0.0000 | acc=0.8175 | binary=0.827 | condition=0.962 | count=0.610 | density=0.832 | time=17.7s
Epoch 003 | step 0055/0093 | loss=0.8573 | main=0.8573 | aux=0.0000 | acc=0.8207 | binary=0.829 | condition=0.962 | count=0.617 | density=0.841 | time=19.7s
Epoch 003 | step 0060/0093 | loss=0.8531 | main=0.8531 | aux=0.0000 | acc=0.8211 | binary=0.832 | condition=0.960 | count=0.611 | density=0.851 | time=21.6s
Epoch 003 | step 0065/0093 | loss=0.8432 | main=0.8432 | aux=0.0000 | acc=0.8255 | binary=0.837 | condition=0.961 | count=0.619 | density=0.855 | time=23.4s
Epoch 003 | step 0070/0093 | loss=0.8367 | main=0.8367 | aux=0.0000 | acc=0.8283 | binary=0.840 | condition=0.960 | count=0.624 | density=0.862 | time=25.1s
Epoch 003 | step 0075/0093 | loss=0.8298 | main=0.8298 | aux=0.0000 | acc=0.8300 | binary=0.844 | condition=0.958 | count=0.622 | density=0.867 | time=26.8s
Epoch 003 | step 0080/0093 | loss=0.8214 | main=0.8214 | aux=0.0000 | acc=0.8291 | binary=0.842 | condition=0.960 | count=0.620 | density=0.873 | time=28.5s
Epoch 003 | step 0085/0093 | loss=0.8095 | main=0.8095 | aux=0.0000 | acc=0.8318 | binary=0.846 | condition=0.961 | count=0.619 | density=0.881 | time=30.1s
Epoch 003 | step 0090/0093 | loss=0.8025 | main=0.8025 | aux=0.0000 | acc=0.8335 | binary=0.846 | condition=0.960 | count=0.626 | density=0.882 | time=31.8s
Epoch 003 | step 0093/0093 | loss=0.8001 | main=0.8001 | aux=0.0000 | acc=0.8333 | binary=0.845 | condition=0.960 | count=0.628 | density=0.884 | time=32.5s

train overall: acc=0.8333 (4915/5898)
train macro acc: 0.6743
train by edge head:
  binary       acc=0.8447 (2225/2634)
  condition    acc=0.9601 (1421/1480)
  count        acc=0.6279 (756/1204)
  density      acc=0.8845 (513/580)
train by question type:
  Building_Condition_Recognition           acc=0.8207 (476/580)
  Complex_Counting                         acc=0.5962 (372/624)
  Density_Estimation                       acc=0.8845 (513/580)
  Entire_Image_Condition_Recognition       acc=0.9186 (1253/1364)
  Risk_Assessment                          acc=0.8431 (489/580)
  Road_Condition_Recognition               acc=0.8981 (1428/1590)
  Simple_Counting                          acc=0.6621 (384/580)

valid overall: acc=0.8200 (1481/1806)
valid macro acc: 0.6452
valid by edge head:
  binary       acc=0.8280 (674/814)
  condition    acc=0.9577 (430/449)
  count        acc=0.6349 (233/367)
  density      acc=0.8182 (144/176)
valid by question type:
  Building_Condition_Recognition           acc=0.8182 (144/176)
  Complex_Counting                         acc=0.6178 (118/191)
  Density_Estimation                       acc=0.8182 (144/176)
  Entire_Image_Condition_Recognition       acc=0.9225 (381/413)
  Risk_Assessment                          acc=0.7784 (137/176)
  Road_Condition_Recognition               acc=0.8876 (442/498)
  Simple_Counting                          acc=0.6534 (115/176)

Epoch 3 done | train_acc=0.8333 | valid_acc=0.8200 | best_valid_acc=0.8200 at epoch 3 | IMPROVED

================================================================================
Epoch 4/30
================================================================================
Epoch 004 | step 0001/0093 | loss=0.6644 | main=0.6644 | aux=0.0000 | acc=0.7969 | binary=0.880 | condition=0.895 | count=0.500 | density=0.833 | time=0.7s
Epoch 004 | step 0005/0093 | loss=0.7408 | main=0.7408 | aux=0.0000 | acc=0.8094 | binary=0.797 | condition=0.963 | count=0.662 | density=0.833 | time=2.0s
Epoch 004 | step 0010/0093 | loss=0.6545 | main=0.6545 | aux=0.0000 | acc=0.8359 | binary=0.825 | condition=0.981 | count=0.679 | density=0.883 | time=3.7s
Epoch 004 | step 0015/0093 | loss=0.6246 | main=0.6246 | aux=0.0000 | acc=0.8365 | binary=0.831 | condition=0.983 | count=0.662 | density=0.870 | time=5.5s
Epoch 004 | step 0020/0093 | loss=0.6132 | main=0.6132 | aux=0.0000 | acc=0.8406 | binary=0.837 | condition=0.981 | count=0.664 | density=0.868 | time=7.2s
Epoch 004 | step 0025/0093 | loss=0.6120 | main=0.6120 | aux=0.0000 | acc=0.8469 | binary=0.837 | condition=0.980 | count=0.695 | density=0.867 | time=9.0s
Epoch 004 | step 0030/0093 | loss=0.6002 | main=0.6002 | aux=0.0000 | acc=0.8484 | binary=0.839 | condition=0.977 | count=0.701 | density=0.874 | time=10.7s
Epoch 004 | step 0035/0093 | loss=0.5948 | main=0.5948 | aux=0.0000 | acc=0.8487 | binary=0.837 | condition=0.978 | count=0.710 | density=0.873 | time=12.4s
Epoch 004 | step 0040/0093 | loss=0.5961 | main=0.5961 | aux=0.0000 | acc=0.8473 | binary=0.843 | condition=0.980 | count=0.684 | density=0.875 | time=14.2s
Epoch 004 | step 0045/0093 | loss=0.5864 | main=0.5864 | aux=0.0000 | acc=0.8510 | binary=0.846 | condition=0.981 | count=0.689 | density=0.878 | time=16.0s
Epoch 004 | step 0050/0093 | loss=0.5836 | main=0.5836 | aux=0.0000 | acc=0.8503 | binary=0.847 | condition=0.980 | count=0.684 | density=0.882 | time=17.7s
Epoch 004 | step 0055/0093 | loss=0.5764 | main=0.5764 | aux=0.0000 | acc=0.8520 | binary=0.850 | condition=0.981 | count=0.684 | density=0.884 | time=19.6s
Epoch 004 | step 0060/0093 | loss=0.5756 | main=0.5756 | aux=0.0000 | acc=0.8529 | binary=0.852 | condition=0.982 | count=0.688 | density=0.878 | time=21.6s
Epoch 004 | step 0065/0093 | loss=0.5783 | main=0.5783 | aux=0.0000 | acc=0.8555 | binary=0.856 | condition=0.982 | count=0.691 | density=0.881 | time=23.6s
Epoch 004 | step 0070/0093 | loss=0.5745 | main=0.5745 | aux=0.0000 | acc=0.8592 | binary=0.859 | condition=0.981 | count=0.694 | density=0.887 | time=25.4s
Epoch 004 | step 0075/0093 | loss=0.5827 | main=0.5827 | aux=0.0000 | acc=0.8592 | binary=0.859 | condition=0.978 | count=0.696 | density=0.895 | time=27.1s
Epoch 004 | step 0080/0093 | loss=0.5818 | main=0.5818 | aux=0.0000 | acc=0.8609 | binary=0.861 | condition=0.979 | count=0.697 | density=0.892 | time=28.9s
Epoch 004 | step 0085/0093 | loss=0.5748 | main=0.5748 | aux=0.0000 | acc=0.8632 | binary=0.864 | condition=0.980 | count=0.703 | density=0.893 | time=30.6s
Epoch 004 | step 0090/0093 | loss=0.5720 | main=0.5720 | aux=0.0000 | acc=0.8637 | binary=0.866 | condition=0.980 | count=0.703 | density=0.891 | time=32.3s
Epoch 004 | step 0093/0093 | loss=0.5700 | main=0.5700 | aux=0.0000 | acc=0.8644 | binary=0.866 | condition=0.980 | count=0.703 | density=0.893 | time=33.0s

train overall: acc=0.8644 (5098/5898)
train macro acc: 0.7334
train by edge head:
  binary       acc=0.8664 (2282/2634)
  condition    acc=0.9804 (1451/1480)
  count        acc=0.7035 (847/1204)
  density      acc=0.8931 (518/580)
train by question type:
  Building_Condition_Recognition           acc=0.8690 (504/580)
  Complex_Counting                         acc=0.6571 (410/624)
  Density_Estimation                       acc=0.8931 (518/580)
  Entire_Image_Condition_Recognition       acc=0.9399 (1282/1364)
  Risk_Assessment                          acc=0.8655 (502/580)
  Road_Condition_Recognition               acc=0.9088 (1445/1590)

T6

In [ ]:
%cd /content/TinyDisasterVQA
%env PYTHONPATH=/content/TinyDisasterVQA/src
%env PYTHONUNBUFFERED=1

!python -u scripts/05_train_teacher.py \
  --dataset-root dataset \
  --runs-dir /content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6 \
  --backbone convnext_tiny \
  --image-size 224 \
  --epochs 30 \
  --batch-size 64 \
  --eval-batch-size 64 \
  --num-workers 2 \
  --early-stopping-patience 5 \
  --early-stopping-min-delta 0.001 \
  --log-interval 5 \
  --pretrained \
  --train-csv outputs/training_data_cap5/train.csv \
  --valid-csv outputs/training_data_cap5/valid.csv \
  --test-csv outputs/training_data_cap5/test.csv \
  --metadata outputs/training_data_cap5/metadata.json \
  --class-weights outputs/answer_space_cap5/class_weights_edge_global_by_label.json \
  --run-name T6_cap5_template_count_aux \
  --question-encoder template \
  --loss-mode count_aux \
  --count-aux-weight 0.5

/content/TinyDisasterVQA
env: PYTHONPATH=/content/TinyDisasterVQA/src
env: PYTHONUNBUFFERED=1
================================================================================
TinyDisasterVQA / Train Teacher
================================================================================
Run dir:          /content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6/T6_cap5_template_count_aux
Device:           cuda
Backbone:         convnext_tiny
Pretrained:       True
Question encoder: template
Loss mode:        count_aux
Count aux weight: 0.5
AMP:              True
Image size:       224
Batch size:       64
Eval batch:       64
Augment train:    True
Epochs:           30
LR:               0.0001
Weight decay:     0.0001
Freeze image:     False
Count cap:        5
Num classes:      14
Count classes:    6
Count head id:    3

Model summary
================================================================================
Class:             TeacherVQA
Total params:      28,649,460
Trainable params:  28,649,460
FP32 param size:   109.29 MB
Int8 param size:   27978.0 KB
Image backbone:    convnext_tiny
Pretrained:        True
Image feature dim: 768
Question encoder:  template
Question dim:      128
Num classes:       14
Count aux:         True
Count classes:     6


================================================================================
Epoch 1/30
================================================================================
Epoch 001 | step 0001/0093 | loss=3.5391 | main=2.5995 | aux=1.8792 | acc=0.1719 | binary=0.205 | condition=0.000 | count=0.250 | density=0.000 | time=32.9s
Epoch 001 | step 0005/0093 | loss=3.4808 | main=2.5748 | aux=1.8120 | acc=0.2250 | binary=0.417 | condition=0.029 | count=0.078 | density=0.057 | time=34.3s
Epoch 001 | step 0010/0093 | loss=3.3965 | main=2.5133 | aux=1.7663 | acc=0.2484 | binary=0.512 | condition=0.027 | count=0.038 | density=0.028 | time=36.0s
Epoch 001 | step 0015/0093 | loss=3.2753 | main=2.4225 | aux=1.7056 | acc=0.2583 | binary=0.530 | condition=0.026 | count=0.026 | density=0.020 | time=37.7s
Epoch 001 | step 0020/0093 | loss=3.1671 | main=2.3270 | aux=1.6801 | acc=0.2875 | binary=0.564 | condition=0.048 | count=0.021 | density=0.015 | time=39.5s
Epoch 001 | step 0025/0093 | loss=3.1000 | main=2.2657 | aux=1.6687 | acc=0.2975 | binary=0.581 | condition=0.070 | count=0.017 | density=0.012 | time=41.4s
Epoch 001 | step 0030/0093 | loss=3.0373 | main=2.2261 | aux=1.6223 | acc=0.3167 | binary=0.591 | condition=0.160 | count=0.013 | density=0.010 | time=43.3s
Epoch 001 | step 0035/0093 | loss=2.9781 | main=2.1838 | aux=1.5887 | acc=0.3299 | binary=0.573 | condition=0.266 | count=0.011 | density=0.009 | time=45.1s
Epoch 001 | step 0040/0093 | loss=2.9352 | main=2.1487 | aux=1.5730 | acc=0.3383 | binary=0.555 | condition=0.335 | count=0.014 | density=0.008 | time=46.9s
Epoch 001 | step 0045/0093 | loss=2.8894 | main=2.1171 | aux=1.5445 | acc=0.3531 | binary=0.564 | condition=0.375 | count=0.017 | density=0.007 | time=48.7s
Epoch 001 | step 0050/0093 | loss=2.8352 | main=2.0755 | aux=1.5195 | acc=0.3681 | binary=0.571 | condition=0.417 | count=0.016 | density=0.006 | time=50.5s
Epoch 001 | step 0055/0093 | loss=2.7882 | main=2.0443 | aux=1.4878 | acc=0.3807 | binary=0.586 | condition=0.448 | count=0.016 | density=0.006 | time=52.4s
Epoch 001 | step 0060/0093 | loss=2.7576 | main=2.0236 | aux=1.4681 | acc=0.3865 | binary=0.595 | condition=0.465 | count=0.018 | density=0.005 | time=54.2s
Epoch 001 | step 0065/0093 | loss=2.7185 | main=1.9962 | aux=1.4445 | acc=0.3974 | binary=0.603 | condition=0.494 | count=0.028 | density=0.005 | time=56.1s
Epoch 001 | step 0070/0093 | loss=2.6728 | main=1.9601 | aux=1.4254 | acc=0.4129 | binary=0.617 | condition=0.522 | count=0.038 | density=0.004 | time=57.9s
Epoch 001 | step 0075/0093 | loss=2.6437 | main=1.9316 | aux=1.4242 | acc=0.4250 | binary=0.628 | condition=0.543 | count=0.048 | density=0.004 | time=59.7s
Epoch 001 | step 0080/0093 | loss=2.6122 | main=1.9053 | aux=1.4139 | acc=0.4352 | binary=0.639 | condition=0.561 | count=0.051 | density=0.004 | time=1.0min
Epoch 001 | step 0085/0093 | loss=2.5754 | main=1.8726 | aux=1.4057 | acc=0.4478 | binary=0.654 | condition=0.575 | count=0.053 | density=0.006 | time=1.1min
Epoch 001 | step 0090/0093 | loss=2.5418 | main=1.8444 | aux=1.3950 | acc=0.4562 | binary=0.664 | condition=0.590 | count=0.052 | density=0.009 | time=1.1min
Epoch 001 | step 0093/0093 | loss=2.5288 | main=1.8342 | aux=1.3891 | acc=0.4588 | binary=0.667 | condition=0.596 | count=0.051 | density=0.010 | time=1.5min

train overall: acc=0.4588 (2706/5898)
train macro acc: 0.1611
train by edge head:
  binary       acc=0.6670 (1757/2634)
  condition    acc=0.5959 (882/1480)
  count        acc=0.0507 (61/1204)
  density      acc=0.0103 (6/580)
train by question type:
  Building_Condition_Recognition           acc=0.6259 (363/580)
  Complex_Counting                         acc=0.0401 (25/624)
  Density_Estimation                       acc=0.0103 (6/580)
  Entire_Image_Condition_Recognition       acc=0.6510 (888/1364)
  Risk_Assessment                          acc=0.7379 (428/580)
  Road_Condition_Recognition               acc=0.6038 (960/1590)
  Simple_Counting                          acc=0.0621 (36/580)

valid overall: acc=0.6351 (1147/1806)
valid macro acc: 0.2472
valid by edge head:
  binary       acc=0.8698 (708/814)
  condition    acc=0.8508 (382/449)
  count        acc=0.1471 (54/367)
  density      acc=0.0170 (3/176)
valid by question type:
  Building_Condition_Recognition           acc=0.8636 (152/176)
  Complex_Counting                         acc=0.0838 (16/191)
  Density_Estimation                       acc=0.0170 (3/176)
  Entire_Image_Condition_Recognition       acc=0.8838 (365/413)
  Risk_Assessment                          acc=0.8977 (158/176)
  Road_Condition_Recognition               acc=0.8333 (415/498)
  Simple_Counting                          acc=0.2159 (38/176)

Epoch 1 done | train_acc=0.4588 | valid_acc=0.6351 | best_valid_acc=0.6351 at epoch 1 | IMPROVED

================================================================================
Epoch 2/30
================================================================================
Epoch 002 | step 0001/0093 | loss=1.6216 | main=1.1985 | aux=0.8462 | acc=0.6562 | binary=0.857 | condition=1.000 | count=0.071 | density=0.167 | time=0.7s
Epoch 002 | step 0005/0093 | loss=1.6245 | main=1.0731 | aux=1.1029 | acc=0.6906 | binary=0.843 | condition=0.941 | count=0.105 | density=0.048 | time=2.1s
Epoch 002 | step 0010/0093 | loss=1.7264 | main=1.1754 | aux=1.1020 | acc=0.6375 | binary=0.812 | condition=0.906 | count=0.129 | density=0.069 | time=3.8s
Epoch 002 | step 0015/0093 | loss=1.7571 | main=1.2220 | aux=1.0701 | acc=0.6271 | binary=0.814 | condition=0.895 | count=0.151 | density=0.086 | time=5.6s
Epoch 002 | step 0020/0093 | loss=1.7361 | main=1.2067 | aux=1.0588 | acc=0.6375 | binary=0.811 | condition=0.898 | count=0.176 | density=0.148 | time=7.4s
Epoch 002 | step 0025/0093 | loss=1.7293 | main=1.1911 | aux=1.0764 | acc=0.6450 | binary=0.815 | condition=0.907 | count=0.167 | density=0.187 | time=9.3s
Epoch 002 | step 0030/0093 | loss=1.6982 | main=1.1744 | aux=1.0477 | acc=0.6469 | binary=0.822 | condition=0.916 | count=0.171 | density=0.193 | time=11.1s
Epoch 002 | step 0035/0093 | loss=1.6820 | main=1.1626 | aux=1.0387 | acc=0.6504 | binary=0.832 | condition=0.915 | count=0.182 | density=0.214 | time=12.9s
Epoch 002 | step 0040/0093 | loss=1.6640 | main=1.1429 | aux=1.0422 | acc=0.6582 | binary=0.833 | condition=0.912 | count=0.202 | density=0.236 | time=14.8s
Epoch 002 | step 0045/0093 | loss=1.6275 | main=1.1061 | aux=1.0430 | acc=0.6698 | binary=0.837 | condition=0.914 | count=0.213 | density=0.256 | time=16.6s
Epoch 002 | step 0050/0093 | loss=1.6024 | main=1.0883 | aux=1.0283 | acc=0.6753 | binary=0.839 | condition=0.914 | count=0.232 | density=0.273 | time=18.4s
Epoch 002 | step 0055/0093 | loss=1.5784 | main=1.0706 | aux=1.0156 | acc=0.6804 | binary=0.841 | condition=0.912 | count=0.240 | density=0.295 | time=20.2s
Epoch 002 | step 0060/0093 | loss=1.5826 | main=1.0652 | aux=1.0349 | acc=0.6820 | binary=0.841 | condition=0.909 | count=0.248 | density=0.315 | time=22.1s
Epoch 002 | step 0065/0093 | loss=1.5708 | main=1.0556 | aux=1.0304 | acc=0.6858 | binary=0.842 | condition=0.907 | count=0.260 | density=0.336 | time=24.0s
Epoch 002 | step 0070/0093 | loss=1.5421 | main=1.0332 | aux=1.0180 | acc=0.6958 | binary=0.846 | condition=0.913 | count=0.276 | density=0.360 | time=25.9s
Epoch 002 | step 0075/0093 | loss=1.5166 | main=1.0167 | aux=0.9999 | acc=0.7008 | binary=0.848 | condition=0.916 | count=0.282 | density=0.378 | time=27.6s
Epoch 002 | step 0080/0093 | loss=1.5105 | main=1.0054 | aux=1.0102 | acc=0.7064 | binary=0.852 | condition=0.918 | count=0.286 | density=0.396 | time=29.4s
Epoch 002 | step 0085/0093 | loss=1.4972 | main=0.9899 | aux=1.0146 | acc=0.7096 | binary=0.850 | condition=0.921 | count=0.287 | density=0.406 | time=31.1s
Epoch 002 | step 0090/0093 | loss=1.4813 | main=0.9782 | aux=1.0062 | acc=0.7142 | binary=0.853 | condition=0.920 | count=0.295 | density=0.424 | time=32.8s
Epoch 002 | step 0093/0093 | loss=1.4785 | main=0.9766 | aux=1.0038 | acc=0.7146 | binary=0.852 | condition=0.920 | count=0.296 | density=0.434 | time=33.6s

train overall: acc=0.7146 (4215/5898)
train macro acc: 0.4057
train by edge head:
  binary       acc=0.8523 (2245/2634)
  condition    acc=0.9203 (1362/1480)
  count        acc=0.2957 (356/1204)
  density      acc=0.4345 (252/580)
train by question type:
  Building_Condition_Recognition           acc=0.8483 (492/580)
  Complex_Counting                         acc=0.2468 (154/624)
  Density_Estimation                       acc=0.4345 (252/580)
  Entire_Image_Condition_Recognition       acc=0.9084 (1239/1364)
  Risk_Assessment                          acc=0.8552 (496/580)
  Road_Condition_Recognition               acc=0.8679 (1380/1590)
  Simple_Counting                          acc=0.3483 (202/580)

valid overall: acc=0.8278 (1495/1806)
valid macro acc: 0.5981
valid by edge head:
  binary       acc=0.9066 (738/814)
  condition    acc=0.9421 (423/449)
  count        acc=0.5259 (193/367)
  density      acc=0.8011 (141/176)
valid by question type:
  Building_Condition_Recognition           acc=0.8750 (154/176)
  Complex_Counting                         acc=0.4555 (87/191)
  Density_Estimation                       acc=0.8011 (141/176)
  Entire_Image_Condition_Recognition       acc=0.9492 (392/413)
  Risk_Assessment                          acc=0.9602 (169/176)
  Road_Condition_Recognition               acc=0.8956 (446/498)
  Simple_Counting                          acc=0.6023 (106/176)

Epoch 2 done | train_acc=0.7146 | valid_acc=0.8278 | best_valid_acc=0.8278 at epoch 2 | IMPROVED

================================================================================
Epoch 3/30
================================================================================
Epoch 003 | step 0001/0093 | loss=0.7463 | main=0.5462 | aux=0.4001 | acc=0.8750 | binary=0.882 | condition=1.000 | count=0.600 | density=1.000 | time=0.7s
Epoch 003 | step 0005/0093 | loss=0.9645 | main=0.6432 | aux=0.6425 | acc=0.8344 | binary=0.888 | condition=0.953 | count=0.500 | density=0.852 | time=2.0s
Epoch 003 | step 0010/0093 | loss=1.0946 | main=0.6911 | aux=0.8070 | acc=0.8250 | binary=0.897 | condition=0.956 | count=0.496 | density=0.828 | time=3.6s
Epoch 003 | step 0015/0093 | loss=1.0937 | main=0.6879 | aux=0.8117 | acc=0.8292 | binary=0.904 | condition=0.959 | count=0.516 | density=0.794 | time=5.2s
Epoch 003 | step 0020/0093 | loss=1.0683 | main=0.6712 | aux=0.7943 | acc=0.8305 | binary=0.895 | condition=0.957 | count=0.533 | density=0.797 | time=7.0s
Epoch 003 | step 0025/0093 | loss=1.0675 | main=0.6720 | aux=0.7910 | acc=0.8244 | binary=0.888 | condition=0.950 | count=0.533 | density=0.793 | time=8.8s
Epoch 003 | step 0030/0093 | loss=1.0594 | main=0.6633 | aux=0.7921 | acc=0.8271 | binary=0.885 | condition=0.957 | count=0.547 | density=0.799 | time=10.6s
Epoch 003 | step 0035/0093 | loss=1.0435 | main=0.6529 | aux=0.7812 | acc=0.8272 | binary=0.884 | condition=0.957 | count=0.555 | density=0.788 | time=12.3s
Epoch 003 | step 0040/0093 | loss=1.0364 | main=0.6428 | aux=0.7871 | acc=0.8293 | binary=0.886 | condition=0.960 | count=0.555 | density=0.788 | time=14.0s
Epoch 003 | step 0045/0093 | loss=1.0485 | main=0.6483 | aux=0.8004 | acc=0.8247 | binary=0.880 | condition=0.962 | count=0.546 | density=0.801 | time=15.8s
Epoch 003 | step 0050/0093 | loss=1.0334 | main=0.6375 | aux=0.7919 | acc=0.8278 | binary=0.884 | condition=0.962 | count=0.553 | density=0.801 | time=17.5s
Epoch 003 | step 0055/0093 | loss=1.0239 | main=0.6306 | aux=0.7866 | acc=0.8295 | binary=0.885 | condition=0.962 | count=0.558 | density=0.797 | time=19.2s
Epoch 003 | step 0060/0093 | loss=1.0154 | main=0.6215 | aux=0.7877 | acc=0.8307 | binary=0.885 | condition=0.964 | count=0.560 | density=0.795 | time=21.0s
Epoch 003 | step 0065/0093 | loss=0.9983 | main=0.6117 | aux=0.7734 | acc=0.8334 | binary=0.887 | condition=0.966 | count=0.569 | density=0.802 | time=23.0s
Epoch 003 | step 0070/0093 | loss=1.0015 | main=0.6101 | aux=0.7828 | acc=0.8333 | binary=0.882 | condition=0.968 | count=0.569 | density=0.810 | time=25.0s
Epoch 003 | step 0075/0093 | loss=0.9996 | main=0.6048 | aux=0.7897 | acc=0.8323 | binary=0.881 | condition=0.969 | count=0.568 | density=0.806 | time=26.7s
Epoch 003 | step 0080/0093 | loss=0.9936 | main=0.5992 | aux=0.7888 | acc=0.8352 | binary=0.885 | condition=0.967 | count=0.578 | density=0.807 | time=28.4s
Epoch 003 | step 0085/0093 | loss=0.9877 | main=0.5938 | aux=0.7877 | acc=0.8360 | binary=0.883 | condition=0.967 | count=0.581 | density=0.812 | time=30.1s
Epoch 003 | step 0090/0093 | loss=0.9743 | main=0.5871 | aux=0.7746 | acc=0.8368 | binary=0.883 | condition=0.968 | count=0.587 | density=0.810 | time=31.8s
Epoch 003 | step 0093/0093 | loss=0.9720 | main=0.5850 | aux=0.7741 | acc=0.8374 | binary=0.882 | condition=0.968 | count=0.589 | density=0.816 | time=32.5s

train overall: acc=0.8374 (4939/5898)
train macro acc: 0.6397
train by edge head:
  binary       acc=0.8823 (2324/2634)
  condition    acc=0.9682 (1433/1480)
  count        acc=0.5889 (709/1204)
  density      acc=0.8155 (473/580)
train by question type:
  Building_Condition_Recognition           acc=0.8879 (515/580)
  Complex_Counting                         acc=0.5304 (331/624)
  Density_Estimation                       acc=0.8155 (473/580)
  Entire_Image_Condition_Recognition       acc=0.9326 (1272/1364)
  Risk_Assessment                          acc=0.8810 (511/580)
  Road_Condition_Recognition               acc=0.9176 (1459/1590)
  Simple_Counting                          acc=0.6517 (378/580)

valid overall: acc=0.8616 (1556/1806)
valid macro acc: 0.6584
valid by edge head:
  binary       acc=0.9177 (747/814)
  condition    acc=0.9688 (435/449)
  count        acc=0.6104 (224/367)
  density      acc=0.8523 (150/176)
valid by question type:
  Building_Condition_Recognition           acc=0.8977 (158/176)
  Complex_Counting                         acc=0.5916 (113/191)
  Density_Estimation                       acc=0.8523 (150/176)
  Entire_Image_Condition_Recognition       acc=0.9613 (397/413)
  Risk_Assessment                          acc=0.9773 (172/176)
  Road_Condition_Recognition               acc=0.9137 (455/498)
  Simple_Counting                          acc=0.6307 (111/176)

Epoch 3 done | train_acc=0.8374 | valid_acc=0.8616 | best_valid_acc=0.8616 at epoch 3 | IMPROVED

================================================================================
Epoch 4/30
================================================================================
Epoch 004 | step 0001/0093 | loss=0.8608 | main=0.4310 | aux=0.8596 | acc=0.8594 | binary=0.857 | condition=1.000 | count=0.556 | density=0.875 | time=0.7s
Epoch 004 | step 0005/0093 | loss=0.8531 | main=0.5074 | aux=0.6914 | acc=0.8500 | binary=0.852 | condition=0.963 | count=0.676 | density=0.931 | time=2.1s
Epoch 004 | step 0010/0093 | loss=0.8242 | main=0.5057 | aux=0.6368 | acc=0.8547 | binary=0.857 | condition=0.968 | count=0.724 | density=0.846 | time=3.7s
Epoch 004 | step 0015/0093 | loss=0.8142 | main=0.4780 | aux=0.6725 | acc=0.8667 | binary=0.882 | condition=0.973 | count=0.711 | density=0.863 | time=5.4s
Epoch 004 | step 0020/0093 | loss=0.8086 | main=0.4708 | aux=0.6756 | acc=0.8641 | binary=0.879 | condition=0.973 | count=0.708 | density=0.857 | time=7.0s
Epoch 004 | step 0025/0093 | loss=0.7978 | main=0.4690 | aux=0.6576 | acc=0.8638 | binary=0.883 | condition=0.973 | count=0.704 | density=0.856 | time=8.8s
Epoch 004 | step 0030/0093 | loss=0.7789 | main=0.4536 | aux=0.6506 | acc=0.8729 | binary=0.891 | condition=0.974 | count=0.716 | density=0.874 | time=10.6s
Epoch 004 | step 0035/0093 | loss=0.7419 | main=0.4326 | aux=0.6186 | acc=0.8812 | binary=0.897 | condition=0.976 | count=0.729 | density=0.888 | time=12.6s
Epoch 004 | step 0040/0093 | loss=0.7383 | main=0.4160 | aux=0.6444 | acc=0.8867 | binary=0.904 | condition=0.978 | count=0.723 | density=0.901 | time=14.3s
Epoch 004 | step 0045/0093 | loss=0.7360 | main=0.4137 | aux=0.6446 | acc=0.8878 | binary=0.905 | condition=0.979 | count=0.729 | density=0.906 | time=16.1s
Epoch 004 | step 0050/0093 | loss=0.7390 | main=0.4146 | aux=0.6488 | acc=0.8872 | binary=0.906 | condition=0.978 | count=0.731 | density=0.904 | time=17.8s
Epoch 004 | step 0055/0093 | loss=0.7222 | main=0.4075 | aux=0.6293 | acc=0.8892 | binary=0.909 | condition=0.980 | count=0.736 | density=0.900 | time=19.5s
Epoch 004 | step 0060/0093 | loss=0.7111 | main=0.4025 | aux=0.6172 | acc=0.8917 | binary=0.911 | condition=0.981 | count=0.742 | density=0.900 | time=21.3s
Epoch 004 | step 0065/0093 | loss=0.7057 | main=0.3986 | aux=0.6141 | acc=0.8918 | binary=0.912 | condition=0.980 | count=0.741 | density=0.898 | time=23.1s
Epoch 004 | step 0070/0093 | loss=0.6967 | main=0.3951 | aux=0.6032 | acc=0.8917 | binary=0.912 | condition=0.981 | count=0.741 | density=0.897 | time=25.1s
Epoch 004 | step 0075/0093 | loss=0.6850 | main=0.3878 | aux=0.5944 | acc=0.8929 | binary=0.915 | condition=0.979 | count=0.740 | density=0.899 | time=27.2s
Epoch 004 | step 0080/0093 | loss=0.6816 | main=0.3861 | aux=0.5909 | acc=0.8932 | binary=0.913 | condition=0.977 | count=0.742 | density=0.903 | time=29.0s
Epoch 004 | step 0085/0093 | loss=0.6795 | main=0.3837 | aux=0.5915 | acc=0.8938 | binary=0.915 | condition=0.978 | count=0.742 | density=0.899 | time=30.7s
Epoch 004 | step 0090/0093 | loss=0.6738 | main=0.3811 | aux=0.5854 | acc=0.8939 | binary=0.915 | condition=0.978 | count=0.743 | density=0.896 | time=32.4s
Epoch 004 | step 0093/0093 | loss=0.6735 | main=0.3801 | aux=0.5868 | acc=0.8939 | binary=0.915 | condition=0.978 | count=0.744 | density=0.893 | time=33.2s

train overall: acc=0.8939 (5272/5898)
train macro acc: 0.7332
train by edge head:
  binary       acc=0.9150 (2410/2634)
  condition    acc=0.9784 (1448/1480)
  count        acc=0.7442 (896/1204)
  density      acc=0.8931 (518/580)
train by question type:
  Building_Condition_Recognition           acc=0.8948 (519/580)
  Complex_Counting                         acc=0.7196 (449/624)
  Density_Estimation                       acc=0.8931 (518/580)
  Entire_Image_Condition_Recognition       acc=0.9501 (1296/1364)
  Risk_Assessment                          acc=0.9155 (531/580)
  Road_Condition_Recognition               acc=0.9509 (1512/1590)
  Simple_Counting                          acc=0.7707 (447/580)

valid overall: acc=0.8721 (1575/1806)
valid macro acc: 0.6526
valid by edge head:
  binary       acc=0.9509 (774/814)
  condition    acc=0.9755 (438/449)
  count        acc=0.5913 (217/367)
  density      acc=0.8295 (146/176)
valid by question type:

## Collect full teacher ablation results

In [ ]:
from pathlib import Path
import json
import pandas as pd

base = Path("/content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6")
rows = []

for summary_path in sorted(base.glob("*/final_summary.json")):
    with summary_path.open("r") as f:
        row = json.load(f)

    test_metrics_path = summary_path.parent / "test_metrics.json"
    if test_metrics_path.exists():
        with test_metrics_path.open("r") as f:
            test_metrics = json.load(f)

        for head, values in test_metrics.get("by_head", {}).items():
            row[f"test_{head}_acc"] = values.get("accuracy")

        if "macro_accuracy" in test_metrics:
            row["test_macro_acc"] = test_metrics["macro_accuracy"]

        if "count_exact" in test_metrics:
            row["test_count_exact_acc"] = test_metrics["count_exact"]["accuracy"]

        if "count_pm1" in test_metrics:
            row["test_count_pm1_acc"] = test_metrics["count_pm1"]["accuracy"]

    row["run_name"] = summary_path.parent.name
    rows.append(row)

df = pd.DataFrame(rows)

preferred_cols = [
    "run_name",
    "count_cap",
    "question_encoder",
    "loss_mode",
    "best_valid_acc",
    "test_acc",
    "test_macro_acc",
    "test_binary_acc",
    "test_condition_acc",
    "test_count_acc",
    "test_density_acc",
    "test_count_exact_acc",
    "test_count_pm1_acc",
    "best_epoch",
]

cols = [c for c in preferred_cols if c in df.columns]
display(df[cols].sort_values("run_name") if len(df) else df)

out_path = base / "teacher_ablation_summary.csv"
if len(df):
    df[cols].sort_values("run_name").to_csv(out_path, index=False)
    print("Saved:", out_path)

,run_name,count_cap,question_encoder,loss_mode,best_valid_acc,test_acc,test_macro_acc,test_binary_acc,test_condition_acc,test_count_acc,test_density_acc,best_epoch
0,T1_cap10_lstm_ce,10,lstm,ce,0.893688,0.857065,0.514437,0.967073,0.975391,0.509138,0.803279,7
1,T2_cap5_lstm_ce,5,lstm,ce,0.901440,0.869067,0.659255,0.968293,0.979866,0.574413,0.770492,6
2,T3_cap10_template_ce,10,template,ce,0.897564,0.867430,0.530212,0.974390,0.979866,0.522193,0.836066,10
3,T4_cap5_template_ce,5,template,ce,0.893688,0.884343,0.686087,0.968293,0.975391,0.626632,0.825137,10
4,T5_cap5_template_weighted_ce,5,template,weighted_ce,0.897010,0.888707,0.689278,0.971951,0.979866,0.639687,0.814208,13
5,T6_cap5_template_count_aux,5,template,count_aux,0.900886,0.887070,0.691252,0.970732,0.975391,0.642298,0.808743,14

Saved: /content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6/teacher_ablation_summary.csv