# TinyDisasterVQA — final student ablation notebook

This notebook mirrors the teacher ablation notebook, but runs the final student ablation:

1. mount Drive and pull the GitHub repo,
2. unpack FloodNet-VQA,
3. regenerate cap5 preprocessing,
4. run sanity tests and one-epoch student smoke/overfit tests,
5. run full S1–S10 student training in separate cells,
6. collect a final student ablation summary.

Student formulation:

```text
single-head edge_global classifier
cap5 / 14 classes
template question encoder: one-hot + Linear
no multihead student
no LSTM student
```

In [ ]:
from google.colab import drive, userdata
from pathlib import Path
import os
import subprocess

drive.mount("/content/drive")

# Edit these only if needed.
GITHUB_REPO = "jacobinsilico/TinyDisasterVQA"
BRANCH = "submission"
REPO_DIR = Path("/content/TinyDisasterVQA")

try:
    GITHUB_TOKEN = userdata.get("GITHUB_TOKEN")
except Exception:
    GITHUB_TOKEN = None

if GITHUB_TOKEN:
    CLONE_URL = f"https://x-access-token:{GITHUB_TOKEN}@github.com/{GITHUB_REPO}.git"
else:
    CLONE_URL = f"https://github.com/{GITHUB_REPO}.git"

print("Repo:", GITHUB_REPO)
print("Branch:", BRANCH)
print("Repo dir:", REPO_DIR)
print("Token available:", bool(GITHUB_TOKEN))

Mounted at /content/drive
Repo: jacobinsilico/TinyDisasterVQA
Branch: submission
Repo dir: /content/TinyDisasterVQA
Token available: True

In [ ]:
if REPO_DIR.exists():
    print("Repo already exists. Fetching and pulling...")
    subprocess.run(["git", "-C", str(REPO_DIR), "fetch", "origin"], check=True)
    subprocess.run(["git", "-C", str(REPO_DIR), "checkout", BRANCH], check=True)
    subprocess.run(["git", "-C", str(REPO_DIR), "pull", "origin", BRANCH], check=True)
else:
    print("Cloning repo...")
    subprocess.run(["git", "clone", "--branch", BRANCH, CLONE_URL, str(REPO_DIR)], check=True)

os.environ["PYTHONPATH"] = f"{REPO_DIR / 'src'}:" + os.environ.get("PYTHONPATH", "")
os.environ["PYTHONUNBUFFERED"] = "1"

print()
subprocess.run(["git", "-C", str(REPO_DIR), "status", "--short"], check=True)
subprocess.run(["git", "-C", str(REPO_DIR), "rev-parse", "--abbrev-ref", "HEAD"], check=True)
subprocess.run(["git", "-C", str(REPO_DIR), "log", "-1", "--oneline"], check=True)
print("PYTHONPATH =", os.environ["PYTHONPATH"])
print("PYTHONUNBUFFERED =", os.environ["PYTHONUNBUFFERED"])

Cloning repo...

PYTHONPATH = /content/TinyDisasterVQA/src:/env/python
PYTHONUNBUFFERED = 1

In [ ]:
%cd /content/TinyDisasterVQA
%env PYTHONPATH=/content/TinyDisasterVQA/src
%env PYTHONUNBUFFERED=1

!nvidia-smi
!python --version
!pip install -q pandas pillow tqdm matplotlib torch torchvision

/content/TinyDisasterVQA
env: PYTHONPATH=/content/TinyDisasterVQA/src
env: PYTHONUNBUFFERED=1
Wed Jun 10 08:51:10 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   59C    P8             12W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
Python 3.12.13

## Dataset setup

This expects:

```text
/content/drive/MyDrive/floodnet-data.tar
```

After extraction, the repo should contain:

```text
dataset/data/
dataset/images/
```

In [ ]:
%cd /content/TinyDisasterVQA

!rm -rf dataset
!mkdir -p dataset
!tar -xf /content/drive/MyDrive/floodnet-data.tar -C dataset

# Normalize old archive layout if it extracts as dataset/floodnet-data/{data,images}.
!if [ -d dataset/floodnet-data ]; then rm -rf dataset/data dataset/images; mv dataset/floodnet-data/data dataset/; mv dataset/floodnet-data/images dataset/; rm -rf dataset/floodnet-data; fi

!echo "Dataset directories:"
!find dataset -maxdepth 3 -type d | sort

!test -f dataset/data/train_annotations.json
!test -f dataset/data/valid_annotations.json
!test -f dataset/data/test_annotations.json
!test -d dataset/images/train_images
!test -d dataset/images/valid_images
!test -d dataset/images/test_images

!echo "Dataset setup OK."

/content/TinyDisasterVQA
Dataset directories:
dataset
dataset/data
dataset/images
dataset/images/test_images
dataset/images/train_images
dataset/images/valid_images
Dataset setup OK.

## Preprocess cap5 only

Students use the final cap5 formulation:

```text
outputs/training_data_cap5
outputs/answer_space_cap5
```

In [ ]:
%cd /content/TinyDisasterVQA
%env PYTHONPATH=/content/TinyDisasterVQA/src
%env PYTHONUNBUFFERED=1

!python -u scripts/01_explore_dataset.py \
  --dataset-root dataset \
  --count-cap 5 \
  --output-dir outputs/exploration_cap5

!python -u scripts/02_build_manifest.py \
  --dataset-root dataset \
  --count-cap 5 \
  --output-dir outputs/processed_cap5

!python -u scripts/03_build_answer_space.py \
  --manifest outputs/processed_cap5/floodnet_manifest.csv \
  --output-dir outputs/answer_space_cap5

!python -u scripts/04_prepare_training_data.py \
  --manifest outputs/processed_cap5/floodnet_manifest.csv \
  --word-to-token outputs/processed_cap5/word_to_token.json \
  --answer-space outputs/answer_space_cap5/answer_space.json \
  --dataset-root dataset \
  --output-dir outputs/training_data_cap5

/content/TinyDisasterVQA
env: PYTHONPATH=/content/TinyDisasterVQA/src
env: PYTHONUNBUFFERED=1
================================================================================
TinyDisasterVQA / FloodNet-VQA Dataset Exploration
================================================================================
Dataset root: /content/TinyDisasterVQA/dataset
Output dir:   /content/TinyDisasterVQA/outputs/exploration_cap5
Count cap:    5+

TinyDisasterVQA / FloodNet-VQA Dataset Exploration
================================================================================
Dataset root: /content/TinyDisasterVQA/dataset
Total QA samples: 9537
Total unique images: 2188
Total unique question templates: 31
Total unique question types: 7
Total unique answers: 49
Question vocabulary size from word_to_token.json: 49
Answer class count from class_to_label.json: 51

Split stats:
split  num_qa_samples  num_unique_images  num_unique_questions  num_unique_question_types  num_unique_answers  num_missing_images
 test            1833                411                    31                          7                  36                   0
train            5898               1364                    31                          7                  43                   0
valid            1806                413                    31                          7                  39                   0

Question type counts:
                     question_type  count  percentage
        Road_Condition_Recognition   2578   27.031561
Entire_Image_Condition_Recognition   2188   22.942225
                  Complex_Counting   1015   10.642760
                Density_Estimation    939    9.845863
    Building_Condition_Recognition    939    9.845863
                   Risk_Assessment    939    9.845863
                   Simple_Counting    939    9.845863

Top 20 answers:
answer_norm  count  percentage
         no   2239   23.476984
        yes   2029   21.275034
non flooded   2028   21.264549
       high    363    3.806228
          1    335    3.512635
    flooded    330    3.460208
          3    324    3.397295
   moderate    292    3.061759
          4    290    3.040789
        low    284    2.977876
          2    271    2.841564
          5    138    1.446996
          6    105    1.100975
          7     62    0.650100
          8     40    0.419419
         16     39    0.408934
         13     35    0.366992
         14     30    0.314564
         17     24    0.251651
         11     24    0.251651

Counting summary:
Counting QA samples: 1954
Counting labels unseen in valid vs train: ['26', '32', '38', '39', '40']
Counting labels unseen in test vs train: ['26', '39', '51']

Image split overlap:
split_a split_b  num_overlapping_images example_overlapping_images
  train   valid                       0
  train    test                       0
  valid    test                       0

Missing images:
Total missing image references: 0

Majority baselines:
                         baseline  valid_accuracy  test_accuracy
  global_majority_train_answer=no        0.248062       0.231315
majority_answer_per_question_type        0.404208       0.405892


Done. Wrote exploration outputs to: outputs/exploration_cap5
================================================================================
TinyDisasterVQA / Build FloodNet Manifest
================================================================================
Dataset root: /content/TinyDisasterVQA/dataset
Output dir:   /content/TinyDisasterVQA/outputs/processed_cap5
Count cap:    5+

TinyDisasterVQA / FloodNet Manifest Summary
================================================================================
Dataset root: /content/TinyDisasterVQA/dataset
Manifest CSV: outputs/processed_cap5/floodnet_manifest.csv
Manifest JSONL: outputs/processed_cap5/floodnet_manifest.jsonl

Task formulation:
  single_head_edge_global
  count_cap: 5+
  edge_global_classes: 14

Total samples: 9537
Unique images: 2188
Question templates: 31
Original answer classes used in data: 49
Original answer classes in class_to_label.json: 51

Split stats:
split  num_samples  num_images  num_question_templates  num_original_answers  num_edge_classes
 test         1833         411                      31                    36                14
train         5898        1364                      31                    43                14
valid         1806         413                      31                    39                14

Edge heads:
split edge_head  count
 test    binary    820
 test condition    447
 test     count    383
 test   density    183
train    binary   2634
train condition   1480
train     count   1204
train   density    580
valid    binary    814
valid condition    449
valid     count    367
valid   density    176

Edge class counts:
split            edge_class  edge_global_label  count
 test             binary:no                  0    424
 test            binary:yes                  1    396
 test     condition:flooded                  2     65
 test       condition:mixed                  3      6
 test condition:non_flooded                  4    376
 test           density:low                  5     61
 test      density:moderate                  6     45
 test          density:high                  7     77
 test               count:1                  8     75
 test               count:2                  9     55
 test               count:3                 10     53
 test               count:4                 11     44
 test               count:5                 12     31
 test              count:5+                 13    125
train             binary:no                  0   1367
train            binary:yes                  1   1267
train     condition:flooded                  2    201
train       condition:mixed                  3      6
train condition:non_flooded                  4   1273
train           density:low                  5    165
train      density:moderate                  6    195
train          density:high                  7    220
train               count:1                  8    184
train               count:2                  9    165
train               count:3                 10    220
train               count:4                 11    190
train               count:5                 12     82
train              count:5+                 13    363
valid             binary:no                  0    448
valid            binary:yes                  1    366
valid     condition:flooded                  2     64
valid       condition:mixed                  3      6
valid condition:non_flooded                  4    379
valid           density:low                  5     58
valid      density:moderate                  6     52
valid          density:high                  7     66
valid               count:1                  8     76
valid               count:2                  9     51
valid               count:3                 10     51
valid               count:4                 11     56
valid               count:5                 12     25
valid              count:5+                 13    108

Head label maps:
{
  "binary": {
    "no": 0,
    "yes": 1
  },
  "condition": {
    "flooded": 0,
    "mixed": 1,
    "non_flooded": 2
  },
  "count": {
    "1": 0,
    "2": 1,
    "3": 2,
    "4": 3,
    "5": 4,
    "5+": 5
  },
  "density": {
    "high": 2,
    "low": 0,
    "moderate": 1
  }
}

Edge class to label:
{
  "binary:no": 0,
  "binary:yes": 1,
  "condition:flooded": 2,
  "condition:mixed": 3,
  "condition:non_flooded": 4,
  "count:1": 8,
  "count:2": 9,
  "count:3": 10,
  "count:4": 11,
  "count:5": 12,
  "count:5+": 13,
  "density:high": 7,
  "density:low": 5,
  "density:moderate": 6
}

Original labels unseen in valid compared to train:
['26', '32', '38', '39', '40']

Original labels unseen in test compared to train:
['26', '39', '51']

Edge classes unseen in valid compared to train:
[]

Edge classes unseen in test compared to train:
[]

Count capped counts:
split edge_answer  edge_global_label  count
 test           1                  8     75
 test           2                  9     55
 test           3                 10     53
 test           4                 11     44
 test           5                 12     31
 test          5+                 13    125
train           1                  8    184
train           2                  9    165
train           3                 10    220
train           4                 11    190
train           5                 12     82
train          5+                 13    363
valid           1                  8     76
valid           2                  9     51
valid           3                 10     51
valid           4                 11     56
valid           5                 12     25
valid          5+                 13    108

Done. Wrote manifest outputs to: outputs/processed_cap5
================================================================================
TinyDisasterVQA / Build Answer Space
================================================================================
Manifest:   /content/TinyDisasterVQA/outputs/processed_cap5/floodnet_manifest.csv
Output dir: /content/TinyDisasterVQA/outputs/answer_space_cap5
Weights:    inverse_sqrt

TinyDisasterVQA / Answer Space Summary
================================================================================
Manifest: outputs/processed_cap5/floodnet_manifest.csv
Total samples: 9537

Task formulation:
  single_head_edge_global
  count_cap: 5+
  edge_global_classes: 14

Original global answer space:
  Classes used in manifest: 49
  Valid unseen answers vs train: ['26', '32', '38', '39', '40']
  Test unseen answers vs train:  ['26', '39', '51']

Edge global answer space:
  Classes: 14
  Valid unseen classes vs train: []
  Test unseen classes vs train:  []

Edge global classes:
  00: binary:no                 train_count=1367  weight=0.3070
  01: binary:yes                train_count=1267  weight=0.3189
  02: condition:flooded         train_count=201   weight=0.8007
  03: condition:mixed           train_count=6     weight=4.6343
  04: condition:non_flooded     train_count=1273  weight=0.3182
  05: density:low               train_count=165   weight=0.8837
  06: density:moderate          train_count=195   weight=0.8129
  07: density:high              train_count=220   weight=0.7653
  08: count:1                   train_count=184   weight=0.8369
  09: count:2                   train_count=165   weight=0.8837
  10: count:3                   train_count=220   weight=0.7653
  11: count:4                   train_count=190   weight=0.8235
  12: count:5                   train_count=82    weight=1.2536
  13: count:5+                  train_count=363   weight=0.5958

Edge heads:
  binary       train_count=2634
  condition    train_count=1480
  count        train_count=1204
  density      train_count=580

Local labels by edge head:
  binary: 2 classes
    00: no           train_count=1367
    01: yes          train_count=1267
  condition: 3 classes
    00: flooded      train_count=201
    01: mixed        train_count=6
    02: non_flooded  train_count=1273
  density: 3 classes
    00: low          train_count=165
    01: moderate     train_count=195
    02: high         train_count=220
  count: 6 classes
    00: 1            train_count=184
    01: 2            train_count=165
    02: 3            train_count=220
    03: 4            train_count=190
    04: 5            train_count=82
    05: 5+           train_count=363

Recommended:
  Use edge_global as the main teacher/student/deployment target.
  Use class_weights_edge_global_by_label.json for weighted CE ablation.
  Use edge_head/target_edge_head only for diagnostics or count auxiliary loss.

Done. Wrote answer-space outputs to: outputs/answer_space_cap5
================================================================================
TinyDisasterVQA / Prepare Training Data
================================================================================
Manifest:         /content/TinyDisasterVQA/outputs/processed_cap5/floodnet_manifest.csv
Word-to-token:    /content/TinyDisasterVQA/outputs/processed_cap5/word_to_token.json
Answer space:     /content/TinyDisasterVQA/outputs/answer_space_cap5/answer_space.json
Dataset root:     /content/TinyDisasterVQA/dataset
Output dir:       /content/TinyDisasterVQA/outputs/training_data_cap5
Max question len: 11

TinyDisasterVQA / Training Data Summary
================================================================================
Task formulation:
  target_formulation: single_head_edge_global
  main target: target_edge_global
  count_cap: 5+
  num_edge_global_classes: 14

Total samples: 9537
Train samples: 5898
Valid samples: 1806
Test samples:  1833

Question templates: 31
Vocabulary size with PAD=0: 50
UNK id: 1
PAD id: 0
Max observed question length: 11
Fixed max question length: 11
Questions longer than max length: 0
OOV token count: 0

Head distribution:
split edge_head  count
 test    binary    820
 test condition    447
 test     count    383
 test   density    183
train    binary   2634
train condition   1480
train     count   1204
train   density    580
valid    binary    814
valid condition    449
valid     count    367
valid   density    176

Target counts:
split            edge_class  target_edge_global  count
 test             binary:no                   0    424
 test            binary:yes                   1    396
 test     condition:flooded                   2     65
 test       condition:mixed                   3      6
 test condition:non_flooded                   4    376
 test           density:low                   5     61
 test      density:moderate                   6     45
 test          density:high                   7     77
 test               count:1                   8     75
 test               count:2                   9     55
 test               count:3                  10     53
 test               count:4                  11     44
 test               count:5                  12     31
 test              count:5+                  13    125
train             binary:no                   0   1367
train            binary:yes                   1   1267
train     condition:flooded                   2    201
train       condition:mixed                   3      6
train condition:non_flooded                   4   1273
train           density:low                   5    165
train      density:moderate                   6    195
train          density:high                   7    220
train               count:1                   8    184
train               count:2                   9    165
train               count:3                  10    220
train               count:4                  11    190
train               count:5                  12     82
train              count:5+                  13    363
valid             binary:no                   0    448
valid            binary:yes                   1    366
valid     condition:flooded                   2     64
valid       condition:mixed                   3      6
valid condition:non_flooded                   4    379
valid           density:low                   5     58
valid      density:moderate                   6     52
valid          density:high                   7     66
valid               count:1                   8     76
valid               count:2                   9     51
valid               count:3                  10     51
valid               count:4                  11     56
valid               count:5                  12     25
valid              count:5+                  13    108

Outputs:
  outputs/training_data_cap5/train.csv
  outputs/training_data_cap5/valid.csv
  outputs/training_data_cap5/test.csv
  outputs/training_data_cap5/metadata.json
  outputs/training_data_cap5/target_counts.csv
  outputs/training_data_cap5/head_distribution.csv
  outputs/training_data_cap5/question_template_distribution.csv

Done. Wrote training data to: outputs/training_data_cap5

## Sanity tests

Run these before full student training.

In [ ]:
%cd /content/TinyDisasterVQA
%env PYTHONPATH=/content/TinyDisasterVQA/src
%env PYTHONUNBUFFERED=1

!python -u testing/01_test_dataloader.py \
  --data-dir outputs/training_data_cap5

!python -u testing/02_test_teacher_forward.py \
  --data-dir outputs/training_data_cap5 \
  --modes template

/content/TinyDisasterVQA
env: PYTHONPATH=/content/TinyDisasterVQA/src
env: PYTHONUNBUFFERED=1
================================================================================
TinyDisasterVQA / Dataloader sanity check
================================================================================
Data dir:      /content/TinyDisasterVQA/outputs/training_data_cap5
Train CSV:     outputs/training_data_cap5/train.csv
Valid CSV:     outputs/training_data_cap5/valid.csv
Test CSV:      outputs/training_data_cap5/test.csv
Dataset root:  /content/TinyDisasterVQA/dataset
Target modes:  ['edge_global', 'edge_multihead', 'original']


================================================================================
Checking target_mode=edge_global / train
================================================================================
Batch summary
============================================================
image:                (8, 3, 224, 224)
question_tokens:      (8, 11)
question_length:      (8,)
question_template_id: (8,)
head_id:              (8,)
target:               (8,)

example image_id:     6972.JPG
example question:     What is the total number of non flooded building?
example question type:Complex_Counting
example edge head:    count
example answer:       3
example target:       10

Tensor checks:
  image dtype:                 torch.float32
  image shape:                 (8, 3, 224, 224)
  image min/max:               -2.118 / 2.640
  question_tokens dtype:       torch.int64
  question_tokens shape:       (8, 11)
  question_template_id dtype:  torch.int64
  target dtype:                torch.int64
  unique head_ids:             [0, 2, 3]
  unique targets:              [0, 1, 6, 10]

First 5 samples:
  [0] image_id=6972.JPG | head=count | target=10 | edge_global=10 | edge_head=2 | original=21 | answer=3 | q=What is the total number of non flooded building?
  [1] image_id=9079.JPG | head=count | target=10 | edge_global=10 | edge_head=2 | original=21 | answer=3 | q=How many buildings are in this image?
  [2] image_id=6964.JPG | head=density | target=6 | edge_global=6 | edge_head=1 | original=47 | answer=moderate | q=How dense the area is?
  [3] image_id=9074.JPG | head=binary | target=0 | edge_global=0 | edge_head=0 | original=48 | answer=no | q=Do the rescuers need to take immediate actions?
  [4] image_id=6842.JPG | head=binary | target=1 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is there any non flooded building?

================================================================================
Checking target_mode=edge_global / valid
================================================================================
Batch summary
============================================================
image:                (8, 3, 224, 224)
question_tokens:      (8, 11)
question_length:      (8,)
question_template_id: (8,)
head_id:              (8,)
target:               (8,)

example image_id:     10169.JPG
example question:     How many buildings can be recognized as non flooded?
example question type:Complex_Counting
example edge head:    count
example answer:       4
example target:       11

Tensor checks:
  image dtype:                 torch.float32
  image shape:                 (8, 3, 224, 224)
  image min/max:               -2.118 / 2.640
  question_tokens dtype:       torch.int64
  question_tokens shape:       (8, 11)
  question_template_id dtype:  torch.int64
  target dtype:                torch.int64
  unique head_ids:             [0, 1, 2, 3]
  unique targets:              [0, 1, 4, 6, 11]

First 5 samples:
  [0] image_id=10169.JPG | head=count | target=11 | edge_global=11 | edge_head=3 | original=30 | answer=4 | q=How many buildings can be recognized as non flooded?
  [1] image_id=10169.JPG | head=binary | target=1 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is the entire road non flooded?
  [2] image_id=10169.JPG | head=condition | target=4 | edge_global=4 | edge_head=2 | original=49 | answer=non flooded | q=What is the condition of the road in this image?
  [3] image_id=10169.JPG | head=condition | target=4 | edge_global=4 | edge_head=2 | original=49 | answer=non flooded | q=What is the overall condition of the given image?
  [4] image_id=10169.JPG | head=density | target=6 | edge_global=6 | edge_head=1 | original=47 | answer=moderate | q=What is the level of density in this image?

================================================================================
Checking target_mode=edge_global / test
================================================================================
Batch summary
============================================================
image:                (8, 3, 224, 224)
question_tokens:      (8, 11)
question_length:      (8,)
question_template_id: (8,)
head_id:              (8,)
target:               (8,)

example image_id:     10163.JPG
example question:     Is the area mostly non flooded
example question type:Entire_Image_Condition_Recognition
example edge head:    binary
example answer:       yes
example target:       1

Tensor checks:
  image dtype:                 torch.float32
  image shape:                 (8, 3, 224, 224)
  image min/max:               -2.118 / 2.640
  question_tokens dtype:       torch.int64
  question_tokens shape:       (8, 11)
  question_template_id dtype:  torch.int64
  target dtype:                torch.int64
  unique head_ids:             [0, 1, 2, 3]
  unique targets:              [0, 1, 4, 7, 13]

First 5 samples:
  [0] image_id=10163.JPG | head=binary | target=1 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is the area mostly non flooded
  [1] image_id=10164.JPG | head=condition | target=4 | edge_global=4 | edge_head=2 | original=49 | answer=non flooded | q=what is the current state of the area?
  [2] image_id=10174.JPG | head=binary | target=1 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is the entire road non flooded?
  [3] image_id=10174.JPG | head=density | target=7 | edge_global=7 | edge_head=2 | original=45 | answer=high | q=What is the level of density in this image?
  [4] image_id=10174.JPG | head=binary | target=1 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is there any non flooded building?

================================================================================
Checking target_mode=edge_multihead / train
================================================================================
Batch summary
============================================================
image:                (8, 3, 224, 224)
question_tokens:      (8, 11)
question_length:      (8,)
question_template_id: (8,)
head_id:              (8,)
target:               (8,)

example image_id:     7267.JPG
example question:     How many flooded buildings can be seen in this image?
example question type:Complex_Counting
example edge head:    count
example answer:       4
example target:       3

Tensor checks:
  image dtype:                 torch.float32
  image shape:                 (8, 3, 224, 224)
  image min/max:               -2.118 / 2.640
  question_tokens dtype:       torch.int64
  question_tokens shape:       (8, 11)
  question_template_id dtype:  torch.int64
  target dtype:                torch.int64
  unique head_ids:             [0, 1, 3]
  unique targets:              [0, 1, 2, 3, 5]

First 5 samples:
  [0] image_id=7267.JPG | head=count | target=3 | edge_global=11 | edge_head=3 | original=30 | answer=4 | q=How many flooded buildings can be seen in this image?
  [1] image_id=7405.JPG | head=count | target=5 | edge_global=13 | edge_head=5 | original=2 | answer=11 | q=How many buildings are flooded in this image?
  [2] image_id=9104.JPG | head=count | target=5 | edge_global=13 | edge_head=5 | original=40 | answer=7 | q=How many buildings are in this image?
  [3] image_id=7298.JPG | head=binary | target=1 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is this area need immediate help?
  [4] image_id=10806.JPG | head=binary | target=0 | edge_global=0 | edge_head=0 | original=48 | answer=no | q=Is there any flooded building?

================================================================================
Checking target_mode=edge_multihead / valid
================================================================================
Batch summary
============================================================
image:                (8, 3, 224, 224)
question_tokens:      (8, 11)
question_length:      (8,)
question_template_id: (8,)
head_id:              (8,)
target:               (8,)

example image_id:     10169.JPG
example question:     How many buildings can be recognized as non flooded?
example question type:Complex_Counting
example edge head:    count
example answer:       4
example target:       3

Tensor checks:
  image dtype:                 torch.float32
  image shape:                 (8, 3, 224, 224)
  image min/max:               -2.118 / 2.640
  question_tokens dtype:       torch.int64
  question_tokens shape:       (8, 11)
  question_template_id dtype:  torch.int64
  target dtype:                torch.int64
  unique head_ids:             [0, 1, 2, 3]
  unique targets:              [0, 1, 2, 3]

First 5 samples:
  [0] image_id=10169.JPG | head=count | target=3 | edge_global=11 | edge_head=3 | original=30 | answer=4 | q=How many buildings can be recognized as non flooded?
  [1] image_id=10169.JPG | head=binary | target=1 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is the entire road non flooded?
  [2] image_id=10169.JPG | head=condition | target=2 | edge_global=4 | edge_head=2 | original=49 | answer=non flooded | q=What is the condition of the road in this image?
  [3] image_id=10169.JPG | head=condition | target=2 | edge_global=4 | edge_head=2 | original=49 | answer=non flooded | q=What is the overall condition of the given image?
  [4] image_id=10169.JPG | head=density | target=1 | edge_global=6 | edge_head=1 | original=47 | answer=moderate | q=What is the level of density in this image?

================================================================================
Checking target_mode=edge_multihead / test
================================================================================
Batch summary
============================================================
image:                (8, 3, 224, 224)
question_tokens:      (8, 11)
question_length:      (8,)
question_template_id: (8,)
head_id:              (8,)
target:               (8,)

example image_id:     10163.JPG
example question:     Is the area mostly non flooded
example question type:Entire_Image_Condition_Recognition
example edge head:    binary
example answer:       yes
example target:       1

Tensor checks:
  image dtype:                 torch.float32
  image shape:                 (8, 3, 224, 224)
  image min/max:               -2.118 / 2.640
  question_tokens dtype:       torch.int64
  question_tokens shape:       (8, 11)
  question_template_id dtype:  torch.int64
  target dtype:                torch.int64
  unique head_ids:             [0, 1, 2, 3]
  unique targets:              [0, 1, 2, 5]

First 5 samples:
  [0] image_id=10163.JPG | head=binary | target=1 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is the area mostly non flooded
  [1] image_id=10164.JPG | head=condition | target=2 | edge_global=4 | edge_head=2 | original=49 | answer=non flooded | q=what is the current state of the area?
  [2] image_id=10174.JPG | head=binary | target=1 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is the entire road non flooded?
  [3] image_id=10174.JPG | head=density | target=2 | edge_global=7 | edge_head=2 | original=45 | answer=high | q=What is the level of density in this image?
  [4] image_id=10174.JPG | head=binary | target=1 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is there any non flooded building?

================================================================================
Checking target_mode=original / train
================================================================================
Batch summary
============================================================
image:                (8, 3, 224, 224)
question_tokens:      (8, 11)
question_length:      (8,)
question_template_id: (8,)
head_id:              (8,)
target:               (8,)

example image_id:     6556.JPG
example question:     How dense the area is?
example question type:Density_Estimation
example edge head:    density
example answer:       moderate
example target:       47

Tensor checks:
  image dtype:                 torch.float32
  image shape:                 (8, 3, 224, 224)
  image min/max:               -2.118 / 2.640
  question_tokens dtype:       torch.int64
  question_tokens shape:       (8, 11)
  question_template_id dtype:  torch.int64
  target dtype:                torch.int64
  unique head_ids:             [0, 1, 2, 3]
  unique targets:              [0, 43, 47, 48, 49, 50]

First 5 samples:
  [0] image_id=6556.JPG | head=density | target=47 | edge_global=6 | edge_head=1 | original=47 | answer=moderate | q=How dense the area is?
  [1] image_id=6656.JPG | head=binary | target=48 | edge_global=0 | edge_head=0 | original=48 | answer=no | q=Do the rescuers need to take immediate actions?
  [2] image_id=7227.JPG | head=binary | target=50 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is the entire road non flooded?
  [3] image_id=8491.JPG | head=condition | target=49 | edge_global=4 | edge_head=2 | original=49 | answer=non flooded | q=What is the condition of the road in this image?
  [4] image_id=7748.JPG | head=count | target=0 | edge_global=8 | edge_head=0 | original=0 | answer=1 | q=How many buildings can be recognized as non flooded?

================================================================================
Checking target_mode=original / valid
================================================================================
Batch summary
============================================================
image:                (8, 3, 224, 224)
question_tokens:      (8, 11)
question_length:      (8,)
question_template_id: (8,)
head_id:              (8,)
target:               (8,)

example image_id:     10169.JPG
example question:     How many buildings can be recognized as non flooded?
example question type:Complex_Counting
example edge head:    count
example answer:       4
example target:       30

Tensor checks:
  image dtype:                 torch.float32
  image shape:                 (8, 3, 224, 224)
  image min/max:               -2.118 / 2.640
  question_tokens dtype:       torch.int64
  question_tokens shape:       (8, 11)
  question_template_id dtype:  torch.int64
  target dtype:                torch.int64
  unique head_ids:             [0, 1, 2, 3]
  unique targets:              [30, 47, 48, 49, 50]

First 5 samples:
  [0] image_id=10169.JPG | head=count | target=30 | edge_global=11 | edge_head=3 | original=30 | answer=4 | q=How many buildings can be recognized as non flooded?
  [1] image_id=10169.JPG | head=binary | target=50 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is the entire road non flooded?
  [2] image_id=10169.JPG | head=condition | target=49 | edge_global=4 | edge_head=2 | original=49 | answer=non flooded | q=What is the condition of the road in this image?
  [3] image_id=10169.JPG | head=condition | target=49 | edge_global=4 | edge_head=2 | original=49 | answer=non flooded | q=What is the overall condition of the given image?
  [4] image_id=10169.JPG | head=density | target=47 | edge_global=6 | edge_head=1 | original=47 | answer=moderate | q=What is the level of density in this image?

================================================================================
Checking target_mode=original / test
================================================================================
Batch summary
============================================================
image:                (8, 3, 224, 224)
question_tokens:      (8, 11)
question_length:      (8,)
question_template_id: (8,)
head_id:              (8,)
target:               (8,)

example image_id:     10163.JPG
example question:     Is the area mostly non flooded
example question type:Entire_Image_Condition_Recognition
example edge head:    binary
example answer:       yes
example target:       50

Tensor checks:
  image dtype:                 torch.float32
  image shape:                 (8, 3, 224, 224)
  image min/max:               -2.118 / 2.640
  question_tokens dtype:       torch.int64
  question_tokens shape:       (8, 11)
  question_template_id dtype:  torch.int64
  target dtype:                torch.int64
  unique head_ids:             [0, 1, 2, 3]
  unique targets:              [39, 45, 48, 49, 50]

First 5 samples:
  [0] image_id=10163.JPG | head=binary | target=50 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is the area mostly non flooded
  [1] image_id=10164.JPG | head=condition | target=49 | edge_global=4 | edge_head=2 | original=49 | answer=non flooded | q=what is the current state of the area?
  [2] image_id=10174.JPG | head=binary | target=50 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is the entire road non flooded?
  [3] image_id=10174.JPG | head=density | target=45 | edge_global=7 | edge_head=2 | original=45 | answer=high | q=What is the level of density in this image?
  [4] image_id=10174.JPG | head=binary | target=50 | edge_global=1 | edge_head=1 | original=50 | answer=yes | q=Is there any non flooded building?

================================================================================
Dataloader sanity check passed.
================================================================================
================================================================================
TinyDisasterVQA / Teacher Forward Sanity Check
================================================================================
Device:             cuda
Data dir:           /content/TinyDisasterVQA/outputs/training_data_cap5
Metadata:           outputs/training_data_cap5/metadata.json
Backbone:           convnext_tiny
Pretrained:         False
Num classes:        14
Num count classes:  6
Modes:              ['template']

================================================================================
Testing teacher mode: template
================================================================================

Model summary
================================================================================
Class:             TeacherVQA
Total params:      28,418,414
Trainable params:  28,418,414
FP32 param size:   108.41 MB
Int8 param size:   27752.4 KB
Image backbone:    convnext_tiny
Pretrained:        False
Image feature dim: 768
Question encoder:  template
Question dim:      128
Num classes:       14
Count aux:         False

Input shapes:
  images:                (4, 3, 224, 224)
  question_tokens:       (4, 11)
  question_lengths:      (4,)
  question_template_ids: (4,)
  targets:               (4,)

Main output:
  logits shape:   (4, 14)
  logits dtype:    torch.float32
  logits min/max:  -0.2231 / 0.1732

First batch predictions:
  [0] pred=11 | target=4 | head=condition | answer=non flooded | q=What is the condition of road?
  [1] pred=11 | target=5 | head=density | answer=low | q=What is the level of density in this image?
  [2] pred=1 | target=6 | head=density | answer=moderate | q=How dense the area is?
  [3] pred=7 | target=0 | head=binary | answer=no | q=Is the entire road flooded?

Teacher mode 'template' forward check passed.

================================================================================
Teacher forward sanity check passed.
================================================================================

## One-epoch student smoke/overfit test

This runs S1–S6 on 32 samples for one epoch.  
It checks that the patched `models.py` and `06_train_student.py` work before launching full training.

KD smoke is skipped here because full KD paths are tested by S7–S10 later.

In [ ]:
%cd /content/TinyDisasterVQA
%env PYTHONPATH=/content/TinyDisasterVQA/src
%env PYTHONUNBUFFERED=1

!mkdir -p /content/drive/MyDrive/TinyDisasterVQA/testing_student_ablation

!python -u testing/04_test_student_ablation.py \
  --skip-kd \
  --runs-dir /content/drive/MyDrive/TinyDisasterVQA/testing_student_ablation \
  --epochs 1 \
  --overfit-samples 32 \
  --batch-size 8 \
  --eval-batch-size 8 \
  --num-workers 0 \
  --device auto

/content/TinyDisasterVQA
env: PYTHONPATH=/content/TinyDisasterVQA/src
env: PYTHONUNBUFFERED=1
================================================================================
TinyDisasterVQA / Student Ablation Smoke + Overfit Test
================================================================================
Repo root:        /content/TinyDisasterVQA
Data dir:         outputs/training_data_cap5
Runs dir:         /content/drive/MyDrive/TinyDisasterVQA/testing_student_ablation
Epochs:           1
Overfit samples:  32
Batch size:       8
Device:           auto
Run stamp:        20260610_085209
PYTHONPATH:       /content/TinyDisasterVQA/src:/content/TinyDisasterVQA/src


================================================================================
[1/6] Running S1 tdm_s ce
================================================================================
/usr/bin/python3 -u scripts/06_train_student.py --dataset-root dataset --runs-dir /content/drive/MyDrive/TinyDisasterVQA/testing_student_ablation --train-csv outputs/training_data_cap5/train.csv --valid-csv outputs/training_data_cap5/valid.csv --test-csv outputs/training_data_cap5/test.csv --metadata outputs/training_data_cap5/metadata.json --class-weights outputs/answer_space_cap5/class_weights_edge_global_by_label.json --image-size 224 --epochs 1 --batch-size 8 --eval-batch-size 8 --num-workers 0 --device auto --overfit-samples 32 --no-augment-train --patience 0 --log-interval 1 --run-name S1_tdm_s_ce_20260610_085209 --student-variant tdm_s --mode ce

================================================================================
TinyDisasterVQA / Train TDM Student
================================================================================
Run dir:              /content/drive/MyDrive/TinyDisasterVQA/testing_student_ablation/S1_tdm_s_ce_20260610_085209
Device:               cuda
Student variant:      tdm_s
Mode:                 ce
Count cap:            5
Num classes:          14
Question templates:   31
AMP:                  True
Image size:           224
Batch size:           8
Eval batch:           8
Epochs:               1
LR:                   0.0003
Weight decay:         0.0001
Patience:             0
Min delta:            0.0
KD alpha:             0.0
KD temp:              0.0

Overfit mode enabled: using first 32 training samples for train/valid/test.
Model summary
================================================================================
Class:             TDMSVQA
Total params:      25,814
Trainable params:  25,814
FP32 param size:   0.10 MB
Int8 param size:   25.2 KB
Student variant:   tdm_s
Image block type:  dsconv
Image channels:    (12, 24, 48, 64, 96)
Image feature dim: 96
Template encoder:  one_hot + Linear
Template input dim:31
Template emb dim:  16
Fusion hidden dim: 96
Fusion layers:     1
Num classes:       14
Head type:         single edge_global


================================================================================
Epoch 1/1
================================================================================
Epoch 001 | step 0001/0004 | loss=2.7202 | ce=2.7202 | kd=0.0000 | acc=0.0000 | binary=0.000 | condition=0.000 | count=0.000 | time=4.8s
Epoch 001 | step 0002/0004 | loss=2.6631 | ce=2.6631 | kd=0.0000 | acc=0.0000 | binary=0.000 | condition=0.000 | count=0.000 | time=4.8s
Epoch 001 | step 0003/0004 | loss=2.6554 | ce=2.6554 | kd=0.0000 | acc=0.0000 | binary=0.000 | condition=0.000 | count=0.000 | density=0.000 | time=4.8s
Epoch 001 | step 0004/0004 | loss=2.6441 | ce=2.6441 | kd=0.0000 | acc=0.0000 | binary=0.000 | condition=0.000 | count=0.000 | density=0.000 | time=4.9s

train overall: acc=0.0000 (0/32)
train macro acc: 0.0000
train count exact: acc=0.0000 (0/8)
train count ±1: acc=0.5000 (4/8)
train by edge head:
  binary       acc=0.0000 (0/15)
  condition    acc=0.0000 (0/5)
  count        acc=0.0000 (0/8)
  density      acc=0.0000 (0/4)
train by question type:
  Building_Condition_Recognition           acc=0.0000 (0/4)
  Complex_Counting                         acc=0.0000 (0/4)
  Density_Estimation                       acc=0.0000 (0/4)
  Entire_Image_Condition_Recognition       acc=0.0000 (0/6)
  Risk_Assessment                          acc=0.0000 (0/4)
  Road_Condition_Recognition               acc=0.0000 (0/6)
  Simple_Counting                          acc=0.0000 (0/4)

valid overall: acc=0.0000 (0/32)
valid macro acc: 0.0000
valid count exact: acc=0.0000 (0/8)
valid count ±1: acc=0.5000 (4/8)
valid by edge head:
  binary       acc=0.0000 (0/15)
  condition    acc=0.0000 (0/5)
  count        acc=0.0000 (0/8)
  density      acc=0.0000 (0/4)
valid by question type:
  Building_Condition_Recognition           acc=0.0000 (0/4)
  Complex_Counting                         acc=0.0000 (0/4)
  Density_Estimation                       acc=0.0000 (0/4)
  Entire_Image_Condition_Recognition       acc=0.0000 (0/6)
  Risk_Assessment                          acc=0.0000 (0/4)
  Road_Condition_Recognition               acc=0.0000 (0/6)
  Simple_Counting                          acc=0.0000 (0/4)

Epoch 1 done | train_acc=0.0000 | valid_acc=0.0000 | best_valid_acc=0.0000 at epoch 1 | no_improve=0/0 | IMPROVED

================================================================================
Evaluating best checkpoint on test set
================================================================================

test overall: acc=0.0000 (0/32)
test macro acc: 0.0000
test count exact: acc=0.0000 (0/8)
test count ±1: acc=0.5000 (4/8)
test by edge head:
  binary       acc=0.0000 (0/15)
  condition    acc=0.0000 (0/5)
  count        acc=0.0000 (0/8)
  density      acc=0.0000 (0/4)
test by question type:
  Building_Condition_Recognition           acc=0.0000 (0/4)
  Complex_Counting                         acc=0.0000 (0/4)
  Density_Estimation                       acc=0.0000 (0/4)
  Entire_Image_Condition_Recognition       acc=0.0000 (0/6)
  Risk_Assessment                          acc=0.0000 (0/4)
  Road_Condition_Recognition               acc=0.0000 (0/6)
  Simple_Counting                          acc=0.0000 (0/4)

================================================================================
Student training complete
================================================================================
Run dir:          /content/drive/MyDrive/TinyDisasterVQA/testing_student_ablation/S1_tdm_s_ce_20260610_085209
Student:          tdm_s
Mode:             ce
Best valid acc:   0.0000
Best epoch:       1
Test acc:         0.0000
Test macro acc:   0.0000
Test count exact: 0.0000
Total time:       5.2s

PASSED: S1 tdm_s ce

================================================================================
[2/6] Running S2 tdm_m ce
================================================================================
/usr/bin/python3 -u scripts/06_train_student.py --dataset-root dataset --runs-dir /content/drive/MyDrive/TinyDisasterVQA/testing_student_ablation --train-csv outputs/training_data_cap5/train.csv --valid-csv outputs/training_data_cap5/valid.csv --test-csv outputs/training_data_cap5/test.csv --metadata outputs/training_data_cap5/metadata.json --class-weights outputs/answer_space_cap5/class_weights_edge_global_by_label.json --image-size 224 --epochs 1 --batch-size 8 --eval-batch-size 8 --num-workers 0 --device auto --overfit-samples 32 --no-augment-train --patience 0 --log-interval 1 --run-name S2_tdm_m_ce_20260610_085209 --student-variant tdm_m --mode ce

================================================================================
TinyDisasterVQA / Train TDM Student
================================================================================
Run dir:              /content/drive/MyDrive/TinyDisasterVQA/testing_student_ablation/S2_tdm_m_ce_20260610_085209
Device:               cuda
Student variant:      tdm_m
Mode:                 ce
Count cap:            5
Num classes:          14
Question templates:   31
AMP:                  True
Image size:           224
Batch size:           8
Eval batch:           8
Epochs:               1
LR:                   0.0003
Weight decay:         0.0001
Patience:             0
Min delta:            0.0
KD alpha:             0.0
KD temp:              0.0

Overfit mode enabled: using first 32 training samples for train/valid/test.
Model summary
================================================================================
Class:             TDMMVQA
Total params:      46,542
Trainable params:  46,542
FP32 param size:   0.18 MB
Int8 param size:   45.5 KB
Student variant:   tdm_m
Image block type:  dsconv
Image channels:    (16, 32, 64, 96, 128)
Image feature dim: 128
Template encoder:  one_hot + Linear
Template input dim:31
Template emb dim:  24
Fusion hidden dim: 128
Fusion layers:     1
Num classes:       14
Head type:         single edge_global


================================================================================
Epoch 1/1
================================================================================
Epoch 001 | step 0001/0004 | loss=2.7271 | ce=2.7271 | kd=0.0000 | acc=0.0000 | binary=0.000 | condition=0.000 | count=0.000 | density=0.000 | time=4.7s
Epoch 001 | step 0002/0004 | loss=2.7051 | ce=2.7051 | kd=0.0000 | acc=0.0000 | binary=0.000 | condition=0.000 | count=0.000 | density=0.000 | time=4.7s
Epoch 001 | step 0003/0004 | loss=2.6862 | ce=2.6862 | kd=0.0000 | acc=0.0000 | binary=0.000 | condition=0.000 | count=0.000 | density=0.000 | time=4.7s
Epoch 001 | step 0004/0004 | loss=2.6635 | ce=2.6635 | kd=0.0000 | acc=0.0000 | binary=0.000 | condition=0.000 | count=0.000 | density=0.000 | time=4.8s

train overall: acc=0.0000 (0/32)
train macro acc: 0.0000
train count exact: acc=0.0000 (0/8)
train count ±1: acc=0.0000 (0/8)
train by edge head:
  binary       acc=0.0000 (0/15)
  condition    acc=0.0000 (0/5)
  count        acc=0.0000 (0/8)
  density      acc=0.0000 (0/4)
train by question type:
  Building_Condition_Recognition           acc=0.0000 (0/4)
  Complex_Counting                         acc=0.0000 (0/4)
  Density_Estimation                       acc=0.0000 (0/4)
  Entire_Image_Condition_Recognition       acc=0.0000 (0/6)
  Risk_Assessment                          acc=0.0000 (0/4)
  Road_Condition_Recognition               acc=0.0000 (0/6)
  Simple_Counting                          acc=0.0000 (0/4)

valid overall: acc=0.0000 (0/32)
valid macro acc: 0.0000
valid count exact: acc=0.0000 (0/8)
valid count ±1: acc=0.0000 (0/8)
valid by edge head:
  binary       acc=0.0000 (0/15)
  condition    acc=0.0000 (0/5)
  count        acc=0.0000 (0/8)
  density      acc=0.0000 (0/4)
valid by question type:
  Building_Condition_Recognition           acc=0.0000 (0/4)
  Complex_Counting                         acc=0.0000 (0/4)
  Density_Estimation                       acc=0.0000 (0/4)
  Entire_Image_Condition_Recognition       acc=0.0000 (0/6)
  Risk_Assessment                          acc=0.0000 (0/4)
  Road_Condition_Recognition               acc=0.0000 (0/6)
  Simple_Counting                          acc=0.0000 (0/4)

Epoch 1 done | train_acc=0.0000 | valid_acc=0.0000 | best_valid_acc=0.0000 at epoch 1 | no_improve=0/0 | IMPROVED

================================================================================
Evaluating best checkpoint on test set
================================================================================

test overall: acc=0.0000 (0/32)
test macro acc: 0.0000
test count exact: acc=0.0000 (0/8)
test count ±1: acc=0.0000 (0/8)
test by edge head:
  binary       acc=0.0000 (0/15)
  condition    acc=0.0000 (0/5)
  count        acc=0.0000 (0/8)
  density      acc=0.0000 (0/4)
test by question type:
  Building_Condition_Recognition           acc=0.0000 (0/4)
  Complex_Counting                         acc=0.0000 (0/4)
  Density_Estimation                       acc=0.0000 (0/4)
  Entire_Image_Condition_Recognition       acc=0.0000 (0/6)
  Risk_Assessment                          acc=0.0000 (0/4)
  Road_Condition_Recognition               acc=0.0000 (0/6)
  Simple_Counting                          acc=0.0000 (0/4)

================================================================================
Student training complete
================================================================================
Run dir:          /content/drive/MyDrive/TinyDisasterVQA/testing_student_ablation/S2_tdm_m_ce_20260610_085209
Student:          tdm_m
Mode:             ce
Best valid acc:   0.0000
Best epoch:       1
Test acc:         0.0000
Test macro acc:   0.0000
Test count exact: 0.0000
Total time:       5.1s

PASSED: S2 tdm_m ce

================================================================================
[3/6] Running S3 tdm_l ce
================================================================================
/usr/bin/python3 -u scripts/06_train_student.py --dataset-root dataset --runs-dir /content/drive/MyDrive/TinyDisasterVQA/testing_student_ablation --train-csv outputs/training_data_cap5/train.csv --valid-csv outputs/training_data_cap5/valid.csv --test-csv outputs/training_data_cap5/test.csv --metadata outputs/training_data_cap5/metadata.json --class-weights outputs/answer_space_cap5/class_weights_edge_global_by_label.json --image-size 224 --epochs 1 --batch-size 8 --eval-batch-size 8 --num-workers 0 --device auto --overfit-samples 32 --no-augment-train --patience 0 --log-interval 1 --run-name S3_tdm_l_ce_20260610_085209 --student-variant tdm_l --mode ce

================================================================================
TinyDisasterVQA / Train TDM Student
================================================================================
Run dir:              /content/drive/MyDrive/TinyDisasterVQA/testing_student_ablation/S3_tdm_l_ce_20260610_085209
Device:               cuda
Student variant:      tdm_l
Mode:                 ce
Count cap:            5
Num classes:          14
Question templates:   31
AMP:                  True
Image size:           224
Batch size:           8
Eval batch:           8
Epochs:               1
LR:                   0.0003
Weight decay:         0.0001
Patience:             0
Min delta:            0.0
KD alpha:             0.0
KD temp:              0.0

Overfit mode enabled: using first 32 training samples for train/valid/test.
Model summary
================================================================================
Class:             TDMLVQA
Total params:      101,310
Trainable params:  101,310
FP32 param size:   0.39 MB
Int8 param size:   98.9 KB
Student variant:   tdm_l
Image block type:  dsconv
Image channels:    (24, 48, 96, 128, 160)
Image feature dim: 160
Template encoder:  one_hot + Linear
Template input dim:31
Template emb dim:  32
Fusion hidden dim: 192
Fusion layers:     2
Num classes:       14
Head type:         single edge_global


================================================================================
Epoch 1/1
================================================================================
Epoch 001 | step 0001/0004 | loss=2.6772 | ce=2.6772 | kd=0.0000 | acc=0.0000 | binary=0.000 | condition=0.000 | count=0.000 | time=2.3s
Epoch 001 | step 0002/0004 | loss=2.6494 | ce=2.6494 | kd=0.0000 | acc=0.1250 | binary=0.000 | condition=0.000 | count=0.000 | density=1.000 | time=2.3s
Epoch 001 | step 0003/0004 | loss=2.6440 | ce=2.6440 | kd=0.0000 | acc=0.1250 | binary=0.000 | condition=0.000 | count=0.000 | density=1.000 | time=2.4s
Epoch 001 | step 0004/0004 | loss=2.6477 | ce=2.6477 | kd=0.0000 | acc=0.0938 | binary=0.000 | condition=0.000 | count=0.000 | density=0.750 | time=2.4s

train overall: acc=0.0938 (3/32)
train macro acc: 0.1250
train count exact: acc=0.0000 (0/8)
train count ±1: acc=0.0000 (0/8)
train by edge head:
  binary       acc=0.0000 (0/15)
  condition    acc=0.0000 (0/5)
  count        acc=0.0000 (0/8)
  density      acc=0.7500 (3/4)
train by question type:
  Building_Condition_Recognition           acc=0.0000 (0/4)
  Complex_Counting                         acc=0.0000 (0/4)
  Density_Estimation                       acc=0.7500 (3/4)
  Entire_Image_Condition_Recognition       acc=0.0000 (0/6)
  Risk_Assessment                          acc=0.0000 (0/4)
  Road_Condition_Recognition               acc=0.0000 (0/6)
  Simple_Counting                          acc=0.0000 (0/4)

valid overall: acc=0.0938 (3/32)
valid macro acc: 0.1250
valid count exact: acc=0.0000 (0/8)
valid count ±1: acc=0.0000 (0/8)
valid by edge head:
  binary       acc=0.0000 (0/15)
  condition    acc=0.0000 (0/5)
  count        acc=0.0000 (0/8)
  density      acc=0.7500 (3/4)
valid by question type:
  Building_Condition_Recognition           acc=0.0000 (0/4)
  Complex_Counting                         acc=0.0000 (0/4)
  Density_Estimation                       acc=0.7500 (3/4)
  Entire_Image_Condition_Recognition       acc=0.0000 (0/6)
  Risk_Assessment                          acc=0.0000 (0/4)
  Road_Condition_Recognition               acc=0.0000 (0/6)
  Simple_Counting                          acc=0.0000 (0/4)

Epoch 1 done | train_acc=0.0938 | valid_acc=0.0938 | best_valid_acc=0.0938 at epoch 1 | no_improve=0/0 | IMPROVED

================================================================================
Evaluating best checkpoint on test set
================================================================================

test overall: acc=0.0938 (3/32)
test macro acc: 0.1250
test count exact: acc=0.0000 (0/8)
test count ±1: acc=0.0000 (0/8)
test by edge head:
  binary       acc=0.0000 (0/15)
  condition    acc=0.0000 (0/5)
  count        acc=0.0000 (0/8)
  density      acc=0.7500 (3/4)
test by question type:
  Building_Condition_Recognition           acc=0.0000 (0/4)
  Complex_Counting                         acc=0.0000 (0/4)
  Density_Estimation                       acc=0.7500 (3/4)
  Entire_Image_Condition_Recognition       acc=0.0000 (0/6)
  Risk_Assessment                          acc=0.0000 (0/4)
  Road_Condition_Recognition               acc=0.0000 (0/6)
  Simple_Counting                          acc=0.0000 (0/4)

================================================================================
Student training complete
================================================================================
Run dir:          /content/drive/MyDrive/TinyDisasterVQA/testing_student_ablation/S3_tdm_l_ce_20260610_085209
Student:          tdm_l
Mode:             ce
Best valid acc:   0.0938
Best epoch:       1
Test acc:         0.0938
Test macro acc:   0.1250
Test count exact: 0.0000
Total time:       2.8s

PASSED: S3 tdm_l ce

================================================================================
[4/6] Running S4 tdm_fast ce
================================================================================
/usr/bin/python3 -u scripts/06_train_student.py --dataset-root dataset --runs-dir /content/drive/MyDrive/TinyDisasterVQA/testing_student_ablation --train-csv outputs/training_data_cap5/train.csv --valid-csv outputs/training_data_cap5/valid.csv --test-csv outputs/training_data_cap5/test.csv --metadata outputs/training_data_cap5/metadata.json --class-weights outputs/answer_space_cap5/class_weights_edge_global_by_label.json --image-size 224 --epochs 1 --batch-size 8 --eval-batch-size 8 --num-workers 0 --device auto --overfit-samples 32 --no-augment-train --patience 0 --log-interval 1 --run-name S4_tdm_fast_ce_20260610_085209 --student-variant tdm_fast --mode ce

================================================================================
TinyDisasterVQA / Train TDM Student
================================================================================
Run dir:              /content/drive/MyDrive/TinyDisasterVQA/testing_student_ablation/S4_tdm_fast_ce_20260610_085209
Device:               cuda
Student variant:      tdm_fast
Mode:                 ce
Count cap:            5
Num classes:          14
Question templates:   31
AMP:                  True
Image size:           224
Batch size:           8
Eval batch:           8
Epochs:               1

## Locate T5 and T6 teacher checkpoints

The KD runs need the best teacher checkpoints from the previous teacher ablation:

```text
/content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6
```

Expected:
- T5 = best overall teacher, weighted CE
- T6 = count-aware teacher

In [ ]:
from pathlib import Path

teacher_base = Path("/content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6")

t5_candidates = sorted(teacher_base.glob("*T5*weighted*/checkpoints/best.pt"))
t6_candidates = sorted(teacher_base.glob("*T6*count*/checkpoints/best.pt"))

T5_CHECKPOINT = str(t5_candidates[-1]) if t5_candidates else ""
T6_CHECKPOINT = str(t6_candidates[-1]) if t6_candidates else ""

print("Teacher base:", teacher_base)
print("T5 candidates:")
for p in t5_candidates:
    print(" ", p)
print("Selected T5:", T5_CHECKPOINT)

print()
print("T6 candidates:")
for p in t6_candidates:
    print(" ", p)
print("Selected T6:", T6_CHECKPOINT)

if not T5_CHECKPOINT:
    raise FileNotFoundError("Could not find T5 checkpoint. Run teacher T5 first or edit T5_CHECKPOINT manually.")

if not T6_CHECKPOINT:
    raise FileNotFoundError("Could not find T6 checkpoint. Run teacher T6 first or edit T6_CHECKPOINT manually.")

Teacher base: /content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6
T5 candidates:
  /content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6/T5_cap5_template_weighted_ce/checkpoints/best.pt
Selected T5: /content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6/T5_cap5_template_weighted_ce/checkpoints/best.pt

T6 candidates:
  /content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6/T6_cap5_template_count_aux/checkpoints/best.pt
Selected T6: /content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6/T6_cap5_template_count_aux/checkpoints/best.pt

# Full S1–S10 student training

All runs write to:

```text
/content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10
```

Each training run is its own cell and uses `!python -u` so Colab prints progress normally.

Default full setting:

- cap5 / 14 classes
- 224×224 images
- 50 epochs
- early stopping patience 8
- batch size 64
- log interval 5

## S1: TDM-S + CE

In [ ]:
%cd /content/TinyDisasterVQA
%env PYTHONPATH=/content/TinyDisasterVQA/src
%env PYTHONUNBUFFERED=1

!mkdir -p /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10

!python -u scripts/06_train_student.py \
  --dataset-root dataset \
  --runs-dir /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10 \
  --train-csv outputs/training_data_cap5/train.csv \
  --valid-csv outputs/training_data_cap5/valid.csv \
  --test-csv outputs/training_data_cap5/test.csv \
  --metadata outputs/training_data_cap5/metadata.json \
  --class-weights outputs/answer_space_cap5/class_weights_edge_global_by_label.json \
  --image-size 224 \
  --epochs 50 \
  --batch-size 64 \
  --eval-batch-size 64 \
  --num-workers 2 \
  --device auto \
  --patience 8 \
  --min-delta 0.001 \
  --log-interval 5 \
  --student-variant tdm_s \
  --mode ce \
  --run-name S1_tdm_s_ce_$(date +%Y%m%d_%H%M%S)

/content/TinyDisasterVQA
env: PYTHONPATH=/content/TinyDisasterVQA/src
env: PYTHONUNBUFFERED=1
================================================================================
TinyDisasterVQA / Train TDM Student
================================================================================
Run dir:              /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10/S1_tdm_s_ce_20260610_085317
Device:               cuda
Student variant:      tdm_s
Mode:                 ce
Count cap:            5
Num classes:          14
Question templates:   31
AMP:                  True
Image size:           224
Batch size:           64
Eval batch:           64
Epochs:               50
LR:                   0.0003
Weight decay:         0.0001
Patience:             8
Min delta:            0.001
KD alpha:             0.0
KD temp:              0.0

Model summary
================================================================================
Class:             TDMSVQA
Total params:      25,814
Trainable params:  25,814
FP32 param size:   0.10 MB
Int8 param size:   25.2 KB
Student variant:   tdm_s
Image block type:  dsconv
Image channels:    (12, 24, 48, 64, 96)
Image feature dim: 96
Template encoder:  one_hot + Linear
Template input dim:31
Template emb dim:  16
Fusion hidden dim: 96
Fusion layers:     1
Num classes:       14
Head type:         single edge_global


================================================================================
Epoch 1/50
================================================================================
Epoch 001 | step 0001/0093 | loss=2.6595 | ce=2.6595 | kd=0.0000 | acc=0.0000 | binary=0.000 | condition=0.000 | count=0.000 | density=0.000 | time=4.9s
Epoch 001 | step 0005/0093 | loss=2.6387 | ce=2.6387 | kd=0.0000 | acc=0.0594 | binary=0.117 | condition=0.000 | count=0.015 | density=0.000 | time=5.1s
Epoch 001 | step 0010/0093 | loss=2.6185 | ce=2.6185 | kd=0.0000 | acc=0.1172 | binary=0.252 | condition=0.000 | count=0.008 | density=0.000 | time=6.0s
Epoch 001 | step 0015/0093 | loss=2.5975 | ce=2.5975 | kd=0.0000 | acc=0.1375 | binary=0.298 | condition=0.000 | count=0.005 | density=0.000 | time=6.5s
Epoch 001 | step 0020/0093 | loss=2.5797 | ce=2.5797 | kd=0.0000 | acc=0.1594 | binary=0.351 | condition=0.000 | count=0.004 | density=0.000 | time=7.5s
Epoch 001 | step 0025/0093 | loss=2.5630 | ce=2.5630 | kd=0.0000 | acc=0.1694 | binary=0.375 | condition=0.000 | count=0.003 | density=0.000 | time=8.8s
Epoch 001 | step 0030/0093 | loss=2.5492 | ce=2.5492 | kd=0.0000 | acc=0.1729 | binary=0.391 | condition=0.000 | count=0.003 | density=0.000 | time=9.9s
Epoch 001 | step 0035/0093 | loss=2.5298 | ce=2.5298 | kd=0.0000 | acc=0.1768 | binary=0.400 | condition=0.000 | count=0.002 | density=0.000 | time=11.2s
Epoch 001 | step 0040/0093 | loss=2.5113 | ce=2.5113 | kd=0.0000 | acc=0.1797 | binary=0.404 | condition=0.000 | count=0.002 | density=0.000 | time=11.9s
Epoch 001 | step 0045/0093 | loss=2.4914 | ce=2.4914 | kd=0.0000 | acc=0.1858 | binary=0.415 | condition=0.000 | count=0.002 | density=0.000 | time=12.7s
Epoch 001 | step 0050/0093 | loss=2.4736 | ce=2.4736 | kd=0.0000 | acc=0.1888 | binary=0.423 | condition=0.000 | count=0.002 | density=0.000 | time=13.3s
Epoch 001 | step 0055/0093 | loss=2.4546 | ce=2.4546 | kd=0.0000 | acc=0.1943 | binary=0.436 | condition=0.000 | count=0.001 | density=0.000 | time=14.0s
Epoch 001 | step 0060/0093 | loss=2.4418 | ce=2.4418 | kd=0.0000 | acc=0.1964 | binary=0.442 | condition=0.000 | count=0.001 | density=0.000 | time=14.7s
Epoch 001 | step 0065/0093 | loss=2.4245 | ce=2.4245 | kd=0.0000 | acc=0.1986 | binary=0.446 | condition=0.000 | count=0.001 | density=0.000 | time=15.3s
Epoch 001 | step 0070/0093 | loss=2.4048 | ce=2.4048 | kd=0.0000 | acc=0.2036 | binary=0.455 | condition=0.000 | count=0.001 | density=0.000 | time=16.0s
Epoch 001 | step 0075/0093 | loss=2.3914 | ce=2.3914 | kd=0.0000 | acc=0.2046 | binary=0.459 | condition=0.000 | count=0.001 | density=0.000 | time=16.6s
Epoch 001 | step 0080/0093 | loss=2.3753 | ce=2.3753 | kd=0.0000 | acc=0.2053 | binary=0.459 | condition=0.000 | count=0.001 | density=0.000 | time=17.4s
Epoch 001 | step 0085/0093 | loss=2.3606 | ce=2.3606 | kd=0.0000 | acc=0.2059 | binary=0.460 | condition=0.003 | count=0.001 | density=0.000 | time=18.1s
Epoch 001 | step 0090/0093 | loss=2.3427 | ce=2.3427 | kd=0.0000 | acc=0.2109 | binary=0.466 | condition=0.012 | count=0.001 | density=0.000 | time=18.7s
Epoch 001 | step 0093/0093 | loss=2.3382 | ce=2.3382 | kd=0.0000 | acc=0.2131 | binary=0.466 | condition=0.020 | count=0.001 | density=0.000 | time=22.3s

train overall: acc=0.2131 (1257/5898)
train macro acc: 0.0709
train count exact: acc=0.0008 (1/1204)
train count ±1: acc=0.0066 (8/1204)
train by edge head:
  binary       acc=0.4658 (1227/2634)
  condition    acc=0.0196 (29/1480)
  count        acc=0.0008 (1/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.5397 (313/580)
  Complex_Counting                         acc=0.0000 (0/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.2507 (342/1364)
  Risk_Assessment                          acc=0.2103 (122/580)
  Road_Condition_Recognition               acc=0.3013 (479/1590)
  Simple_Counting                          acc=0.0017 (1/580)

valid overall: acc=0.3511 (634/1806)
valid macro acc: 0.1114
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.4693 (382/814)
  condition    acc=0.5612 (252/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.5000 (88/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.5012 (207/413)
  Risk_Assessment                          acc=0.5057 (89/176)
  Road_Condition_Recognition               acc=0.5020 (250/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 1 done | train_acc=0.2131 | valid_acc=0.3511 | best_valid_acc=0.3511 at epoch 1 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 2/50
================================================================================
Epoch 002 | step 0001/0093 | loss=2.0461 | ce=2.0461 | kd=0.0000 | acc=0.2969 | binary=0.355 | condition=0.471 | count=0.000 | density=0.000 | time=0.4s
Epoch 002 | step 0005/0093 | loss=2.0951 | ce=2.0951 | kd=0.0000 | acc=0.3094 | binary=0.401 | condition=0.488 | count=0.000 | density=0.000 | time=0.9s
Epoch 002 | step 0010/0093 | loss=2.0976 | ce=2.0976 | kd=0.0000 | acc=0.2891 | binary=0.418 | condition=0.394 | count=0.000 | density=0.000 | time=1.5s
Epoch 002 | step 0015/0093 | loss=2.1015 | ce=2.1015 | kd=0.0000 | acc=0.2844 | binary=0.424 | condition=0.367 | count=0.000 | density=0.000 | time=2.2s
Epoch 002 | step 0020/0093 | loss=2.0906 | ce=2.0906 | kd=0.0000 | acc=0.2961 | binary=0.448 | condition=0.356 | count=0.000 | density=0.000 | time=2.8s
Epoch 002 | step 0025/0093 | loss=2.1111 | ce=2.1111 | kd=0.0000 | acc=0.2925 | binary=0.459 | condition=0.348 | count=0.000 | density=0.000 | time=3.5s
Epoch 002 | step 0030/0093 | loss=2.1047 | ce=2.1047 | kd=0.0000 | acc=0.2979 | binary=0.465 | condition=0.356 | count=0.000 | density=0.000 | time=4.1s
Epoch 002 | step 0035/0093 | loss=2.1033 | ce=2.1033 | kd=0.0000 | acc=0.3022 | binary=0.453 | condition=0.397 | count=0.000 | density=0.000 | time=4.9s
Epoch 002 | step 0040/0093 | loss=2.0960 | ce=2.0960 | kd=0.0000 | acc=0.3055 | binary=0.442 | condition=0.420 | count=0.000 | density=0.000 | time=5.5s
Epoch 002 | step 0045/0093 | loss=2.0954 | ce=2.0954 | kd=0.0000 | acc=0.3069 | binary=0.434 | condition=0.445 | count=0.000 | density=0.000 | time=6.3s
Epoch 002 | step 0050/0093 | loss=2.0960 | ce=2.0960 | kd=0.0000 | acc=0.3122 | binary=0.434 | condition=0.469 | count=0.000 | density=0.000 | time=7.0s
Epoch 002 | step 0055/0093 | loss=2.0851 | ce=2.0851 | kd=0.0000 | acc=0.3196 | binary=0.436 | condition=0.487 | count=0.000 | density=0.000 | time=7.7s
Epoch 002 | step 0060/0093 | loss=2.0820 | ce=2.0820 | kd=0.0000 | acc=0.3221 | binary=0.432 | condition=0.504 | count=0.000 | density=0.000 | time=8.4s
Epoch 002 | step 0065/0093 | loss=2.0828 | ce=2.0828 | kd=0.0000 | acc=0.3214 | binary=0.424 | condition=0.516 | count=0.000 | density=0.000 | time=9.3s
Epoch 002 | step 0070/0093 | loss=2.0870 | ce=2.0870 | kd=0.0000 | acc=0.3237 | binary=0.427 | condition=0.529 | count=0.000 | density=0.000 | time=10.5s
Epoch 002 | step 0075/0093 | loss=2.0792 | ce=2.0792 | kd=0.0000 | acc=0.3275 | binary=0.428 | condition=0.540 | count=0.000 | density=0.000 | time=11.5s
Epoch 002 | step 0080/0093 | loss=2.0733 | ce=2.0733 | kd=0.0000 | acc=0.3293 | binary=0.427 | condition=0.548 | count=0.000 | density=0.000 | time=12.6s
Epoch 002 | step 0085/0093 | loss=2.0681 | ce=2.0681 | kd=0.0000 | acc=0.3309 | binary=0.430 | condition=0.550 | count=0.000 | density=0.000 | time=13.9s
Epoch 002 | step 0090/0093 | loss=2.0660 | ce=2.0660 | kd=0.0000 | acc=0.3309 | binary=0.432 | condition=0.549 | count=0.000 | density=0.000 | time=14.5s
Epoch 002 | step 0093/0093 | loss=2.0670 | ce=2.0670 | kd=0.0000 | acc=0.3318 | binary=0.435 | condition=0.547 | count=0.000 | density=0.000 | time=14.7s

train overall: acc=0.3318 (1957/5898)
train macro acc: 0.1063
train count exact: acc=0.0000 (0/1204)
train count ±1: acc=0.0000 (0/1204)
train by edge head:
  binary       acc=0.4355 (1147/2634)
  condition    acc=0.5473 (810/1480)
  count        acc=0.0000 (0/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.4310 (250/580)
  Complex_Counting                         acc=0.0000 (0/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.4956 (676/1364)
  Risk_Assessment                          acc=0.5500 (319/580)
  Road_Condition_Recognition               acc=0.4478 (712/1590)
  Simple_Counting                          acc=0.0000 (0/580)

valid overall: acc=0.3904 (705/1806)
valid macro acc: 0.1225
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.5356 (436/814)
  condition    acc=0.5991 (269/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.4830 (85/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.6102 (252/413)
  Risk_Assessment                          acc=0.6761 (119/176)
  Road_Condition_Recognition               acc=0.5000 (249/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 2 done | train_acc=0.3318 | valid_acc=0.3904 | best_valid_acc=0.3904 at epoch 2 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 3/50
================================================================================
Epoch 003 | step 0001/0093 | loss=1.9775 | ce=1.9775 | kd=0.0000 | acc=0.3438 | binary=0.406 | condition=0.692 | count=0.000 | density=0.000 | time=0.4s
Epoch 003 | step 0005/0093 | loss=1.9877 | ce=1.9877 | kd=0.0000 | acc=0.3875 | binary=0.513 | condition=0.625 | count=0.000 | density=0.000 | time=0.9s
Epoch 003 | step 0010/0093 | loss=2.0565 | ce=2.0565 | kd=0.0000 | acc=0.3594 | binary=0.500 | condition=0.602 | count=0.000 | density=0.000 | time=1.6s
Epoch 003 | step 0015/0093 | loss=2.0173 | ce=2.0173 | kd=0.0000 | acc=0.3760 | binary=0.507 | condition=0.638 | count=0.000 | density=0.000 | time=2.3s
Epoch 003 | step 0020/0093 | loss=2.0197 | ce=2.0197 | kd=0.0000 | acc=0.3812 | binary=0.515 | condition=0.651 | count=0.000 | density=0.000 | time=3.1s
Epoch 003 | step 0025/0093 | loss=2.0115 | ce=2.0115 | kd=0.0000 | acc=0.3769 | binary=0.499 | condition=0.654 | count=0.000 | density=0.000 | time=3.7s
Epoch 003 | step 0030/0093 | loss=2.0030 | ce=2.0030 | kd=0.0000 | acc=0.3896 | binary=0.516 | condition=0.678 | count=0.000 | density=0.000 | time=4.4s
Epoch 003 | step 0035/0093 | loss=1.9890 | ce=1.9890 | kd=0.0000 | acc=0.3955 | binary=0.512 | condition=0.692 | count=0.000 | density=0.000 | time=5.0s
Epoch 003 | step 0040/0093 | loss=1.9837 | ce=1.9837 | kd=0.0000 | acc=0.3934 | binary=0.494 | condition=0.706 | count=0.000 | density=0.000 | time=5.9s
Epoch 003 | step 0045/0093 | loss=1.9690 | ce=1.9690 | kd=0.0000 | acc=0.3983 | binary=0.494 | condition=0.723 | count=0.000 | density=0.000 | time=7.1s
Epoch 003 | step 0050/0093 | loss=1.9706 | ce=1.9706 | kd=0.0000 | acc=0.3966 | binary=0.489 | condition=0.731 | count=0.000 | density=0.000 | time=8.0s
Epoch 003 | step 0055/0093 | loss=1.9623 | ce=1.9623 | kd=0.0000 | acc=0.3969 | binary=0.489 | condition=0.736 | count=0.000 | density=0.000 | time=9.3s
Epoch 003 | step 0060/0093 | loss=1.9567 | ce=1.9567 | kd=0.0000 | acc=0.3990 | binary=0.496 | condition=0.731 | count=0.000 | density=0.000 | time=10.2s
Epoch 003 | step 0065/0093 | loss=1.9572 | ce=1.9572 | kd=0.0000 | acc=0.3969 | binary=0.501 | condition=0.717 | count=0.000 | density=0.000 | time=10.8s
Epoch 003 | step 0070/0093 | loss=1.9422 | ce=1.9422 | kd=0.0000 | acc=0.4000 | binary=0.502 | condition=0.712 | count=0.000 | density=0.000 | time=11.4s
Epoch 003 | step 0075/0093 | loss=1.9368 | ce=1.9368 | kd=0.0000 | acc=0.4015 | binary=0.506 | condition=0.708 | count=0.000 | density=0.000 | time=12.2s
Epoch 003 | step 0080/0093 | loss=1.9277 | ce=1.9277 | kd=0.0000 | acc=0.4074 | binary=0.514 | condition=0.714 | count=0.000 | density=0.000 | time=12.8s
Epoch 003 | step 0085/0093 | loss=1.9206 | ce=1.9206 | kd=0.0000 | acc=0.4142 | binary=0.524 | condition=0.723 | count=0.000 | density=0.000 | time=13.6s
Epoch 003 | step 0090/0093 | loss=1.9115 | ce=1.9115 | kd=0.0000 | acc=0.4184 | binary=0.530 | condition=0.726 | count=0.000 | density=0.000 | time=14.2s
Epoch 003 | step 0093/0093 | loss=1.9056 | ce=1.9056 | kd=0.0000 | acc=0.4207 | binary=0.532 | condition=0.730 | count=0.000 | density=0.000 | time=14.4s

train overall: acc=0.4207 (2481/5898)
train macro acc: 0.1355
train count exact: acc=0.0000 (0/1204)
train count ±1: acc=0.0000 (0/1204)
train by edge head:
  binary       acc=0.5319 (1401/2634)
  condition    acc=0.7297 (1080/1480)
  count        acc=0.0000 (0/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.5483 (318/580)
  Complex_Counting                         acc=0.0000 (0/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.6554 (894/1364)
  Risk_Assessment                          acc=0.6931 (402/580)
  Road_Condition_Recognition               acc=0.5453 (867/1590)
  Simple_Counting                          acc=0.0000 (0/580)

valid overall: acc=0.4795 (866/1806)
valid macro acc: 0.1552
valid count exact: acc=0.0136 (5/367)
valid count ±1: acc=0.0136 (5/367)
valid by edge head:
  binary       acc=0.6057 (493/814)
  condition    acc=0.8196 (368/449)
  count        acc=0.0136 (5/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.5625 (99/176)
  Complex_Counting                         acc=0.0052 (1/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.7603 (314/413)
  Risk_Assessment                          acc=0.7557 (133/176)
  Road_Condition_Recognition               acc=0.6325 (315/498)
  Simple_Counting                          acc=0.0227 (4/176)

Epoch 3 done | train_acc=0.4207 | valid_acc=0.4795 | best_valid_acc=0.4795 at epoch 3 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 4/50
================================================================================
Epoch 004 | step 0001/0093 | loss=1.7439 | ce=1.7439 | kd=0.0000 | acc=0.5469 | binary=0.636 | condition=0.909 | count=0.062 | density=0.000 | time=0.4s
Epoch 004 | step 0005/0093 | loss=1.7187 | ce=1.7187 | kd=0.0000 | acc=0.4781 | binary=0.544 | condition=0.867 | count=0.014 | density=0.000 | time=0.9s
Epoch 004 | step 0010/0093 | loss=1.7225 | ce=1.7225 | kd=0.0000 | acc=0.4750 | binary=0.552 | condition=0.844 | count=0.023 | density=0.000 | time=1.5s
Epoch 004 | step 0015/0093 | loss=1.7249 | ce=1.7249 | kd=0.0000 | acc=0.4760 | binary=0.551 | condition=0.857 | count=0.040 | density=0.000 | time=2.3s
Epoch 004 | step 0020/0093 | loss=1.7024 | ce=1.7024 | kd=0.0000 | acc=0.4734 | binary=0.543 | condition=0.852 | count=0.046 | density=0.000 | time=3.3s
Epoch 004 | step 0025/0093 | loss=1.7040 | ce=1.7040 | kd=0.0000 | acc=0.4656 | binary=0.540 | condition=0.843 | count=0.055 | density=0.000 | time=4.7s
Epoch 004 | step 0030/0093 | loss=1.6947 | ce=1.6947 | kd=0.0000 | acc=0.4703 | binary=0.552 | condition=0.836 | count=0.051 | density=0.000 | time=5.8s
Epoch 004 | step 0035/0093 | loss=1.7059 | ce=1.7059 | kd=0.0000 | acc=0.4763 | binary=0.571 | condition=0.828 | count=0.054 | density=0.000 | time=7.0s
Epoch 004 | step 0040/0093 | loss=1.6746 | ce=1.6746 | kd=0.0000 | acc=0.4984 | binary=0.590 | condition=0.844 | count=0.069 | density=0.000 | time=7.6s
Epoch 004 | step 0045/0093 | loss=1.6793 | ce=1.6793 | kd=0.0000 | acc=0.5045 | binary=0.606 | condition=0.852 | count=0.075 | density=0.000 | time=8.3s
Epoch 004 | step 0050/0093 | loss=1.6724 | ce=1.6724 | kd=0.0000 | acc=0.5112 | binary=0.622 | condition=0.849 | count=0.084 | density=0.000 | time=8.9s
Epoch 004 | step 0055/0093 | loss=1.6578 | ce=1.6578 | kd=0.0000 | acc=0.5188 | binary=0.632 | condition=0.853 | count=0.086 | density=0.000 | time=9.6s
Epoch 004 | step 0060/0093 | loss=1.6579 | ce=1.6579 | kd=0.0000 | acc=0.5169 | binary=0.633 | condition=0.851 | count=0.086 | density=0.000 | time=10.3s
Epoch 004 | step 0065/0093 | loss=1.6496 | ce=1.6496 | kd=0.0000 | acc=0.5183 | binary=0.641 | condition=0.847 | count=0.084 | density=0.000 | time=11.0s
Epoch 004 | step 0070/0093 | loss=1.6412 | ce=1.6412 | kd=0.0000 | acc=0.5192 | binary=0.642 | condition=0.847 | count=0.085 | density=0.000 | time=11.7s
Epoch 004 | step 0075/0093 | loss=1.6333 | ce=1.6333 | kd=0.0000 | acc=0.5219 | binary=0.648 | condition=0.845 | count=0.088 | density=0.000 | time=12.4s
Epoch 004 | step 0080/0093 | loss=1.6244 | ce=1.6244 | kd=0.0000 | acc=0.5244 | binary=0.653 | condition=0.844 | count=0.094 | density=0.000 | time=13.0s
Epoch 004 | step 0085/0093 | loss=1.6211 | ce=1.6211 | kd=0.0000 | acc=0.5232 | binary=0.653 | condition=0.843 | count=0.095 | density=0.000 | time=13.8s
Epoch 004 | step 0090/0093 | loss=1.6136 | ce=1.6136 | kd=0.0000 | acc=0.5245 | binary=0.653 | condition=0.848 | count=0.099 | density=0.000 | time=14.4s
Epoch 004 | step 0093/0093 | loss=1.6121 | ce=1.6121 | kd=0.0000 | acc=0.5246 | binary=0.651 | condition=0.850 | count=0.100 | density=0.000 | time=14.6s

train overall: acc=0.5246 (3094/5898)
train macro acc: 0.1868
train count exact: acc=0.1005 (121/1204)
train count ±1: acc=0.1005 (121/1204)
train by edge head:
  binary       acc=0.6511 (1715/2634)
  condition    acc=0.8500 (1258/1480)
  count        acc=0.1005 (121/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.6466 (375/580)
  Complex_Counting                         acc=0.0817 (51/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.7793 (1063/1364)
  Risk_Assessment                          acc=0.8293 (481/580)
  Road_Condition_Recognition               acc=0.6629 (1054/1590)

## S2: TDM-M + CE

In [ ]:
%cd /content/TinyDisasterVQA
%env PYTHONPATH=/content/TinyDisasterVQA/src
%env PYTHONUNBUFFERED=1

!mkdir -p /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10

!python -u scripts/06_train_student.py \
  --dataset-root dataset \
  --runs-dir /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10 \
  --train-csv outputs/training_data_cap5/train.csv \
  --valid-csv outputs/training_data_cap5/valid.csv \
  --test-csv outputs/training_data_cap5/test.csv \
  --metadata outputs/training_data_cap5/metadata.json \
  --class-weights outputs/answer_space_cap5/class_weights_edge_global_by_label.json \
  --image-size 224 \
  --epochs 50 \
  --batch-size 64 \
  --eval-batch-size 64 \
  --num-workers 2 \
  --device auto \
  --patience 8 \
  --min-delta 0.001 \
  --log-interval 5 \
  --student-variant tdm_m \
  --mode ce \
  --run-name S2_tdm_m_ce_$(date +%Y%m%d_%H%M%S)

/content/TinyDisasterVQA
env: PYTHONPATH=/content/TinyDisasterVQA/src
env: PYTHONUNBUFFERED=1
================================================================================
TinyDisasterVQA / Train TDM Student
================================================================================
Run dir:              /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10/S2_tdm_m_ce_20260610_090412
Device:               cuda
Student variant:      tdm_m
Mode:                 ce
Count cap:            5
Num classes:          14
Question templates:   31
AMP:                  True
Image size:           224
Batch size:           64
Eval batch:           64
Epochs:               50
LR:                   0.0003
Weight decay:         0.0001
Patience:             8
Min delta:            0.001
KD alpha:             0.0
KD temp:              0.0

Model summary
================================================================================
Class:             TDMMVQA
Total params:      46,542
Trainable params:  46,542
FP32 param size:   0.18 MB
Int8 param size:   45.5 KB
Student variant:   tdm_m
Image block type:  dsconv
Image channels:    (16, 32, 64, 96, 128)
Image feature dim: 128
Template encoder:  one_hot + Linear
Template input dim:31
Template emb dim:  24
Fusion hidden dim: 128
Fusion layers:     1
Num classes:       14
Head type:         single edge_global


================================================================================
Epoch 1/50
================================================================================
Epoch 001 | step 0001/0093 | loss=2.7052 | ce=2.7052 | kd=0.0000 | acc=0.0156 | binary=0.000 | condition=0.000 | count=0.100 | density=0.000 | time=5.4s
Epoch 001 | step 0005/0093 | loss=2.6707 | ce=2.6707 | kd=0.0000 | acc=0.0094 | binary=0.000 | condition=0.000 | count=0.045 | density=0.000 | time=5.5s
Epoch 001 | step 0010/0093 | loss=2.6390 | ce=2.6390 | kd=0.0000 | acc=0.0453 | binary=0.004 | condition=0.061 | count=0.133 | density=0.000 | time=6.8s
Epoch 001 | step 0015/0093 | loss=2.6085 | ce=2.6085 | kd=0.0000 | acc=0.1000 | binary=0.031 | condition=0.267 | count=0.091 | density=0.000 | time=7.8s
Epoch 001 | step 0020/0093 | loss=2.5789 | ce=2.5789 | kd=0.0000 | acc=0.1328 | binary=0.050 | condition=0.389 | count=0.065 | density=0.000 | time=9.0s
Epoch 001 | step 0025/0093 | loss=2.5434 | ce=2.5434 | kd=0.0000 | acc=0.1631 | binary=0.062 | condition=0.480 | count=0.053 | density=0.000 | time=10.1s
Epoch 001 | step 0030/0093 | loss=2.5100 | ce=2.5100 | kd=0.0000 | acc=0.1755 | binary=0.072 | condition=0.525 | count=0.045 | density=0.000 | time=10.9s
Epoch 001 | step 0035/0093 | loss=2.4780 | ce=2.4780 | kd=0.0000 | acc=0.1893 | binary=0.078 | condition=0.571 | count=0.040 | density=0.000 | time=11.5s
Epoch 001 | step 0040/0093 | loss=2.4525 | ce=2.4525 | kd=0.0000 | acc=0.1984 | binary=0.086 | condition=0.598 | count=0.035 | density=0.000 | time=12.3s
Epoch 001 | step 0045/0093 | loss=2.4266 | ce=2.4266 | kd=0.0000 | acc=0.2028 | binary=0.093 | condition=0.609 | count=0.031 | density=0.000 | time=13.1s
Epoch 001 | step 0050/0093 | loss=2.4027 | ce=2.4027 | kd=0.0000 | acc=0.2094 | binary=0.103 | condition=0.620 | count=0.028 | density=0.000 | time=13.7s
Epoch 001 | step 0055/0093 | loss=2.3766 | ce=2.3766 | kd=0.0000 | acc=0.2156 | binary=0.112 | condition=0.630 | count=0.025 | density=0.000 | time=14.5s
Epoch 001 | step 0060/0093 | loss=2.3506 | ce=2.3506 | kd=0.0000 | acc=0.2227 | binary=0.123 | condition=0.635 | count=0.023 | density=0.000 | time=15.1s
Epoch 001 | step 0065/0093 | loss=2.3347 | ce=2.3347 | kd=0.0000 | acc=0.2274 | binary=0.136 | condition=0.639 | count=0.022 | density=0.000 | time=15.8s
Epoch 001 | step 0070/0093 | loss=2.3245 | ce=2.3245 | kd=0.0000 | acc=0.2306 | binary=0.151 | condition=0.631 | count=0.020 | density=0.000 | time=16.5s
Epoch 001 | step 0075/0093 | loss=2.3127 | ce=2.3127 | kd=0.0000 | acc=0.2373 | binary=0.180 | condition=0.611 | count=0.018 | density=0.000 | time=17.1s
Epoch 001 | step 0080/0093 | loss=2.2970 | ce=2.2970 | kd=0.0000 | acc=0.2389 | binary=0.199 | condition=0.583 | count=0.017 | density=0.000 | time=17.8s
Epoch 001 | step 0085/0093 | loss=2.2851 | ce=2.2851 | kd=0.0000 | acc=0.2443 | binary=0.224 | condition=0.565 | count=0.016 | density=0.000 | time=18.6s
Epoch 001 | step 0090/0093 | loss=2.2675 | ce=2.2675 | kd=0.0000 | acc=0.2488 | binary=0.244 | condition=0.545 | count=0.015 | density=0.000 | time=19.3s
Epoch 001 | step 0093/0093 | loss=2.2610 | ce=2.2610 | kd=0.0000 | acc=0.2508 | binary=0.251 | condition=0.540 | count=0.015 | density=0.000 | time=24.3s

train overall: acc=0.2508 (1479/5898)
train macro acc: 0.0836
train count exact: acc=0.0150 (18/1204)
train count ±1: acc=0.0158 (19/1204)
train by edge head:
  binary       acc=0.2513 (662/2634)
  condition    acc=0.5399 (799/1480)
  count        acc=0.0150 (18/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.2414 (140/580)
  Complex_Counting                         acc=0.0128 (8/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.4304 (587/1364)
  Risk_Assessment                          acc=0.3310 (192/580)
  Road_Condition_Recognition               acc=0.3409 (542/1590)
  Simple_Counting                          acc=0.0172 (10/580)

valid overall: acc=0.3466 (626/1806)
valid macro acc: 0.1054
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.5467 (445/814)
  condition    acc=0.4031 (181/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.4545 (80/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.5424 (224/413)
  Risk_Assessment                          acc=0.7784 (137/176)
  Road_Condition_Recognition               acc=0.3715 (185/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 1 done | train_acc=0.2508 | valid_acc=0.3466 | best_valid_acc=0.3466 at epoch 1 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 2/50
================================================================================
Epoch 002 | step 0001/0093 | loss=2.0721 | ce=2.0721 | kd=0.0000 | acc=0.2812 | binary=0.423 | condition=0.350 | count=0.000 | density=0.000 | time=0.4s
Epoch 002 | step 0005/0093 | loss=2.1056 | ce=2.1056 | kd=0.0000 | acc=0.3187 | binary=0.455 | condition=0.477 | count=0.000 | density=0.000 | time=0.9s
Epoch 002 | step 0010/0093 | loss=2.1251 | ce=2.1251 | kd=0.0000 | acc=0.3172 | binary=0.410 | condition=0.571 | count=0.000 | density=0.000 | time=1.5s
Epoch 002 | step 0015/0093 | loss=2.0566 | ce=2.0566 | kd=0.0000 | acc=0.3385 | binary=0.380 | condition=0.661 | count=0.000 | density=0.000 | time=2.2s
Epoch 002 | step 0020/0093 | loss=2.0612 | ce=2.0612 | kd=0.0000 | acc=0.3484 | binary=0.399 | condition=0.677 | count=0.000 | density=0.000 | time=3.0s
Epoch 002 | step 0025/0093 | loss=2.0658 | ce=2.0658 | kd=0.0000 | acc=0.3412 | binary=0.407 | condition=0.649 | count=0.000 | density=0.000 | time=3.6s
Epoch 002 | step 0030/0093 | loss=2.0563 | ce=2.0563 | kd=0.0000 | acc=0.3443 | binary=0.419 | condition=0.621 | count=0.000 | density=0.000 | time=4.3s
Epoch 002 | step 0035/0093 | loss=2.0604 | ce=2.0604 | kd=0.0000 | acc=0.3420 | binary=0.419 | condition=0.624 | count=0.000 | density=0.000 | time=5.0s
Epoch 002 | step 0040/0093 | loss=2.0516 | ce=2.0516 | kd=0.0000 | acc=0.3461 | binary=0.416 | condition=0.642 | count=0.000 | density=0.000 | time=5.8s
Epoch 002 | step 0045/0093 | loss=2.0505 | ce=2.0505 | kd=0.0000 | acc=0.3493 | binary=0.423 | condition=0.645 | count=0.000 | density=0.000 | time=6.4s
Epoch 002 | step 0050/0093 | loss=2.0451 | ce=2.0451 | kd=0.0000 | acc=0.3531 | binary=0.422 | condition=0.656 | count=0.000 | density=0.000 | time=7.6s
Epoch 002 | step 0055/0093 | loss=2.0455 | ce=2.0455 | kd=0.0000 | acc=0.3545 | binary=0.426 | condition=0.663 | count=0.000 | density=0.000 | time=8.6s
Epoch 002 | step 0060/0093 | loss=2.0341 | ce=2.0341 | kd=0.0000 | acc=0.3615 | binary=0.435 | condition=0.662 | count=0.000 | density=0.000 | time=9.8s
Epoch 002 | step 0065/0093 | loss=2.0349 | ce=2.0349 | kd=0.0000 | acc=0.3639 | binary=0.448 | condition=0.660 | count=0.000 | density=0.000 | time=10.8s
Epoch 002 | step 0070/0093 | loss=2.0270 | ce=2.0270 | kd=0.0000 | acc=0.3650 | binary=0.453 | condition=0.651 | count=0.000 | density=0.000 | time=11.6s
Epoch 002 | step 0075/0093 | loss=2.0210 | ce=2.0210 | kd=0.0000 | acc=0.3656 | binary=0.453 | condition=0.651 | count=0.000 | density=0.000 | time=12.4s
Epoch 002 | step 0080/0093 | loss=2.0159 | ce=2.0159 | kd=0.0000 | acc=0.3684 | binary=0.454 | condition=0.660 | count=0.000 | density=0.000 | time=13.0s
Epoch 002 | step 0085/0093 | loss=2.0102 | ce=2.0102 | kd=0.0000 | acc=0.3732 | binary=0.458 | condition=0.673 | count=0.000 | density=0.000 | time=13.9s
Epoch 002 | step 0090/0093 | loss=2.0058 | ce=2.0058 | kd=0.0000 | acc=0.3771 | binary=0.464 | condition=0.678 | count=0.000 | density=0.000 | time=14.5s
Epoch 002 | step 0093/0093 | loss=2.0005 | ce=2.0005 | kd=0.0000 | acc=0.3796 | binary=0.467 | condition=0.681 | count=0.000 | density=0.000 | time=14.7s

train overall: acc=0.3796 (2239/5898)
train macro acc: 0.1226
train count exact: acc=0.0000 (0/1204)
train count ±1: acc=0.0000 (0/1204)
train by edge head:
  binary       acc=0.4674 (1231/2634)
  condition    acc=0.6811 (1008/1480)
  count        acc=0.0000 (0/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.5052 (293/580)
  Complex_Counting                         acc=0.0000 (0/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.5872 (801/1364)
  Risk_Assessment                          acc=0.5845 (339/580)
  Road_Condition_Recognition               acc=0.5069 (806/1590)
  Simple_Counting                          acc=0.0000 (0/580)

valid overall: acc=0.4662 (842/1806)
valid macro acc: 0.1537
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.6057 (493/814)
  condition    acc=0.7773 (349/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.6818 (120/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.7337 (303/413)
  Risk_Assessment                          acc=0.5739 (101/176)
  Road_Condition_Recognition               acc=0.6386 (318/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 2 done | train_acc=0.3796 | valid_acc=0.4662 | best_valid_acc=0.4662 at epoch 2 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 3/50
================================================================================
Epoch 003 | step 0001/0093 | loss=2.0200 | ce=2.0200 | kd=0.0000 | acc=0.3594 | binary=0.381 | condition=0.652 | count=0.000 | density=0.000 | time=0.3s
Epoch 003 | step 0005/0093 | loss=1.9380 | ce=1.9380 | kd=0.0000 | acc=0.4281 | binary=0.569 | condition=0.716 | count=0.000 | density=0.000 | time=0.9s
Epoch 003 | step 0010/0093 | loss=1.8866 | ce=1.8866 | kd=0.0000 | acc=0.4359 | binary=0.571 | condition=0.707 | count=0.000 | density=0.000 | time=1.5s
Epoch 003 | step 0015/0093 | loss=1.8795 | ce=1.8795 | kd=0.0000 | acc=0.4490 | binary=0.601 | condition=0.726 | count=0.000 | density=0.000 | time=2.3s
Epoch 003 | step 0020/0093 | loss=1.8626 | ce=1.8626 | kd=0.0000 | acc=0.4484 | binary=0.601 | condition=0.720 | count=0.000 | density=0.000 | time=3.0s
Epoch 003 | step 0025/0093 | loss=1.8500 | ce=1.8500 | kd=0.0000 | acc=0.4562 | binary=0.605 | condition=0.742 | count=0.000 | density=0.000 | time=4.1s
Epoch 003 | step 0030/0093 | loss=1.8407 | ce=1.8407 | kd=0.0000 | acc=0.4641 | binary=0.608 | condition=0.768 | count=0.000 | density=0.000 | time=5.2s
Epoch 003 | step 0035/0093 | loss=1.8292 | ce=1.8292 | kd=0.0000 | acc=0.4652 | binary=0.604 | condition=0.773 | count=0.000 | density=0.000 | time=6.7s
Epoch 003 | step 0040/0093 | loss=1.8264 | ce=1.8264 | kd=0.0000 | acc=0.4652 | binary=0.607 | condition=0.782 | count=0.000 | density=0.000 | time=7.6s
Epoch 003 | step 0045/0093 | loss=1.8153 | ce=1.8153 | kd=0.0000 | acc=0.4740 | binary=0.618 | condition=0.791 | count=0.002 | density=0.000 | time=8.6s
Epoch 003 | step 0050/0093 | loss=1.8098 | ce=1.8098 | kd=0.0000 | acc=0.4763 | binary=0.625 | condition=0.789 | count=0.003 | density=0.000 | time=9.3s
Epoch 003 | step 0055/0093 | loss=1.8091 | ce=1.8091 | kd=0.0000 | acc=0.4793 | binary=0.633 | condition=0.790 | count=0.008 | density=0.000 | time=10.0s
Epoch 003 | step 0060/0093 | loss=1.8039 | ce=1.8039 | kd=0.0000 | acc=0.4828 | binary=0.637 | condition=0.793 | count=0.015 | density=0.000 | time=10.7s
Epoch 003 | step 0065/0093 | loss=1.7884 | ce=1.7884 | kd=0.0000 | acc=0.4921 | binary=0.648 | condition=0.801 | count=0.019 | density=0.000 | time=11.5s
Epoch 003 | step 0070/0093 | loss=1.7693 | ce=1.7693 | kd=0.0000 | acc=0.5000 | binary=0.652 | condition=0.804 | count=0.031 | density=0.000 | time=12.1s
Epoch 003 | step 0075/0093 | loss=1.7632 | ce=1.7632 | kd=0.0000 | acc=0.5042 | binary=0.659 | condition=0.807 | count=0.039 | density=0.000 | time=12.9s
Epoch 003 | step 0080/0093 | loss=1.7530 | ce=1.7530 | kd=0.0000 | acc=0.5064 | binary=0.660 | condition=0.807 | count=0.038 | density=0.000 | time=13.4s
Epoch 003 | step 0085/0093 | loss=1.7465 | ce=1.7465 | kd=0.0000 | acc=0.5105 | binary=0.666 | condition=0.809 | count=0.046 | density=0.000 | time=14.3s
Epoch 003 | step 0090/0093 | loss=1.7413 | ce=1.7413 | kd=0.0000 | acc=0.5099 | binary=0.663 | condition=0.813 | count=0.048 | density=0.000 | time=14.9s
Epoch 003 | step 0093/0093 | loss=1.7374 | ce=1.7374 | kd=0.0000 | acc=0.5112 | binary=0.664 | condition=0.814 | count=0.051 | density=0.000 | time=15.1s

train overall: acc=0.5112 (3015/5898)
train macro acc: 0.1758
train count exact: acc=0.0507 (61/1204)
train count ±1: acc=0.0507 (61/1204)
train by edge head:
  binary       acc=0.6640 (1749/2634)
  condition    acc=0.8142 (1205/1480)
  count        acc=0.0507 (61/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.7000 (406/580)
  Complex_Counting                         acc=0.0401 (25/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.7353 (1003/1364)
  Risk_Assessment                          acc=0.7534 (437/580)
  Road_Condition_Recognition               acc=0.6969 (1108/1590)
  Simple_Counting                          acc=0.0621 (36/580)

valid overall: acc=0.5509 (995/1806)
valid macro acc: 0.2141
valid count exact: acc=0.1798 (66/367)
valid count ±1: acc=0.1798 (66/367)
valid by edge head:
  binary       acc=0.6683 (544/814)
  condition    acc=0.8575 (385/449)
  count        acc=0.1798 (66/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.6307 (111/176)
  Complex_Counting                         acc=0.1675 (32/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.7458 (308/413)
  Risk_Assessment                          acc=0.8580 (151/176)
  Road_Condition_Recognition               acc=0.7209 (359/498)
  Simple_Counting                          acc=0.1932 (34/176)

Epoch 3 done | train_acc=0.5112 | valid_acc=0.5509 | best_valid_acc=0.5509 at epoch 3 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 4/50
================================================================================
Epoch 004 | step 0001/0093 | loss=1.2824 | ce=1.2824 | kd=0.0000 | acc=0.6875 | binary=0.750 | condition=1.000 | count=0.250 | density=0.000 | time=0.6s
Epoch 004 | step 0005/0093 | loss=1.5079 | ce=1.5079 | kd=0.0000 | acc=0.5344 | binary=0.594 | condition=0.948 | count=0.107 | density=0.000 | time=1.6s
Epoch 004 | step 0010/0093 | loss=1.4988 | ce=1.4988 | kd=0.0000 | acc=0.5625 | binary=0.637 | condition=0.932 | count=0.088 | density=0.000 | time=2.6s
Epoch 004 | step 0015/0093 | loss=1.5395 | ce=1.5395 | kd=0.0000 | acc=0.5500 | binary=0.669 | condition=0.903 | count=0.066 | density=0.000 | time=3.8s
Epoch 004 | step 0020/0093 | loss=1.5110 | ce=1.5110 | kd=0.0000 | acc=0.5734 | binary=0.702 | condition=0.913 | count=0.089 | density=0.000 | time=4.5s
Epoch 004 | step 0025/0093 | loss=1.4995 | ce=1.4995 | kd=0.0000 | acc=0.5825 | binary=0.722 | condition=0.921 | count=0.087 | density=0.006 | time=5.3s
Epoch 004 | step 0030/0093 | loss=1.4939 | ce=1.4939 | kd=0.0000 | acc=0.5849 | binary=0.732 | condition=0.909 | count=0.087 | density=0.011 | time=5.9s
Epoch 004 | step 0035/0093 | loss=1.4822 | ce=1.4822 | kd=0.0000 | acc=0.5835 | binary=0.732 | condition=0.905 | count=0.094 | density=0.009 | time=6.7s
Epoch 004 | step 0040/0093 | loss=1.4639 | ce=1.4639 | kd=0.0000 | acc=0.5910 | binary=0.738 | condition=0.911 | count=0.117 | density=0.008 | time=7.3s
Epoch 004 | step 0045/0093 | loss=1.4562 | ce=1.4562 | kd=0.0000 | acc=0.5965 | binary=0.744 | condition=0.918 | count=0.129 | density=0.007 | time=8.1s
Epoch 004 | step 0050/0093 | loss=1.4382 | ce=1.4382 | kd=0.0000 | acc=0.6047 | binary=0.753 | condition=0.923 | count=0.141 | density=0.006 | time=8.8s
Epoch 004 | step 0055/0093 | loss=1.4353 | ce=1.4353 | kd=0.0000 | acc=0.6062 | binary=0.760 | condition=0.918 | count=0.151 | density=0.006 | time=9.5s
Epoch 004 | step 0060/0093 | loss=1.4237 | ce=1.4237 | kd=0.0000 | acc=0.6112 | binary=0.767 | condition=0.916 | count=0.155 | density=0.005 | time=10.2s
Epoch 004 | step 0065/0093 | loss=1.4201 | ce=1.4201 | kd=0.0000 | acc=0.6101 | binary=0.768 | condition=0.912 | count=0.162 | density=0.005 | time=10.9s
Epoch 004 | step 0070/0093 | loss=1.4134 | ce=1.4134 | kd=0.0000 | acc=0.6085 | binary=0.767 | condition=0.913 | count=0.162 | density=0.005 | time=11.6s
Epoch 004 | step 0075/0093 | loss=1.4018 | ce=1.4018 | kd=0.0000 | acc=0.6092 | binary=0.765 | condition=0.915 | count=0.167 | density=0.004 | time=12.3s
Epoch 004 | step 0080/0093 | loss=1.3974 | ce=1.3974 | kd=0.0000 | acc=0.6072 | binary=0.762 | condition=0.917 | count=0.170 | density=0.004 | time=13.1s
Epoch 004 | step 0085/0093 | loss=1.3935 | ce=1.3935 | kd=0.0000 | acc=0.6094 | binary=0.768 | condition=0.917 | count=0.175 | density=0.007 | time=13.9s
Epoch 004 | step 0090/0093 | loss=1.3853 | ce=1.3853 | kd=0.0000 | acc=0.6134 | binary=0.773 | condition=0.919 | count=0.177 | density=0.011 | time=14.8s
Epoch 004 | step 0093/0093 | loss=1.3841 | ce=1.3841 | kd=0.0000 | acc=0.6138 | binary=0.775 | condition=0.918 | count=0.177 | density=0.010 | time=15.1s

train overall: acc=0.6138 (3620/5898)
train macro acc: 0.2576
train count exact: acc=0.1769 (213/1204)
train count ±1: acc=0.1769 (213/1204)
train by edge head:
  binary       acc=0.7752 (2042/2634)
  condition    acc=0.9182 (1359/1480)
  count        acc=0.1769 (213/1204)
  density      acc=0.0103 (6/580)
train by question type:
  Building_Condition_Recognition           acc=0.7724 (448/580)
  Complex_Counting                         acc=0.1667 (104/624)
  Density_Estimation                       acc=0.0103 (6/580)
  Entire_Image_Condition_Recognition       acc=0.8490 (1158/1364)
  Risk_Assessment                          acc=0.8466 (491/580)

## S3: TDM-L + CE

In [ ]:
%cd /content/TinyDisasterVQA
%env PYTHONPATH=/content/TinyDisasterVQA/src
%env PYTHONUNBUFFERED=1

!mkdir -p /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10

!python -u scripts/06_train_student.py \
  --dataset-root dataset \
  --runs-dir /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10 \
  --train-csv outputs/training_data_cap5/train.csv \
  --valid-csv outputs/training_data_cap5/valid.csv \
  --test-csv outputs/training_data_cap5/test.csv \
  --metadata outputs/training_data_cap5/metadata.json \
  --class-weights outputs/answer_space_cap5/class_weights_edge_global_by_label.json \
  --image-size 224 \
  --epochs 50 \
  --batch-size 64 \
  --eval-batch-size 64 \
  --num-workers 2 \
  --device auto \
  --patience 8 \
  --min-delta 0.001 \
  --log-interval 5 \
  --student-variant tdm_l \
  --mode ce \
  --run-name S3_tdm_l_ce_$(date +%Y%m%d_%H%M%S)

/content/TinyDisasterVQA
env: PYTHONPATH=/content/TinyDisasterVQA/src
env: PYTHONUNBUFFERED=1
================================================================================
TinyDisasterVQA / Train TDM Student
================================================================================
Run dir:              /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10/S3_tdm_l_ce_20260610_091325
Device:               cuda
Student variant:      tdm_l
Mode:                 ce
Count cap:            5
Num classes:          14
Question templates:   31
AMP:                  True
Image size:           224
Batch size:           64
Eval batch:           64
Epochs:               50
LR:                   0.0003
Weight decay:         0.0001
Patience:             8
Min delta:            0.001
KD alpha:             0.0
KD temp:              0.0

Model summary
================================================================================
Class:             TDMLVQA
Total params:      101,310
Trainable params:  101,310
FP32 param size:   0.39 MB
Int8 param size:   98.9 KB
Student variant:   tdm_l
Image block type:  dsconv
Image channels:    (24, 48, 96, 128, 160)
Image feature dim: 160
Template encoder:  one_hot + Linear
Template input dim:31
Template emb dim:  32
Fusion hidden dim: 192
Fusion layers:     2
Num classes:       14
Head type:         single edge_global


================================================================================
Epoch 1/50
================================================================================
Epoch 001 | step 0001/0093 | loss=2.6852 | ce=2.6852 | kd=0.0000 | acc=0.0312 | binary=0.000 | condition=0.000 | count=0.000 | density=0.250 | time=2.5s
Epoch 001 | step 0005/0093 | loss=2.6560 | ce=2.6560 | kd=0.0000 | acc=0.0437 | binary=0.007 | condition=0.000 | count=0.015 | density=0.267 | time=2.6s
Epoch 001 | step 0010/0093 | loss=2.6303 | ce=2.6303 | kd=0.0000 | acc=0.1062 | binary=0.190 | condition=0.000 | count=0.008 | density=0.181 | time=3.5s
Epoch 001 | step 0015/0093 | loss=2.6039 | ce=2.6039 | kd=0.0000 | acc=0.1437 | binary=0.294 | condition=0.000 | count=0.005 | density=0.123 | time=4.9s
Epoch 001 | step 0020/0093 | loss=2.5786 | ce=2.5786 | kd=0.0000 | acc=0.1586 | binary=0.335 | condition=0.003 | count=0.004 | density=0.096 | time=5.8s
Epoch 001 | step 0025/0093 | loss=2.5473 | ce=2.5473 | kd=0.0000 | acc=0.1700 | binary=0.361 | condition=0.005 | count=0.003 | density=0.075 | time=7.2s
Epoch 001 | step 0030/0093 | loss=2.5122 | ce=2.5122 | kd=0.0000 | acc=0.1755 | binary=0.375 | condition=0.004 | count=0.003 | density=0.067 | time=8.2s
Epoch 001 | step 0035/0093 | loss=2.4834 | ce=2.4834 | kd=0.0000 | acc=0.1772 | binary=0.384 | condition=0.004 | count=0.002 | density=0.057 | time=8.9s
Epoch 001 | step 0040/0093 | loss=2.4474 | ce=2.4474 | kd=0.0000 | acc=0.1824 | binary=0.394 | condition=0.011 | count=0.002 | density=0.050 | time=9.6s
Epoch 001 | step 0045/0093 | loss=2.4204 | ce=2.4204 | kd=0.0000 | acc=0.1878 | binary=0.404 | condition=0.022 | count=0.002 | density=0.045 | time=10.3s
Epoch 001 | step 0050/0093 | loss=2.3909 | ce=2.3909 | kd=0.0000 | acc=0.1941 | binary=0.403 | condition=0.049 | count=0.002 | density=0.040 | time=11.0s
Epoch 001 | step 0055/0093 | loss=2.3700 | ce=2.3700 | kd=0.0000 | acc=0.1969 | binary=0.393 | condition=0.073 | count=0.001 | density=0.037 | time=11.8s
Epoch 001 | step 0060/0093 | loss=2.3476 | ce=2.3476 | kd=0.0000 | acc=0.1995 | binary=0.392 | condition=0.082 | count=0.001 | density=0.034 | time=12.5s
Epoch 001 | step 0065/0093 | loss=2.3381 | ce=2.3381 | kd=0.0000 | acc=0.2031 | binary=0.396 | condition=0.095 | count=0.001 | density=0.031 | time=13.3s
Epoch 001 | step 0070/0093 | loss=2.3251 | ce=2.3251 | kd=0.0000 | acc=0.2060 | binary=0.399 | condition=0.105 | count=0.001 | density=0.029 | time=14.0s
Epoch 001 | step 0075/0093 | loss=2.3117 | ce=2.3117 | kd=0.0000 | acc=0.2106 | binary=0.394 | condition=0.132 | count=0.001 | density=0.027 | time=14.8s
Epoch 001 | step 0080/0093 | loss=2.3000 | ce=2.3000 | kd=0.0000 | acc=0.2146 | binary=0.394 | condition=0.147 | count=0.001 | density=0.026 | time=15.5s
Epoch 001 | step 0085/0093 | loss=2.2895 | ce=2.2895 | kd=0.0000 | acc=0.2199 | binary=0.397 | condition=0.163 | count=0.001 | density=0.024 | time=16.3s
Epoch 001 | step 0090/0093 | loss=2.2781 | ce=2.2781 | kd=0.0000 | acc=0.2227 | binary=0.400 | condition=0.168 | count=0.001 | density=0.023 | time=16.9s
Epoch 001 | step 0093/0093 | loss=2.2698 | ce=2.2698 | kd=0.0000 | acc=0.2247 | binary=0.404 | condition=0.167 | count=0.001 | density=0.022 | time=21.8s

train overall: acc=0.2247 (1325/5898)
train macro acc: 0.0771
train count exact: acc=0.0008 (1/1204)
train count ±1: acc=0.0066 (8/1204)
train by edge head:
  binary       acc=0.4039 (1064/2634)
  condition    acc=0.1669 (247/1480)
  count        acc=0.0008 (1/1204)
  density      acc=0.0224 (13/580)
train by question type:
  Building_Condition_Recognition           acc=0.4638 (269/580)
  Complex_Counting                         acc=0.0000 (0/624)
  Density_Estimation                       acc=0.0224 (13/580)
  Entire_Image_Condition_Recognition       acc=0.2896 (395/1364)
  Risk_Assessment                          acc=0.3500 (203/580)
  Road_Condition_Recognition               acc=0.2792 (444/1590)
  Simple_Counting                          acc=0.0017 (1/580)

valid overall: acc=0.2984 (539/1806)
valid macro acc: 0.0907
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.6057 (493/814)
  condition    acc=0.1024 (46/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.5057 (89/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.3680 (152/413)
  Risk_Assessment                          acc=0.6875 (121/176)
  Road_Condition_Recognition               acc=0.3554 (177/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 1 done | train_acc=0.2247 | valid_acc=0.2984 | best_valid_acc=0.2984 at epoch 1 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 2/50
================================================================================
Epoch 002 | step 0001/0093 | loss=2.1200 | ce=2.1200 | kd=0.0000 | acc=0.3125 | binary=0.571 | condition=0.286 | count=0.000 | density=0.000 | time=0.4s
Epoch 002 | step 0005/0093 | loss=2.1502 | ce=2.1502 | kd=0.0000 | acc=0.2750 | binary=0.493 | condition=0.269 | count=0.000 | density=0.000 | time=0.9s
Epoch 002 | step 0010/0093 | loss=2.1244 | ce=2.1244 | kd=0.0000 | acc=0.2906 | binary=0.489 | condition=0.314 | count=0.000 | density=0.000 | time=1.6s
Epoch 002 | step 0015/0093 | loss=2.1033 | ce=2.1033 | kd=0.0000 | acc=0.2958 | binary=0.448 | condition=0.398 | count=0.000 | density=0.000 | time=2.4s
Epoch 002 | step 0020/0093 | loss=2.0956 | ce=2.0956 | kd=0.0000 | acc=0.2961 | binary=0.401 | condition=0.471 | count=0.000 | density=0.000 | time=3.1s
Epoch 002 | step 0025/0093 | loss=2.0912 | ce=2.0912 | kd=0.0000 | acc=0.2969 | binary=0.392 | condition=0.489 | count=0.000 | density=0.000 | time=4.0s
Epoch 002 | step 0030/0093 | loss=2.0867 | ce=2.0867 | kd=0.0000 | acc=0.3042 | binary=0.403 | condition=0.497 | count=0.000 | density=0.000 | time=4.6s
Epoch 002 | step 0035/0093 | loss=2.0944 | ce=2.0944 | kd=0.0000 | acc=0.2996 | binary=0.411 | condition=0.475 | count=0.000 | density=0.000 | time=5.4s
Epoch 002 | step 0040/0093 | loss=2.0895 | ce=2.0895 | kd=0.0000 | acc=0.2977 | binary=0.423 | condition=0.441 | count=0.000 | density=0.000 | time=6.0s
Epoch 002 | step 0045/0093 | loss=2.0845 | ce=2.0845 | kd=0.0000 | acc=0.3024 | binary=0.428 | condition=0.450 | count=0.000 | density=0.000 | time=6.8s
Epoch 002 | step 0050/0093 | loss=2.0711 | ce=2.0711 | kd=0.0000 | acc=0.3125 | binary=0.433 | condition=0.476 | count=0.000 | density=0.000 | time=7.9s
Epoch 002 | step 0055/0093 | loss=2.0698 | ce=2.0698 | kd=0.0000 | acc=0.3134 | binary=0.428 | condition=0.490 | count=0.000 | density=0.000 | time=9.2s
Epoch 002 | step 0060/0093 | loss=2.0579 | ce=2.0579 | kd=0.0000 | acc=0.3214 | binary=0.430 | condition=0.511 | count=0.000 | density=0.000 | time=10.3s
Epoch 002 | step 0065/0093 | loss=2.0519 | ce=2.0519 | kd=0.0000 | acc=0.3257 | binary=0.435 | condition=0.519 | count=0.000 | density=0.000 | time=11.5s
Epoch 002 | step 0070/0093 | loss=2.0461 | ce=2.0461 | kd=0.0000 | acc=0.3326 | binary=0.449 | condition=0.522 | count=0.000 | density=0.000 | time=12.2s
Epoch 002 | step 0075/0093 | loss=2.0393 | ce=2.0393 | kd=0.0000 | acc=0.3381 | binary=0.459 | condition=0.526 | count=0.000 | density=0.000 | time=12.8s
Epoch 002 | step 0080/0093 | loss=2.0309 | ce=2.0309 | kd=0.0000 | acc=0.3451 | binary=0.468 | condition=0.537 | count=0.000 | density=0.000 | time=13.7s
Epoch 002 | step 0085/0093 | loss=2.0250 | ce=2.0250 | kd=0.0000 | acc=0.3509 | binary=0.475 | condition=0.550 | count=0.000 | density=0.000 | time=14.3s
Epoch 002 | step 0090/0093 | loss=2.0144 | ce=2.0144 | kd=0.0000 | acc=0.3566 | binary=0.475 | condition=0.571 | count=0.000 | density=0.000 | time=15.1s
Epoch 002 | step 0093/0093 | loss=2.0140 | ce=2.0140 | kd=0.0000 | acc=0.3569 | binary=0.474 | condition=0.579 | count=0.000 | density=0.000 | time=15.3s

train overall: acc=0.3569 (2105/5898)
train macro acc: 0.1149
train count exact: acc=0.0000 (0/1204)
train count ±1: acc=0.0000 (0/1204)
train by edge head:
  binary       acc=0.4738 (1248/2634)
  condition    acc=0.5791 (857/1480)
  count        acc=0.0000 (0/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.4966 (288/580)
  Complex_Counting                         acc=0.0000 (0/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.5455 (744/1364)
  Risk_Assessment                          acc=0.4759 (276/580)
  Road_Condition_Recognition               acc=0.5013 (797/1590)
  Simple_Counting                          acc=0.0000 (0/580)

valid overall: acc=0.4707 (850/1806)
valid macro acc: 0.1482
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.5786 (471/814)
  condition    acc=0.8441 (379/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.4830 (85/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.7458 (308/413)
  Risk_Assessment                          acc=0.7102 (125/176)
  Road_Condition_Recognition               acc=0.6667 (332/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 2 done | train_acc=0.3569 | valid_acc=0.4707 | best_valid_acc=0.4707 at epoch 2 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 3/50
================================================================================
Epoch 003 | step 0001/0093 | loss=1.7688 | ce=1.7688 | kd=0.0000 | acc=0.5625 | binary=0.708 | condition=0.864 | count=0.000 | density=0.000 | time=0.3s
Epoch 003 | step 0005/0093 | loss=1.7339 | ce=1.7339 | kd=0.0000 | acc=0.4875 | binary=0.551 | condition=0.900 | count=0.000 | density=0.000 | time=0.9s
Epoch 003 | step 0010/0093 | loss=1.7937 | ce=1.7937 | kd=0.0000 | acc=0.4672 | binary=0.559 | condition=0.865 | count=0.000 | density=0.000 | time=1.5s
Epoch 003 | step 0015/0093 | loss=1.7719 | ce=1.7719 | kd=0.0000 | acc=0.4708 | binary=0.560 | condition=0.864 | count=0.000 | density=0.000 | time=2.2s
Epoch 003 | step 0020/0093 | loss=1.7617 | ce=1.7617 | kd=0.0000 | acc=0.4680 | binary=0.554 | condition=0.858 | count=0.000 | density=0.000 | time=3.3s
Epoch 003 | step 0025/0093 | loss=1.7241 | ce=1.7241 | kd=0.0000 | acc=0.4806 | binary=0.578 | condition=0.860 | count=0.000 | density=0.000 | time=4.5s
Epoch 003 | step 0030/0093 | loss=1.7140 | ce=1.7140 | kd=0.0000 | acc=0.4755 | binary=0.574 | condition=0.857 | count=0.000 | density=0.000 | time=5.7s
Epoch 003 | step 0035/0093 | loss=1.7037 | ce=1.7037 | kd=0.0000 | acc=0.4728 | binary=0.578 | condition=0.853 | count=0.000 | density=0.000 | time=6.7s
Epoch 003 | step 0040/0093 | loss=1.6851 | ce=1.6851 | kd=0.0000 | acc=0.4785 | binary=0.590 | condition=0.852 | count=0.002 | density=0.000 | time=7.7s
Epoch 003 | step 0045/0093 | loss=1.6616 | ce=1.6616 | kd=0.0000 | acc=0.4792 | binary=0.586 | condition=0.860 | count=0.002 | density=0.000 | time=8.5s
Epoch 003 | step 0050/0093 | loss=1.6449 | ce=1.6449 | kd=0.0000 | acc=0.4788 | binary=0.581 | condition=0.863 | count=0.005 | density=0.000 | time=9.2s
Epoch 003 | step 0055/0093 | loss=1.6182 | ce=1.6182 | kd=0.0000 | acc=0.4835 | binary=0.583 | condition=0.866 | count=0.010 | density=0.000 | time=9.9s
Epoch 003 | step 0060/0093 | loss=1.5982 | ce=1.5982 | kd=0.0000 | acc=0.4844 | binary=0.585 | condition=0.872 | count=0.010 | density=0.000 | time=10.7s
Epoch 003 | step 0065/0093 | loss=1.5835 | ce=1.5835 | kd=0.0000 | acc=0.4880 | binary=0.591 | condition=0.868 | count=0.019 | density=0.000 | time=11.4s
Epoch 003 | step 0070/0093 | loss=1.5674 | ce=1.5674 | kd=0.0000 | acc=0.4897 | binary=0.593 | condition=0.865 | count=0.031 | density=0.000 | time=12.2s
Epoch 003 | step 0075/0093 | loss=1.5508 | ce=1.5508 | kd=0.0000 | acc=0.4921 | binary=0.594 | condition=0.862 | count=0.043 | density=0.000 | time=12.9s
Epoch 003 | step 0080/0093 | loss=1.5338 | ce=1.5338 | kd=0.0000 | acc=0.4949 | binary=0.596 | condition=0.861 | count=0.055 | density=0.000 | time=13.7s
Epoch 003 | step 0085/0093 | loss=1.5175 | ce=1.5175 | kd=0.0000 | acc=0.4978 | binary=0.598 | condition=0.860 | count=0.067 | density=0.000 | time=14.4s
Epoch 003 | step 0090/0093 | loss=1.5064 | ce=1.5064 | kd=0.0000 | acc=0.4983 | binary=0.599 | condition=0.858 | count=0.071 | density=0.002 | time=15.1s
Epoch 003 | step 0093/0093 | loss=1.5026 | ce=1.5026 | kd=0.0000 | acc=0.4976 | binary=0.598 | condition=0.860 | count=0.072 | density=0.002 | time=15.4s

train overall: acc=0.4976 (2935/5898)
train macro acc: 0.1740
train count exact: acc=0.0723 (87/1204)
train count ±1: acc=0.0723 (87/1204)
train by edge head:
  binary       acc=0.5976 (1574/2634)
  condition    acc=0.8601 (1273/1480)
  count        acc=0.0723 (87/1204)
  density      acc=0.0017 (1/580)
train by question type:
  Building_Condition_Recognition           acc=0.5931 (344/580)
  Complex_Counting                         acc=0.0497 (31/624)
  Density_Estimation                       acc=0.0017 (1/580)
  Entire_Image_Condition_Recognition       acc=0.7661 (1045/1364)
  Risk_Assessment                          acc=0.5879 (341/580)
  Road_Condition_Recognition               acc=0.7025 (1117/1590)
  Simple_Counting                          acc=0.0966 (56/580)

valid overall: acc=0.6179 (1116/1806)
valid macro acc: 0.2403
valid count exact: acc=0.2262 (83/367)
valid count ±1: acc=0.2262 (83/367)
valid by edge head:
  binary       acc=0.8034 (654/814)
  condition    acc=0.8441 (379/449)
  count        acc=0.2262 (83/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.7955 (140/176)
  Complex_Counting                         acc=0.2094 (40/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.8814 (364/413)
  Risk_Assessment                          acc=0.7159 (126/176)
  Road_Condition_Recognition               acc=0.8092 (403/498)
  Simple_Counting                          acc=0.2443 (43/176)

Epoch 3 done | train_acc=0.4976 | valid_acc=0.6179 | best_valid_acc=0.6179 at epoch 3 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 4/50
================================================================================
Epoch 004 | step 0001/0093 | loss=1.2831 | ce=1.2831 | kd=0.0000 | acc=0.6094 | binary=0.840 | condition=0.938 | count=0.167 | density=0.000 | time=0.6s
Epoch 004 | step 0005/0093 | loss=1.2416 | ce=1.2416 | kd=0.0000 | acc=0.5281 | binary=0.633 | condition=0.890 | count=0.151 | density=0.000 | time=1.6s
Epoch 004 | step 0010/0093 | loss=1.2045 | ce=1.2045 | kd=0.0000 | acc=0.5437 | binary=0.643 | condition=0.853 | count=0.188 | density=0.000 | time=2.5s
Epoch 004 | step 0015/0093 | loss=1.1689 | ce=1.1689 | kd=0.0000 | acc=0.5500 | binary=0.639 | condition=0.847 | count=0.212 | density=0.023 | time=3.3s
Epoch 004 | step 0020/0093 | loss=1.1598 | ce=1.1598 | kd=0.0000 | acc=0.5484 | binary=0.621 | condition=0.858 | count=0.225 | density=0.026 | time=4.0s
Epoch 004 | step 0025/0093 | loss=1.1485 | ce=1.1485 | kd=0.0000 | acc=0.5475 | binary=0.607 | condition=0.875 | count=0.237 | density=0.019 | time=4.9s
Epoch 004 | step 0030/0093 | loss=1.1452 | ce=1.1452 | kd=0.0000 | acc=0.5536 | binary=0.619 | condition=0.882 | count=0.243 | density=0.021 | time=5.5s
Epoch 004 | step 0035/0093 | loss=1.1366 | ce=1.1366 | kd=0.0000 | acc=0.5603 | binary=0.627 | condition=0.887 | count=0.247 | density=0.028 | time=6.4s
Epoch 004 | step 0040/0093 | loss=1.1311 | ce=1.1311 | kd=0.0000 | acc=0.5652 | binary=0.632 | condition=0.890 | count=0.254 | density=0.037 | time=7.0s
Epoch 004 | step 0045/0093 | loss=1.1293 | ce=1.1293 | kd=0.0000 | acc=0.5656 | binary=0.637 | condition=0.898 | count=0.247 | density=0.047 | time=7.8s
Epoch 004 | step 0050/0093 | loss=1.1243 | ce=1.1243 | kd=0.0000 | acc=0.5703 | binary=0.641 | condition=0.900 | count=0.252 | density=0.065 | time=8.5s
Epoch 004 | step 0055/0093 | loss=1.1235 | ce=1.1235 | kd=0.0000 | acc=0.5744 | binary=0.647 | condition=0.900 | count=0.258 | density=0.072 | time=9.1s
Epoch 004 | step 0060/0093 | loss=1.1177 | ce=1.1177 | kd=0.0000 | acc=0.5758 | binary=0.647 | condition=0.901 | count=0.265 | density=0.078 | time=9.8s
Epoch 004 | step 0065/0093 | loss=1.1063 | ce=1.1063 | kd=0.0000 | acc=0.5827 | binary=0.656 | condition=0.907 | count=0.270 | density=0.086 | time=10.6s
Epoch 004 | step 0070/0093 | loss=1.0981 | ce=1.0981 | kd=0.0000 | acc=0.5877 | binary=0.664 | condition=0.907 | count=0.271 | density=0.085 | time=11.3s
Epoch 004 | step 0075/0093 | loss=1.0910 | ce=1.0910 | kd=0.0000 | acc=0.5906 | binary=0.669 | condition=0.910 | count=0.275 | density=0.084 | time=12.1s
Epoch 004 | step 0080/0093 | loss=1.0857 | ce=1.0857 | kd=0.0000 | acc=0.5957 | binary=0.676 | condition=0.913 | count=0.280 | density=0.096 | time=12.8s
Epoch 004 | step 0085/0093 | loss=1.0783 | ce=1.0783 | kd=0.0000 | acc=0.6007 | binary=0.685 | condition=0.915 | count=0.275 | density=0.104 | time=14.1s
Epoch 004 | step 0090/0093 | loss=1.0672 | ce=1.0672 | kd=0.0000 | acc=0.6054 | binary=0.690 | condition=0.919 | count=0.275 | density=0.112 | time=15.1s
Epoch 004 | step 0093/0093 | loss=1.0610 | ce=1.0610 | kd=0.0000 | acc=0.6092 | binary=0.694 | condition=0.920 | count=0.278 | density=0.121 | time=15.4s

train overall: acc=0.6092 (3593/5898)
train macro acc: 0.3009
train count exact: acc=0.2782 (335/1204)
train count ±1: acc=0.3206 (386/1204)
train by edge head:
  binary       acc=0.6936 (1827/2634)
  condition    acc=0.9196 (1361/1480)
  count        acc=0.2782 (335/1204)
  density      acc=0.1207 (70/580)
train by question type:
  Building_Condition_Recognition           acc=0.6776 (393/580)
  Complex_Counting                         acc=0.2644 (165/624)
  Density_Estimation                       acc=0.1207 (70/580)
  Entire_Image_Condition_Recognition       acc=0.8504 (1160/1364)
  Risk_Assessment                          acc=0.6552 (380/580)

## S4: TDM-Fast + CE

In [ ]:
%cd /content/TinyDisasterVQA
%env PYTHONPATH=/content/TinyDisasterVQA/src
%env PYTHONUNBUFFERED=1

!mkdir -p /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10

!python -u scripts/06_train_student.py \
  --dataset-root dataset \
  --runs-dir /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10 \
  --train-csv outputs/training_data_cap5/train.csv \
  --valid-csv outputs/training_data_cap5/valid.csv \
  --test-csv outputs/training_data_cap5/test.csv \
  --metadata outputs/training_data_cap5/metadata.json \
  --class-weights outputs/answer_space_cap5/class_weights_edge_global_by_label.json \
  --image-size 224 \
  --epochs 50 \
  --batch-size 64 \
  --eval-batch-size 64 \
  --num-workers 2 \
  --device auto \
  --patience 8 \
  --min-delta 0.001 \
  --log-interval 5 \
  --student-variant tdm_fast \
  --mode ce \
  --run-name S4_tdm_fast_ce_$(date +%Y%m%d_%H%M%S)

/content/TinyDisasterVQA
env: PYTHONPATH=/content/TinyDisasterVQA/src
env: PYTHONUNBUFFERED=1
================================================================================
TinyDisasterVQA / Train TDM Student
================================================================================
Run dir:              /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10/S4_tdm_fast_ce_20260610_092129
Device:               cuda
Student variant:      tdm_fast
Mode:                 ce
Count cap:            5
Num classes:          14
Question templates:   31
AMP:                  True
Image size:           224
Batch size:           64
Eval batch:           64
Epochs:               50
LR:                   0.0003
Weight decay:         0.0001
Patience:             8
Min delta:            0.001
KD alpha:             0.0
KD temp:              0.0

Model summary
================================================================================
Class:             TDMFastVQA
Total params:      91,902
Trainable params:  91,902
FP32 param size:   0.35 MB
Int8 param size:   89.7 KB
Student variant:   tdm_fast
Image block type:  conv
Image channels:    (16, 32, 64, 96)
Image feature dim: 96
Template encoder:  one_hot + Linear
Template input dim:31
Template emb dim:  16
Fusion hidden dim: 96
Fusion layers:     1
Num classes:       14
Head type:         single edge_global


================================================================================
Epoch 1/50
================================================================================
Epoch 001 | step 0001/0093 | loss=2.6924 | ce=2.6924 | kd=0.0000 | acc=0.0625 | binary=0.000 | condition=0.000 | count=0.308 | density=0.000 | time=3.0s
Epoch 001 | step 0005/0093 | loss=2.6426 | ce=2.6426 | kd=0.0000 | acc=0.0969 | binary=0.015 | condition=0.253 | count=0.117 | density=0.000 | time=3.2s
Epoch 001 | step 0010/0093 | loss=2.6217 | ce=2.6217 | kd=0.0000 | acc=0.1453 | binary=0.082 | condition=0.377 | count=0.067 | density=0.000 | time=4.0s
Epoch 001 | step 0015/0093 | loss=2.5915 | ce=2.5915 | kd=0.0000 | acc=0.1885 | binary=0.140 | condition=0.467 | count=0.042 | density=0.000 | time=4.7s
Epoch 001 | step 0020/0093 | loss=2.5619 | ce=2.5619 | kd=0.0000 | acc=0.2195 | binary=0.172 | condition=0.523 | count=0.033 | density=0.000 | time=5.4s
Epoch 001 | step 0025/0093 | loss=2.5383 | ce=2.5383 | kd=0.0000 | acc=0.2281 | binary=0.173 | condition=0.554 | count=0.026 | density=0.000 | time=6.2s
Epoch 001 | step 0030/0093 | loss=2.5191 | ce=2.5191 | kd=0.0000 | acc=0.2328 | binary=0.182 | condition=0.573 | count=0.021 | density=0.000 | time=6.8s
Epoch 001 | step 0035/0093 | loss=2.4973 | ce=2.4973 | kd=0.0000 | acc=0.2362 | binary=0.180 | condition=0.596 | count=0.018 | density=0.000 | time=7.6s
Epoch 001 | step 0040/0093 | loss=2.4775 | ce=2.4775 | kd=0.0000 | acc=0.2367 | binary=0.177 | condition=0.615 | count=0.015 | density=0.000 | time=8.3s
Epoch 001 | step 0045/0093 | loss=2.4544 | ce=2.4544 | kd=0.0000 | acc=0.2392 | binary=0.179 | condition=0.624 | count=0.013 | density=0.000 | time=9.0s
Epoch 001 | step 0050/0093 | loss=2.4313 | ce=2.4313 | kd=0.0000 | acc=0.2412 | binary=0.175 | condition=0.633 | count=0.012 | density=0.000 | time=9.7s
Epoch 001 | step 0055/0093 | loss=2.4094 | ce=2.4094 | kd=0.0000 | acc=0.2437 | binary=0.172 | condition=0.647 | count=0.011 | density=0.000 | time=10.8s
Epoch 001 | step 0060/0093 | loss=2.3890 | ce=2.3890 | kd=0.0000 | acc=0.2453 | binary=0.171 | condition=0.659 | count=0.010 | density=0.000 | time=11.9s
Epoch 001 | step 0065/0093 | loss=2.3673 | ce=2.3673 | kd=0.0000 | acc=0.2498 | binary=0.172 | condition=0.668 | count=0.009 | density=0.000 | time=13.4s
Epoch 001 | step 0070/0093 | loss=2.3504 | ce=2.3504 | kd=0.0000 | acc=0.2496 | binary=0.169 | condition=0.677 | count=0.009 | density=0.000 | time=14.4s
Epoch 001 | step 0075/0093 | loss=2.3337 | ce=2.3337 | kd=0.0000 | acc=0.2502 | binary=0.168 | condition=0.681 | count=0.008 | density=0.000 | time=15.3s
Epoch 001 | step 0080/0093 | loss=2.3223 | ce=2.3223 | kd=0.0000 | acc=0.2490 | binary=0.170 | condition=0.680 | count=0.008 | density=0.000 | time=15.9s
Epoch 001 | step 0085/0093 | loss=2.3081 | ce=2.3081 | kd=0.0000 | acc=0.2487 | binary=0.176 | condition=0.670 | count=0.007 | density=0.000 | time=16.8s
Epoch 001 | step 0090/0093 | loss=2.2950 | ce=2.2950 | kd=0.0000 | acc=0.2488 | binary=0.183 | condition=0.661 | count=0.007 | density=0.000 | time=17.3s
Epoch 001 | step 0093/0093 | loss=2.2879 | ce=2.2879 | kd=0.0000 | acc=0.2504 | binary=0.189 | condition=0.657 | count=0.007 | density=0.000 | time=18.9s

train overall: acc=0.2504 (1477/5898)
train macro acc: 0.0852
train count exact: acc=0.0066 (8/1204)
train count ±1: acc=0.0141 (17/1204)
train by edge head:
  binary       acc=0.1887 (497/2634)
  condition    acc=0.6568 (972/1480)
  count        acc=0.0066 (8/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.2310 (134/580)
  Complex_Counting                         acc=0.0064 (4/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.4157 (567/1364)
  Risk_Assessment                          acc=0.2379 (138/580)
  Road_Condition_Recognition               acc=0.3962 (630/1590)
  Simple_Counting                          acc=0.0069 (4/580)

valid overall: acc=0.2857 (516/1806)
valid macro acc: 0.0937
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.3943 (321/814)
  condition    acc=0.4343 (195/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.4432 (78/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.4310 (178/413)
  Risk_Assessment                          acc=0.4659 (82/176)
  Road_Condition_Recognition               acc=0.3574 (178/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 1 done | train_acc=0.2504 | valid_acc=0.2857 | best_valid_acc=0.2857 at epoch 1 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 2/50
================================================================================
Epoch 002 | step 0001/0093 | loss=1.9523 | ce=1.9523 | kd=0.0000 | acc=0.2500 | binary=0.310 | condition=0.318 | count=0.000 | density=0.000 | time=0.3s
Epoch 002 | step 0005/0093 | loss=2.0035 | ce=2.0035 | kd=0.0000 | acc=0.2969 | binary=0.404 | condition=0.439 | count=0.000 | density=0.000 | time=0.9s
Epoch 002 | step 0010/0093 | loss=2.0129 | ce=2.0129 | kd=0.0000 | acc=0.2922 | binary=0.410 | condition=0.429 | count=0.000 | density=0.000 | time=1.5s
Epoch 002 | step 0015/0093 | loss=2.0059 | ce=2.0059 | kd=0.0000 | acc=0.3042 | binary=0.415 | condition=0.453 | count=0.000 | density=0.000 | time=2.6s
Epoch 002 | step 0020/0093 | loss=2.0139 | ce=2.0139 | kd=0.0000 | acc=0.3125 | binary=0.431 | condition=0.472 | count=0.000 | density=0.000 | time=3.7s
Epoch 002 | step 0025/0093 | loss=2.0136 | ce=2.0136 | kd=0.0000 | acc=0.3075 | binary=0.423 | condition=0.478 | count=0.000 | density=0.000 | time=4.9s
Epoch 002 | step 0030/0093 | loss=2.0135 | ce=2.0135 | kd=0.0000 | acc=0.3052 | binary=0.424 | condition=0.466 | count=0.000 | density=0.000 | time=6.0s
Epoch 002 | step 0035/0093 | loss=2.0262 | ce=2.0262 | kd=0.0000 | acc=0.3085 | binary=0.439 | condition=0.466 | count=0.000 | density=0.000 | time=7.1s
Epoch 002 | step 0040/0093 | loss=2.0237 | ce=2.0237 | kd=0.0000 | acc=0.3082 | binary=0.441 | condition=0.457 | count=0.002 | density=0.000 | time=7.7s
Epoch 002 | step 0045/0093 | loss=2.0242 | ce=2.0242 | kd=0.0000 | acc=0.3083 | binary=0.440 | condition=0.458 | count=0.003 | density=0.000 | time=8.5s
Epoch 002 | step 0050/0093 | loss=2.0184 | ce=2.0184 | kd=0.0000 | acc=0.3088 | binary=0.434 | condition=0.467 | count=0.003 | density=0.000 | time=9.1s
Epoch 002 | step 0055/0093 | loss=2.0157 | ce=2.0157 | kd=0.0000 | acc=0.3142 | binary=0.435 | condition=0.490 | count=0.004 | density=0.000 | time=10.0s
Epoch 002 | step 0060/0093 | loss=2.0092 | ce=2.0092 | kd=0.0000 | acc=0.3146 | binary=0.425 | condition=0.515 | count=0.004 | density=0.000 | time=10.6s
Epoch 002 | step 0065/0093 | loss=2.0022 | ce=2.0022 | kd=0.0000 | acc=0.3173 | binary=0.420 | condition=0.530 | count=0.006 | density=0.000 | time=11.4s
Epoch 002 | step 0070/0093 | loss=1.9969 | ce=1.9969 | kd=0.0000 | acc=0.3208 | binary=0.415 | condition=0.547 | count=0.006 | density=0.000 | time=12.1s
Epoch 002 | step 0075/0093 | loss=1.9941 | ce=1.9941 | kd=0.0000 | acc=0.3210 | binary=0.410 | condition=0.556 | count=0.009 | density=0.000 | time=12.9s
Epoch 002 | step 0080/0093 | loss=1.9868 | ce=1.9868 | kd=0.0000 | acc=0.3242 | binary=0.411 | condition=0.558 | count=0.011 | density=0.000 | time=13.6s
Epoch 002 | step 0085/0093 | loss=1.9841 | ce=1.9841 | kd=0.0000 | acc=0.3256 | binary=0.411 | condition=0.561 | count=0.011 | density=0.000 | time=14.4s
Epoch 002 | step 0090/0093 | loss=1.9799 | ce=1.9799 | kd=0.0000 | acc=0.3255 | binary=0.408 | condition=0.564 | count=0.010 | density=0.000 | time=14.9s
Epoch 002 | step 0093/0093 | loss=1.9779 | ce=1.9779 | kd=0.0000 | acc=0.3276 | binary=0.410 | condition=0.568 | count=0.010 | density=0.000 | time=15.1s

train overall: acc=0.3276 (1932/5898)
train macro acc: 0.1076
train count exact: acc=0.0100 (12/1204)
train count ±1: acc=0.0100 (12/1204)
train by edge head:
  binary       acc=0.4096 (1079/2634)
  condition    acc=0.5682 (841/1480)
  count        acc=0.0100 (12/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.4552 (264/580)
  Complex_Counting                         acc=0.0064 (4/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.4934 (673/1364)
  Risk_Assessment                          acc=0.5517 (320/580)
  Road_Condition_Recognition               acc=0.4170 (663/1590)
  Simple_Counting                          acc=0.0138 (8/580)

valid overall: acc=0.3605 (651/1806)
valid macro acc: 0.1208
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.4005 (326/814)
  condition    acc=0.7238 (325/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.5057 (89/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.5666 (234/413)
  Risk_Assessment                          acc=0.4830 (85/176)
  Road_Condition_Recognition               acc=0.4880 (243/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 2 done | train_acc=0.3276 | valid_acc=0.3605 | best_valid_acc=0.3605 at epoch 2 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 3/50
================================================================================
Epoch 003 | step 0001/0093 | loss=1.8862 | ce=1.8862 | kd=0.0000 | acc=0.3906 | binary=0.440 | condition=0.700 | count=0.000 | density=0.000 | time=0.6s
Epoch 003 | step 0005/0093 | loss=1.8887 | ce=1.8887 | kd=0.0000 | acc=0.3625 | binary=0.409 | condition=0.733 | count=0.000 | density=0.000 | time=1.6s
Epoch 003 | step 0010/0093 | loss=1.9346 | ce=1.9346 | kd=0.0000 | acc=0.3719 | binary=0.475 | condition=0.707 | count=0.000 | density=0.000 | time=2.6s
Epoch 003 | step 0015/0093 | loss=1.9054 | ce=1.9054 | kd=0.0000 | acc=0.4010 | binary=0.512 | condition=0.704 | count=0.005 | density=0.000 | time=3.4s
Epoch 003 | step 0020/0093 | loss=1.9182 | ce=1.9182 | kd=0.0000 | acc=0.4055 | binary=0.517 | condition=0.718 | count=0.011 | density=0.000 | time=4.0s
Epoch 003 | step 0025/0093 | loss=1.9087 | ce=1.9087 | kd=0.0000 | acc=0.4106 | binary=0.516 | condition=0.731 | count=0.021 | density=0.000 | time=4.8s
Epoch 003 | step 0030/0093 | loss=1.8908 | ce=1.8908 | kd=0.0000 | acc=0.4188 | binary=0.524 | condition=0.737 | count=0.025 | density=0.000 | time=5.4s
Epoch 003 | step 0035/0093 | loss=1.8836 | ce=1.8836 | kd=0.0000 | acc=0.4232 | binary=0.527 | condition=0.746 | count=0.027 | density=0.000 | time=6.3s
Epoch 003 | step 0040/0093 | loss=1.8783 | ce=1.8783 | kd=0.0000 | acc=0.4223 | binary=0.523 | condition=0.740 | count=0.034 | density=0.000 | time=6.9s
Epoch 003 | step 0045/0093 | loss=1.8644 | ce=1.8644 | kd=0.0000 | acc=0.4295 | binary=0.530 | condition=0.738 | count=0.045 | density=0.000 | time=7.7s
Epoch 003 | step 0050/0093 | loss=1.8657 | ce=1.8657 | kd=0.0000 | acc=0.4284 | binary=0.528 | condition=0.730 | count=0.047 | density=0.000 | time=8.3s
Epoch 003 | step 0055/0093 | loss=1.8613 | ce=1.8613 | kd=0.0000 | acc=0.4324 | binary=0.534 | condition=0.731 | count=0.053 | density=0.000 | time=9.1s
Epoch 003 | step 0060/0093 | loss=1.8662 | ce=1.8662 | kd=0.0000 | acc=0.4323 | binary=0.536 | condition=0.737 | count=0.054 | density=0.000 | time=9.8s
Epoch 003 | step 0065/0093 | loss=1.8608 | ce=1.8608 | kd=0.0000 | acc=0.4349 | binary=0.541 | condition=0.737 | count=0.059 | density=0.000 | time=10.6s
Epoch 003 | step 0070/0093 | loss=1.8560 | ce=1.8560 | kd=0.0000 | acc=0.4371 | binary=0.543 | condition=0.736 | count=0.063 | density=0.000 | time=11.2s
Epoch 003 | step 0075/0093 | loss=1.8477 | ce=1.8477 | kd=0.0000 | acc=0.4404 | binary=0.540 | condition=0.746 | count=0.068 | density=0.000 | time=12.1s
Epoch 003 | step 0080/0093 | loss=1.8417 | ce=1.8417 | kd=0.0000 | acc=0.4395 | binary=0.530 | condition=0.755 | count=0.074 | density=0.000 | time=12.7s
Epoch 003 | step 0085/0093 | loss=1.8321 | ce=1.8321 | kd=0.0000 | acc=0.4437 | binary=0.533 | condition=0.762 | count=0.077 | density=0.000 | time=14.0s
Epoch 003 | step 0090/0093 | loss=1.8237 | ce=1.8237 | kd=0.0000 | acc=0.4474 | binary=0.537 | condition=0.764 | count=0.077 | density=0.000 | time=15.1s
Epoch 003 | step 0093/0093 | loss=1.8226 | ce=1.8226 | kd=0.0000 | acc=0.4483 | binary=0.538 | condition=0.768 | count=0.076 | density=0.000 | time=15.3s

train overall: acc=0.4483 (2644/5898)
train macro acc: 0.1575
train count exact: acc=0.0756 (91/1204)
train count ±1: acc=0.0756 (91/1204)
train by edge head:
  binary       acc=0.5380 (1417/2634)
  condition    acc=0.7676 (1136/1480)
  count        acc=0.0756 (91/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.4983 (289/580)
  Complex_Counting                         acc=0.0657 (41/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.6716 (916/1364)
  Risk_Assessment                          acc=0.7931 (460/580)
  Road_Condition_Recognition               acc=0.5585 (888/1590)
  Simple_Counting                          acc=0.0862 (50/580)

valid overall: acc=0.5055 (913/1806)
valid macro acc: 0.1664
valid count exact: acc=0.0109 (4/367)
valid count ±1: acc=0.0109 (4/367)
valid by edge head:
  binary       acc=0.6585 (536/814)
  condition    acc=0.8307 (373/449)
  count        acc=0.0109 (4/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.6364 (112/176)
  Complex_Counting                         acc=0.0105 (2/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.8039 (332/413)
  Risk_Assessment                          acc=0.8523 (150/176)
  Road_Condition_Recognition               acc=0.6325 (315/498)
  Simple_Counting                          acc=0.0114 (2/176)

Epoch 3 done | train_acc=0.4483 | valid_acc=0.5055 | best_valid_acc=0.5055 at epoch 3 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 4/50
================================================================================
Epoch 004 | step 0001/0093 | loss=1.8512 | ce=1.8512 | kd=0.0000 | acc=0.4688 | binary=0.643 | condition=0.800 | count=0.000 | density=0.000 | time=0.3s
Epoch 004 | step 0005/0093 | loss=1.6928 | ce=1.6928 | kd=0.0000 | acc=0.5094 | binary=0.652 | condition=0.789 | count=0.037 | density=0.000 | time=1.0s
Epoch 004 | step 0010/0093 | loss=1.6883 | ce=1.6883 | kd=0.0000 | acc=0.5078 | binary=0.657 | condition=0.842 | count=0.024 | density=0.000 | time=1.6s
Epoch 004 | step 0015/0093 | loss=1.7149 | ce=1.7149 | kd=0.0000 | acc=0.4938 | binary=0.649 | condition=0.830 | count=0.020 | density=0.000 | time=2.4s
Epoch 004 | step 0020/0093 | loss=1.6948 | ce=1.6948 | kd=0.0000 | acc=0.5125 | binary=0.658 | condition=0.838 | count=0.045 | density=0.000 | time=3.1s
Epoch 004 | step 0025/0093 | loss=1.6935 | ce=1.6935 | kd=0.0000 | acc=0.5069 | binary=0.650 | condition=0.824 | count=0.064 | density=0.000 | time=3.9s
Epoch 004 | step 0030/0093 | loss=1.6914 | ce=1.6914 | kd=0.0000 | acc=0.5115 | binary=0.649 | condition=0.836 | count=0.080 | density=0.000 | time=4.5s
Epoch 004 | step 0035/0093 | loss=1.6901 | ce=1.6901 | kd=0.0000 | acc=0.5121 | binary=0.658 | condition=0.833 | count=0.085 | density=0.000 | time=5.2s
Epoch 004 | step 0040/0093 | loss=1.6871 | ce=1.6871 | kd=0.0000 | acc=0.5137 | binary=0.655 | condition=0.837 | count=0.095 | density=0.000 | time=5.8s
Epoch 004 | step 0045/0093 | loss=1.6762 | ce=1.6762 | kd=0.0000 | acc=0.5135 | binary=0.648 | condition=0.835 | count=0.098 | density=0.000 | time=6.7s
Epoch 004 | step 0050/0093 | loss=1.6642 | ce=1.6642 | kd=0.0000 | acc=0.5191 | binary=0.650 | condition=0.842 | count=0.104 | density=0.000 | time=7.4s
Epoch 004 | step 0055/0093 | loss=1.6595 | ce=1.6595 | kd=0.0000 | acc=0.5193 | binary=0.649 | condition=0.842 | count=0.119 | density=0.000 | time=8.3s
Epoch 004 | step 0060/0093 | loss=1.6590 | ce=1.6590 | kd=0.0000 | acc=0.5174 | binary=0.646 | condition=0.841 | count=0.125 | density=0.000 | time=9.3s
Epoch 004 | step 0065/0093 | loss=1.6455 | ce=1.6455 | kd=0.0000 | acc=0.5190 | binary=0.641 | condition=0.841 | count=0.131 | density=0.000 | time=10.7s
Epoch 004 | step 0070/0093 | loss=1.6335 | ce=1.6335 | kd=0.0000 | acc=0.5219 | binary=0.639 | condition=0.842 | count=0.136 | density=0.000 | time=11.7s
Epoch 004 | step 0075/0093 | loss=1.6250 | ce=1.6250 | kd=0.0000 | acc=0.5246 | binary=0.644 | condition=0.842 | count=0.134 | density=0.000 | time=13.0s
Epoch 004 | step 0080/0093 | loss=1.6161 | ce=1.6161 | kd=0.0000 | acc=0.5238 | binary=0.640 | condition=0.846 | count=0.133 | density=0.000 | time=13.7s
Epoch 004 | step 0085/0093 | loss=1.6077 | ce=1.6077 | kd=0.0000 | acc=0.5257 | binary=0.644 | condition=0.845 | count=0.133 | density=0.000 | time=14.4s
Epoch 004 | step 0090/0093 | loss=1.5979 | ce=1.5979 | kd=0.0000 | acc=0.5252 | binary=0.640 | condition=0.849 | count=0.128 | density=0.000 | time=15.0s
Epoch 004 | step 0093/0093 | loss=1.5963 | ce=1.5963 | kd=0.0000 | acc=0.5239 | binary=0.639 | condition=0.849 | count=0.126 | density=0.000 | time=15.2s

train overall: acc=0.5239 (3090/5898)
train macro acc: 0.1927
train count exact: acc=0.1262 (152/1204)
train count ±1: acc=0.1262 (152/1204)
train by edge head:
  binary       acc=0.6386 (1682/2634)
  condition    acc=0.8486 (1256/1480)
  count        acc=0.1262 (152/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.5828 (338/580)
  Complex_Counting                         acc=0.1218 (76/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.7808 (1065/1364)
  Risk_Assessment                          acc=0.8500 (493/580)

## S5: TDM-M + weighted CE

In [ ]:
%cd /content/TinyDisasterVQA
%env PYTHONPATH=/content/TinyDisasterVQA/src
%env PYTHONUNBUFFERED=1

!mkdir -p /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10

!python -u scripts/06_train_student.py \
  --dataset-root dataset \
  --runs-dir /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10 \
  --train-csv outputs/training_data_cap5/train.csv \
  --valid-csv outputs/training_data_cap5/valid.csv \
  --test-csv outputs/training_data_cap5/test.csv \
  --metadata outputs/training_data_cap5/metadata.json \
  --class-weights outputs/answer_space_cap5/class_weights_edge_global_by_label.json \
  --image-size 224 \
  --epochs 50 \
  --batch-size 64 \
  --eval-batch-size 64 \
  --num-workers 2 \
  --device auto \
  --patience 8 \
  --min-delta 0.001 \
  --log-interval 5 \
  --student-variant tdm_m \
  --mode weighted_ce \
  --run-name S5_tdm_m_weighted_ce_$(date +%Y%m%d_%H%M%S)

/content/TinyDisasterVQA
env: PYTHONPATH=/content/TinyDisasterVQA/src
env: PYTHONUNBUFFERED=1
================================================================================
TinyDisasterVQA / Train TDM Student
================================================================================
Run dir:              /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10/S5_tdm_m_weighted_ce_20260610_093722
Device:               cuda
Student variant:      tdm_m
Mode:                 weighted_ce
Count cap:            5
Num classes:          14
Question templates:   31
AMP:                  True
Image size:           224
Batch size:           64
Eval batch:           64
Epochs:               50
LR:                   0.0003
Weight decay:         0.0001
Patience:             8
Min delta:            0.001
KD alpha:             0.0
KD temp:              0.0

Model summary
================================================================================
Class:             TDMMVQA
Total params:      46,542
Trainable params:  46,542
FP32 param size:   0.18 MB
Int8 param size:   45.5 KB
Student variant:   tdm_m
Image block type:  dsconv
Image channels:    (16, 32, 64, 96, 128)
Image feature dim: 128
Template encoder:  one_hot + Linear
Template input dim:31
Template emb dim:  24
Fusion hidden dim: 128
Fusion layers:     1
Num classes:       14
Head type:         single edge_global

Using edge_global class weights:
[0.3070286810398102, 0.3189149796962738, 0.8006914258003235, 4.634336948394775, 0.3181625306606293, 0.883733332157135, 0.8129164576530457, 0.7653355598449707, 0.8368628621101379, 0.883733332157135, 0.7653355598449707, 0.8235432505607605, 1.2535922527313232, 0.5958129167556763]

================================================================================
Epoch 1/50
================================================================================
Epoch 001 | step 0001/0093 | loss=2.6862 | ce=2.6862 | kd=0.0000 | acc=0.0156 | binary=0.000 | condition=0.000 | count=0.100 | density=0.000 | time=6.5s
Epoch 001 | step 0005/0093 | loss=2.6607 | ce=2.6607 | kd=0.0000 | acc=0.0125 | binary=0.000 | condition=0.000 | count=0.061 | density=0.000 | time=6.7s
Epoch 001 | step 0010/0093 | loss=2.6508 | ce=2.6508 | kd=0.0000 | acc=0.0375 | binary=0.000 | condition=0.000 | count=0.178 | density=0.000 | time=7.4s
Epoch 001 | step 0015/0093 | loss=2.6420 | ce=2.6420 | kd=0.0000 | acc=0.0552 | binary=0.005 | condition=0.078 | count=0.162 | density=0.000 | time=8.0s
Epoch 001 | step 0020/0093 | loss=2.6305 | ce=2.6305 | kd=0.0000 | acc=0.0922 | binary=0.039 | condition=0.197 | count=0.119 | density=0.000 | time=8.8s
Epoch 001 | step 0025/0093 | loss=2.6161 | ce=2.6161 | kd=0.0000 | acc=0.1325 | binary=0.075 | condition=0.305 | count=0.097 | density=0.000 | time=9.4s
Epoch 001 | step 0030/0093 | loss=2.6056 | ce=2.6056 | kd=0.0000 | acc=0.1516 | binary=0.094 | condition=0.363 | count=0.083 | density=0.000 | time=10.1s
Epoch 001 | step 0035/0093 | loss=2.5942 | ce=2.5942 | kd=0.0000 | acc=0.1728 | binary=0.115 | condition=0.417 | count=0.073 | density=0.000 | time=10.8s
Epoch 001 | step 0040/0093 | loss=2.5871 | ce=2.5871 | kd=0.0000 | acc=0.1855 | binary=0.127 | condition=0.455 | count=0.063 | density=0.000 | time=11.5s
Epoch 001 | step 0045/0093 | loss=2.5795 | ce=2.5795 | kd=0.0000 | acc=0.1934 | binary=0.138 | condition=0.475 | count=0.057 | density=0.000 | time=12.2s
Epoch 001 | step 0050/0093 | loss=2.5716 | ce=2.5716 | kd=0.0000 | acc=0.2022 | binary=0.149 | condition=0.494 | count=0.051 | density=0.000 | time=13.0s
Epoch 001 | step 0055/0093 | loss=2.5639 | ce=2.5639 | kd=0.0000 | acc=0.2102 | binary=0.159 | condition=0.512 | count=0.047 | density=0.000 | time=14.0s
Epoch 001 | step 0060/0093 | loss=2.5534 | ce=2.5534 | kd=0.0000 | acc=0.2174 | binary=0.163 | condition=0.531 | count=0.043 | density=0.000 | time=15.2s
Epoch 001 | step 0065/0093 | loss=2.5472 | ce=2.5472 | kd=0.0000 | acc=0.2214 | binary=0.170 | condition=0.543 | count=0.040 | density=0.000 | time=16.1s
Epoch 001 | step 0070/0093 | loss=2.5435 | ce=2.5435 | kd=0.0000 | acc=0.2243 | binary=0.175 | condition=0.552 | count=0.036 | density=0.000 | time=17.5s
Epoch 001 | step 0075/0093 | loss=2.5392 | ce=2.5392 | kd=0.0000 | acc=0.2304 | binary=0.195 | condition=0.545 | count=0.034 | density=0.000 | time=18.1s
Epoch 001 | step 0080/0093 | loss=2.5306 | ce=2.5306 | kd=0.0000 | acc=0.2348 | binary=0.212 | condition=0.532 | count=0.032 | density=0.000 | time=18.9s
Epoch 001 | step 0085/0093 | loss=2.5265 | ce=2.5265 | kd=0.0000 | acc=0.2417 | binary=0.236 | condition=0.523 | count=0.030 | density=0.000 | time=19.6s
Epoch 001 | step 0090/0093 | loss=2.5178 | ce=2.5178 | kd=0.0000 | acc=0.2464 | binary=0.255 | condition=0.505 | count=0.028 | density=0.000 | time=20.3s
Epoch 001 | step 0093/0093 | loss=2.5138 | ce=2.5138 | kd=0.0000 | acc=0.2484 | binary=0.262 | condition=0.502 | count=0.027 | density=0.000 | time=23.7s

train overall: acc=0.2484 (1465/5898)
train macro acc: 0.0856
train count exact: acc=0.0274 (33/1204)
train count ±1: acc=0.0324 (39/1204)
train by edge head:
  binary       acc=0.2616 (689/2634)
  condition    acc=0.5020 (743/1480)
  count        acc=0.0274 (33/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.3017 (175/580)
  Complex_Counting                         acc=0.0208 (13/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.4018 (548/1364)
  Risk_Assessment                          acc=0.2828 (164/580)
  Road_Condition_Recognition               acc=0.3428 (545/1590)
  Simple_Counting                          acc=0.0345 (20/580)

valid overall: acc=0.3239 (585/1806)
valid macro acc: 0.0977
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.5528 (450/814)
  condition    acc=0.3007 (135/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.4602 (81/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.5157 (213/413)
  Risk_Assessment                          acc=0.7841 (138/176)
  Road_Condition_Recognition               acc=0.3072 (153/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 1 done | train_acc=0.2484 | valid_acc=0.3239 | best_valid_acc=0.3239 at epoch 1 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 2/50
================================================================================
Epoch 002 | step 0001/0093 | loss=2.4504 | ce=2.4504 | kd=0.0000 | acc=0.3125 | binary=0.500 | condition=0.350 | count=0.000 | density=0.000 | time=0.4s
Epoch 002 | step 0005/0093 | loss=2.4268 | ce=2.4268 | kd=0.0000 | acc=0.3281 | binary=0.492 | condition=0.455 | count=0.000 | density=0.000 | time=1.1s
Epoch 002 | step 0010/0093 | loss=2.4470 | ce=2.4470 | kd=0.0000 | acc=0.3250 | binary=0.443 | condition=0.547 | count=0.000 | density=0.000 | time=2.2s
Epoch 002 | step 0015/0093 | loss=2.4093 | ce=2.4093 | kd=0.0000 | acc=0.3458 | binary=0.417 | condition=0.624 | count=0.000 | density=0.000 | time=3.4s
Epoch 002 | step 0020/0093 | loss=2.4196 | ce=2.4196 | kd=0.0000 | acc=0.3563 | binary=0.429 | condition=0.655 | count=0.000 | density=0.000 | time=4.4s
Epoch 002 | step 0025/0093 | loss=2.4169 | ce=2.4169 | kd=0.0000 | acc=0.3488 | binary=0.430 | condition=0.638 | count=0.000 | density=0.000 | time=5.5s
Epoch 002 | step 0030/0093 | loss=2.4094 | ce=2.4094 | kd=0.0000 | acc=0.3516 | binary=0.436 | condition=0.619 | count=0.000 | density=0.000 | time=6.1s
Epoch 002 | step 0035/0093 | loss=2.4066 | ce=2.4066 | kd=0.0000 | acc=0.3464 | binary=0.432 | condition=0.619 | count=0.000 | density=0.000 | time=6.9s
Epoch 002 | step 0040/0093 | loss=2.4025 | ce=2.4025 | kd=0.0000 | acc=0.3480 | binary=0.424 | condition=0.636 | count=0.000 | density=0.000 | time=7.5s
Epoch 002 | step 0045/0093 | loss=2.3989 | ce=2.3989 | kd=0.0000 | acc=0.3479 | binary=0.421 | condition=0.642 | count=0.000 | density=0.000 | time=8.3s
Epoch 002 | step 0050/0093 | loss=2.3938 | ce=2.3938 | kd=0.0000 | acc=0.3500 | binary=0.416 | condition=0.649 | count=0.003 | density=0.003 | time=8.9s
Epoch 002 | step 0055/0093 | loss=2.3938 | ce=2.3938 | kd=0.0000 | acc=0.3511 | binary=0.417 | condition=0.657 | count=0.008 | density=0.003 | time=9.7s
Epoch 002 | step 0060/0093 | loss=2.3813 | ce=2.3813 | kd=0.0000 | acc=0.3581 | binary=0.418 | condition=0.666 | count=0.016 | density=0.003 | time=10.3s
Epoch 002 | step 0065/0093 | loss=2.3800 | ce=2.3800 | kd=0.0000 | acc=0.3596 | binary=0.420 | condition=0.670 | count=0.027 | density=0.002 | time=11.1s
Epoch 002 | step 0070/0093 | loss=2.3689 | ce=2.3689 | kd=0.0000 | acc=0.3663 | binary=0.427 | condition=0.670 | count=0.040 | density=0.002 | time=11.7s
Epoch 002 | step 0075/0093 | loss=2.3609 | ce=2.3609 | kd=0.0000 | acc=0.3715 | binary=0.428 | condition=0.676 | count=0.051 | density=0.002 | time=12.4s
Epoch 002 | step 0080/0093 | loss=2.3564 | ce=2.3564 | kd=0.0000 | acc=0.3732 | binary=0.425 | condition=0.686 | count=0.055 | density=0.002 | time=13.0s
Epoch 002 | step 0085/0093 | loss=2.3487 | ce=2.3487 | kd=0.0000 | acc=0.3770 | binary=0.425 | condition=0.696 | count=0.061 | density=0.002 | time=13.8s
Epoch 002 | step 0090/0093 | loss=2.3415 | ce=2.3415 | kd=0.0000 | acc=0.3792 | binary=0.425 | condition=0.701 | count=0.068 | density=0.002 | time=14.5s
Epoch 002 | step 0093/0093 | loss=2.3366 | ce=2.3366 | kd=0.0000 | acc=0.3815 | binary=0.425 | condition=0.704 | count=0.072 | density=0.002 | time=14.7s

train overall: acc=0.3815 (2250/5898)
train macro acc: 0.1435
train count exact: acc=0.0723 (87/1204)
train count ±1: acc=0.0723 (87/1204)
train by edge head:
  binary       acc=0.4252 (1120/2634)
  condition    acc=0.7041 (1042/1480)
  count        acc=0.0723 (87/1204)
  density      acc=0.0017 (1/580)
train by question type:
  Building_Condition_Recognition           acc=0.4690 (272/580)
  Complex_Counting                         acc=0.0641 (40/624)
  Density_Estimation                       acc=0.0017 (1/580)
  Entire_Image_Condition_Recognition       acc=0.5916 (807/1364)
  Risk_Assessment                          acc=0.5086 (295/580)
  Road_Condition_Recognition               acc=0.4956 (788/1590)
  Simple_Counting                          acc=0.0810 (47/580)

valid overall: acc=0.4302 (777/1806)
valid macro acc: 0.1940
valid count exact: acc=0.2125 (78/367)
valid count ±1: acc=0.2125 (78/367)
valid by edge head:
  binary       acc=0.4140 (337/814)
  condition    acc=0.8062 (362/449)
  count        acc=0.2125 (78/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.4034 (71/176)
  Complex_Counting                         acc=0.2094 (40/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.7119 (294/413)
  Risk_Assessment                          acc=0.2898 (51/176)
  Road_Condition_Recognition               acc=0.5683 (283/498)
  Simple_Counting                          acc=0.2159 (38/176)

Epoch 2 done | train_acc=0.3815 | valid_acc=0.4302 | best_valid_acc=0.4302 at epoch 2 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 3/50
================================================================================
Epoch 003 | step 0001/0093 | loss=2.3243 | ce=2.3243 | kd=0.0000 | acc=0.3906 | binary=0.238 | condition=0.739 | count=0.200 | density=0.000 | time=0.3s
Epoch 003 | step 0005/0093 | loss=2.2159 | ce=2.2159 | kd=0.0000 | acc=0.4250 | binary=0.438 | condition=0.773 | count=0.157 | density=0.000 | time=0.9s
Epoch 003 | step 0010/0093 | loss=2.2120 | ce=2.2120 | kd=0.0000 | acc=0.4203 | binary=0.425 | condition=0.771 | count=0.173 | density=0.000 | time=1.5s
Epoch 003 | step 0015/0093 | loss=2.2070 | ce=2.2070 | kd=0.0000 | acc=0.4365 | binary=0.464 | condition=0.788 | count=0.169 | density=0.000 | time=2.1s
Epoch 003 | step 0020/0093 | loss=2.1897 | ce=2.1897 | kd=0.0000 | acc=0.4516 | binary=0.494 | condition=0.782 | count=0.179 | density=0.008 | time=2.8s
Epoch 003 | step 0025/0093 | loss=2.1750 | ce=2.1750 | kd=0.0000 | acc=0.4537 | binary=0.497 | condition=0.781 | count=0.177 | density=0.013 | time=3.5s
Epoch 003 | step 0030/0093 | loss=2.1700 | ce=2.1700 | kd=0.0000 | acc=0.4620 | binary=0.510 | condition=0.785 | count=0.177 | density=0.016 | time=4.2s
Epoch 003 | step 0035/0093 | loss=2.1546 | ce=2.1546 | kd=0.0000 | acc=0.4616 | binary=0.504 | condition=0.785 | count=0.185 | density=0.014 | time=4.9s
Epoch 003 | step 0040/0093 | loss=2.1464 | ce=2.1464 | kd=0.0000 | acc=0.4586 | binary=0.497 | condition=0.788 | count=0.189 | density=0.016 | time=5.6s
Epoch 003 | step 0045/0093 | loss=2.1423 | ce=2.1423 | kd=0.0000 | acc=0.4615 | binary=0.496 | condition=0.797 | count=0.195 | density=0.014 | time=6.3s
Epoch 003 | step 0050/0093 | loss=2.1377 | ce=2.1377 | kd=0.0000 | acc=0.4659 | binary=0.504 | condition=0.796 | count=0.202 | density=0.016 | time=7.1s
Epoch 003 | step 0055/0093 | loss=2.1311 | ce=2.1311 | kd=0.0000 | acc=0.4699 | binary=0.512 | condition=0.798 | count=0.209 | density=0.014 | time=7.8s
Epoch 003 | step 0060/0093 | loss=2.1318 | ce=2.1318 | kd=0.0000 | acc=0.4711 | binary=0.515 | condition=0.803 | count=0.205 | density=0.013 | time=8.5s
Epoch 003 | step 0065/0093 | loss=2.1190 | ce=2.1190 | kd=0.0000 | acc=0.4798 | binary=0.526 | condition=0.814 | count=0.204 | density=0.012 | time=9.2s
Epoch 003 | step 0070/0093 | loss=2.1012 | ce=2.1012 | kd=0.0000 | acc=0.4904 | binary=0.537 | condition=0.822 | count=0.213 | density=0.011 | time=10.0s
Epoch 003 | step 0075/0093 | loss=2.0986 | ce=2.0986 | kd=0.0000 | acc=0.4952 | binary=0.547 | condition=0.825 | count=0.212 | density=0.015 | time=10.9s
Epoch 003 | step 0080/0093 | loss=2.0914 | ce=2.0914 | kd=0.0000 | acc=0.5002 | binary=0.557 | condition=0.829 | count=0.203 | density=0.016 | time=12.1s
Epoch 003 | step 0085/0093 | loss=2.0890 | ce=2.0890 | kd=0.0000 | acc=0.5050 | binary=0.565 | condition=0.832 | count=0.203 | density=0.019 | time=13.1s
Epoch 003 | step 0090/0093 | loss=2.0848 | ce=2.0848 | kd=0.0000 | acc=0.5047 | binary=0.563 | condition=0.838 | count=0.201 | density=0.019 | time=14.3s
Epoch 003 | step 0093/0093 | loss=2.0857 | ce=2.0857 | kd=0.0000 | acc=0.5059 | binary=0.565 | condition=0.841 | count=0.199 | density=0.019 | time=14.6s

train overall: acc=0.5059 (2984/5898)
train macro acc: 0.2255
train count exact: acc=0.1993 (240/1204)
train count ±1: acc=0.1993 (240/1204)
train by edge head:
  binary       acc=0.5649 (1488/2634)
  condition    acc=0.8412 (1245/1480)
  count        acc=0.1993 (240/1204)
  density      acc=0.0190 (11/580)
train by question type:
  Building_Condition_Recognition           acc=0.5655 (328/580)
  Complex_Counting                         acc=0.1891 (118/624)
  Density_Estimation                       acc=0.0190 (11/580)
  Entire_Image_Condition_Recognition       acc=0.7243 (988/1364)
  Risk_Assessment                          acc=0.5672 (329/580)
  Road_Condition_Recognition               acc=0.6843 (1088/1590)
  Simple_Counting                          acc=0.2103 (122/580)

valid overall: acc=0.5598 (1011/1806)
valid macro acc: 0.2703
valid count exact: acc=0.1662 (61/367)
valid count ±1: acc=0.1662 (61/367)
valid by edge head:
  binary       acc=0.6290 (512/814)
  condition    acc=0.9599 (431/449)
  count        acc=0.1662 (61/367)
  density      acc=0.0398 (7/176)
valid by question type:
  Building_Condition_Recognition           acc=0.5455 (96/176)
  Complex_Counting                         acc=0.1466 (28/191)
  Density_Estimation                       acc=0.0398 (7/176)
  Entire_Image_Condition_Recognition       acc=0.7918 (327/413)
  Risk_Assessment                          acc=0.8125 (143/176)
  Road_Condition_Recognition               acc=0.7570 (377/498)
  Simple_Counting                          acc=0.1875 (33/176)

Epoch 3 done | train_acc=0.5059 | valid_acc=0.5598 | best_valid_acc=0.5598 at epoch 3 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 4/50
================================================================================
Epoch 004 | step 0001/0093 | loss=1.7071 | ce=1.7071 | kd=0.0000 | acc=0.5938 | binary=0.625 | condition=0.944 | count=0.125 | density=0.000 | time=0.4s
Epoch 004 | step 0005/0093 | loss=1.8820 | ce=1.8820 | kd=0.0000 | acc=0.5375 | binary=0.581 | condition=0.974 | count=0.125 | density=0.000 | time=1.0s
Epoch 004 | step 0010/0093 | loss=1.9315 | ce=1.9315 | kd=0.0000 | acc=0.5609 | binary=0.606 | condition=0.960 | count=0.088 | density=0.051 | time=1.6s
Epoch 004 | step 0015/0093 | loss=1.9395 | ce=1.9395 | kd=0.0000 | acc=0.5552 | binary=0.624 | condition=0.953 | count=0.094 | density=0.061 | time=2.3s
Epoch 004 | step 0020/0093 | loss=1.9105 | ce=1.9105 | kd=0.0000 | acc=0.5750 | binary=0.649 | condition=0.957 | count=0.114 | density=0.084 | time=2.9s
Epoch 004 | step 0025/0093 | loss=1.9036 | ce=1.9036 | kd=0.0000 | acc=0.5887 | binary=0.676 | condition=0.960 | count=0.117 | density=0.115 | time=3.7s
Epoch 004 | step 0030/0093 | loss=1.9028 | ce=1.9028 | kd=0.0000 | acc=0.5906 | binary=0.680 | condition=0.961 | count=0.114 | density=0.112 | time=4.3s
Epoch 004 | step 0035/0093 | loss=1.8828 | ce=1.8828 | kd=0.0000 | acc=0.6004 | binary=0.696 | condition=0.964 | count=0.127 | density=0.129 | time=5.1s
Epoch 004 | step 0040/0093 | loss=1.8567 | ce=1.8567 | kd=0.0000 | acc=0.6082 | binary=0.698 | condition=0.964 | count=0.156 | density=0.151 | time=5.8s
Epoch 004 | step 0045/0093 | loss=1.8443 | ce=1.8443 | kd=0.0000 | acc=0.6101 | binary=0.698 | condition=0.966 | count=0.162 | density=0.161 | time=6.5s
Epoch 004 | step 0050/0093 | loss=1.8206 | ce=1.8206 | kd=0.0000 | acc=0.6156 | binary=0.701 | condition=0.967 | count=0.174 | density=0.166 | time=7.5s
Epoch 004 | step 0055/0093 | loss=1.8161 | ce=1.8161 | kd=0.0000 | acc=0.6179 | binary=0.706 | condition=0.969 | count=0.182 | density=0.167 | time=8.7s
Epoch 004 | step 0060/0093 | loss=1.8039 | ce=1.8039 | kd=0.0000 | acc=0.6216 | binary=0.710 | condition=0.968 | count=0.186 | density=0.168 | time=9.9s
Epoch 004 | step 0065/0093 | loss=1.7950 | ce=1.7950 | kd=0.0000 | acc=0.6221 | binary=0.714 | condition=0.964 | count=0.196 | density=0.163 | time=11.2s
Epoch 004 | step 0070/0093 | loss=1.7875 | ce=1.7875 | kd=0.0000 | acc=0.6232 | binary=0.717 | condition=0.964 | count=0.197 | density=0.170 | time=11.8s
Epoch 004 | step 0075/0093 | loss=1.7737 | ce=1.7737 | kd=0.0000 | acc=0.6258 | binary=0.716 | condition=0.965 | count=0.204 | density=0.187 | time=12.6s
Epoch 004 | step 0080/0093 | loss=1.7717 | ce=1.7717 | kd=0.0000 | acc=0.6248 | binary=0.714 | condition=0.964 | count=0.209 | density=0.193 | time=13.2s
Epoch 004 | step 0085/0093 | loss=1.7658 | ce=1.7658 | kd=0.0000 | acc=0.6279 | binary=0.721 | condition=0.965 | count=0.212 | density=0.203 | time=13.9s
Epoch 004 | step 0090/0093 | loss=1.7623 | ce=1.7623 | kd=0.0000 | acc=0.6307 | binary=0.724 | condition=0.965 | count=0.213 | density=0.214 | time=14.6s
Epoch 004 | step 0093/0093 | loss=1.7603 | ce=1.7603 | kd=0.0000 | acc=0.6309 | binary=0.726 | condition=0.964 | count=0.213 | density=0.219 | time=14.8s

train overall: acc=0.6309 (3721/5898)
train macro acc: 0.3325
train count exact: acc=0.2135 (257/1204)
train count ±1: acc=0.2226 (268/1204)
train by edge head:
  binary       acc=0.7255 (1911/2634)
  condition    acc=0.9635 (1426/1480)
  count        acc=0.2135 (257/1204)
  density      acc=0.2190 (127/580)
train by question type:

## S6: TDM-L + weighted CE

In [ ]:
%cd /content/TinyDisasterVQA
%env PYTHONPATH=/content/TinyDisasterVQA/src
%env PYTHONUNBUFFERED=1

!mkdir -p /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10

!python -u scripts/06_train_student.py \
  --dataset-root dataset \
  --runs-dir /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10 \
  --train-csv outputs/training_data_cap5/train.csv \
  --valid-csv outputs/training_data_cap5/valid.csv \
  --test-csv outputs/training_data_cap5/test.csv \
  --metadata outputs/training_data_cap5/metadata.json \
  --class-weights outputs/answer_space_cap5/class_weights_edge_global_by_label.json \
  --image-size 224 \
  --epochs 50 \
  --batch-size 64 \
  --eval-batch-size 64 \
  --num-workers 2 \
  --device auto \
  --patience 8 \
  --min-delta 0.001 \
  --log-interval 5 \
  --student-variant tdm_l \
  --mode weighted_ce \
  --run-name S6_tdm_l_weighted_ce_$(date +%Y%m%d_%H%M%S)

/content/TinyDisasterVQA
env: PYTHONPATH=/content/TinyDisasterVQA/src
env: PYTHONUNBUFFERED=1
================================================================================
TinyDisasterVQA / Train TDM Student
================================================================================
Run dir:              /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10/S6_tdm_l_weighted_ce_20260610_094801
Device:               cuda
Student variant:      tdm_l
Mode:                 weighted_ce
Count cap:            5
Num classes:          14
Question templates:   31
AMP:                  True
Image size:           224
Batch size:           64
Eval batch:           64
Epochs:               50
LR:                   0.0003
Weight decay:         0.0001
Patience:             8
Min delta:            0.001
KD alpha:             0.0
KD temp:              0.0

Model summary
================================================================================
Class:             TDMLVQA
Total params:      101,310
Trainable params:  101,310
FP32 param size:   0.39 MB
Int8 param size:   98.9 KB
Student variant:   tdm_l
Image block type:  dsconv
Image channels:    (24, 48, 96, 128, 160)
Image feature dim: 160
Template encoder:  one_hot + Linear
Template input dim:31
Template emb dim:  32
Fusion hidden dim: 192
Fusion layers:     2
Num classes:       14
Head type:         single edge_global

Using edge_global class weights:
[0.3070286810398102, 0.3189149796962738, 0.8006914258003235, 4.634336948394775, 0.3181625306606293, 0.883733332157135, 0.8129164576530457, 0.7653355598449707, 0.8368628621101379, 0.883733332157135, 0.7653355598449707, 0.8235432505607605, 1.2535922527313232, 0.5958129167556763]

================================================================================
Epoch 1/50
================================================================================
Epoch 001 | step 0001/0093 | loss=2.6677 | ce=2.6677 | kd=0.0000 | acc=0.0312 | binary=0.000 | condition=0.000 | count=0.000 | density=0.250 | time=3.2s
Epoch 001 | step 0005/0093 | loss=2.6491 | ce=2.6491 | kd=0.0000 | acc=0.0437 | binary=0.000 | condition=0.000 | count=0.000 | density=0.311 | time=3.4s
Epoch 001 | step 0010/0093 | loss=2.6391 | ce=2.6391 | kd=0.0000 | acc=0.0609 | binary=0.067 | condition=0.000 | count=0.000 | density=0.278 | time=5.0s
Epoch 001 | step 0015/0093 | loss=2.6283 | ce=2.6283 | kd=0.0000 | acc=0.1156 | binary=0.197 | condition=0.025 | count=0.000 | density=0.208 | time=6.0s
Epoch 001 | step 0020/0093 | loss=2.6198 | ce=2.6198 | kd=0.0000 | acc=0.1359 | binary=0.257 | condition=0.025 | count=0.000 | density=0.162 | time=6.8s
Epoch 001 | step 0025/0093 | loss=2.6104 | ce=2.6104 | kd=0.0000 | acc=0.1512 | binary=0.294 | condition=0.025 | count=0.003 | density=0.127 | time=7.5s
Epoch 001 | step 0030/0093 | loss=2.6003 | ce=2.6003 | kd=0.0000 | acc=0.1589 | binary=0.317 | condition=0.021 | count=0.003 | density=0.113 | time=8.3s
Epoch 001 | step 0035/0093 | loss=2.5962 | ce=2.5962 | kd=0.0000 | acc=0.1621 | binary=0.332 | condition=0.020 | count=0.002 | density=0.097 | time=9.0s
Epoch 001 | step 0040/0093 | loss=2.5862 | ce=2.5862 | kd=0.0000 | acc=0.1691 | binary=0.345 | condition=0.031 | count=0.002 | density=0.085 | time=9.7s
Epoch 001 | step 0045/0093 | loss=2.5778 | ce=2.5778 | kd=0.0000 | acc=0.1743 | binary=0.354 | condition=0.042 | count=0.002 | density=0.076 | time=10.3s
Epoch 001 | step 0050/0093 | loss=2.5678 | ce=2.5678 | kd=0.0000 | acc=0.1828 | binary=0.359 | condition=0.070 | count=0.002 | density=0.068 | time=11.0s
Epoch 001 | step 0055/0093 | loss=2.5614 | ce=2.5614 | kd=0.0000 | acc=0.1901 | binary=0.360 | condition=0.095 | count=0.001 | density=0.062 | time=11.8s
Epoch 001 | step 0060/0093 | loss=2.5523 | ce=2.5523 | kd=0.0000 | acc=0.1938 | binary=0.365 | condition=0.098 | count=0.001 | density=0.058 | time=12.5s
Epoch 001 | step 0065/0093 | loss=2.5526 | ce=2.5526 | kd=0.0000 | acc=0.1954 | binary=0.368 | condition=0.106 | count=0.001 | density=0.053 | time=13.1s
Epoch 001 | step 0070/0093 | loss=2.5470 | ce=2.5470 | kd=0.0000 | acc=0.1967 | binary=0.373 | condition=0.105 | count=0.001 | density=0.049 | time=13.8s
Epoch 001 | step 0075/0093 | loss=2.5427 | ce=2.5427 | kd=0.0000 | acc=0.2023 | binary=0.376 | condition=0.124 | count=0.001 | density=0.046 | time=14.4s
Epoch 001 | step 0080/0093 | loss=2.5395 | ce=2.5395 | kd=0.0000 | acc=0.2064 | binary=0.378 | condition=0.136 | count=0.001 | density=0.043 | time=15.2s
Epoch 001 | step 0085/0093 | loss=2.5352 | ce=2.5352 | kd=0.0000 | acc=0.2121 | binary=0.382 | condition=0.152 | count=0.001 | density=0.041 | time=15.9s
Epoch 001 | step 0090/0093 | loss=2.5302 | ce=2.5302 | kd=0.0000 | acc=0.2148 | binary=0.387 | condition=0.154 | count=0.001 | density=0.038 | time=16.9s
Epoch 001 | step 0093/0093 | loss=2.5260 | ce=2.5260 | kd=0.0000 | acc=0.2155 | binary=0.388 | condition=0.152 | count=0.001 | density=0.038 | time=21.6s

train overall: acc=0.2155 (1271/5898)
train macro acc: 0.0770
train count exact: acc=0.0008 (1/1204)
train count ±1: acc=0.0050 (6/1204)
train by edge head:
  binary       acc=0.3884 (1023/2634)
  condition    acc=0.1520 (225/1480)
  count        acc=0.0008 (1/1204)
  density      acc=0.0379 (22/580)
train by question type:
  Building_Condition_Recognition           acc=0.4345 (252/580)
  Complex_Counting                         acc=0.0016 (1/624)
  Density_Estimation                       acc=0.0379 (22/580)
  Entire_Image_Condition_Recognition       acc=0.2749 (375/1364)
  Risk_Assessment                          acc=0.3017 (175/580)
  Road_Condition_Recognition               acc=0.2805 (446/1590)
  Simple_Counting                          acc=0.0000 (0/580)

valid overall: acc=0.2697 (487/1806)
valid macro acc: 0.0810
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.5983 (487/814)
  condition    acc=0.0000 (0/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.5170 (91/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.3269 (135/413)
  Risk_Assessment                          acc=0.6591 (116/176)
  Road_Condition_Recognition               acc=0.2912 (145/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 1 done | train_acc=0.2155 | valid_acc=0.2697 | best_valid_acc=0.2697 at epoch 1 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 2/50
================================================================================
Epoch 002 | step 0001/0093 | loss=2.4419 | ce=2.4419 | kd=0.0000 | acc=0.2812 | binary=0.571 | condition=0.143 | count=0.000 | density=0.000 | time=0.3s
Epoch 002 | step 0005/0093 | loss=2.4827 | ce=2.4827 | kd=0.0000 | acc=0.2469 | binary=0.515 | condition=0.115 | count=0.000 | density=0.000 | time=0.8s
Epoch 002 | step 0010/0093 | loss=2.4783 | ce=2.4783 | kd=0.0000 | acc=0.2641 | binary=0.532 | condition=0.124 | count=0.000 | density=0.000 | time=1.6s
Epoch 002 | step 0015/0093 | loss=2.4606 | ce=2.4606 | kd=0.0000 | acc=0.2760 | binary=0.505 | condition=0.220 | count=0.000 | density=0.000 | time=2.3s
Epoch 002 | step 0020/0093 | loss=2.4533 | ce=2.4533 | kd=0.0000 | acc=0.2781 | binary=0.442 | condition=0.330 | count=0.000 | density=0.000 | time=3.0s
Epoch 002 | step 0025/0093 | loss=2.4482 | ce=2.4482 | kd=0.0000 | acc=0.2812 | binary=0.409 | condition=0.398 | count=0.000 | density=0.000 | time=3.8s
Epoch 002 | step 0030/0093 | loss=2.4419 | ce=2.4419 | kd=0.0000 | acc=0.2901 | binary=0.408 | condition=0.433 | count=0.000 | density=0.000 | time=4.6s
Epoch 002 | step 0035/0093 | loss=2.4487 | ce=2.4487 | kd=0.0000 | acc=0.2862 | binary=0.411 | condition=0.420 | count=0.000 | density=0.000 | time=5.3s
Epoch 002 | step 0040/0093 | loss=2.4517 | ce=2.4517 | kd=0.0000 | acc=0.2859 | binary=0.423 | condition=0.394 | count=0.000 | density=0.000 | time=6.8s
Epoch 002 | step 0045/0093 | loss=2.4457 | ce=2.4457 | kd=0.0000 | acc=0.2892 | binary=0.430 | condition=0.395 | count=0.000 | density=0.000 | time=7.9s
Epoch 002 | step 0050/0093 | loss=2.4332 | ce=2.4332 | kd=0.0000 | acc=0.3009 | binary=0.440 | condition=0.417 | count=0.002 | density=0.000 | time=9.3s
Epoch 002 | step 0055/0093 | loss=2.4282 | ce=2.4282 | kd=0.0000 | acc=0.3063 | binary=0.441 | condition=0.440 | count=0.001 | density=0.000 | time=10.0s
Epoch 002 | step 0060/0093 | loss=2.4171 | ce=2.4171 | kd=0.0000 | acc=0.3125 | binary=0.434 | condition=0.469 | count=0.001 | density=0.000 | time=10.9s
Epoch 002 | step 0065/0093 | loss=2.4096 | ce=2.4096 | kd=0.0000 | acc=0.3180 | binary=0.436 | condition=0.486 | count=0.001 | density=0.000 | time=11.5s
Epoch 002 | step 0070/0093 | loss=2.4093 | ce=2.4093 | kd=0.0000 | acc=0.3241 | binary=0.444 | condition=0.496 | count=0.001 | density=0.000 | time=12.3s
Epoch 002 | step 0075/0093 | loss=2.4016 | ce=2.4016 | kd=0.0000 | acc=0.3287 | binary=0.455 | condition=0.493 | count=0.003 | density=0.000 | time=12.9s
Epoch 002 | step 0080/0093 | loss=2.3931 | ce=2.3931 | kd=0.0000 | acc=0.3336 | binary=0.462 | condition=0.493 | count=0.010 | density=0.000 | time=13.7s
Epoch 002 | step 0085/0093 | loss=2.3866 | ce=2.3866 | kd=0.0000 | acc=0.3390 | binary=0.469 | condition=0.503 | count=0.014 | density=0.000 | time=14.3s
Epoch 002 | step 0090/0093 | loss=2.3785 | ce=2.3785 | kd=0.0000 | acc=0.3455 | binary=0.470 | condition=0.515 | count=0.027 | density=0.000 | time=14.9s
Epoch 002 | step 0093/0093 | loss=2.3773 | ce=2.3773 | kd=0.0000 | acc=0.3469 | binary=0.468 | condition=0.523 | count=0.032 | density=0.000 | time=15.1s

train overall: acc=0.3469 (2046/5898)
train macro acc: 0.1172
train count exact: acc=0.0324 (39/1204)
train count ±1: acc=0.0324 (39/1204)
train by edge head:
  binary       acc=0.4681 (1233/2634)
  condition    acc=0.5230 (774/1480)
  count        acc=0.0324 (39/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.4810 (279/580)
  Complex_Counting                         acc=0.0224 (14/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.5037 (687/1364)
  Risk_Assessment                          acc=0.4362 (253/580)
  Road_Condition_Recognition               acc=0.4956 (788/1590)
  Simple_Counting                          acc=0.0431 (25/580)

valid overall: acc=0.4729 (854/1806)
valid macro acc: 0.1893
valid count exact: acc=0.2289 (84/367)
valid count ±1: acc=0.2289 (84/367)
valid by edge head:
  binary       acc=0.5000 (407/814)
  condition    acc=0.8085 (363/449)
  count        acc=0.2289 (84/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.3807 (67/176)
  Complex_Counting                         acc=0.2147 (41/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.7070 (292/413)
  Risk_Assessment                          acc=0.6818 (120/176)
  Road_Condition_Recognition               acc=0.5843 (291/498)
  Simple_Counting                          acc=0.2443 (43/176)

Epoch 2 done | train_acc=0.3469 | valid_acc=0.4729 | best_valid_acc=0.4729 at epoch 2 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 3/50
================================================================================
Epoch 003 | step 0001/0093 | loss=2.2558 | ce=2.2558 | kd=0.0000 | acc=0.5312 | binary=0.625 | condition=0.818 | count=0.071 | density=0.000 | time=0.4s
Epoch 003 | step 0005/0093 | loss=2.1130 | ce=2.1130 | kd=0.0000 | acc=0.5031 | binary=0.485 | condition=0.867 | count=0.283 | density=0.000 | time=1.0s
Epoch 003 | step 0010/0093 | loss=2.1471 | ce=2.1471 | kd=0.0000 | acc=0.4641 | binary=0.460 | condition=0.829 | count=0.234 | density=0.014 | time=1.8s
Epoch 003 | step 0015/0093 | loss=2.1251 | ce=2.1251 | kd=0.0000 | acc=0.4760 | binary=0.474 | condition=0.833 | count=0.240 | density=0.010 | time=3.1s
Epoch 003 | step 0020/0093 | loss=2.1346 | ce=2.1346 | kd=0.0000 | acc=0.4727 | binary=0.475 | condition=0.824 | count=0.233 | density=0.008 | time=4.1s
Epoch 003 | step 0025/0093 | loss=2.1219 | ce=2.1219 | kd=0.0000 | acc=0.4869 | binary=0.505 | condition=0.825 | count=0.237 | density=0.006 | time=5.3s
Epoch 003 | step 0030/0093 | loss=2.1117 | ce=2.1117 | kd=0.0000 | acc=0.4849 | binary=0.508 | condition=0.825 | count=0.226 | density=0.010 | time=6.3s
Epoch 003 | step 0035/0093 | loss=2.1115 | ce=2.1115 | kd=0.0000 | acc=0.4844 | binary=0.515 | condition=0.829 | count=0.215 | density=0.014 | time=7.0s
Epoch 003 | step 0040/0093 | loss=2.0931 | ce=2.0931 | kd=0.0000 | acc=0.4906 | binary=0.523 | condition=0.831 | count=0.223 | density=0.016 | time=7.8s
Epoch 003 | step 0045/0093 | loss=2.0736 | ce=2.0736 | kd=0.0000 | acc=0.4958 | binary=0.526 | condition=0.844 | count=0.218 | density=0.029 | time=8.5s
Epoch 003 | step 0050/0093 | loss=2.0681 | ce=2.0681 | kd=0.0000 | acc=0.4956 | binary=0.526 | condition=0.845 | count=0.207 | density=0.042 | time=9.2s
Epoch 003 | step 0055/0093 | loss=2.0485 | ce=2.0485 | kd=0.0000 | acc=0.5031 | binary=0.534 | condition=0.848 | count=0.210 | density=0.059 | time=9.9s
Epoch 003 | step 0060/0093 | loss=2.0262 | ce=2.0262 | kd=0.0000 | acc=0.5089 | binary=0.541 | condition=0.855 | count=0.213 | density=0.071 | time=10.6s
Epoch 003 | step 0065/0093 | loss=2.0070 | ce=2.0070 | kd=0.0000 | acc=0.5118 | binary=0.544 | condition=0.853 | count=0.215 | density=0.087 | time=11.3s
Epoch 003 | step 0070/0093 | loss=1.9833 | ce=1.9833 | kd=0.0000 | acc=0.5147 | binary=0.546 | condition=0.851 | count=0.218 | density=0.113 | time=12.0s
Epoch 003 | step 0075/0093 | loss=1.9623 | ce=1.9623 | kd=0.0000 | acc=0.5173 | binary=0.547 | condition=0.850 | count=0.221 | density=0.134 | time=12.5s
Epoch 003 | step 0080/0093 | loss=1.9389 | ce=1.9389 | kd=0.0000 | acc=0.5191 | binary=0.548 | condition=0.850 | count=0.222 | density=0.152 | time=13.3s
Epoch 003 | step 0085/0093 | loss=1.9233 | ce=1.9233 | kd=0.0000 | acc=0.5233 | binary=0.549 | condition=0.857 | count=0.225 | density=0.167 | time=13.8s
Epoch 003 | step 0090/0093 | loss=1.9059 | ce=1.9059 | kd=0.0000 | acc=0.5259 | binary=0.552 | condition=0.863 | count=0.217 | density=0.183 | time=14.7s
Epoch 003 | step 0093/0093 | loss=1.9007 | ce=1.9007 | kd=0.0000 | acc=0.5251 | binary=0.550 | condition=0.866 | count=0.212 | density=0.190 | time=14.9s

train overall: acc=0.5251 (3097/5898)
train macro acc: 0.2539
train count exact: acc=0.2118 (255/1204)
train count ±1: acc=0.2126 (256/1204)
train by edge head:
  binary       acc=0.5505 (1450/2634)
  condition    acc=0.8662 (1282/1480)
  count        acc=0.2118 (255/1204)
  density      acc=0.1897 (110/580)
train by question type:
  Building_Condition_Recognition           acc=0.5224 (303/580)
  Complex_Counting                         acc=0.1971 (123/624)
  Density_Estimation                       acc=0.1897 (110/580)
  Entire_Image_Condition_Recognition       acc=0.7441 (1015/1364)
  Risk_Assessment                          acc=0.5707 (331/580)
  Road_Condition_Recognition               acc=0.6811 (1083/1590)
  Simple_Counting                          acc=0.2276 (132/580)

valid overall: acc=0.5808 (1049/1806)
valid macro acc: 0.3572
valid count exact: acc=0.0599 (22/367)
valid count ±1: acc=0.0599 (22/367)
valid by edge head:
  binary       acc=0.6020 (490/814)
  condition    acc=0.9555 (429/449)
  count        acc=0.0599 (22/367)
  density      acc=0.6136 (108/176)
valid by question type:
  Building_Condition_Recognition           acc=0.4659 (82/176)
  Complex_Counting                         acc=0.0524 (10/191)
  Density_Estimation                       acc=0.6136 (108/176)
  Entire_Image_Condition_Recognition       acc=0.8499 (351/413)
  Risk_Assessment                          acc=0.7955 (140/176)
  Road_Condition_Recognition               acc=0.6948 (346/498)
  Simple_Counting                          acc=0.0682 (12/176)

Epoch 3 done | train_acc=0.5251 | valid_acc=0.5808 | best_valid_acc=0.5808 at epoch 3 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 4/50
================================================================================
Epoch 004 | step 0001/0093 | loss=1.6715 | ce=1.6715 | kd=0.0000 | acc=0.5938 | binary=0.760 | condition=1.000 | count=0.056 | density=0.400 | time=0.6s
Epoch 004 | step 0005/0093 | loss=1.5790 | ce=1.5790 | kd=0.0000 | acc=0.5375 | binary=0.558 | condition=0.959 | count=0.068 | density=0.556 | time=1.3s
Epoch 004 | step 0010/0093 | loss=1.4994 | ce=1.4994 | kd=0.0000 | acc=0.5703 | binary=0.563 | condition=0.963 | count=0.083 | density=0.621 | time=1.9s
Epoch 004 | step 0015/0093 | loss=1.4462 | ce=1.4462 | kd=0.0000 | acc=0.5813 | binary=0.571 | condition=0.967 | count=0.083 | density=0.667 | time=2.6s
Epoch 004 | step 0020/0093 | loss=1.4741 | ce=1.4741 | kd=0.0000 | acc=0.5836 | binary=0.564 | condition=0.967 | count=0.109 | density=0.641 | time=3.3s
Epoch 004 | step 0025/0093 | loss=1.4474 | ce=1.4474 | kd=0.0000 | acc=0.5850 | binary=0.552 | condition=0.966 | count=0.135 | density=0.615 | time=4.0s
Epoch 004 | step 0030/0093 | loss=1.4293 | ce=1.4293 | kd=0.0000 | acc=0.5964 | binary=0.566 | condition=0.966 | count=0.164 | density=0.626 | time=4.6s
Epoch 004 | step 0035/0093 | loss=1.4199 | ce=1.4199 | kd=0.0000 | acc=0.5969 | binary=0.568 | condition=0.966 | count=0.180 | density=0.604 | time=5.4s
Epoch 004 | step 0040/0093 | loss=1.4112 | ce=1.4112 | kd=0.0000 | acc=0.5969 | binary=0.570 | condition=0.962 | count=0.196 | density=0.593 | time=6.1s
Epoch 004 | step 0045/0093 | loss=1.4247 | ce=1.4247 | kd=0.0000 | acc=0.5934 | binary=0.567 | condition=0.963 | count=0.203 | density=0.581 | time=6.8s
Epoch 004 | step 0050/0093 | loss=1.4331 | ce=1.4331 | kd=0.0000 | acc=0.5969 | binary=0.573 | condition=0.960 | count=0.218 | density=0.575 | time=7.5s
Epoch 004 | step 0055/0093 | loss=1.4368 | ce=1.4368 | kd=0.0000 | acc=0.5994 | binary=0.573 | condition=0.958 | count=0.236 | density=0.578 | time=8.2s
Epoch 004 | step 0060/0093 | loss=1.4231 | ce=1.4231 | kd=0.0000 | acc=0.5992 | binary=0.568 | condition=0.957 | count=0.244 | density=0.582 | time=8.8s
Epoch 004 | step 0065/0093 | loss=1.4052 | ce=1.4052 | kd=0.0000 | acc=0.6031 | binary=0.570 | condition=0.960 | count=0.252 | density=0.587 | time=9.5s
Epoch 004 | step 0070/0093 | loss=1.3936 | ce=1.3936 | kd=0.0000 | acc=0.6060 | binary=0.575 | condition=0.959 | count=0.255 | density=0.583 | time=10.1s
Epoch 004 | step 0075/0093 | loss=1.3830 | ce=1.3830 | kd=0.0000 | acc=0.6071 | binary=0.579 | condition=0.959 | count=0.263 | density=0.575 | time=10.9s
Epoch 004 | step 0080/0093 | loss=1.3832 | ce=1.3832 | kd=0.0000 | acc=0.6107 | binary=0.581 | condition=0.958 | count=0.276 | density=0.566 | time=12.0s
Epoch 004 | step 0085/0093 | loss=1.3744 | ce=1.3744 | kd=0.0000 | acc=0.6121 | binary=0.584 | condition=0.957 | count=0.277 | density=0.564 | time=13.0s
Epoch 004 | step 0090/0093 | loss=1.3591 | ce=1.3591 | kd=0.0000 | acc=0.6146 | binary=0.585 | condition=0.957 | count=0.282 | density=0.567 | time=14.2s
Epoch 004 | step 0093/0093 | loss=1.3509 | ce=1.3509 | kd=0.0000 | acc=0.6168 | binary=0.587 | condition=0.957 | count=0.287 | density=0.571 | time=14.4s

train overall: acc=0.6168 (3638/5898)
train macro acc: 0.4207
train count exact: acc=0.2874 (346/1204)
train count ±1: acc=0.3879 (467/1204)
train by edge head:
  binary       acc=0.5866 (1545/2634)
  condition    acc=0.9568 (1416/1480)
  count        acc=0.2874 (346/1204)
  density      acc=0.5707 (331/580)
train by question type:

In [ ]:
#emergency git pull
%cd /content/TinyDisasterVQA

!git status
!git fetch origin
!git pull origin submission

/content/TinyDisasterVQA
On branch submission
Your branch is up to date with 'origin/submission'.

nothing to commit, working tree clean
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Total 7 (delta 5), reused 7 (delta 5), pack-reused 0 (from 0)
Unpacking objects: 100% (7/7), 745 bytes | 186.00 KiB/s, done.
From https://github.com/jacobinsilico/TinyDisasterVQA
   d586ec8..292c332  submission -> origin/submission
From https://github.com/jacobinsilico/TinyDisasterVQA
 * branch            submission -> FETCH_HEAD
Updating d586ec8..292c332
Fast-forward
 scripts/06_train_student.py   |  4 +++-
 src/tinydisastervqa/models.py | 38 +++++++++++++++++++++++++++++++++++++-
 2 files changed, 40 insertions(+), 2 deletions(-)

## S7: TDM-M + KD from T5

In [ ]:
%cd /content/TinyDisasterVQA
%env PYTHONPATH=/content/TinyDisasterVQA/src
%env PYTHONUNBUFFERED=1

!mkdir -p /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10

!python -u scripts/06_train_student.py \
  --dataset-root dataset \
  --runs-dir /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10 \
  --train-csv outputs/training_data_cap5/train.csv \
  --valid-csv outputs/training_data_cap5/valid.csv \
  --test-csv outputs/training_data_cap5/test.csv \
  --metadata outputs/training_data_cap5/metadata.json \
  --class-weights outputs/answer_space_cap5/class_weights_edge_global_by_label.json \
  --image-size 224 \
  --epochs 50 \
  --batch-size 64 \
  --eval-batch-size 64 \
  --num-workers 2 \
  --device auto \
  --patience 8 \
  --min-delta 0.001 \
  --log-interval 5 \
  --student-variant tdm_m \
  --mode kd \
  --teacher-checkpoint "{T5_CHECKPOINT}" \
  --kd-alpha 0.7 \
  --kd-temperature 4.0 \
  --run-name S7_tdm_m_kd_$(date +%Y%m%d_%H%M%S)

/content/TinyDisasterVQA
env: PYTHONPATH=/content/TinyDisasterVQA/src
env: PYTHONUNBUFFERED=1
================================================================================
TinyDisasterVQA / Train TDM Student
================================================================================
Run dir:              /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10/S7_tdm_m_kd_20260610_100303
Device:               cuda
Student variant:      tdm_m
Mode:                 kd
Count cap:            5
Num classes:          14
Question templates:   31
AMP:                  True
Image size:           224
Batch size:           64
Eval batch:           64
Epochs:               50
LR:                   0.0003
Weight decay:         0.0001
Patience:             8
Min delta:            0.001
KD alpha:             0.7
KD temp:              4.0

Model summary
================================================================================
Class:             TDMMVQA
Total params:      46,542
Trainable params:  46,542
FP32 param size:   0.18 MB
Int8 param size:   45.5 KB
Student variant:   tdm_m
Image block type:  dsconv
Image channels:    (16, 32, 64, 96, 128)
Image feature dim: 128
Template encoder:  one_hot + Linear
Template input dim:31
Template emb dim:  24
Fusion hidden dim: 128
Fusion layers:     1
Num classes:       14
Head type:         single edge_global

Loading teacher...
Adapted legacy teacher checkpoint: embedding.weight -> linear.weight/bias
Loaded KD teacher:
  checkpoint:        /content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6/T5_cap5_template_weighted_ce/checkpoints/best.pt
  backbone:          convnext_tiny
  question_encoder:  template
  pretrained:        True
  use_count_aux:     False

Model summary
================================================================================
Class:             TeacherVQA
Total params:      28,418,414
Trainable params:  0
FP32 param size:   108.41 MB
Int8 param size:   27752.4 KB
Image backbone:    convnext_tiny
Pretrained:        True
Image feature dim: 768
Question encoder:  template
Question dim:      128
Num classes:       14
Count aux:         False


================================================================================
Epoch 1/50
================================================================================
Epoch 001 | step 0001/0093 | loss=12.0103 | ce=2.7007 | kd=16.0001 | acc=0.0312 | binary=0.000 | condition=0.000 | count=0.182 | density=0.000 | time=17.5s
Epoch 001 | step 0005/0093 | loss=11.7940 | ce=2.6738 | kd=15.7027 | acc=0.0094 | binary=0.000 | condition=0.000 | count=0.047 | density=0.000 | time=18.0s
Epoch 001 | step 0010/0093 | loss=11.7285 | ce=2.6390 | kd=15.6240 | acc=0.0328 | binary=0.043 | condition=0.007 | count=0.057 | density=0.000 | time=18.8s
Epoch 001 | step 0015/0093 | loss=11.7271 | ce=2.6009 | kd=15.6383 | acc=0.0865 | binary=0.145 | condition=0.045 | count=0.044 | density=0.000 | time=19.5s
Epoch 001 | step 0020/0093 | loss=11.5657 | ce=2.5718 | kd=15.4203 | acc=0.1117 | binary=0.201 | condition=0.058 | count=0.031 | density=0.000 | time=20.3s
Epoch 001 | step 0025/0093 | loss=11.4404 | ce=2.5390 | kd=15.2553 | acc=0.1300 | binary=0.246 | condition=0.054 | count=0.025 | density=0.000 | time=21.1s
Epoch 001 | step 0030/0093 | loss=11.3862 | ce=2.4995 | kd=15.1948 | acc=0.1432 | binary=0.278 | condition=0.053 | count=0.021 | density=0.000 | time=21.9s
Epoch 001 | step 0035/0093 | loss=11.2717 | ce=2.4695 | kd=15.0441 | acc=0.1540 | binary=0.304 | condition=0.053 | count=0.018 | density=0.000 | time=22.7s
Epoch 001 | step 0040/0093 | loss=11.1431 | ce=2.4386 | kd=14.8736 | acc=0.1691 | binary=0.338 | condition=0.054 | count=0.015 | density=0.000 | time=23.4s
Epoch 001 | step 0045/0093 | loss=11.0561 | ce=2.4035 | kd=14.7643 | acc=0.1781 | binary=0.356 | condition=0.057 | count=0.014 | density=0.000 | time=24.2s
Epoch 001 | step 0050/0093 | loss=10.9737 | ce=2.3852 | kd=14.6545 | acc=0.1797 | binary=0.364 | condition=0.057 | count=0.012 | density=0.000 | time=24.9s
Epoch 001 | step 0055/0093 | loss=10.8708 | ce=2.3667 | kd=14.5154 | acc=0.1832 | binary=0.365 | condition=0.072 | count=0.011 | density=0.000 | time=25.7s
Epoch 001 | step 0060/0093 | loss=10.7743 | ce=2.3508 | kd=14.3844 | acc=0.1888 | binary=0.361 | condition=0.100 | count=0.010 | density=0.000 | time=26.4s
Epoch 001 | step 0065/0093 | loss=10.6765 | ce=2.3441 | kd=14.2475 | acc=0.1964 | binary=0.364 | condition=0.123 | count=0.009 | density=0.000 | time=27.4s
Epoch 001 | step 0070/0093 | loss=10.6030 | ce=2.3545 | kd=14.1381 | acc=0.2007 | binary=0.365 | condition=0.144 | count=0.009 | density=0.000 | time=29.0s
Epoch 001 | step 0075/0093 | loss=10.5206 | ce=2.3576 | kd=14.0191 | acc=0.2042 | binary=0.362 | condition=0.163 | count=0.008 | density=0.000 | time=31.1s
Epoch 001 | step 0080/0093 | loss=10.4194 | ce=2.3659 | kd=13.8709 | acc=0.2078 | binary=0.362 | condition=0.178 | count=0.008 | density=0.000 | time=32.8s
Epoch 001 | step 0085/0093 | loss=10.3446 | ce=2.3843 | kd=13.7561 | acc=0.2110 | binary=0.362 | condition=0.191 | count=0.007 | density=0.000 | time=33.8s
Epoch 001 | step 0090/0093 | loss=10.2570 | ce=2.3912 | kd=13.6281 | acc=0.2170 | binary=0.367 | condition=0.206 | count=0.007 | density=0.000 | time=34.5s
Epoch 001 | step 0093/0093 | loss=10.2325 | ce=2.3978 | kd=13.5903 | acc=0.2189 | binary=0.370 | condition=0.209 | count=0.007 | density=0.000 | time=45.7s

train overall: acc=0.2189 (1291/5898)
train macro acc: 0.0728
train count exact: acc=0.0066 (8/1204)
train count ±1: acc=0.0066 (8/1204)
train by edge head:
  binary       acc=0.3698 (974/2634)
  condition    acc=0.2088 (309/1480)
  count        acc=0.0066 (8/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.4138 (240/580)
  Complex_Counting                         acc=0.0064 (4/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.2991 (408/1364)
  Risk_Assessment                          acc=0.2948 (171/580)
  Road_Condition_Recognition               acc=0.2918 (464/1590)
  Simple_Counting                          acc=0.0069 (4/580)

valid overall: acc=0.3422 (618/1806)
valid macro acc: 0.1048
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.5663 (461/814)
  condition    acc=0.3497 (157/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.5170 (91/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.5109 (211/413)
  Risk_Assessment                          acc=0.7784 (137/176)
  Road_Condition_Recognition               acc=0.3594 (179/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 1 done | train_acc=0.2189 | valid_acc=0.3422 | best_valid_acc=0.3422 at epoch 1 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 2/50
================================================================================
Epoch 002 | step 0001/0093 | loss=8.9587 | ce=2.4955 | kd=11.7287 | acc=0.2812 | binary=0.419 | condition=0.312 | count=0.000 | density=0.000 | time=0.5s
Epoch 002 | step 0005/0093 | loss=8.7189 | ce=2.4280 | kd=11.4150 | acc=0.3469 | binary=0.520 | condition=0.398 | count=0.000 | density=0.000 | time=1.1s
Epoch 002 | step 0010/0093 | loss=8.8210 | ce=2.5616 | kd=11.5036 | acc=0.3344 | binary=0.498 | condition=0.418 | count=0.000 | density=0.000 | time=1.9s
Epoch 002 | step 0015/0093 | loss=8.7838 | ce=2.5848 | kd=11.4405 | acc=0.3240 | binary=0.451 | condition=0.457 | count=0.000 | density=0.000 | time=2.7s
Epoch 002 | step 0020/0093 | loss=8.7907 | ce=2.6447 | kd=11.4247 | acc=0.3109 | binary=0.415 | condition=0.482 | count=0.000 | density=0.000 | time=3.6s
Epoch 002 | step 0025/0093 | loss=8.7968 | ce=2.6702 | kd=11.4224 | acc=0.3125 | binary=0.405 | condition=0.518 | count=0.000 | density=0.000 | time=4.4s
Epoch 002 | step 0030/0093 | loss=8.8163 | ce=2.6903 | kd=11.4417 | acc=0.3109 | binary=0.406 | condition=0.520 | count=0.000 | density=0.000 | time=5.2s
Epoch 002 | step 0035/0093 | loss=8.8120 | ce=2.6917 | kd=11.4350 | acc=0.3156 | binary=0.411 | condition=0.530 | count=0.000 | density=0.000 | time=6.0s
Epoch 002 | step 0040/0093 | loss=8.8010 | ce=2.6623 | kd=11.4319 | acc=0.3168 | binary=0.407 | condition=0.536 | count=0.000 | density=0.000 | time=7.3s
Epoch 002 | step 0045/0093 | loss=8.7786 | ce=2.6548 | kd=11.4030 | acc=0.3181 | binary=0.400 | condition=0.558 | count=0.000 | density=0.000 | time=8.5s
Epoch 002 | step 0050/0093 | loss=8.7486 | ce=2.6397 | kd=11.3667 | acc=0.3203 | binary=0.395 | condition=0.569 | count=0.000 | density=0.000 | time=10.1s
Epoch 002 | step 0055/0093 | loss=8.7324 | ce=2.6394 | kd=11.3437 | acc=0.3193 | binary=0.392 | condition=0.574 | count=0.000 | density=0.000 | time=11.2s
Epoch 002 | step 0060/0093 | loss=8.7062 | ce=2.6259 | kd=11.3120 | acc=0.3221 | binary=0.397 | condition=0.573 | count=0.000 | density=0.000 | time=12.2s
Epoch 002 | step 0065/0093 | loss=8.7101 | ce=2.6280 | kd=11.3167 | acc=0.3224 | binary=0.405 | condition=0.562 | count=0.000 | density=0.000 | time=13.0s
Epoch 002 | step 0070/0093 | loss=8.6963 | ce=2.6328 | kd=11.2950 | acc=0.3234 | binary=0.415 | condition=0.548 | count=0.000 | density=0.000 | time=13.8s
Epoch 002 | step 0075/0093 | loss=8.6899 | ce=2.6274 | kd=11.2881 | acc=0.3244 | binary=0.419 | condition=0.544 | count=0.000 | density=0.000 | time=14.7s
Epoch 002 | step 0080/0093 | loss=8.6909 | ce=2.6218 | kd=11.2919 | acc=0.3262 | binary=0.422 | condition=0.549 | count=0.000 | density=0.000 | time=15.5s
Epoch 002 | step 0085/0093 | loss=8.6863 | ce=2.6212 | kd=11.2856 | acc=0.3259 | binary=0.423 | condition=0.550 | count=0.000 | density=0.000 | time=16.3s
Epoch 002 | step 0090/0093 | loss=8.6756 | ce=2.6135 | kd=11.2737 | acc=0.3260 | binary=0.423 | condition=0.548 | count=0.000 | density=0.000 | time=17.0s
Epoch 002 | step 0093/0093 | loss=8.6762 | ce=2.6088 | kd=11.2765 | acc=0.3266 | binary=0.422 | condition=0.551 | count=0.000 | density=0.000 | time=17.3s

train overall: acc=0.3266 (1926/5898)
train macro acc: 0.1057
train count exact: acc=0.0000 (0/1204)
train count ±1: acc=0.0000 (0/1204)
train by edge head:
  binary       acc=0.4218 (1111/2634)
  condition    acc=0.5507 (815/1480)
  count        acc=0.0000 (0/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.5172 (300/580)
  Complex_Counting                         acc=0.0000 (0/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.4758 (649/1364)
  Risk_Assessment                          acc=0.4845 (281/580)
  Road_Condition_Recognition               acc=0.4377 (696/1590)
  Simple_Counting                          acc=0.0000 (0/580)

valid overall: acc=0.4114 (743/1806)
valid macro acc: 0.1339
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.5455 (444/814)
  condition    acc=0.6659 (299/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.6705 (118/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.6199 (256/413)
  Risk_Assessment                          acc=0.5739 (101/176)
  Road_Condition_Recognition               acc=0.5382 (268/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 2 done | train_acc=0.3266 | valid_acc=0.4114 | best_valid_acc=0.4114 at epoch 2 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 3/50
================================================================================
Epoch 003 | step 0001/0093 | loss=8.6369 | ce=2.3612 | kd=11.3265 | acc=0.3594 | binary=0.423 | condition=0.600 | count=0.000 | density=0.000 | time=0.7s
Epoch 003 | step 0005/0093 | loss=8.4977 | ce=2.4321 | kd=11.0972 | acc=0.3500 | binary=0.421 | condition=0.616 | count=0.000 | density=0.000 | time=1.8s
Epoch 003 | step 0010/0093 | loss=8.5939 | ce=2.4664 | kd=11.2199 | acc=0.3594 | binary=0.430 | condition=0.638 | count=0.000 | density=0.000 | time=3.0s
Epoch 003 | step 0015/0093 | loss=8.5017 | ce=2.4474 | kd=11.0964 | acc=0.3688 | binary=0.439 | condition=0.665 | count=0.000 | density=0.000 | time=4.2s
Epoch 003 | step 0020/0093 | loss=8.3815 | ce=2.4095 | kd=10.9409 | acc=0.3688 | binary=0.419 | condition=0.686 | count=0.000 | density=0.000 | time=5.3s
Epoch 003 | step 0025/0093 | loss=8.4564 | ce=2.4561 | kd=11.0280 | acc=0.3625 | binary=0.413 | condition=0.690 | count=0.000 | density=0.000 | time=6.2s
Epoch 003 | step 0030/0093 | loss=8.4072 | ce=2.4276 | kd=10.9699 | acc=0.3646 | binary=0.410 | condition=0.704 | count=0.000 | density=0.000 | time=7.1s
Epoch 003 | step 0035/0093 | loss=8.3896 | ce=2.4395 | kd=10.9397 | acc=0.3701 | binary=0.418 | condition=0.720 | count=0.000 | density=0.000 | time=8.0s
Epoch 003 | step 0040/0093 | loss=8.3436 | ce=2.4088 | kd=10.8872 | acc=0.3711 | binary=0.419 | condition=0.714 | count=0.000 | density=0.000 | time=8.8s
Epoch 003 | step 0045/0093 | loss=8.3335 | ce=2.4290 | kd=10.8640 | acc=0.3663 | binary=0.410 | condition=0.714 | count=0.000 | density=0.000 | time=9.6s
Epoch 003 | step 0050/0093 | loss=8.2932 | ce=2.4113 | kd=10.8141 | acc=0.3703 | binary=0.418 | condition=0.714 | count=0.000 | density=0.000 | time=10.3s
Epoch 003 | step 0055/0093 | loss=8.2861 | ce=2.4198 | kd=10.8002 | acc=0.3716 | binary=0.426 | condition=0.712 | count=0.000 | density=0.000 | time=11.1s
Epoch 003 | step 0060/0093 | loss=8.2905 | ce=2.4196 | kd=10.8065 | acc=0.3732 | binary=0.434 | condition=0.712 | count=0.000 | density=0.000 | time=11.9s
Epoch 003 | step 0065/0093 | loss=8.2683 | ce=2.4133 | kd=10.7776 | acc=0.3721 | binary=0.434 | condition=0.711 | count=0.000 | density=0.000 | time=12.7s
Epoch 003 | step 0070/0093 | loss=8.2312 | ce=2.3969 | kd=10.7316 | acc=0.3761 | binary=0.442 | condition=0.713 | count=0.000 | density=0.000 | time=13.4s
Epoch 003 | step 0075/0093 | loss=8.1960 | ce=2.3777 | kd=10.6895 | acc=0.3781 | binary=0.444 | condition=0.715 | count=0.000 | density=0.000 | time=14.2s
Epoch 003 | step 0080/0093 | loss=8.1787 | ce=2.3746 | kd=10.6662 | acc=0.3814 | binary=0.453 | condition=0.715 | count=0.000 | density=0.000 | time=15.0s
Epoch 003 | step 0085/0093 | loss=8.1590 | ce=2.3664 | kd=10.6415 | acc=0.3824 | binary=0.455 | condition=0.714 | count=0.000 | density=0.000 | time=15.9s
Epoch 003 | step 0090/0093 | loss=8.1470 | ce=2.3667 | kd=10.6242 | acc=0.3847 | binary=0.462 | condition=0.711 | count=0.000 | density=0.000 | time=17.0s
Epoch 003 | step 0093/0093 | loss=8.1399 | ce=2.3640 | kd=10.6152 | acc=0.3859 | binary=0.465 | condition=0.710 | count=0.000 | density=0.000 | time=17.3s

train overall: acc=0.3859 (2276/5898)
train macro acc: 0.1254
train count exact: acc=0.0000 (0/1204)
train count ±1: acc=0.0000 (0/1204)
train by edge head:
  binary       acc=0.4651 (1225/2634)
  condition    acc=0.7101 (1051/1480)
  count        acc=0.0000 (0/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.5241 (304/580)
  Complex_Counting                         acc=0.0000 (0/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.5975 (815/1364)
  Risk_Assessment                          acc=0.4897 (284/580)
  Road_Condition_Recognition               acc=0.5491 (873/1590)
  Simple_Counting                          acc=0.0000 (0/580)

valid overall: acc=0.4767 (861/1806)
valid macro acc: 0.1541
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.6400 (521/814)
  condition    acc=0.7572 (340/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.6875 (121/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.7191 (297/413)
  Risk_Assessment                          acc=0.7102 (125/176)
  Road_Condition_Recognition               acc=0.6386 (318/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 3 done | train_acc=0.3859 | valid_acc=0.4767 | best_valid_acc=0.4767 at epoch 3 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 4/50
================================================================================
Epoch 004 | step 0001/0093 | loss=7.5920 | ce=1.7801 | kd=10.0828 | acc=0.5781 | binary=0.636 | condition=0.842 | count=0.000 | time=0.4s
Epoch 004 | step 0005/0093 | loss=7.6407 | ce=2.1460 | kd=9.9956 | acc=0.4594 | binary=0.550 | condition=0.778 | count=0.000 | density=0.000 | time=1.1s
Epoch 004 | step 0010/0093 | loss=7.6940 | ce=2.2126 | kd=10.0432 | acc=0.4375 | binary=0.540 | condition=0.788 | count=0.000 | density=0.000 | time=1.9s
Epoch 004 | step 0015/0093 | loss=7.5848 | ce=2.1695 | kd=9.9057 | acc=0.4333 | binary=0.522 | condition=0.792 | count=0.000 | density=0.000 | time=2.6s
Epoch 004 | step 0020/0093 | loss=7.6223 | ce=2.2140 | kd=9.9402 | acc=0.4281 | binary=0.533 | condition=0.778 | count=0.000 | density=0.000 | time=3.4s
Epoch 004 | step 0025/0093 | loss=7.6139 | ce=2.1956 | kd=9.9361 | acc=0.4325 | binary=0.540 | condition=0.771 | count=0.000 | density=0.000 | time=4.2s
Epoch 004 | step 0030/0093 | loss=7.5768 | ce=2.1895 | kd=9.8857 | acc=0.4339 | binary=0.537 | condition=0.783 | count=0.000 | density=0.000 | time=5.0s
Epoch 004 | step 0035/0093 | loss=7.5698 | ce=2.2063 | kd=9.8685 | acc=0.4313 | binary=0.536 | condition=0.783 | count=0.000 | density=0.000 | time=5.8s
Epoch 004 | step 0040/0093 | loss=7.5381 | ce=2.1790 | kd=9.8348 | acc=0.4410 | binary=0.549 | condition=0.790 | count=0.000 | density=0.000 | time=6.6s
Epoch 004 | step 0045/0093 | loss=7.5077 | ce=2.1738 | kd=9.7936 | acc=0.4410 | binary=0.555 | condition=0.784 | count=0.000 | density=0.000 | time=7.3s
Epoch 004 | step 0050/0093 | loss=7.4597 | ce=2.1440 | kd=9.7379 | acc=0.4453 | binary=0.561 | condition=0.788 | count=0.000 | density=0.000 | time=8.1s
Epoch 004 | step 0055/0093 | loss=7.4432 | ce=2.1310 | kd=9.7198 | acc=0.4486 | binary=0.568 | condition=0.784 | count=0.000 | density=0.000 | time=9.1s
Epoch 004 | step 0060/0093 | loss=7.4351 | ce=2.1354 | kd=9.7064 | acc=0.4492 | binary=0.573 | condition=0.786 | count=0.000 | density=0.000 | time=10.3s
Epoch 004 | step 0065/0093 | loss=7.4048 | ce=2.1301 | kd=9.6654 | acc=0.4450 | binary=0.567 | condition=0.787 | count=0.000 | density=0.000 | time=11.5s
Epoch 004 | step 0070/0093 | loss=7.3373 | ce=2.1030 | kd=9.5806 | acc=0.4446 | binary=0.559 | condition=0.792 | count=0.000 | density=0.000 | time=12.7s
Epoch 004 | step 0075/0093 | loss=7.2942 | ce=2.0799 | kd=9.5289 | acc=0.4523 | binary=0.570 | condition=0.799 | count=0.000 | density=0.000 | time=13.7s
Epoch 004 | step 0080/0093 | loss=7.2515 | ce=2.0580 | kd=9.4772 | acc=0.4590 | binary=0.581 | condition=0.798 | count=0.000 | density=0.000 | time=14.5s
Epoch 004 | step 0085/0093 | loss=7.2193 | ce=2.0508 | kd=9.4344 | acc=0.4616 | binary=0.586 | condition=0.799 | count=0.000 | density=0.000 | time=15.3s
Epoch 004 | step 0090/0093 | loss=7.2036 | ce=2.0513 | kd=9.4117 | acc=0.4613 | binary=0.584 | condition=0.801 | count=0.000 | density=0.000 | time=16.1s

## S8: TDM-M + KD from T6

In [ ]:
%cd /content/TinyDisasterVQA
%env PYTHONPATH=/content/TinyDisasterVQA/src
%env PYTHONUNBUFFERED=1

!mkdir -p /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10

!python -u scripts/06_train_student.py \
  --dataset-root dataset \
  --runs-dir /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10 \
  --train-csv outputs/training_data_cap5/train.csv \
  --valid-csv outputs/training_data_cap5/valid.csv \
  --test-csv outputs/training_data_cap5/test.csv \
  --metadata outputs/training_data_cap5/metadata.json \
  --class-weights outputs/answer_space_cap5/class_weights_edge_global_by_label.json \
  --image-size 224 \
  --epochs 50 \
  --batch-size 64 \
  --eval-batch-size 64 \
  --num-workers 2 \
  --device auto \
  --patience 8 \
  --min-delta 0.001 \
  --log-interval 5 \
  --student-variant tdm_m \
  --mode kd \
  --teacher-checkpoint "{T6_CHECKPOINT}" \
  --kd-alpha 0.7 \
  --kd-temperature 4.0 \
  --run-name S8_tdm_m_kd_$(date +%Y%m%d_%H%M%S)

/content/TinyDisasterVQA
env: PYTHONPATH=/content/TinyDisasterVQA/src
env: PYTHONUNBUFFERED=1
================================================================================
TinyDisasterVQA / Train TDM Student
================================================================================
Run dir:              /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10/S8_tdm_m_kd_20260610_101614
Device:               cuda
Student variant:      tdm_m
Mode:                 kd
Count cap:            5
Num classes:          14
Question templates:   31
AMP:                  True
Image size:           224
Batch size:           64
Eval batch:           64
Epochs:               50
LR:                   0.0003
Weight decay:         0.0001
Patience:             8
Min delta:            0.001
KD alpha:             0.7
KD temp:              4.0

Model summary
================================================================================
Class:             TDMMVQA
Total params:      46,542
Trainable params:  46,542
FP32 param size:   0.18 MB
Int8 param size:   45.5 KB
Student variant:   tdm_m
Image block type:  dsconv
Image channels:    (16, 32, 64, 96, 128)
Image feature dim: 128
Template encoder:  one_hot + Linear
Template input dim:31
Template emb dim:  24
Fusion hidden dim: 128
Fusion layers:     1
Num classes:       14
Head type:         single edge_global

Loading teacher...
Adapted legacy teacher checkpoint: embedding.weight -> linear.weight/bias
Loaded KD teacher:
  checkpoint:        /content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6/T6_cap5_template_count_aux/checkpoints/best.pt
  backbone:          convnext_tiny
  question_encoder:  template
  pretrained:        True
  use_count_aux:     True

Model summary
================================================================================
Class:             TeacherVQA
Total params:      28,649,588
Trainable params:  0
FP32 param size:   109.29 MB
Int8 param size:   27978.1 KB
Image backbone:    convnext_tiny
Pretrained:        True
Image feature dim: 768
Question encoder:  template
Question dim:      128
Num classes:       14
Count aux:         True
Count classes:     6


================================================================================
Epoch 1/50
================================================================================
Epoch 001 | step 0001/0093 | loss=14.2890 | ce=2.6956 | kd=19.2576 | acc=0.0000 | binary=0.000 | condition=0.000 | count=0.000 | density=0.000 | time=16.4s
Epoch 001 | step 0005/0093 | loss=14.5724 | ce=2.6667 | kd=19.6749 | acc=0.0156 | binary=0.000 | condition=0.012 | count=0.059 | density=0.000 | time=16.9s
Epoch 001 | step 0010/0093 | loss=14.3895 | ce=2.6319 | kd=19.4285 | acc=0.0609 | binary=0.011 | condition=0.120 | count=0.120 | density=0.000 | time=17.7s
Epoch 001 | step 0015/0093 | loss=14.3995 | ce=2.6000 | kd=19.4564 | acc=0.1187 | binary=0.060 | condition=0.307 | count=0.092 | density=0.000 | time=18.5s
Epoch 001 | step 0020/0093 | loss=14.3959 | ce=2.5667 | kd=19.4655 | acc=0.1453 | binary=0.075 | condition=0.404 | count=0.070 | density=0.000 | time=19.2s
Epoch 001 | step 0025/0093 | loss=14.4176 | ce=2.5315 | kd=19.5117 | acc=0.1706 | binary=0.095 | condition=0.482 | count=0.059 | density=0.000 | time=20.0s
Epoch 001 | step 0030/0093 | loss=14.3650 | ce=2.4971 | kd=19.4513 | acc=0.1844 | binary=0.105 | condition=0.512 | count=0.050 | density=0.000 | time=20.9s
Epoch 001 | step 0035/0093 | loss=14.2461 | ce=2.4671 | kd=19.2943 | acc=0.1924 | binary=0.109 | condition=0.544 | count=0.043 | density=0.000 | time=21.7s
Epoch 001 | step 0040/0093 | loss=14.1071 | ce=2.4337 | kd=19.1100 | acc=0.1949 | binary=0.098 | condition=0.576 | count=0.038 | density=0.000 | time=22.4s
Epoch 001 | step 0045/0093 | loss=14.0138 | ce=2.4048 | kd=18.9890 | acc=0.1990 | binary=0.094 | condition=0.603 | count=0.034 | density=0.000 | time=23.3s
Epoch 001 | step 0050/0093 | loss=13.8824 | ce=2.3809 | kd=18.8115 | acc=0.2034 | binary=0.090 | condition=0.624 | count=0.030 | density=0.000 | time=24.2s
Epoch 001 | step 0055/0093 | loss=13.7542 | ce=2.3582 | kd=18.6382 | acc=0.2088 | binary=0.089 | condition=0.645 | count=0.028 | density=0.000 | time=25.4s
Epoch 001 | step 0060/0093 | loss=13.6116 | ce=2.3529 | kd=18.4368 | acc=0.2102 | binary=0.086 | condition=0.660 | count=0.025 | density=0.000 | time=26.5s
Epoch 001 | step 0065/0093 | loss=13.4862 | ce=2.3487 | kd=18.2594 | acc=0.2139 | binary=0.089 | condition=0.674 | count=0.023 | density=0.000 | time=27.9s
Epoch 001 | step 0070/0093 | loss=13.3647 | ce=2.3509 | kd=18.0850 | acc=0.2172 | binary=0.091 | condition=0.684 | count=0.022 | density=0.000 | time=28.8s
Epoch 001 | step 0075/0093 | loss=13.2473 | ce=2.3647 | kd=17.9113 | acc=0.2219 | binary=0.096 | condition=0.695 | count=0.020 | density=0.000 | time=29.7s
Epoch 001 | step 0080/0093 | loss=13.1048 | ce=2.3803 | kd=17.7010 | acc=0.2260 | binary=0.102 | condition=0.698 | count=0.019 | density=0.000 | time=30.5s
Epoch 001 | step 0085/0093 | loss=13.0034 | ce=2.3982 | kd=17.5485 | acc=0.2285 | binary=0.108 | condition=0.700 | count=0.018 | density=0.000 | time=31.3s
Epoch 001 | step 0090/0093 | loss=12.9086 | ce=2.4119 | kd=17.4072 | acc=0.2342 | binary=0.122 | condition=0.701 | count=0.017 | density=0.000 | time=32.0s
Epoch 001 | step 0093/0093 | loss=12.8662 | ce=2.4236 | kd=17.3416 | acc=0.2353 | binary=0.128 | condition=0.696 | count=0.017 | density=0.000 | time=43.2s

train overall: acc=0.2353 (1388/5898)
train macro acc: 0.0920
train count exact: acc=0.0166 (20/1204)
train count ±1: acc=0.0174 (21/1204)
train by edge head:
  binary       acc=0.1283 (338/2634)
  condition    acc=0.6959 (1030/1480)
  count        acc=0.0166 (20/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.1379 (80/580)
  Complex_Counting                         acc=0.0224 (14/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.4399 (600/1364)
  Risk_Assessment                          acc=0.1586 (92/580)
  Road_Condition_Recognition               acc=0.3748 (596/1590)
  Simple_Counting                          acc=0.0103 (6/580)

valid overall: acc=0.3643 (658/1806)
valid macro acc: 0.1119
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.5123 (417/814)
  condition    acc=0.5367 (241/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.4261 (75/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.5714 (236/413)
  Risk_Assessment                          acc=0.7386 (130/176)
  Road_Condition_Recognition               acc=0.4357 (217/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 1 done | train_acc=0.2353 | valid_acc=0.3643 | best_valid_acc=0.3643 at epoch 1 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 2/50
================================================================================
Epoch 002 | step 0001/0093 | loss=10.6239 | ce=2.6525 | kd=14.0402 | acc=0.3750 | binary=0.417 | condition=0.636 | count=0.000 | density=0.000 | time=0.5s
Epoch 002 | step 0005/0093 | loss=10.9798 | ce=2.9301 | kd=14.4296 | acc=0.3063 | binary=0.419 | condition=0.512 | count=0.000 | density=0.000 | time=1.1s
Epoch 002 | step 0010/0093 | loss=11.0232 | ce=2.9932 | kd=14.4646 | acc=0.3109 | binary=0.436 | condition=0.503 | count=0.000 | density=0.000 | time=1.8s
Epoch 002 | step 0015/0093 | loss=10.9604 | ce=2.9498 | kd=14.3935 | acc=0.3042 | binary=0.438 | condition=0.454 | count=0.000 | density=0.000 | time=2.6s
Epoch 002 | step 0020/0093 | loss=10.9090 | ce=2.9016 | kd=14.3407 | acc=0.3016 | binary=0.423 | condition=0.444 | count=0.000 | density=0.000 | time=3.4s
Epoch 002 | step 0025/0093 | loss=10.8888 | ce=2.9235 | kd=14.3026 | acc=0.2963 | binary=0.413 | condition=0.446 | count=0.000 | density=0.000 | time=4.3s
Epoch 002 | step 0030/0093 | loss=10.8544 | ce=2.9167 | kd=14.2562 | acc=0.3016 | binary=0.419 | condition=0.454 | count=0.000 | density=0.000 | time=5.1s
Epoch 002 | step 0035/0093 | loss=10.8383 | ce=2.9113 | kd=14.2356 | acc=0.3067 | binary=0.423 | condition=0.463 | count=0.000 | density=0.000 | time=6.0s
Epoch 002 | step 0040/0093 | loss=10.8637 | ce=2.9268 | kd=14.2652 | acc=0.3098 | binary=0.431 | condition=0.467 | count=0.000 | density=0.000 | time=7.1s
Epoch 002 | step 0045/0093 | loss=10.8610 | ce=2.9348 | kd=14.2580 | acc=0.3073 | binary=0.425 | condition=0.475 | count=0.000 | density=0.000 | time=8.2s
Epoch 002 | step 0050/0093 | loss=10.8562 | ce=2.9297 | kd=14.2532 | acc=0.3094 | binary=0.420 | condition=0.493 | count=0.000 | density=0.000 | time=9.6s
Epoch 002 | step 0055/0093 | loss=10.8519 | ce=2.9501 | kd=14.2384 | acc=0.3091 | binary=0.419 | condition=0.501 | count=0.000 | density=0.000 | time=10.7s
Epoch 002 | step 0060/0093 | loss=10.8302 | ce=2.9269 | kd=14.2174 | acc=0.3086 | binary=0.415 | condition=0.505 | count=0.000 | density=0.000 | time=11.5s
Epoch 002 | step 0065/0093 | loss=10.8239 | ce=2.9082 | kd=14.2164 | acc=0.3151 | binary=0.422 | condition=0.512 | count=0.000 | density=0.000 | time=12.3s
Epoch 002 | step 0070/0093 | loss=10.8094 | ce=2.8926 | kd=14.2024 | acc=0.3176 | binary=0.417 | condition=0.529 | count=0.000 | density=0.000 | time=13.1s
Epoch 002 | step 0075/0093 | loss=10.8023 | ce=2.8830 | kd=14.1963 | acc=0.3185 | binary=0.411 | condition=0.543 | count=0.000 | density=0.000 | time=13.9s
Epoch 002 | step 0080/0093 | loss=10.7740 | ce=2.8706 | kd=14.1612 | acc=0.3232 | binary=0.410 | condition=0.559 | count=0.000 | density=0.000 | time=14.7s
Epoch 002 | step 0085/0093 | loss=10.7618 | ce=2.8713 | kd=14.1435 | acc=0.3237 | binary=0.403 | condition=0.573 | count=0.000 | density=0.000 | time=15.5s
Epoch 002 | step 0090/0093 | loss=10.7639 | ce=2.8658 | kd=14.1488 | acc=0.3210 | binary=0.395 | condition=0.579 | count=0.000 | density=0.000 | time=16.2s
Epoch 002 | step 0093/0093 | loss=10.7519 | ce=2.8557 | kd=14.1360 | acc=0.3218 | binary=0.393 | condition=0.583 | count=0.000 | density=0.000 | time=16.5s

train overall: acc=0.3218 (1898/5898)
train macro acc: 0.1029
train count exact: acc=0.0000 (0/1204)
train count ±1: acc=0.0000 (0/1204)
train by edge head:
  binary       acc=0.3929 (1035/2634)
  condition    acc=0.5831 (863/1480)
  count        acc=0.0000 (0/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.3724 (216/580)
  Complex_Counting                         acc=0.0000 (0/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.4971 (678/1364)
  Risk_Assessment                          acc=0.5448 (316/580)
  Road_Condition_Recognition               acc=0.4327 (688/1590)
  Simple_Counting                          acc=0.0000 (0/580)

valid overall: acc=0.3555 (642/1806)
valid macro acc: 0.1125
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.3575 (291/814)
  condition    acc=0.7817 (351/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.3523 (62/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.5811 (240/413)
  Risk_Assessment                          acc=0.5682 (100/176)
  Road_Condition_Recognition               acc=0.4819 (240/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 2 done | train_acc=0.3218 | valid_acc=0.3555 | best_valid_acc=0.3643 at epoch 1 | no_improve=1/8 | no improvement

================================================================================
Epoch 3/50
================================================================================
Epoch 003 | step 0001/0093 | loss=10.3902 | ce=2.6364 | kd=13.7133 | acc=0.3438 | binary=0.333 | condition=0.786 | count=0.000 | density=0.000 | time=0.5s
Epoch 003 | step 0005/0093 | loss=10.6056 | ce=2.7728 | kd=13.9625 | acc=0.3312 | binary=0.318 | condition=0.841 | count=0.000 | density=0.000 | time=1.2s
Epoch 003 | step 0010/0093 | loss=10.5485 | ce=2.7382 | kd=13.8958 | acc=0.3703 | binary=0.392 | condition=0.773 | count=0.000 | density=0.000 | time=2.2s
Epoch 003 | step 0015/0093 | loss=10.3520 | ce=2.7140 | kd=13.6255 | acc=0.3656 | binary=0.391 | condition=0.750 | count=0.000 | density=0.000 | time=3.6s
Epoch 003 | step 0020/0093 | loss=10.3805 | ce=2.7283 | kd=13.6601 | acc=0.3633 | binary=0.397 | condition=0.749 | count=0.000 | density=0.000 | time=4.8s
Epoch 003 | step 0025/0093 | loss=10.4067 | ce=2.7523 | kd=13.6871 | acc=0.3619 | binary=0.402 | condition=0.742 | count=0.000 | density=0.000 | time=5.9s
Epoch 003 | step 0030/0093 | loss=10.4780 | ce=2.7703 | kd=13.7813 | acc=0.3604 | binary=0.410 | condition=0.724 | count=0.000 | density=0.000 | time=6.7s
Epoch 003 | step 0035/0093 | loss=10.4498 | ce=2.7733 | kd=13.7397 | acc=0.3603 | binary=0.422 | condition=0.717 | count=0.000 | density=0.000 | time=7.4s
Epoch 003 | step 0040/0093 | loss=10.4120 | ce=2.7570 | kd=13.6928 | acc=0.3613 | binary=0.429 | condition=0.705 | count=0.000 | density=0.000 | time=8.2s
Epoch 003 | step 0045/0093 | loss=10.3884 | ce=2.7338 | kd=13.6689 | acc=0.3632 | binary=0.432 | condition=0.707 | count=0.000 | density=0.000 | time=9.1s
Epoch 003 | step 0050/0093 | loss=10.3750 | ce=2.7078 | kd=13.6610 | acc=0.3669 | binary=0.438 | condition=0.710 | count=0.000 | density=0.000 | time=9.9s
Epoch 003 | step 0055/0093 | loss=10.3467 | ce=2.6905 | kd=13.6278 | acc=0.3702 | binary=0.441 | condition=0.714 | count=0.000 | density=0.000 | time=10.6s
Epoch 003 | step 0060/0093 | loss=10.3013 | ce=2.6544 | kd=13.5785 | acc=0.3745 | binary=0.445 | condition=0.712 | count=0.000 | density=0.000 | time=11.5s
Epoch 003 | step 0065/0093 | loss=10.2829 | ce=2.6346 | kd=13.5607 | acc=0.3791 | binary=0.447 | condition=0.718 | count=0.000 | density=0.000 | time=12.2s
Epoch 003 | step 0070/0093 | loss=10.2929 | ce=2.6506 | kd=13.5682 | acc=0.3781 | binary=0.443 | condition=0.721 | count=0.000 | density=0.000 | time=13.0s
Epoch 003 | step 0075/0093 | loss=10.2774 | ce=2.6477 | kd=13.5473 | acc=0.3779 | binary=0.438 | condition=0.727 | count=0.000 | density=0.000 | time=13.8s
Epoch 003 | step 0080/0093 | loss=10.2593 | ce=2.6484 | kd=13.5211 | acc=0.3785 | binary=0.436 | condition=0.730 | count=0.000 | density=0.000 | time=14.6s
Epoch 003 | step 0085/0093 | loss=10.2521 | ce=2.6558 | kd=13.5077 | acc=0.3767 | binary=0.433 | condition=0.733 | count=0.000 | density=0.000 | time=15.5s
Epoch 003 | step 0090/0093 | loss=10.2352 | ce=2.6589 | kd=13.4822 | acc=0.3774 | binary=0.434 | condition=0.735 | count=0.000 | density=0.000 | time=16.5s
Epoch 003 | step 0093/0093 | loss=10.2212 | ce=2.6518 | kd=13.4652 | acc=0.3788 | binary=0.434 | condition=0.736 | count=0.000 | density=0.000 | time=16.8s

train overall: acc=0.3788 (2234/5898)
train macro acc: 0.1218
train count exact: acc=0.0000 (0/1204)
train count ±1: acc=0.0000 (0/1204)
train by edge head:
  binary       acc=0.4343 (1144/2634)
  condition    acc=0.7365 (1090/1480)
  count        acc=0.0000 (0/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.4362 (253/580)
  Complex_Counting                         acc=0.0000 (0/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.5946 (811/1364)
  Risk_Assessment                          acc=0.5690 (330/580)
  Road_Condition_Recognition               acc=0.5283 (840/1590)
  Simple_Counting                          acc=0.0000 (0/580)

valid overall: acc=0.3882 (701/1806)
valid macro acc: 0.1224
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.4177 (340/814)
  condition    acc=0.8040 (361/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.3864 (68/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.6174 (255/413)
  Risk_Assessment                          acc=0.6477 (114/176)
  Road_Condition_Recognition               acc=0.5301 (264/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 3 done | train_acc=0.3788 | valid_acc=0.3882 | best_valid_acc=0.3882 at epoch 3 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 4/50
================================================================================
Epoch 004 | step 0001/0093 | loss=9.5720 | ce=2.4143 | kd=12.6395 | acc=0.4219 | binary=0.464 | condition=0.778 | count=0.000 | density=0.000 | time=0.4s
Epoch 004 | step 0005/0093 | loss=9.5350 | ce=2.4639 | kd=12.5655 | acc=0.4062 | binary=0.439 | condition=0.793 | count=0.000 | density=0.000 | time=1.1s
Epoch 004 | step 0010/0093 | loss=9.4826 | ce=2.3614 | kd=12.5345 | acc=0.4359 | binary=0.480 | condition=0.791 | count=0.000 | density=0.000 | time=1.8s
Epoch 004 | step 0015/0093 | loss=9.5529 | ce=2.3952 | kd=12.6204 | acc=0.4323 | binary=0.495 | condition=0.783 | count=0.000 | density=0.000 | time=2.7s
Epoch 004 | step 0020/0093 | loss=9.6317 | ce=2.4261 | kd=12.7198 | acc=0.4305 | binary=0.500 | condition=0.775 | count=0.000 | density=0.000 | time=3.5s
Epoch 004 | step 0025/0093 | loss=9.6177 | ce=2.4161 | kd=12.7041 | acc=0.4338 | binary=0.503 | condition=0.779 | count=0.000 | density=0.000 | time=4.4s
Epoch 004 | step 0030/0093 | loss=9.6508 | ce=2.4167 | kd=12.7511 | acc=0.4385 | binary=0.512 | condition=0.789 | count=0.000 | density=0.000 | time=5.2s
Epoch 004 | step 0035/0093 | loss=9.6500 | ce=2.4242 | kd=12.7468 | acc=0.4348 | binary=0.506 | condition=0.792 | count=0.000 | density=0.000 | time=6.0s
Epoch 004 | step 0040/0093 | loss=9.6238 | ce=2.4281 | kd=12.7077 | acc=0.4313 | binary=0.501 | condition=0.800 | count=0.000 | density=0.000 | time=6.8s
Epoch 004 | step 0045/0093 | loss=9.6191 | ce=2.4323 | kd=12.6992 | acc=0.4302 | binary=0.502 | condition=0.808 | count=0.000 | density=0.000 | time=7.6s
Epoch 004 | step 0050/0093 | loss=9.5371 | ce=2.4143 | kd=12.5897 | acc=0.4281 | binary=0.497 | condition=0.805 | count=0.000 | density=0.000 | time=8.4s
Epoch 004 | step 0055/0093 | loss=9.5024 | ce=2.4143 | kd=12.5401 | acc=0.4313 | binary=0.504 | condition=0.806 | count=0.000 | density=0.000 | time=9.2s
Epoch 004 | step 0060/0093 | loss=9.5397 | ce=2.4361 | kd=12.5841 | acc=0.4313 | binary=0.513 | condition=0.803 | count=0.000 | density=0.000 | time=10.4s
Epoch 004 | step 0065/0093 | loss=9.4932 | ce=2.4085 | kd=12.5295 | acc=0.4337 | binary=0.515 | condition=0.802 | count=0.000 | density=0.000 | time=11.7s
Epoch 004 | step 0070/0093 | loss=9.4597 | ce=2.4007 | kd=12.4850 | acc=0.4353 | binary=0.517 | condition=0.804 | count=0.000 | density=0.000 | time=12.8s
Epoch 004 | step 0075/0093 | loss=9.4278 | ce=2.3948 | kd=12.4419 | acc=0.4358 | binary=0.518 | condition=0.803 | count=0.000 | density=0.000 | time=14.0s
Epoch 004 | step 0080/0093 | loss=9.3799 | ce=2.3787 | kd=12.3804 | acc=0.4379 | binary=0.521 | condition=0.805 | count=0.000 | density=0.000 | time=14.8s
Epoch 004 | step 0085/0093 | loss=9.3497 | ce=2.3777 | kd=12.3378 | acc=0.4393 | binary=0.528 | condition=0.806 | count=0.000 | density=0.000 | time=15.6s

## S9: TDM-L + KD from T5

In [ ]:
%cd /content/TinyDisasterVQA
%env PYTHONPATH=/content/TinyDisasterVQA/src
%env PYTHONUNBUFFERED=1

!mkdir -p /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10

!python -u scripts/06_train_student.py \
  --dataset-root dataset \
  --runs-dir /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10 \
  --train-csv outputs/training_data_cap5/train.csv \
  --valid-csv outputs/training_data_cap5/valid.csv \
  --test-csv outputs/training_data_cap5/test.csv \
  --metadata outputs/training_data_cap5/metadata.json \
  --class-weights outputs/answer_space_cap5/class_weights_edge_global_by_label.json \
  --image-size 224 \
  --epochs 50 \
  --batch-size 64 \
  --eval-batch-size 64 \
  --num-workers 2 \
  --device auto \
  --patience 8 \
  --min-delta 0.001 \
  --log-interval 5 \
  --student-variant tdm_l \
  --mode kd \
  --teacher-checkpoint "{T5_CHECKPOINT}" \
  --kd-alpha 0.7 \
  --kd-temperature 4.0 \
  --run-name S9_tdm_l_kd_$(date +%Y%m%d_%H%M%S)

/content/TinyDisasterVQA
env: PYTHONPATH=/content/TinyDisasterVQA/src
env: PYTHONUNBUFFERED=1
================================================================================
TinyDisasterVQA / Train TDM Student
================================================================================
Run dir:              /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10/S9_tdm_l_kd_20260610_103020
Device:               cuda
Student variant:      tdm_l
Mode:                 kd
Count cap:            5
Num classes:          14
Question templates:   31
AMP:                  True
Image size:           224
Batch size:           64
Eval batch:           64
Epochs:               50
LR:                   0.0003
Weight decay:         0.0001
Patience:             8
Min delta:            0.001
KD alpha:             0.7
KD temp:              4.0

Model summary
================================================================================
Class:             TDMLVQA
Total params:      101,310
Trainable params:  101,310
FP32 param size:   0.39 MB
Int8 param size:   98.9 KB
Student variant:   tdm_l
Image block type:  dsconv
Image channels:    (24, 48, 96, 128, 160)
Image feature dim: 160
Template encoder:  one_hot + Linear
Template input dim:31
Template emb dim:  32
Fusion hidden dim: 192
Fusion layers:     2
Num classes:       14
Head type:         single edge_global

Loading teacher...
Adapted legacy teacher checkpoint: embedding.weight -> linear.weight/bias
Loaded KD teacher:
  checkpoint:        /content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6/T5_cap5_template_weighted_ce/checkpoints/best.pt
  backbone:          convnext_tiny
  question_encoder:  template
  pretrained:        True
  use_count_aux:     False

Model summary
================================================================================
Class:             TeacherVQA
Total params:      28,418,414
Trainable params:  0
FP32 param size:   108.41 MB
Int8 param size:   27752.4 KB
Image backbone:    convnext_tiny
Pretrained:        True
Image feature dim: 768
Question encoder:  template
Question dim:      128
Num classes:       14
Count aux:         False


================================================================================
Epoch 1/50
================================================================================
Epoch 001 | step 0001/0093 | loss=12.0331 | ce=2.6723 | kd=16.0448 | acc=0.0000 | binary=0.000 | condition=0.000 | count=0.000 | density=0.000 | time=12.9s
Epoch 001 | step 0005/0093 | loss=11.6906 | ce=2.6560 | kd=15.5626 | acc=0.0281 | binary=0.008 | condition=0.000 | count=0.027 | density=0.146 | time=13.5s
Epoch 001 | step 0010/0093 | loss=11.6327 | ce=2.6299 | kd=15.4910 | acc=0.1078 | binary=0.207 | condition=0.000 | count=0.043 | density=0.099 | time=14.6s
Epoch 001 | step 0015/0093 | loss=11.5697 | ce=2.6045 | kd=15.4119 | acc=0.1500 | binary=0.320 | condition=0.000 | count=0.030 | density=0.065 | time=15.5s
Epoch 001 | step 0020/0093 | loss=11.5432 | ce=2.5792 | kd=15.3849 | acc=0.1633 | binary=0.367 | condition=0.000 | count=0.022 | density=0.052 | time=16.3s
Epoch 001 | step 0025/0093 | loss=11.4888 | ce=2.5483 | kd=15.3204 | acc=0.1688 | binary=0.384 | condition=0.000 | count=0.018 | density=0.042 | time=17.1s
Epoch 001 | step 0030/0093 | loss=11.4045 | ce=2.5103 | kd=15.2163 | acc=0.1786 | binary=0.401 | condition=0.000 | count=0.015 | density=0.035 | time=17.9s
Epoch 001 | step 0035/0093 | loss=11.3283 | ce=2.4690 | kd=15.1252 | acc=0.1920 | binary=0.427 | condition=0.000 | count=0.013 | density=0.031 | time=18.7s
Epoch 001 | step 0040/0093 | loss=11.2289 | ce=2.4370 | kd=14.9968 | acc=0.1934 | binary=0.431 | condition=0.000 | count=0.011 | density=0.027 | time=19.5s
Epoch 001 | step 0045/0093 | loss=11.1269 | ce=2.4124 | kd=14.8616 | acc=0.1944 | binary=0.434 | condition=0.000 | count=0.010 | density=0.024 | time=20.3s
Epoch 001 | step 0050/0093 | loss=10.9820 | ce=2.4021 | kd=14.6590 | acc=0.1959 | binary=0.437 | condition=0.000 | count=0.009 | density=0.021 | time=21.0s
Epoch 001 | step 0055/0093 | loss=10.8609 | ce=2.4085 | kd=14.4834 | acc=0.1986 | binary=0.445 | condition=0.000 | count=0.008 | density=0.020 | time=21.8s
Epoch 001 | step 0060/0093 | loss=10.7153 | ce=2.4213 | kd=14.2699 | acc=0.2005 | binary=0.448 | condition=0.000 | count=0.008 | density=0.018 | time=22.6s
Epoch 001 | step 0065/0093 | loss=10.5903 | ce=2.4453 | kd=14.0810 | acc=0.2007 | binary=0.446 | condition=0.000 | count=0.007 | density=0.017 | time=23.4s
Epoch 001 | step 0070/0093 | loss=10.4785 | ce=2.4590 | kd=13.9154 | acc=0.2033 | binary=0.449 | condition=0.001 | count=0.007 | density=0.016 | time=24.2s
Epoch 001 | step 0075/0093 | loss=10.3968 | ce=2.5003 | kd=13.7810 | acc=0.2054 | binary=0.454 | condition=0.003 | count=0.006 | density=0.015 | time=25.0s
Epoch 001 | step 0080/0093 | loss=10.3260 | ce=2.5212 | kd=13.6709 | acc=0.2080 | binary=0.459 | condition=0.007 | count=0.006 | density=0.014 | time=26.0s
Epoch 001 | step 0085/0093 | loss=10.2362 | ce=2.5288 | kd=13.5394 | acc=0.2079 | binary=0.455 | condition=0.012 | count=0.005 | density=0.013 | time=27.3s
Epoch 001 | step 0090/0093 | loss=10.1470 | ce=2.5387 | kd=13.4078 | acc=0.2104 | binary=0.451 | condition=0.026 | count=0.005 | density=0.012 | time=28.5s
Epoch 001 | step 0093/0093 | loss=10.1072 | ce=2.5443 | kd=13.3485 | acc=0.2111 | binary=0.451 | condition=0.030 | count=0.005 | density=0.012 | time=38.3s

train overall: acc=0.2111 (1245/5898)
train macro acc: 0.0733
train count exact: acc=0.0050 (6/1204)
train count ±1: acc=0.0158 (19/1204)
train by edge head:
  binary       acc=0.4506 (1187/2634)
  condition    acc=0.0304 (45/1480)
  count        acc=0.0050 (6/1204)
  density      acc=0.0121 (7/580)
train by question type:
  Building_Condition_Recognition           acc=0.4879 (283/580)
  Complex_Counting                         acc=0.0032 (2/624)
  Density_Estimation                       acc=0.0121 (7/580)
  Entire_Image_Condition_Recognition       acc=0.2617 (357/1364)
  Risk_Assessment                          acc=0.3103 (180/580)
  Road_Condition_Recognition               acc=0.2591 (412/1590)
  Simple_Counting                          acc=0.0069 (4/580)

valid overall: acc=0.3909 (706/1806)
valid macro acc: 0.1293
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.4472 (364/814)
  condition    acc=0.7617 (342/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.5511 (97/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.5932 (245/413)
  Risk_Assessment                          acc=0.4602 (81/176)
  Road_Condition_Recognition               acc=0.5683 (283/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 1 done | train_acc=0.2111 | valid_acc=0.3909 | best_valid_acc=0.3909 at epoch 1 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 2/50
================================================================================
Epoch 002 | step 0001/0093 | loss=9.0590 | ce=2.8590 | kd=11.7161 | acc=0.2031 | binary=0.267 | condition=0.385 | count=0.000 | density=0.000 | time=0.5s
Epoch 002 | step 0005/0093 | loss=8.7647 | ce=2.7706 | kd=11.3337 | acc=0.2562 | binary=0.374 | condition=0.353 | count=0.000 | density=0.000 | time=1.1s
Epoch 002 | step 0010/0093 | loss=8.8354 | ce=2.7086 | kd=11.4612 | acc=0.2609 | binary=0.368 | condition=0.365 | count=0.000 | density=0.000 | time=2.0s
Epoch 002 | step 0015/0093 | loss=8.7758 | ce=2.5810 | kd=11.4307 | acc=0.2729 | binary=0.361 | condition=0.405 | count=0.000 | density=0.000 | time=2.8s
Epoch 002 | step 0020/0093 | loss=8.8146 | ce=2.6536 | kd=11.4551 | acc=0.2648 | binary=0.337 | condition=0.433 | count=0.000 | density=0.000 | time=3.6s
Epoch 002 | step 0025/0093 | loss=8.8086 | ce=2.6416 | kd=11.4516 | acc=0.2637 | binary=0.315 | condition=0.465 | count=0.000 | density=0.000 | time=4.4s
Epoch 002 | step 0030/0093 | loss=8.8400 | ce=2.6599 | kd=11.4886 | acc=0.2583 | binary=0.297 | condition=0.484 | count=0.000 | density=0.000 | time=5.2s
Epoch 002 | step 0035/0093 | loss=8.8630 | ce=2.6831 | kd=11.5115 | acc=0.2531 | binary=0.281 | condition=0.500 | count=0.000 | density=0.000 | time=6.0s
Epoch 002 | step 0040/0093 | loss=8.8451 | ce=2.6738 | kd=11.4900 | acc=0.2508 | binary=0.287 | condition=0.488 | count=0.000 | density=0.000 | time=6.8s
Epoch 002 | step 0045/0093 | loss=8.8383 | ce=2.6480 | kd=11.4913 | acc=0.2503 | binary=0.295 | condition=0.469 | count=0.000 | density=0.000 | time=7.6s
Epoch 002 | step 0050/0093 | loss=8.8206 | ce=2.6247 | kd=11.4760 | acc=0.2572 | binary=0.313 | condition=0.458 | count=0.000 | density=0.000 | time=8.4s
Epoch 002 | step 0055/0093 | loss=8.7715 | ce=2.6010 | kd=11.4160 | acc=0.2639 | binary=0.322 | condition=0.465 | count=0.000 | density=0.000 | time=9.2s
Epoch 002 | step 0060/0093 | loss=8.7633 | ce=2.6154 | kd=11.3981 | acc=0.2635 | binary=0.322 | condition=0.465 | count=0.000 | density=0.000 | time=10.0s
Epoch 002 | step 0065/0093 | loss=8.7528 | ce=2.6174 | kd=11.3822 | acc=0.2661 | binary=0.326 | condition=0.474 | count=0.000 | density=0.000 | time=10.8s
Epoch 002 | step 0070/0093 | loss=8.7310 | ce=2.6206 | kd=11.3498 | acc=0.2667 | binary=0.329 | condition=0.472 | count=0.000 | density=0.000 | time=12.1s
Epoch 002 | step 0075/0093 | loss=8.7198 | ce=2.6175 | kd=11.3350 | acc=0.2646 | binary=0.335 | condition=0.455 | count=0.000 | density=0.000 | time=13.3s
Epoch 002 | step 0080/0093 | loss=8.7268 | ce=2.6289 | kd=11.3402 | acc=0.2615 | binary=0.342 | condition=0.435 | count=0.000 | density=0.000 | time=14.5s
Epoch 002 | step 0085/0093 | loss=8.7124 | ce=2.6132 | kd=11.3264 | acc=0.2618 | binary=0.349 | condition=0.422 | count=0.000 | density=0.000 | time=15.6s
Epoch 002 | step 0090/0093 | loss=8.7025 | ce=2.6073 | kd=11.3148 | acc=0.2630 | binary=0.353 | condition=0.418 | count=0.000 | density=0.000 | time=16.4s
Epoch 002 | step 0093/0093 | loss=8.7031 | ce=2.6081 | kd=11.3152 | acc=0.2640 | binary=0.356 | condition=0.419 | count=0.000 | density=0.000 | time=16.7s

train overall: acc=0.2640 (1557/5898)
train macro acc: 0.0853
train count exact: acc=0.0000 (0/1204)
train count ±1: acc=0.0000 (0/1204)
train by edge head:
  binary       acc=0.3557 (937/2634)
  condition    acc=0.4189 (620/1480)
  count        acc=0.0000 (0/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.3603 (209/580)
  Complex_Counting                         acc=0.0000 (0/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.3966 (541/1364)
  Risk_Assessment                          acc=0.3966 (230/580)
  Road_Condition_Recognition               acc=0.3629 (577/1590)
  Simple_Counting                          acc=0.0000 (0/580)

valid overall: acc=0.3776 (682/1806)
valid macro acc: 0.1309
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.4459 (363/814)
  condition    acc=0.7105 (319/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.5511 (97/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.5496 (227/413)
  Risk_Assessment                          acc=0.2216 (39/176)
  Road_Condition_Recognition               acc=0.6406 (319/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 2 done | train_acc=0.2640 | valid_acc=0.3776 | best_valid_acc=0.3909 at epoch 1 | no_improve=1/8 | no improvement

================================================================================
Epoch 3/50
================================================================================
Epoch 003 | step 0001/0093 | loss=8.0319 | ce=2.3296 | kd=10.4758 | acc=0.3125 | binary=0.382 | condition=0.583 | count=0.000 | density=0.000 | time=0.5s
Epoch 003 | step 0005/0093 | loss=8.2335 | ce=2.3205 | kd=10.7676 | acc=0.3406 | binary=0.442 | condition=0.529 | count=0.000 | density=0.000 | time=1.1s
Epoch 003 | step 0010/0093 | loss=8.2110 | ce=2.2532 | kd=10.7643 | acc=0.3266 | binary=0.434 | condition=0.490 | count=0.000 | density=0.000 | time=2.0s
Epoch 003 | step 0015/0093 | loss=8.3006 | ce=2.3848 | kd=10.8360 | acc=0.3208 | binary=0.434 | condition=0.509 | count=0.000 | density=0.000 | time=2.7s
Epoch 003 | step 0020/0093 | loss=8.3980 | ce=2.3851 | kd=10.9749 | acc=0.3289 | binary=0.421 | condition=0.568 | count=0.000 | density=0.000 | time=3.5s
Epoch 003 | step 0025/0093 | loss=8.3872 | ce=2.3971 | kd=10.9545 | acc=0.3319 | binary=0.403 | condition=0.619 | count=0.000 | density=0.000 | time=4.4s
Epoch 003 | step 0030/0093 | loss=8.3793 | ce=2.4095 | kd=10.9377 | acc=0.3370 | binary=0.404 | condition=0.633 | count=0.000 | density=0.000 | time=5.2s
Epoch 003 | step 0035/0093 | loss=8.3107 | ce=2.3731 | kd=10.8554 | acc=0.3446 | binary=0.401 | condition=0.664 | count=0.000 | density=0.000 | time=6.2s
Epoch 003 | step 0040/0093 | loss=8.2973 | ce=2.3885 | kd=10.8296 | acc=0.3445 | binary=0.402 | condition=0.661 | count=0.000 | density=0.000 | time=7.4s
Epoch 003 | step 0045/0093 | loss=8.2384 | ce=2.3653 | kd=10.7555 | acc=0.3566 | binary=0.420 | condition=0.674 | count=0.000 | density=0.000 | time=8.8s
Epoch 003 | step 0050/0093 | loss=8.2008 | ce=2.3520 | kd=10.7074 | acc=0.3575 | binary=0.422 | condition=0.676 | count=0.000 | density=0.000 | time=9.8s
Epoch 003 | step 0055/0093 | loss=8.1769 | ce=2.3539 | kd=10.6724 | acc=0.3594 | binary=0.428 | condition=0.674 | count=0.000 | density=0.000 | time=10.7s
Epoch 003 | step 0060/0093 | loss=8.1636 | ce=2.3453 | kd=10.6572 | acc=0.3682 | binary=0.442 | condition=0.683 | count=0.000 | density=0.000 | time=11.5s
Epoch 003 | step 0065/0093 | loss=8.1049 | ce=2.3229 | kd=10.5829 | acc=0.3728 | binary=0.446 | condition=0.695 | count=0.000 | density=0.000 | time=12.3s
Epoch 003 | step 0070/0093 | loss=8.0361 | ce=2.2986 | kd=10.4950 | acc=0.3770 | binary=0.451 | condition=0.701 | count=0.000 | density=0.000 | time=13.1s
Epoch 003 | step 0075/0093 | loss=7.9736 | ce=2.2801 | kd=10.4137 | acc=0.3806 | binary=0.455 | condition=0.707 | count=0.000 | density=0.000 | time=13.8s
Epoch 003 | step 0080/0093 | loss=7.9109 | ce=2.2596 | kd=10.3328 | acc=0.3844 | binary=0.459 | condition=0.710 | count=0.000 | density=0.000 | time=14.6s
Epoch 003 | step 0085/0093 | loss=7.8631 | ce=2.2513 | kd=10.2682 | acc=0.3869 | binary=0.461 | condition=0.719 | count=0.000 | density=0.000 | time=15.4s
Epoch 003 | step 0090/0093 | loss=7.8097 | ce=2.2321 | kd=10.2001 | acc=0.3908 | binary=0.467 | condition=0.724 | count=0.000 | density=0.000 | time=16.2s
Epoch 003 | step 0093/0093 | loss=7.7805 | ce=2.2253 | kd=10.1613 | acc=0.3925 | binary=0.470 | condition=0.727 | count=0.000 | density=0.000 | time=16.4s

train overall: acc=0.3925 (2315/5898)
train macro acc: 0.1277
train count exact: acc=0.0000 (0/1204)
train count ±1: acc=0.0000 (0/1204)
train by edge head:
  binary       acc=0.4704 (1239/2634)
  condition    acc=0.7270 (1076/1480)
  count        acc=0.0000 (0/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.4690 (272/580)
  Complex_Counting                         acc=0.0000 (0/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.6136 (837/1364)
  Risk_Assessment                          acc=0.4362 (253/580)
  Road_Condition_Recognition               acc=0.5994 (953/1590)
  Simple_Counting                          acc=0.0000 (0/580)

valid overall: acc=0.4579 (827/1806)
valid macro acc: 0.1429
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.5504 (448/814)
  condition    acc=0.8441 (379/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.4489 (79/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.7167 (296/413)
  Risk_Assessment                          acc=0.7784 (137/176)
  Road_Condition_Recognition               acc=0.6325 (315/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 3 done | train_acc=0.3925 | valid_acc=0.4579 | best_valid_acc=0.4579 at epoch 3 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 4/50
================================================================================
Epoch 004 | step 0001/0093 | loss=6.6463 | ce=1.8087 | kd=8.7196 | acc=0.4375 | binary=0.500 | condition=0.800 | count=0.000 | density=0.000 | time=0.6s
Epoch 004 | step 0005/0093 | loss=6.3564 | ce=1.7991 | kd=8.3095 | acc=0.4281 | binary=0.507 | condition=0.827 | count=0.000 | density=0.000 | time=1.6s
Epoch 004 | step 0010/0093 | loss=6.2387 | ce=1.7133 | kd=8.1781 | acc=0.4500 | binary=0.515 | condition=0.831 | count=0.000 | density=0.000 | time=2.8s
Epoch 004 | step 0015/0093 | loss=6.1299 | ce=1.6979 | kd=8.0293 | acc=0.4552 | binary=0.523 | condition=0.825 | count=0.000 | density=0.000 | time=4.0s
Epoch 004 | step 0020/0093 | loss=6.1616 | ce=1.7464 | kd=8.0538 | acc=0.4430 | binary=0.520 | condition=0.820 | count=0.000 | density=0.000 | time=4.9s
Epoch 004 | step 0025/0093 | loss=6.0753 | ce=1.7468 | kd=7.9304 | acc=0.4481 | binary=0.528 | condition=0.827 | count=0.000 | density=0.000 | time=5.7s
Epoch 004 | step 0030/0093 | loss=6.0317 | ce=1.7491 | kd=7.8671 | acc=0.4495 | binary=0.528 | condition=0.835 | count=0.000 | density=0.000 | time=6.5s
Epoch 004 | step 0035/0093 | loss=5.9809 | ce=1.7349 | kd=7.8006 | acc=0.4469 | binary=0.527 | condition=0.828 | count=0.000 | density=0.000 | time=7.3s
Epoch 004 | step 0040/0093 | loss=5.8790 | ce=1.7110 | kd=7.6653 | acc=0.4469 | binary=0.528 | condition=0.827 | count=0.000 | density=0.000 | time=8.1s
Epoch 004 | step 0045/0093 | loss=5.7894 | ce=1.6771 | kd=7.5518 | acc=0.4507 | binary=0.528 | condition=0.830 | count=0.000 | density=0.000 | time=8.8s
Epoch 004 | step 0050/0093 | loss=5.7635 | ce=1.6816 | kd=7.5128 | acc=0.4487 | binary=0.529 | condition=0.835 | count=0.005 | density=0.000 | time=9.7s
Epoch 004 | step 0055/0093 | loss=5.7182 | ce=1.6743 | kd=7.4513 | acc=0.4483 | binary=0.527 | condition=0.842 | count=0.011 | density=0.003 | time=10.4s
Epoch 004 | step 0060/0093 | loss=5.6417 | ce=1.6501 | kd=7.3524 | acc=0.4508 | binary=0.526 | condition=0.843 | count=0.018 | density=0.008 | time=11.2s
Epoch 004 | step 0065/0093 | loss=5.6036 | ce=1.6439 | kd=7.3006 | acc=0.4512 | binary=0.521 | condition=0.846 | count=0.024 | density=0.007 | time=12.1s
Epoch 004 | step 0070/0093 | loss=5.5681 | ce=1.6355 | kd=7.2535 | acc=0.4547 | binary=0.526 | condition=0.847 | count=0.029 | density=0.007 | time=12.8s
Epoch 004 | step 0075/0093 | loss=5.5337 | ce=1.6261 | kd=7.2084 | acc=0.4548 | binary=0.524 | condition=0.852 | count=0.034 | density=0.006 | time=13.7s
Epoch 004 | step 0080/0093 | loss=5.4691 | ce=1.6024 | kd=7.1262 | acc=0.4619 | binary=0.529 | condition=0.857 | count=0.047 | density=0.006 | time=14.5s
Epoch 004 | step 0085/0093 | loss=5.4370 | ce=1.5909 | kd=7.0853 | acc=0.4618 | binary=0.526 | condition=0.858 | count=0.052 | density=0.009 | time=15.6s

## S10: TDM-Fast + KD from T5

In [ ]:
%cd /content/TinyDisasterVQA
%env PYTHONPATH=/content/TinyDisasterVQA/src
%env PYTHONUNBUFFERED=1

!mkdir -p /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10

!python -u scripts/06_train_student.py \
  --dataset-root dataset \
  --runs-dir /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10 \
  --train-csv outputs/training_data_cap5/train.csv \
  --valid-csv outputs/training_data_cap5/valid.csv \
  --test-csv outputs/training_data_cap5/test.csv \
  --metadata outputs/training_data_cap5/metadata.json \
  --class-weights outputs/answer_space_cap5/class_weights_edge_global_by_label.json \
  --image-size 224 \
  --epochs 50 \
  --batch-size 64 \
  --eval-batch-size 64 \
  --num-workers 2 \
  --device auto \
  --patience 8 \
  --min-delta 0.001 \
  --log-interval 5 \
  --student-variant tdm_fast \
  --mode kd \
  --teacher-checkpoint "{T5_CHECKPOINT}" \
  --kd-alpha 0.7 \
  --kd-temperature 4.0 \
  --run-name S10_tdm_fast_kd_$(date +%Y%m%d_%H%M%S)

/content/TinyDisasterVQA
env: PYTHONPATH=/content/TinyDisasterVQA/src
env: PYTHONUNBUFFERED=1
================================================================================
TinyDisasterVQA / Train TDM Student
================================================================================
Run dir:              /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10/S10_tdm_fast_kd_20260610_103859
Device:               cuda
Student variant:      tdm_fast
Mode:                 kd
Count cap:            5
Num classes:          14
Question templates:   31
AMP:                  True
Image size:           224
Batch size:           64
Eval batch:           64
Epochs:               50
LR:                   0.0003
Weight decay:         0.0001
Patience:             8
Min delta:            0.001
KD alpha:             0.7
KD temp:              4.0

Model summary
================================================================================
Class:             TDMFastVQA
Total params:      91,902
Trainable params:  91,902
FP32 param size:   0.35 MB
Int8 param size:   89.7 KB
Student variant:   tdm_fast
Image block type:  conv
Image channels:    (16, 32, 64, 96)
Image feature dim: 96
Template encoder:  one_hot + Linear
Template input dim:31
Template emb dim:  16
Fusion hidden dim: 96
Fusion layers:     1
Num classes:       14
Head type:         single edge_global

Loading teacher...
Adapted legacy teacher checkpoint: embedding.weight -> linear.weight/bias
Loaded KD teacher:
  checkpoint:        /content/drive/MyDrive/TinyDisasterVQA/TeacherAblation_T1_T6/T5_cap5_template_weighted_ce/checkpoints/best.pt
  backbone:          convnext_tiny
  question_encoder:  template
  pretrained:        True
  use_count_aux:     False

Model summary
================================================================================
Class:             TeacherVQA
Total params:      28,418,414
Trainable params:  0
FP32 param size:   108.41 MB
Int8 param size:   27752.4 KB
Image backbone:    convnext_tiny
Pretrained:        True
Image feature dim: 768
Question encoder:  template
Question dim:      128
Num classes:       14
Count aux:         False


================================================================================
Epoch 1/50
================================================================================
Epoch 001 | step 0001/0093 | loss=11.3408 | ce=2.7027 | kd=15.0429 | acc=0.0156 | binary=0.000 | condition=0.000 | count=0.111 | density=0.000 | time=13.9s
Epoch 001 | step 0005/0093 | loss=11.7673 | ce=2.6562 | kd=15.6720 | acc=0.0813 | binary=0.049 | condition=0.127 | count=0.145 | density=0.000 | time=14.6s
Epoch 001 | step 0010/0093 | loss=11.5418 | ce=2.6239 | kd=15.3638 | acc=0.1297 | binary=0.118 | condition=0.258 | count=0.066 | density=0.000 | time=15.6s
Epoch 001 | step 0015/0093 | loss=11.5405 | ce=2.6006 | kd=15.3719 | acc=0.1656 | binary=0.160 | condition=0.343 | count=0.045 | density=0.000 | time=16.9s
Epoch 001 | step 0020/0093 | loss=11.3541 | ce=2.5758 | kd=15.1163 | acc=0.1844 | binary=0.190 | condition=0.381 | count=0.036 | density=0.000 | time=17.6s
Epoch 001 | step 0025/0093 | loss=11.3300 | ce=2.5483 | kd=15.0936 | acc=0.2019 | binary=0.194 | condition=0.451 | count=0.029 | density=0.000 | time=18.4s
Epoch 001 | step 0030/0093 | loss=11.3189 | ce=2.5183 | kd=15.0907 | acc=0.2135 | binary=0.200 | condition=0.484 | count=0.025 | density=0.000 | time=19.2s
Epoch 001 | step 0035/0093 | loss=11.2876 | ce=2.4948 | kd=15.0560 | acc=0.2214 | binary=0.196 | condition=0.520 | count=0.021 | density=0.000 | time=20.1s
Epoch 001 | step 0040/0093 | loss=11.2346 | ce=2.4708 | kd=14.9905 | acc=0.2254 | binary=0.195 | condition=0.546 | count=0.019 | density=0.000 | time=20.8s
Epoch 001 | step 0045/0093 | loss=11.2197 | ce=2.4474 | kd=14.9793 | acc=0.2302 | binary=0.193 | condition=0.572 | count=0.017 | density=0.000 | time=21.6s
Epoch 001 | step 0050/0093 | loss=11.1595 | ce=2.4164 | kd=14.9065 | acc=0.2359 | binary=0.191 | condition=0.591 | count=0.015 | density=0.000 | time=22.4s
Epoch 001 | step 0055/0093 | loss=11.0839 | ce=2.3923 | kd=14.8088 | acc=0.2389 | binary=0.185 | condition=0.604 | count=0.014 | density=0.000 | time=23.2s
Epoch 001 | step 0060/0093 | loss=10.9815 | ce=2.3793 | kd=14.6682 | acc=0.2393 | binary=0.183 | condition=0.614 | count=0.013 | density=0.000 | time=24.0s
Epoch 001 | step 0065/0093 | loss=10.9073 | ce=2.3583 | kd=14.5712 | acc=0.2440 | binary=0.181 | condition=0.629 | count=0.012 | density=0.000 | time=24.8s
Epoch 001 | step 0070/0093 | loss=10.8383 | ce=2.3469 | kd=14.4774 | acc=0.2446 | binary=0.177 | condition=0.640 | count=0.011 | density=0.000 | time=25.6s
Epoch 001 | step 0075/0093 | loss=10.7601 | ce=2.3368 | kd=14.3701 | acc=0.2458 | binary=0.177 | condition=0.651 | count=0.010 | density=0.000 | time=26.4s
Epoch 001 | step 0080/0093 | loss=10.6871 | ce=2.3225 | kd=14.2719 | acc=0.2486 | binary=0.176 | condition=0.663 | count=0.010 | density=0.000 | time=27.3s
Epoch 001 | step 0085/0093 | loss=10.6019 | ce=2.3132 | kd=14.1542 | acc=0.2500 | binary=0.176 | condition=0.667 | count=0.009 | density=0.000 | time=28.7s
Epoch 001 | step 0090/0093 | loss=10.5181 | ce=2.3117 | kd=14.0352 | acc=0.2512 | binary=0.180 | condition=0.670 | count=0.009 | density=0.000 | time=29.9s
Epoch 001 | step 0093/0093 | loss=10.4947 | ce=2.3137 | kd=14.0009 | acc=0.2497 | binary=0.178 | condition=0.671 | count=0.008 | density=0.000 | time=38.1s

train overall: acc=0.2497 (1473/5898)
train macro acc: 0.0861
train count exact: acc=0.0083 (10/1204)
train count ±1: acc=0.0166 (20/1204)
train by edge head:
  binary       acc=0.1784 (470/2634)
  condition    acc=0.6709 (993/1480)
  count        acc=0.0083 (10/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.2448 (142/580)
  Complex_Counting                         acc=0.0064 (4/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.4179 (570/1364)
  Risk_Assessment                          acc=0.1897 (110/580)
  Road_Condition_Recognition               acc=0.4031 (641/1590)
  Simple_Counting                          acc=0.0103 (6/580)

valid overall: acc=0.2630 (475/1806)
valid macro acc: 0.0906
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.1978 (161/814)
  condition    acc=0.6993 (314/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.2898 (51/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.4213 (174/413)
  Risk_Assessment                          acc=0.2216 (39/176)
  Road_Condition_Recognition               acc=0.4237 (211/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 1 done | train_acc=0.2497 | valid_acc=0.2630 | best_valid_acc=0.2630 at epoch 1 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 2/50
================================================================================
Epoch 002 | step 0001/0093 | loss=9.1020 | ce=2.1627 | kd=12.0759 | acc=0.2812 | binary=0.226 | condition=0.786 | count=0.000 | density=0.000 | time=0.7s
Epoch 002 | step 0005/0093 | loss=9.2353 | ce=2.3143 | kd=12.2015 | acc=0.2781 | binary=0.259 | condition=0.614 | count=0.000 | density=0.000 | time=1.7s
Epoch 002 | step 0010/0093 | loss=8.9540 | ce=2.2977 | kd=11.8068 | acc=0.2687 | binary=0.258 | condition=0.591 | count=0.000 | density=0.000 | time=2.8s
Epoch 002 | step 0015/0093 | loss=8.9290 | ce=2.3634 | kd=11.7428 | acc=0.2667 | binary=0.269 | condition=0.574 | count=0.000 | density=0.000 | time=3.8s
Epoch 002 | step 0020/0093 | loss=8.9114 | ce=2.3670 | kd=11.7161 | acc=0.2547 | binary=0.265 | condition=0.553 | count=0.000 | density=0.000 | time=4.6s
Epoch 002 | step 0025/0093 | loss=8.8453 | ce=2.3273 | kd=11.6387 | acc=0.2719 | binary=0.288 | condition=0.566 | count=0.000 | density=0.000 | time=5.3s
Epoch 002 | step 0030/0093 | loss=8.8665 | ce=2.3843 | kd=11.6446 | acc=0.2714 | binary=0.302 | condition=0.540 | count=0.000 | density=0.000 | time=6.1s
Epoch 002 | step 0035/0093 | loss=8.8102 | ce=2.4160 | kd=11.5506 | acc=0.2741 | binary=0.311 | condition=0.543 | count=0.000 | density=0.000 | time=6.9s
Epoch 002 | step 0040/0093 | loss=8.7960 | ce=2.4190 | kd=11.5289 | acc=0.2777 | binary=0.315 | condition=0.543 | count=0.000 | density=0.000 | time=7.7s
Epoch 002 | step 0045/0093 | loss=8.7839 | ce=2.4338 | kd=11.5053 | acc=0.2785 | binary=0.316 | condition=0.551 | count=0.000 | density=0.000 | time=8.6s
Epoch 002 | step 0050/0093 | loss=8.7597 | ce=2.4331 | kd=11.4710 | acc=0.2803 | binary=0.319 | condition=0.549 | count=0.000 | density=0.000 | time=9.4s
Epoch 002 | step 0055/0093 | loss=8.7478 | ce=2.4399 | kd=11.4512 | acc=0.2810 | binary=0.323 | condition=0.544 | count=0.000 | density=0.000 | time=10.2s
Epoch 002 | step 0060/0093 | loss=8.7328 | ce=2.4470 | kd=11.4267 | acc=0.2807 | binary=0.327 | condition=0.537 | count=0.000 | density=0.000 | time=11.0s
Epoch 002 | step 0065/0093 | loss=8.6948 | ce=2.4430 | kd=11.3741 | acc=0.2858 | binary=0.337 | condition=0.539 | count=0.000 | density=0.000 | time=11.8s
Epoch 002 | step 0070/0093 | loss=8.6861 | ce=2.4441 | kd=11.3612 | acc=0.2886 | binary=0.344 | condition=0.534 | count=0.000 | density=0.000 | time=12.6s
Epoch 002 | step 0075/0093 | loss=8.6844 | ce=2.4522 | kd=11.3554 | acc=0.2902 | binary=0.346 | condition=0.538 | count=0.000 | density=0.000 | time=13.4s
Epoch 002 | step 0080/0093 | loss=8.6655 | ce=2.4509 | kd=11.3288 | acc=0.2889 | binary=0.344 | condition=0.535 | count=0.000 | density=0.000 | time=14.5s
Epoch 002 | step 0085/0093 | loss=8.6442 | ce=2.4455 | kd=11.3007 | acc=0.2881 | binary=0.342 | condition=0.534 | count=0.000 | density=0.000 | time=15.7s
Epoch 002 | step 0090/0093 | loss=8.6481 | ce=2.4592 | kd=11.3005 | acc=0.2894 | binary=0.342 | condition=0.543 | count=0.000 | density=0.000 | time=17.0s
Epoch 002 | step 0093/0093 | loss=8.6511 | ce=2.4638 | kd=11.3028 | acc=0.2898 | binary=0.343 | condition=0.544 | count=0.000 | density=0.000 | time=17.3s

train overall: acc=0.2898 (1709/5898)
train macro acc: 0.0951
train count exact: acc=0.0000 (0/1204)
train count ±1: acc=0.0000 (0/1204)
train by edge head:
  binary       acc=0.3432 (904/2634)
  condition    acc=0.5439 (805/1480)
  count        acc=0.0000 (0/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.4172 (242/580)
  Complex_Counting                         acc=0.0000 (0/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.4457 (608/1364)
  Risk_Assessment                          acc=0.3741 (217/580)
  Road_Condition_Recognition               acc=0.4038 (642/1590)
  Simple_Counting                          acc=0.0000 (0/580)

valid overall: acc=0.3012 (544/1806)
valid macro acc: 0.1011
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.3084 (251/814)
  condition    acc=0.6526 (293/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.3807 (67/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.4528 (187/413)
  Risk_Assessment                          acc=0.4602 (81/176)
  Road_Condition_Recognition               acc=0.4197 (209/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 2 done | train_acc=0.2898 | valid_acc=0.3012 | best_valid_acc=0.3012 at epoch 2 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 3/50
================================================================================
Epoch 003 | step 0001/0093 | loss=7.6799 | ce=2.3630 | kd=9.9585 | acc=0.2344 | binary=0.265 | condition=0.545 | count=0.000 | density=0.000 | time=0.4s
Epoch 003 | step 0005/0093 | loss=8.3784 | ce=2.4085 | kd=10.9369 | acc=0.2969 | binary=0.374 | condition=0.571 | count=0.000 | density=0.000 | time=1.0s
Epoch 003 | step 0010/0093 | loss=8.5226 | ce=2.5306 | kd=11.0906 | acc=0.2797 | binary=0.366 | condition=0.521 | count=0.000 | density=0.000 | time=1.9s
Epoch 003 | step 0015/0093 | loss=8.4847 | ce=2.5417 | kd=11.0317 | acc=0.2865 | binary=0.384 | condition=0.519 | count=0.000 | density=0.000 | time=2.8s
Epoch 003 | step 0020/0093 | loss=8.4025 | ce=2.5067 | kd=10.9292 | acc=0.3039 | binary=0.416 | condition=0.512 | count=0.000 | density=0.000 | time=3.6s
Epoch 003 | step 0025/0093 | loss=8.3936 | ce=2.4648 | kd=10.9345 | acc=0.3144 | binary=0.434 | condition=0.501 | count=0.000 | density=0.000 | time=4.4s
Epoch 003 | step 0030/0093 | loss=8.4172 | ce=2.4726 | kd=10.9648 | acc=0.3130 | binary=0.437 | condition=0.489 | count=0.000 | density=0.000 | time=5.3s
Epoch 003 | step 0035/0093 | loss=8.3798 | ce=2.4389 | kd=10.9259 | acc=0.3156 | binary=0.434 | condition=0.491 | count=0.000 | density=0.000 | time=6.1s
Epoch 003 | step 0040/0093 | loss=8.3524 | ce=2.4181 | kd=10.8956 | acc=0.3180 | binary=0.429 | condition=0.502 | count=0.000 | density=0.000 | time=6.8s
Epoch 003 | step 0045/0093 | loss=8.3603 | ce=2.4464 | kd=10.8948 | acc=0.3142 | binary=0.425 | condition=0.505 | count=0.000 | density=0.000 | time=8.0s
Epoch 003 | step 0050/0093 | loss=8.3360 | ce=2.4379 | kd=10.8637 | acc=0.3194 | binary=0.430 | condition=0.515 | count=0.000 | density=0.000 | time=9.2s
Epoch 003 | step 0055/0093 | loss=8.3429 | ce=2.4304 | kd=10.8768 | acc=0.3219 | binary=0.430 | condition=0.525 | count=0.000 | density=0.000 | time=10.5s
Epoch 003 | step 0060/0093 | loss=8.3177 | ce=2.4164 | kd=10.8469 | acc=0.3224 | binary=0.425 | condition=0.532 | count=0.000 | density=0.000 | time=11.7s
Epoch 003 | step 0065/0093 | loss=8.2991 | ce=2.4091 | kd=10.8234 | acc=0.3240 | binary=0.425 | condition=0.537 | count=0.000 | density=0.000 | time=12.5s
Epoch 003 | step 0070/0093 | loss=8.2996 | ce=2.4112 | kd=10.8232 | acc=0.3257 | binary=0.426 | condition=0.538 | count=0.000 | density=0.000 | time=13.2s
Epoch 003 | step 0075/0093 | loss=8.2854 | ce=2.4042 | kd=10.8059 | acc=0.3285 | binary=0.428 | condition=0.546 | count=0.000 | density=0.000 | time=14.0s
Epoch 003 | step 0080/0093 | loss=8.2787 | ce=2.4072 | kd=10.7951 | acc=0.3303 | binary=0.432 | condition=0.546 | count=0.000 | density=0.000 | time=14.8s
Epoch 003 | step 0085/0093 | loss=8.2607 | ce=2.4046 | kd=10.7704 | acc=0.3322 | binary=0.432 | condition=0.555 | count=0.000 | density=0.000 | time=15.6s
Epoch 003 | step 0090/0093 | loss=8.2680 | ce=2.4140 | kd=10.7769 | acc=0.3332 | binary=0.434 | condition=0.556 | count=0.000 | density=0.000 | time=16.4s
Epoch 003 | step 0093/0093 | loss=8.2525 | ce=2.4064 | kd=10.7580 | acc=0.3344 | binary=0.435 | condition=0.559 | count=0.000 | density=0.000 | time=16.6s

train overall: acc=0.3344 (1972/5898)
train macro acc: 0.1082
train count exact: acc=0.0000 (0/1204)
train count ±1: acc=0.0000 (0/1204)
train by edge head:
  binary       acc=0.4347 (1145/2634)
  condition    acc=0.5588 (827/1480)
  count        acc=0.0000 (0/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.4845 (281/580)
  Complex_Counting                         acc=0.0000 (0/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.4890 (667/1364)
  Risk_Assessment                          acc=0.6103 (354/580)
  Road_Condition_Recognition               acc=0.4214 (670/1590)
  Simple_Counting                          acc=0.0000 (0/580)

valid overall: acc=0.3815 (689/1806)
valid macro acc: 0.1243
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.5012 (408/814)
  condition    acc=0.6258 (281/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.5284 (93/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.5593 (231/413)
  Risk_Assessment                          acc=0.7216 (127/176)
  Road_Condition_Recognition               acc=0.4779 (238/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 3 done | train_acc=0.3344 | valid_acc=0.3815 | best_valid_acc=0.3815 at epoch 3 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 4/50
================================================================================
Epoch 004 | step 0001/0093 | loss=8.1985 | ce=2.2133 | kd=10.7637 | acc=0.3438 | binary=0.375 | condition=0.714 | count=0.000 | density=0.000 | time=0.5s
Epoch 004 | step 0005/0093 | loss=8.2610 | ce=2.3600 | kd=10.7900 | acc=0.3438 | binary=0.433 | condition=0.598 | count=0.000 | density=0.000 | time=1.1s
Epoch 004 | step 0010/0093 | loss=7.9730 | ce=2.2753 | kd=10.4149 | acc=0.3641 | binary=0.465 | condition=0.619 | count=0.000 | density=0.000 | time=2.1s
Epoch 004 | step 0015/0093 | loss=7.8817 | ce=2.2450 | kd=10.2975 | acc=0.3667 | binary=0.472 | condition=0.604 | count=0.000 | density=0.000 | time=3.5s
Epoch 004 | step 0020/0093 | loss=7.8826 | ce=2.2503 | kd=10.2965 | acc=0.3641 | binary=0.483 | condition=0.567 | count=0.000 | density=0.000 | time=4.5s
Epoch 004 | step 0025/0093 | loss=7.8744 | ce=2.2504 | kd=10.2847 | acc=0.3694 | binary=0.489 | condition=0.566 | count=0.000 | density=0.000 | time=5.9s
Epoch 004 | step 0030/0093 | loss=7.8944 | ce=2.2680 | kd=10.3057 | acc=0.3677 | binary=0.487 | condition=0.580 | count=0.000 | density=0.000 | time=6.6s
Epoch 004 | step 0035/0093 | loss=7.8625 | ce=2.2535 | kd=10.2664 | acc=0.3741 | binary=0.495 | condition=0.585 | count=0.000 | density=0.000 | time=7.5s
Epoch 004 | step 0040/0093 | loss=7.8652 | ce=2.2769 | kd=10.2602 | acc=0.3793 | binary=0.508 | condition=0.595 | count=0.000 | density=0.000 | time=8.3s
Epoch 004 | step 0045/0093 | loss=7.8673 | ce=2.2912 | kd=10.2570 | acc=0.3826 | binary=0.515 | condition=0.602 | count=0.000 | density=0.000 | time=9.1s
Epoch 004 | step 0050/0093 | loss=7.8446 | ce=2.2710 | kd=10.2334 | acc=0.3875 | binary=0.517 | condition=0.615 | count=0.000 | density=0.000 | time=9.9s
Epoch 004 | step 0055/0093 | loss=7.8374 | ce=2.2603 | kd=10.2276 | acc=0.3881 | binary=0.513 | condition=0.621 | count=0.000 | density=0.000 | time=10.7s
Epoch 004 | step 0060/0093 | loss=7.8562 | ce=2.2710 | kd=10.2499 | acc=0.3839 | binary=0.505 | condition=0.629 | count=0.000 | density=0.000 | time=11.5s
Epoch 004 | step 0065/0093 | loss=7.8389 | ce=2.2621 | kd=10.2289 | acc=0.3839 | binary=0.501 | condition=0.638 | count=0.000 | density=0.000 | time=12.3s
Epoch 004 | step 0070/0093 | loss=7.8149 | ce=2.2515 | kd=10.1992 | acc=0.3897 | binary=0.504 | condition=0.653 | count=0.000 | density=0.000 | time=13.0s
Epoch 004 | step 0075/0093 | loss=7.8142 | ce=2.2520 | kd=10.1980 | acc=0.3883 | binary=0.501 | condition=0.657 | count=0.000 | density=0.000 | time=13.7s
Epoch 004 | step 0080/0093 | loss=7.7844 | ce=2.2374 | kd=10.1617 | acc=0.3916 | binary=0.504 | condition=0.663 | count=0.000 | density=0.000 | time=14.6s
Epoch 004 | step 0085/0093 | loss=7.7513 | ce=2.2257 | kd=10.1194 | acc=0.3949 | binary=0.506 | condition=0.671 | count=0.000 | density=0.000 | time=15.3s

## Collect full student ablation results

In [ ]:
from pathlib import Path
import json
import pandas as pd

base = Path("/content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10")
rows = []

for summary_path in sorted(base.glob("*/final_summary.json")):
    with summary_path.open("r") as f:
        row = json.load(f)

    test_metrics_path = summary_path.parent / "test_metrics.json"
    if test_metrics_path.exists():
        with test_metrics_path.open("r") as f:
            test_metrics = json.load(f)

        for head, values in test_metrics.get("by_head", {}).items():
            row[f"test_{head}_acc"] = values.get("accuracy")

        if "macro_accuracy" in test_metrics:
            row["test_macro_acc"] = test_metrics["macro_accuracy"]

        if "count_exact" in test_metrics:
            row["test_count_exact_acc"] = test_metrics["count_exact"]["accuracy"]

        if "count_pm1" in test_metrics:
            row["test_count_pm1_acc"] = test_metrics["count_pm1"]["accuracy"]

    row["run_name"] = summary_path.parent.name
    rows.append(row)

df = pd.DataFrame(rows)

preferred_cols = [
    "run_name",
    "student_variant",
    "mode",
    "best_valid_acc",
    "test_acc",
    "test_macro_accuracy",
    "test_macro_acc",
    "test_binary_acc",
    "test_condition_acc",
    "test_count_acc",
    "test_density_acc",
    "test_count_exact",
    "test_count_exact_acc",
    "test_count_pm1",
    "test_count_pm1_acc",
    "total_params",
    "trainable_params",
    "best_epoch",
    "teacher_checkpoint",
    "kd_alpha",
    "kd_temperature",
]

cols = [c for c in preferred_cols if c in df.columns]

if len(df):
    df_view = df[cols].sort_values(["student_variant", "mode", "run_name"])
    display(df_view)

    out_path = base / "student_ablation_summary.csv"
    df_view.to_csv(out_path, index=False)
    print("Saved:", out_path)
else:
    display(df)
    print("No final_summary.json files found yet.")

,run_name,student_variant,mode,best_valid_acc,test_acc,test_macro_accuracy,test_macro_acc,test_binary_acc,test_condition_acc,test_count_acc,...,test_count_exact,test_count_exact_acc,test_count_pm1,test_count_pm1_acc,total_params,trainable_params,best_epoch,teacher_checkpoint,kd_alpha,kd_temperature
4,S4_tdm_fast_ce_20260610_092129,tdm_fast,ce,0.879291,0.852155,0.603659,0.603659,0.962195,0.973154,0.543081,...,0.543081,0.543081,0.762402,0.762402,91902,91902,41,None,NaN,NaN
0,S10_tdm_fast_kd_20260610_103859,tdm_fast,kd,0.854928,0.836334,0.605157,0.605157,0.913415,0.977629,0.553525,...,0.553525,0.553525,0.765013,0.765013,91902,91902,47,/content/drive/MyDrive/TinyDisasterVQA/Teacher...,0.7,4.0
3,S3_tdm_l_ce_20260610_091325,tdm_l,ce,0.852159,0.833061,0.567783,0.567783,0.968293,0.966443,0.459530,...,0.459530,0.459530,0.712794,0.712794,101310,101310,16,None,NaN,NaN
9,S9_tdm_l_kd_20260610_103020,tdm_l,kd,0.851052,0.840153,0.590545,0.590545,0.956098,0.970917,0.503916,...,0.503916,0.503916,0.720627,0.720627,101310,101310,15,/content/drive/MyDrive/TinyDisasterVQA/Teacher...,0.7,4.0
6,S6_tdm_l_weighted_ce_20260610_094801,tdm_l,weighted_ce,0.833333,0.821604,0.550708,0.550708,0.958537,0.966443,0.446475,...,0.446475,0.446475,0.676240,0.676240,101310,101310,12,None,NaN,NaN
2,S2_tdm_m_ce_20260610_090412,tdm_m,ce,0.853267,0.840153,0.576528,0.576528,0.965854,0.977629,0.485640,...,0.485640,0.485640,0.704961,0.704961,46542,46542,20,None,NaN,NaN
7,S7_tdm_m_kd_20260610_100303,tdm_m,kd,0.850498,0.839607,0.588443,0.588443,0.951220,0.975391,0.514360,...,0.514360,0.514360,0.751958,0.751958,46542,46542,28,/content/drive/MyDrive/TinyDisasterVQA/Teacher...,0.7,4.0
8,S8_tdm_m_kd_20260610_101614,tdm_m,kd,0.854374,0.836334,0.571441,0.571441,0.959756,0.970917,0.490862,...,0.490862,0.490862,0.744125,0.744125,46542,46542,31,/content/drive/MyDrive/TinyDisasterVQA/Teacher...,0.7,4.0
5,S5_tdm_m_weighted_ce_20260610_093722,tdm_m,weighted_ce,0.846069,0.830878,0.572978,0.572978,0.964634,0.966443,0.449086,...,0.449086,0.449086,0.720627,0.720627,46542,46542,25,None,NaN,NaN
1,S1_tdm_s_ce_20260610_085317,tdm_s,ce,0.855482,0.845608,0.584631,0.584631,0.965854,0.977629,0.503916,...,0.503916,0.503916,0.741514,0.741514,25814,25814,26,None,NaN,NaN

Saved: /content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10/student_ablation_summary.csv

## Quick best-run view

In [ ]:
if len(df):
    rank_cols = [
        c for c in [
            "run_name",
            "student_variant",
            "mode",
            "test_acc",
            "test_macro_accuracy",
            "test_macro_acc",
            "test_count_exact",
            "test_count_exact_acc",
            "total_params",
            "best_epoch",
        ]
        if c in df.columns
    ]

    metric_col = "test_acc" if "test_acc" in df.columns else None

    if metric_col is not None:
        display(df[rank_cols].sort_values(metric_col, ascending=False).head(10))

,run_name,student_variant,mode,test_acc,test_macro_accuracy,test_macro_acc,test_count_exact,test_count_exact_acc,total_params,best_epoch
4,S4_tdm_fast_ce_20260610_092129,tdm_fast,ce,0.852155,0.603659,0.603659,0.543081,0.543081,91902,41
1,S1_tdm_s_ce_20260610_085317,tdm_s,ce,0.845608,0.584631,0.584631,0.503916,0.503916,25814,26
9,S9_tdm_l_kd_20260610_103020,tdm_l,kd,0.840153,0.590545,0.590545,0.503916,0.503916,101310,15
2,S2_tdm_m_ce_20260610_090412,tdm_m,ce,0.840153,0.576528,0.576528,0.485640,0.485640,46542,20
7,S7_tdm_m_kd_20260610_100303,tdm_m,kd,0.839607,0.588443,0.588443,0.514360,0.514360,46542,28
0,S10_tdm_fast_kd_20260610_103859,tdm_fast,kd,0.836334,0.605157,0.605157,0.553525,0.553525,91902,47
8,S8_tdm_m_kd_20260610_101614,tdm_m,kd,0.836334,0.571441,0.571441,0.490862,0.490862,46542,31
3,S3_tdm_l_ce_20260610_091325,tdm_l,ce,0.833061,0.567783,0.567783,0.459530,0.459530,101310,16
5,S5_tdm_m_weighted_ce_20260610_093722,tdm_m,weighted_ce,0.830878,0.572978,0.572978,0.449086,0.449086,46542,25
6,S6_tdm_l_weighted_ce_20260610_094801,tdm_l,weighted_ce,0.821604,0.550708,0.550708,0.446475,0.446475,101310,12

Basic ablation is done
time for experimentatoin

In [ ]:
%cd /content/TinyDisasterVQA
%env PYTHONPATH=/content/TinyDisasterVQA/src
%env PYTHONUNBUFFERED=1

!python -u scripts/06_train_student.py \
  --dataset-root dataset \
  --runs-dir /content/drive/MyDrive/TinyDisasterVQA/StudentResolutionAblation_R1_R3 \
  --train-csv outputs/training_data_cap5/train.csv \
  --valid-csv outputs/training_data_cap5/valid.csv \
  --test-csv outputs/training_data_cap5/test.csv \
  --metadata outputs/training_data_cap5/metadata.json \
  --class-weights outputs/answer_space_cap5/class_weights_edge_global_by_label.json \
  --student-variant tdm_fast \
  --mode ce \
  --image-size 128 \
  --epochs 50 \
  --batch-size 64 \
  --eval-batch-size 64 \
  --num-workers 2 \
  --device auto \
  --patience 8 \
  --min-delta 0.001 \
  --log-interval 5 \
  --run-name R1_tdm_fast_128_ce_$(date +%Y%m%d_%H%M%S)

/content/TinyDisasterVQA
env: PYTHONPATH=/content/TinyDisasterVQA/src
env: PYTHONUNBUFFERED=1
================================================================================
TinyDisasterVQA / Train TDM Student
================================================================================
Run dir:              /content/drive/MyDrive/TinyDisasterVQA/StudentResolutionAblation_R1_R3/R1_tdm_fast_128_ce_20260610_111228
Device:               cuda
Student variant:      tdm_fast
Mode:                 ce
Count cap:            5
Num classes:          14
Question templates:   31
AMP:                  True
Image size:           128
Batch size:           64
Eval batch:           64
Epochs:               50
LR:                   0.0003
Weight decay:         0.0001
Patience:             8
Min delta:            0.001
KD alpha:             0.0
KD temp:              0.0

Model summary
================================================================================
Class:             TDMFastVQA
Total params:      91,902
Trainable params:  91,902
FP32 param size:   0.35 MB
Int8 param size:   89.7 KB
Student variant:   tdm_fast
Image block type:  conv
Image channels:    (16, 32, 64, 96)
Image feature dim: 96
Template encoder:  one_hot + Linear
Template input dim:31
Template emb dim:  16
Fusion hidden dim: 96
Fusion layers:     1
Num classes:       14
Head type:         single edge_global


================================================================================
Epoch 1/50
================================================================================
Epoch 001 | step 0001/0093 | loss=2.6939 | ce=2.6939 | kd=0.0000 | acc=0.0625 | binary=0.000 | condition=0.000 | count=0.308 | density=0.000 | time=3.0s
Epoch 001 | step 0005/0093 | loss=2.6387 | ce=2.6387 | kd=0.0000 | acc=0.0844 | binary=0.007 | condition=0.218 | count=0.117 | density=0.000 | time=3.2s
Epoch 001 | step 0010/0093 | loss=2.6178 | ce=2.6178 | kd=0.0000 | acc=0.1453 | binary=0.088 | condition=0.370 | count=0.059 | density=0.000 | time=4.3s
Epoch 001 | step 0015/0093 | loss=2.5866 | ce=2.5866 | kd=0.0000 | acc=0.1906 | binary=0.140 | condition=0.479 | count=0.037 | density=0.000 | time=5.2s
Epoch 001 | step 0020/0093 | loss=2.5571 | ce=2.5571 | kd=0.0000 | acc=0.2211 | binary=0.170 | condition=0.535 | count=0.029 | density=0.000 | time=5.7s
Epoch 001 | step 0025/0093 | loss=2.5338 | ce=2.5338 | kd=0.0000 | acc=0.2300 | binary=0.173 | condition=0.564 | count=0.023 | density=0.000 | time=6.4s
Epoch 001 | step 0030/0093 | loss=2.5144 | ce=2.5144 | kd=0.0000 | acc=0.2354 | binary=0.183 | condition=0.583 | count=0.018 | density=0.000 | time=6.9s
Epoch 001 | step 0035/0093 | loss=2.4925 | ce=2.4925 | kd=0.0000 | acc=0.2362 | binary=0.180 | condition=0.598 | count=0.015 | density=0.000 | time=7.6s
Epoch 001 | step 0040/0093 | loss=2.4728 | ce=2.4728 | kd=0.0000 | acc=0.2363 | binary=0.177 | condition=0.615 | count=0.013 | density=0.000 | time=8.1s
Epoch 001 | step 0045/0093 | loss=2.4488 | ce=2.4488 | kd=0.0000 | acc=0.2396 | binary=0.180 | condition=0.624 | count=0.012 | density=0.000 | time=8.7s
Epoch 001 | step 0050/0093 | loss=2.4262 | ce=2.4262 | kd=0.0000 | acc=0.2412 | binary=0.176 | condition=0.631 | count=0.011 | density=0.000 | time=9.2s
Epoch 001 | step 0055/0093 | loss=2.4037 | ce=2.4037 | kd=0.0000 | acc=0.2437 | binary=0.173 | condition=0.645 | count=0.010 | density=0.000 | time=9.9s
Epoch 001 | step 0060/0093 | loss=2.3830 | ce=2.3830 | kd=0.0000 | acc=0.2451 | binary=0.173 | condition=0.655 | count=0.009 | density=0.000 | time=10.4s
Epoch 001 | step 0065/0093 | loss=2.3607 | ce=2.3607 | kd=0.0000 | acc=0.2486 | binary=0.173 | condition=0.663 | count=0.008 | density=0.000 | time=11.0s
Epoch 001 | step 0070/0093 | loss=2.3434 | ce=2.3434 | kd=0.0000 | acc=0.2473 | binary=0.168 | condition=0.671 | count=0.008 | density=0.000 | time=11.6s
Epoch 001 | step 0075/0093 | loss=2.3257 | ce=2.3257 | kd=0.0000 | acc=0.2481 | binary=0.168 | condition=0.674 | count=0.007 | density=0.000 | time=12.2s
Epoch 001 | step 0080/0093 | loss=2.3137 | ce=2.3137 | kd=0.0000 | acc=0.2473 | binary=0.169 | condition=0.675 | count=0.007 | density=0.000 | time=12.7s
Epoch 001 | step 0085/0093 | loss=2.2992 | ce=2.2992 | kd=0.0000 | acc=0.2476 | binary=0.178 | condition=0.663 | count=0.006 | density=0.000 | time=13.3s
Epoch 001 | step 0090/0093 | loss=2.2854 | ce=2.2854 | kd=0.0000 | acc=0.2477 | binary=0.185 | condition=0.654 | count=0.006 | density=0.000 | time=13.9s
Epoch 001 | step 0093/0093 | loss=2.2780 | ce=2.2780 | kd=0.0000 | acc=0.2486 | binary=0.189 | condition=0.649 | count=0.006 | density=0.000 | time=15.8s

train overall: acc=0.2486 (1466/5898)
train macro acc: 0.0843
train count exact: acc=0.0058 (7/1204)
train count ±1: acc=0.0133 (16/1204)
train by edge head:
  binary       acc=0.1894 (499/2634)
  condition    acc=0.6486 (960/1480)
  count        acc=0.0058 (7/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.2345 (136/580)
  Complex_Counting                         acc=0.0048 (3/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.4164 (568/1364)
  Risk_Assessment                          acc=0.2431 (141/580)
  Road_Condition_Recognition               acc=0.3862 (614/1590)
  Simple_Counting                          acc=0.0069 (4/580)

valid overall: acc=0.2918 (527/1806)
valid macro acc: 0.0965
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.4091 (333/814)
  condition    acc=0.4321 (194/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.4830 (85/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.4310 (178/413)
  Risk_Assessment                          acc=0.5455 (96/176)
  Road_Condition_Recognition               acc=0.3373 (168/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 1 done | train_acc=0.2486 | valid_acc=0.2918 | best_valid_acc=0.2918 at epoch 1 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 2/50
================================================================================
Epoch 002 | step 0001/0093 | loss=1.9310 | ce=1.9310 | kd=0.0000 | acc=0.2500 | binary=0.276 | condition=0.364 | count=0.000 | density=0.000 | time=0.3s
Epoch 002 | step 0005/0093 | loss=1.9843 | ce=1.9843 | kd=0.0000 | acc=0.2938 | binary=0.390 | condition=0.451 | count=0.000 | density=0.000 | time=0.7s
Epoch 002 | step 0010/0093 | loss=1.9907 | ce=1.9907 | kd=0.0000 | acc=0.3031 | binary=0.434 | condition=0.429 | count=0.000 | density=0.000 | time=1.3s
Epoch 002 | step 0015/0093 | loss=1.9858 | ce=1.9858 | kd=0.0000 | acc=0.3042 | binary=0.424 | condition=0.436 | count=0.000 | density=0.000 | time=1.9s
Epoch 002 | step 0020/0093 | loss=1.9933 | ce=1.9933 | kd=0.0000 | acc=0.3078 | binary=0.428 | condition=0.459 | count=0.000 | density=0.000 | time=2.4s
Epoch 002 | step 0025/0093 | loss=1.9894 | ce=1.9894 | kd=0.0000 | acc=0.3063 | binary=0.420 | condition=0.478 | count=0.000 | density=0.000 | time=3.1s
Epoch 002 | step 0030/0093 | loss=1.9892 | ce=1.9892 | kd=0.0000 | acc=0.3063 | binary=0.427 | condition=0.466 | count=0.000 | density=0.000 | time=3.6s
Epoch 002 | step 0035/0093 | loss=2.0026 | ce=2.0026 | kd=0.0000 | acc=0.3116 | binary=0.443 | condition=0.470 | count=0.002 | density=0.000 | time=4.2s
Epoch 002 | step 0040/0093 | loss=1.9998 | ce=1.9998 | kd=0.0000 | acc=0.3090 | binary=0.439 | condition=0.462 | count=0.004 | density=0.000 | time=4.8s
Epoch 002 | step 0045/0093 | loss=2.0017 | ce=2.0017 | kd=0.0000 | acc=0.3094 | binary=0.440 | condition=0.461 | count=0.005 | density=0.000 | time=5.3s
Epoch 002 | step 0050/0093 | loss=1.9955 | ce=1.9955 | kd=0.0000 | acc=0.3109 | binary=0.433 | condition=0.473 | count=0.007 | density=0.000 | time=6.0s
Epoch 002 | step 0055/0093 | loss=1.9938 | ce=1.9938 | kd=0.0000 | acc=0.3153 | binary=0.436 | condition=0.489 | count=0.008 | density=0.000 | time=6.5s
Epoch 002 | step 0060/0093 | loss=1.9865 | ce=1.9865 | kd=0.0000 | acc=0.3169 | binary=0.428 | condition=0.514 | count=0.010 | density=0.000 | time=7.2s
Epoch 002 | step 0065/0093 | loss=1.9788 | ce=1.9788 | kd=0.0000 | acc=0.3200 | binary=0.424 | condition=0.525 | count=0.016 | density=0.000 | time=7.6s
Epoch 002 | step 0070/0093 | loss=1.9740 | ce=1.9740 | kd=0.0000 | acc=0.3239 | binary=0.422 | condition=0.541 | count=0.016 | density=0.000 | time=8.3s
Epoch 002 | step 0075/0093 | loss=1.9704 | ce=1.9704 | kd=0.0000 | acc=0.3262 | binary=0.417 | condition=0.552 | count=0.024 | density=0.000 | time=8.9s
Epoch 002 | step 0080/0093 | loss=1.9630 | ce=1.9630 | kd=0.0000 | acc=0.3285 | binary=0.414 | condition=0.554 | count=0.029 | density=0.000 | time=10.0s
Epoch 002 | step 0085/0093 | loss=1.9612 | ce=1.9612 | kd=0.0000 | acc=0.3285 | binary=0.410 | condition=0.557 | count=0.031 | density=0.000 | time=10.9s
Epoch 002 | step 0090/0093 | loss=1.9575 | ce=1.9575 | kd=0.0000 | acc=0.3276 | binary=0.405 | condition=0.561 | count=0.031 | density=0.000 | time=12.0s
Epoch 002 | step 0093/0093 | loss=1.9560 | ce=1.9560 | kd=0.0000 | acc=0.3298 | binary=0.407 | condition=0.565 | count=0.030 | density=0.000 | time=12.2s

train overall: acc=0.3298 (1945/5898)
train macro acc: 0.1117
train count exact: acc=0.0299 (36/1204)
train count ±1: acc=0.0299 (36/1204)
train by edge head:
  binary       acc=0.4074 (1073/2634)
  condition    acc=0.5649 (836/1480)
  count        acc=0.0299 (36/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.4759 (276/580)
  Complex_Counting                         acc=0.0224 (14/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.4839 (660/1364)
  Risk_Assessment                          acc=0.5879 (341/580)
  Road_Condition_Recognition               acc=0.3975 (632/1590)
  Simple_Counting                          acc=0.0379 (22/580)

valid overall: acc=0.3538 (639/1806)
valid macro acc: 0.1186
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.3931 (320/814)
  condition    acc=0.7105 (319/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.4886 (86/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.5617 (232/413)
  Risk_Assessment                          acc=0.4716 (83/176)
  Road_Condition_Recognition               acc=0.4779 (238/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 2 done | train_acc=0.3298 | valid_acc=0.3538 | best_valid_acc=0.3538 at epoch 2 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 3/50
================================================================================
Epoch 003 | step 0001/0093 | loss=1.8971 | ce=1.8971 | kd=0.0000 | acc=0.4219 | binary=0.480 | condition=0.700 | count=0.100 | density=0.000 | time=0.3s
Epoch 003 | step 0005/0093 | loss=1.8764 | ce=1.8764 | kd=0.0000 | acc=0.3563 | binary=0.409 | condition=0.693 | count=0.017 | density=0.000 | time=0.7s
Epoch 003 | step 0010/0093 | loss=1.9171 | ce=1.9171 | kd=0.0000 | acc=0.3797 | binary=0.489 | condition=0.687 | count=0.030 | density=0.000 | time=1.3s
Epoch 003 | step 0015/0093 | loss=1.8870 | ce=1.8870 | kd=0.0000 | acc=0.4021 | binary=0.502 | condition=0.691 | count=0.046 | density=0.000 | time=1.9s
Epoch 003 | step 0020/0093 | loss=1.9015 | ce=1.9015 | kd=0.0000 | acc=0.4047 | binary=0.508 | condition=0.696 | count=0.052 | density=0.000 | time=2.4s
Epoch 003 | step 0025/0093 | loss=1.8956 | ce=1.8956 | kd=0.0000 | acc=0.4081 | binary=0.506 | condition=0.711 | count=0.054 | density=0.000 | time=3.1s
Epoch 003 | step 0030/0093 | loss=1.8801 | ce=1.8801 | kd=0.0000 | acc=0.4172 | binary=0.514 | condition=0.720 | count=0.059 | density=0.000 | time=3.6s
Epoch 003 | step 0035/0093 | loss=1.8722 | ce=1.8722 | kd=0.0000 | acc=0.4214 | binary=0.518 | condition=0.726 | count=0.061 | density=0.000 | time=4.3s
Epoch 003 | step 0040/0093 | loss=1.8678 | ce=1.8678 | kd=0.0000 | acc=0.4207 | binary=0.513 | condition=0.723 | count=0.067 | density=0.000 | time=4.8s
Epoch 003 | step 0045/0093 | loss=1.8546 | ce=1.8546 | kd=0.0000 | acc=0.4260 | binary=0.517 | condition=0.720 | count=0.078 | density=0.000 | time=5.4s
Epoch 003 | step 0050/0093 | loss=1.8562 | ce=1.8562 | kd=0.0000 | acc=0.4259 | binary=0.516 | condition=0.711 | count=0.084 | density=0.000 | time=5.9s
Epoch 003 | step 0055/0093 | loss=1.8525 | ce=1.8525 | kd=0.0000 | acc=0.4307 | binary=0.522 | condition=0.717 | count=0.089 | density=0.000 | time=6.6s
Epoch 003 | step 0060/0093 | loss=1.8579 | ce=1.8579 | kd=0.0000 | acc=0.4294 | binary=0.520 | condition=0.723 | count=0.089 | density=0.000 | time=7.1s
Epoch 003 | step 0065/0093 | loss=1.8524 | ce=1.8524 | kd=0.0000 | acc=0.4322 | binary=0.526 | condition=0.725 | count=0.093 | density=0.000 | time=7.8s
Epoch 003 | step 0070/0093 | loss=1.8475 | ce=1.8475 | kd=0.0000 | acc=0.4353 | binary=0.530 | condition=0.727 | count=0.094 | density=0.000 | time=8.5s
Epoch 003 | step 0075/0093 | loss=1.8393 | ce=1.8393 | kd=0.0000 | acc=0.4394 | binary=0.530 | condition=0.735 | count=0.096 | density=0.000 | time=9.6s
Epoch 003 | step 0080/0093 | loss=1.8337 | ce=1.8337 | kd=0.0000 | acc=0.4389 | binary=0.523 | condition=0.745 | count=0.099 | density=0.000 | time=10.3s
Epoch 003 | step 0085/0093 | loss=1.8250 | ce=1.8250 | kd=0.0000 | acc=0.4417 | binary=0.526 | condition=0.749 | count=0.097 | density=0.000 | time=11.5s
Epoch 003 | step 0090/0093 | loss=1.8168 | ce=1.8168 | kd=0.0000 | acc=0.4443 | binary=0.529 | condition=0.751 | count=0.095 | density=0.000 | time=12.3s
Epoch 003 | step 0093/0093 | loss=1.8160 | ce=1.8160 | kd=0.0000 | acc=0.4447 | binary=0.530 | condition=0.754 | count=0.093 | density=0.000 | time=12.7s

train overall: acc=0.4447 (2623/5898)
train macro acc: 0.1592
train count exact: acc=0.0930 (112/1204)
train count ±1: acc=0.0930 (112/1204)
train by edge head:
  binary       acc=0.5296 (1395/2634)
  condition    acc=0.7541 (1116/1480)
  count        acc=0.0930 (112/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.5069 (294/580)
  Complex_Counting                         acc=0.0817 (51/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.6642 (906/1364)
  Risk_Assessment                          acc=0.7603 (441/580)
  Road_Condition_Recognition               acc=0.5472 (870/1590)
  Simple_Counting                          acc=0.1052 (61/580)

valid overall: acc=0.5288 (955/1806)
valid macro acc: 0.1737
valid count exact: acc=0.0163 (6/367)
valid count ±1: acc=0.0163 (6/367)
valid by edge head:
  binary       acc=0.7162 (583/814)
  condition    acc=0.8151 (366/449)
  count        acc=0.0163 (6/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.6875 (121/176)
  Complex_Counting                         acc=0.0105 (2/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.8208 (339/413)
  Risk_Assessment                          acc=0.9148 (161/176)
  Road_Condition_Recognition               acc=0.6586 (328/498)
  Simple_Counting                          acc=0.0227 (4/176)

Epoch 3 done | train_acc=0.4447 | valid_acc=0.5288 | best_valid_acc=0.5288 at epoch 3 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 4/50
================================================================================
Epoch 004 | step 0001/0093 | loss=1.8150 | ce=1.8150 | kd=0.0000 | acc=0.4688 | binary=0.679 | condition=0.667 | count=0.091 | density=0.000 | time=0.3s
Epoch 004 | step 0005/0093 | loss=1.6847 | ce=1.6847 | kd=0.0000 | acc=0.5156 | binary=0.684 | condition=0.737 | count=0.056 | density=0.000 | time=0.7s
Epoch 004 | step 0010/0093 | loss=1.6812 | ce=1.6812 | kd=0.0000 | acc=0.5094 | binary=0.673 | condition=0.808 | count=0.032 | density=0.000 | time=1.2s
Epoch 004 | step 0015/0093 | loss=1.7050 | ce=1.7050 | kd=0.0000 | acc=0.5010 | binary=0.663 | condition=0.816 | count=0.040 | density=0.000 | time=1.9s
Epoch 004 | step 0020/0093 | loss=1.6874 | ce=1.6874 | kd=0.0000 | acc=0.5148 | binary=0.670 | condition=0.816 | count=0.057 | density=0.000 | time=2.5s
Epoch 004 | step 0025/0093 | loss=1.6890 | ce=1.6890 | kd=0.0000 | acc=0.5094 | binary=0.662 | condition=0.806 | count=0.070 | density=0.000 | time=3.1s
Epoch 004 | step 0030/0093 | loss=1.6890 | ce=1.6890 | kd=0.0000 | acc=0.5141 | binary=0.662 | condition=0.821 | count=0.082 | density=0.000 | time=3.6s
Epoch 004 | step 0035/0093 | loss=1.6872 | ce=1.6872 | kd=0.0000 | acc=0.5143 | binary=0.669 | condition=0.819 | count=0.087 | density=0.000 | time=4.3s
Epoch 004 | step 0040/0093 | loss=1.6860 | ce=1.6860 | kd=0.0000 | acc=0.5133 | binary=0.665 | condition=0.818 | count=0.094 | density=0.000 | time=4.8s
Epoch 004 | step 0045/0093 | loss=1.6746 | ce=1.6746 | kd=0.0000 | acc=0.5139 | binary=0.659 | condition=0.818 | count=0.097 | density=0.000 | time=5.4s
Epoch 004 | step 0050/0093 | loss=1.6626 | ce=1.6626 | kd=0.0000 | acc=0.5194 | binary=0.661 | condition=0.823 | count=0.104 | density=0.000 | time=5.9s
Epoch 004 | step 0055/0093 | loss=1.6576 | ce=1.6576 | kd=0.0000 | acc=0.5210 | binary=0.663 | condition=0.824 | count=0.118 | density=0.000 | time=6.6s
Epoch 004 | step 0060/0093 | loss=1.6569 | ce=1.6569 | kd=0.0000 | acc=0.5188 | binary=0.659 | condition=0.824 | count=0.123 | density=0.000 | time=7.2s
Epoch 004 | step 0065/0093 | loss=1.6437 | ce=1.6437 | kd=0.0000 | acc=0.5228 | binary=0.658 | condition=0.825 | count=0.131 | density=0.000 | time=8.2s
Epoch 004 | step 0070/0093 | loss=1.6318 | ce=1.6318 | kd=0.0000 | acc=0.5254 | binary=0.657 | condition=0.826 | count=0.135 | density=0.000 | time=9.0s
Epoch 004 | step 0075/0093 | loss=1.6225 | ce=1.6225 | kd=0.0000 | acc=0.5296 | binary=0.664 | condition=0.827 | count=0.133 | density=0.000 | time=10.2s
Epoch 004 | step 0080/0093 | loss=1.6138 | ce=1.6138 | kd=0.0000 | acc=0.5297 | binary=0.662 | condition=0.832 | count=0.130 | density=0.000 | time=11.0s
Epoch 004 | step 0085/0093 | loss=1.6059 | ce=1.6059 | kd=0.0000 | acc=0.5298 | binary=0.664 | condition=0.831 | count=0.126 | density=0.000 | time=12.0s
Epoch 004 | step 0090/0093 | loss=1.5974 | ce=1.5974 | kd=0.0000 | acc=0.5288 | binary=0.659 | condition=0.834 | count=0.122 | density=0.000 | time=12.5s
Epoch 004 | step 0093/0093 | loss=1.5959 | ce=1.5959 | kd=0.0000 | acc=0.5273 | binary=0.658 | condition=0.833 | count=0.120 | density=0.000 | time=12.7s

train overall: acc=0.5273 (3110/5898)
train macro acc: 0.1923
train count exact: acc=0.1196 (144/1204)
train count ±1: acc=0.1196 (144/1204)
train by edge head:
  binary       acc=0.6579 (1733/2634)
  condition    acc=0.8331 (1233/1480)
  count        acc=0.1196 (144/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.6103 (354/580)
  Complex_Counting                         acc=0.1170 (73/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.7925 (1081/1364)
  Risk_Assessment                          acc=0.8672 (503/580)

In [ ]:
%cd /content/TinyDisasterVQA
%env PYTHONPATH=/content/TinyDisasterVQA/src
%env PYTHONUNBUFFERED=1

!python -u scripts/06_train_student.py \
  --dataset-root dataset \
  --runs-dir /content/drive/MyDrive/TinyDisasterVQA/StudentResolutionAblation_R1_R3 \
  --train-csv outputs/training_data_cap5/train.csv \
  --valid-csv outputs/training_data_cap5/valid.csv \
  --test-csv outputs/training_data_cap5/test.csv \
  --metadata outputs/training_data_cap5/metadata.json \
  --class-weights outputs/answer_space_cap5/class_weights_edge_global_by_label.json \
  --student-variant tdm_s \
  --mode ce \
  --image-size 128 \
  --epochs 50 \
  --batch-size 64 \
  --eval-batch-size 64 \
  --num-workers 2 \
  --device auto \
  --patience 8 \
  --min-delta 0.001 \
  --log-interval 5 \
  --run-name R2_tdm_s_128_ce_$(date +%Y%m%d_%H%M%S)

/content/TinyDisasterVQA
env: PYTHONPATH=/content/TinyDisasterVQA/src
env: PYTHONUNBUFFERED=1
================================================================================
TinyDisasterVQA / Train TDM Student
================================================================================
Run dir:              /content/drive/MyDrive/TinyDisasterVQA/StudentResolutionAblation_R1_R3/R2_tdm_s_128_ce_20260610_112222
Device:               cuda
Student variant:      tdm_s
Mode:                 ce
Count cap:            5
Num classes:          14
Question templates:   31
AMP:                  True
Image size:           128
Batch size:           64
Eval batch:           64
Epochs:               50
LR:                   0.0003
Weight decay:         0.0001
Patience:             8
Min delta:            0.001
KD alpha:             0.0
KD temp:              0.0

Model summary
================================================================================
Class:             TDMSVQA
Total params:      25,814
Trainable params:  25,814
FP32 param size:   0.10 MB
Int8 param size:   25.2 KB
Student variant:   tdm_s
Image block type:  dsconv
Image channels:    (12, 24, 48, 64, 96)
Image feature dim: 96
Template encoder:  one_hot + Linear
Template input dim:31
Template emb dim:  16
Fusion hidden dim: 96
Fusion layers:     1
Num classes:       14
Head type:         single edge_global


================================================================================
Epoch 1/50
================================================================================
Epoch 001 | step 0001/0093 | loss=2.6564 | ce=2.6564 | kd=0.0000 | acc=0.0000 | binary=0.000 | condition=0.000 | count=0.000 | density=0.000 | time=5.2s
Epoch 001 | step 0005/0093 | loss=2.6389 | ce=2.6389 | kd=0.0000 | acc=0.0656 | binary=0.136 | condition=0.000 | count=0.000 | density=0.000 | time=5.4s
Epoch 001 | step 0010/0093 | loss=2.6206 | ce=2.6206 | kd=0.0000 | acc=0.1219 | binary=0.265 | condition=0.000 | count=0.000 | density=0.000 | time=6.4s
Epoch 001 | step 0015/0093 | loss=2.5988 | ce=2.5988 | kd=0.0000 | acc=0.1406 | binary=0.307 | condition=0.000 | count=0.000 | density=0.000 | time=7.3s
Epoch 001 | step 0020/0093 | loss=2.5818 | ce=2.5818 | kd=0.0000 | acc=0.1602 | binary=0.355 | condition=0.000 | count=0.000 | density=0.000 | time=8.5s
Epoch 001 | step 0025/0093 | loss=2.5652 | ce=2.5652 | kd=0.0000 | acc=0.1719 | binary=0.382 | condition=0.000 | count=0.000 | density=0.000 | time=9.1s
Epoch 001 | step 0030/0093 | loss=2.5509 | ce=2.5509 | kd=0.0000 | acc=0.1766 | binary=0.400 | condition=0.000 | count=0.000 | density=0.000 | time=9.8s
Epoch 001 | step 0035/0093 | loss=2.5312 | ce=2.5312 | kd=0.0000 | acc=0.1804 | binary=0.409 | condition=0.000 | count=0.000 | density=0.000 | time=10.3s
Epoch 001 | step 0040/0093 | loss=2.5112 | ce=2.5112 | kd=0.0000 | acc=0.1828 | binary=0.412 | condition=0.000 | count=0.000 | density=0.000 | time=10.9s
Epoch 001 | step 0045/0093 | loss=2.4906 | ce=2.4906 | kd=0.0000 | acc=0.1885 | binary=0.422 | condition=0.000 | count=0.000 | density=0.000 | time=11.4s
Epoch 001 | step 0050/0093 | loss=2.4730 | ce=2.4730 | kd=0.0000 | acc=0.1900 | binary=0.426 | condition=0.000 | count=0.000 | density=0.000 | time=12.1s
Epoch 001 | step 0055/0093 | loss=2.4533 | ce=2.4533 | kd=0.0000 | acc=0.1940 | binary=0.436 | condition=0.000 | count=0.000 | density=0.000 | time=12.6s
Epoch 001 | step 0060/0093 | loss=2.4397 | ce=2.4397 | kd=0.0000 | acc=0.1956 | binary=0.441 | condition=0.000 | count=0.000 | density=0.000 | time=13.2s
Epoch 001 | step 0065/0093 | loss=2.4222 | ce=2.4222 | kd=0.0000 | acc=0.1971 | binary=0.443 | condition=0.000 | count=0.000 | density=0.000 | time=13.7s
Epoch 001 | step 0070/0093 | loss=2.4023 | ce=2.4023 | kd=0.0000 | acc=0.2029 | binary=0.454 | condition=0.000 | count=0.000 | density=0.000 | time=14.4s
Epoch 001 | step 0075/0093 | loss=2.3887 | ce=2.3887 | kd=0.0000 | acc=0.2044 | binary=0.459 | condition=0.000 | count=0.000 | density=0.000 | time=14.9s
Epoch 001 | step 0080/0093 | loss=2.3721 | ce=2.3721 | kd=0.0000 | acc=0.2047 | binary=0.458 | condition=0.000 | count=0.000 | density=0.000 | time=15.5s
Epoch 001 | step 0085/0093 | loss=2.3572 | ce=2.3572 | kd=0.0000 | acc=0.2050 | binary=0.459 | condition=0.001 | count=0.000 | density=0.000 | time=16.1s
Epoch 001 | step 0090/0093 | loss=2.3389 | ce=2.3389 | kd=0.0000 | acc=0.2123 | binary=0.466 | condition=0.018 | count=0.000 | density=0.000 | time=16.7s
Epoch 001 | step 0093/0093 | loss=2.3345 | ce=2.3345 | kd=0.0000 | acc=0.2150 | binary=0.467 | condition=0.026 | count=0.000 | density=0.000 | time=21.3s

train overall: acc=0.2150 (1268/5898)
train macro acc: 0.0710
train count exact: acc=0.0000 (0/1204)
train count ±1: acc=0.0066 (8/1204)
train by edge head:
  binary       acc=0.4666 (1229/2634)
  condition    acc=0.0264 (39/1480)
  count        acc=0.0000 (0/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.5328 (309/580)
  Complex_Counting                         acc=0.0000 (0/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.2588 (353/1364)
  Risk_Assessment                          acc=0.2362 (137/580)
  Road_Condition_Recognition               acc=0.2950 (469/1590)
  Simple_Counting                          acc=0.0000 (0/580)

valid overall: acc=0.3306 (597/1806)
valid macro acc: 0.1032
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.4410 (359/814)
  condition    acc=0.5301 (238/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.4716 (83/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.4915 (203/413)
  Risk_Assessment                          acc=0.5341 (94/176)
  Road_Condition_Recognition               acc=0.4357 (217/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 1 done | train_acc=0.2150 | valid_acc=0.3306 | best_valid_acc=0.3306 at epoch 1 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 2/50
================================================================================
Epoch 002 | step 0001/0093 | loss=2.0535 | ce=2.0535 | kd=0.0000 | acc=0.2344 | binary=0.258 | condition=0.412 | count=0.000 | density=0.000 | time=0.3s
Epoch 002 | step 0005/0093 | loss=2.0896 | ce=2.0896 | kd=0.0000 | acc=0.2969 | binary=0.367 | condition=0.500 | count=0.000 | density=0.000 | time=0.8s
Epoch 002 | step 0010/0093 | loss=2.0890 | ce=2.0890 | kd=0.0000 | acc=0.2922 | binary=0.394 | condition=0.452 | count=0.000 | density=0.000 | time=1.3s
Epoch 002 | step 0015/0093 | loss=2.0964 | ce=2.0964 | kd=0.0000 | acc=0.2885 | binary=0.408 | condition=0.414 | count=0.000 | density=0.000 | time=1.9s
Epoch 002 | step 0020/0093 | loss=2.0865 | ce=2.0865 | kd=0.0000 | acc=0.2938 | binary=0.426 | condition=0.387 | count=0.000 | density=0.000 | time=2.4s
Epoch 002 | step 0025/0093 | loss=2.1056 | ce=2.1056 | kd=0.0000 | acc=0.2944 | binary=0.442 | condition=0.386 | count=0.000 | density=0.000 | time=3.0s
Epoch 002 | step 0030/0093 | loss=2.0978 | ce=2.0978 | kd=0.0000 | acc=0.3000 | binary=0.450 | condition=0.392 | count=0.000 | density=0.000 | time=3.7s
Epoch 002 | step 0035/0093 | loss=2.0960 | ce=2.0960 | kd=0.0000 | acc=0.3027 | binary=0.440 | condition=0.422 | count=0.000 | density=0.000 | time=4.2s
Epoch 002 | step 0040/0093 | loss=2.0893 | ce=2.0893 | kd=0.0000 | acc=0.3051 | binary=0.430 | condition=0.440 | count=0.000 | density=0.000 | time=4.9s
Epoch 002 | step 0045/0093 | loss=2.0880 | ce=2.0880 | kd=0.0000 | acc=0.3059 | binary=0.424 | condition=0.458 | count=0.000 | density=0.000 | time=5.4s
Epoch 002 | step 0050/0093 | loss=2.0881 | ce=2.0881 | kd=0.0000 | acc=0.3091 | binary=0.423 | condition=0.476 | count=0.000 | density=0.000 | time=6.0s
Epoch 002 | step 0055/0093 | loss=2.0766 | ce=2.0766 | kd=0.0000 | acc=0.3156 | binary=0.424 | condition=0.494 | count=0.000 | density=0.000 | time=6.6s
Epoch 002 | step 0060/0093 | loss=2.0729 | ce=2.0729 | kd=0.0000 | acc=0.3219 | binary=0.428 | condition=0.511 | count=0.000 | density=0.000 | time=7.2s
Epoch 002 | step 0065/0093 | loss=2.0726 | ce=2.0726 | kd=0.0000 | acc=0.3212 | binary=0.421 | condition=0.521 | count=0.000 | density=0.000 | time=7.8s
Epoch 002 | step 0070/0093 | loss=2.0772 | ce=2.0772 | kd=0.0000 | acc=0.3212 | binary=0.418 | condition=0.534 | count=0.000 | density=0.000 | time=8.8s
Epoch 002 | step 0075/0093 | loss=2.0685 | ce=2.0685 | kd=0.0000 | acc=0.3250 | binary=0.419 | condition=0.546 | count=0.000 | density=0.000 | time=9.8s
Epoch 002 | step 0080/0093 | loss=2.0633 | ce=2.0633 | kd=0.0000 | acc=0.3266 | binary=0.418 | condition=0.554 | count=0.000 | density=0.000 | time=10.9s
Epoch 002 | step 0085/0093 | loss=2.0578 | ce=2.0578 | kd=0.0000 | acc=0.3296 | binary=0.422 | condition=0.558 | count=0.000 | density=0.000 | time=11.8s
Epoch 002 | step 0090/0093 | loss=2.0551 | ce=2.0551 | kd=0.0000 | acc=0.3293 | binary=0.425 | condition=0.554 | count=0.000 | density=0.000 | time=12.8s
Epoch 002 | step 0093/0093 | loss=2.0556 | ce=2.0556 | kd=0.0000 | acc=0.3311 | binary=0.430 | condition=0.555 | count=0.000 | density=0.000 | time=13.0s

train overall: acc=0.3311 (1953/5898)
train macro acc: 0.1059
train count exact: acc=0.0000 (0/1204)
train count ±1: acc=0.0000 (0/1204)
train by edge head:
  binary       acc=0.4298 (1132/2634)
  condition    acc=0.5547 (821/1480)
  count        acc=0.0000 (0/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.4310 (250/580)
  Complex_Counting                         acc=0.0000 (0/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.5029 (686/1364)
  Risk_Assessment                          acc=0.5310 (308/580)
  Road_Condition_Recognition               acc=0.4459 (709/1590)
  Simple_Counting                          acc=0.0000 (0/580)

valid overall: acc=0.3920 (708/1806)
valid macro acc: 0.1225
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.5516 (449/814)
  condition    acc=0.5768 (259/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.5057 (89/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.5956 (246/413)
  Risk_Assessment                          acc=0.6648 (117/176)
  Road_Condition_Recognition               acc=0.5141 (256/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 2 done | train_acc=0.3311 | valid_acc=0.3920 | best_valid_acc=0.3920 at epoch 2 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 3/50
================================================================================
Epoch 003 | step 0001/0093 | loss=1.9537 | ce=1.9537 | kd=0.0000 | acc=0.4531 | binary=0.562 | condition=0.846 | count=0.000 | density=0.000 | time=0.3s
Epoch 003 | step 0005/0093 | loss=1.9682 | ce=1.9682 | kd=0.0000 | acc=0.4156 | binary=0.558 | condition=0.653 | count=0.000 | density=0.000 | time=0.8s
Epoch 003 | step 0010/0093 | loss=2.0342 | ce=2.0342 | kd=0.0000 | acc=0.3688 | binary=0.520 | condition=0.602 | count=0.000 | density=0.000 | time=1.3s
Epoch 003 | step 0015/0093 | loss=1.9978 | ce=1.9978 | kd=0.0000 | acc=0.3833 | binary=0.518 | condition=0.647 | count=0.000 | density=0.000 | time=1.9s
Epoch 003 | step 0020/0093 | loss=2.0006 | ce=2.0006 | kd=0.0000 | acc=0.3844 | binary=0.515 | condition=0.664 | count=0.000 | density=0.000 | time=2.5s
Epoch 003 | step 0025/0093 | loss=1.9924 | ce=1.9924 | kd=0.0000 | acc=0.3800 | binary=0.496 | condition=0.669 | count=0.003 | density=0.000 | time=3.2s
Epoch 003 | step 0030/0093 | loss=1.9822 | ce=1.9822 | kd=0.0000 | acc=0.3906 | binary=0.511 | condition=0.686 | count=0.005 | density=0.000 | time=3.7s
Epoch 003 | step 0035/0093 | loss=1.9698 | ce=1.9698 | kd=0.0000 | acc=0.3978 | binary=0.510 | condition=0.698 | count=0.008 | density=0.000 | time=4.3s
Epoch 003 | step 0040/0093 | loss=1.9636 | ce=1.9636 | kd=0.0000 | acc=0.3953 | binary=0.493 | condition=0.708 | count=0.009 | density=0.000 | time=4.8s
Epoch 003 | step 0045/0093 | loss=1.9496 | ce=1.9496 | kd=0.0000 | acc=0.4007 | binary=0.493 | condition=0.724 | count=0.013 | density=0.000 | time=5.5s
Epoch 003 | step 0050/0093 | loss=1.9526 | ce=1.9526 | kd=0.0000 | acc=0.3987 | binary=0.489 | condition=0.726 | count=0.017 | density=0.000 | time=6.0s
Epoch 003 | step 0055/0093 | loss=1.9431 | ce=1.9431 | kd=0.0000 | acc=0.4003 | binary=0.490 | condition=0.731 | count=0.019 | density=0.000 | time=6.7s
Epoch 003 | step 0060/0093 | loss=1.9385 | ce=1.9385 | kd=0.0000 | acc=0.4016 | binary=0.494 | condition=0.728 | count=0.020 | density=0.000 | time=7.3s
Epoch 003 | step 0065/0093 | loss=1.9383 | ce=1.9383 | kd=0.0000 | acc=0.4014 | binary=0.497 | condition=0.718 | count=0.027 | density=0.000 | time=8.5s
Epoch 003 | step 0070/0093 | loss=1.9250 | ce=1.9250 | kd=0.0000 | acc=0.4051 | binary=0.500 | condition=0.712 | count=0.028 | density=0.000 | time=9.3s
Epoch 003 | step 0075/0093 | loss=1.9191 | ce=1.9191 | kd=0.0000 | acc=0.4075 | binary=0.505 | condition=0.708 | count=0.031 | density=0.000 | time=10.5s
Epoch 003 | step 0080/0093 | loss=1.9116 | ce=1.9116 | kd=0.0000 | acc=0.4135 | binary=0.515 | condition=0.708 | count=0.034 | density=0.000 | time=11.3s
Epoch 003 | step 0085/0093 | loss=1.9053 | ce=1.9053 | kd=0.0000 | acc=0.4169 | binary=0.520 | condition=0.712 | count=0.036 | density=0.000 | time=12.1s
Epoch 003 | step 0090/0093 | loss=1.8967 | ce=1.8967 | kd=0.0000 | acc=0.4227 | binary=0.528 | condition=0.717 | count=0.036 | density=0.000 | time=12.7s
Epoch 003 | step 0093/0093 | loss=1.8911 | ce=1.8911 | kd=0.0000 | acc=0.4259 | binary=0.531 | condition=0.721 | count=0.039 | density=0.000 | time=12.9s

train overall: acc=0.4259 (2512/5898)
train macro acc: 0.1437
train count exact: acc=0.0390 (47/1204)
train count ±1: acc=0.0390 (47/1204)
train by edge head:
  binary       acc=0.5308 (1398/2634)
  condition    acc=0.7209 (1067/1480)
  count        acc=0.0390 (47/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.5586 (324/580)
  Complex_Counting                         acc=0.0385 (24/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.6657 (908/1364)
  Risk_Assessment                          acc=0.6138 (356/580)
  Road_Condition_Recognition               acc=0.5516 (877/1590)
  Simple_Counting                          acc=0.0397 (23/580)

valid overall: acc=0.5155 (931/1806)
valid macro acc: 0.1801
valid count exact: acc=0.0872 (32/367)
valid count ±1: acc=0.0872 (32/367)
valid by edge head:
  binary       acc=0.6548 (533/814)
  condition    acc=0.8151 (366/449)
  count        acc=0.0872 (32/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.6364 (112/176)
  Complex_Counting                         acc=0.0785 (15/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.7893 (326/413)
  Risk_Assessment                          acc=0.7045 (124/176)
  Road_Condition_Recognition               acc=0.6767 (337/498)
  Simple_Counting                          acc=0.0966 (17/176)

Epoch 3 done | train_acc=0.4259 | valid_acc=0.5155 | best_valid_acc=0.5155 at epoch 3 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 4/50
================================================================================
Epoch 004 | step 0001/0093 | loss=1.7290 | ce=1.7290 | kd=0.0000 | acc=0.5312 | binary=0.591 | condition=0.909 | count=0.062 | density=0.000 | time=0.3s
Epoch 004 | step 0005/0093 | loss=1.7082 | ce=1.7082 | kd=0.0000 | acc=0.5031 | binary=0.551 | condition=0.878 | count=0.099 | density=0.000 | time=0.7s
Epoch 004 | step 0010/0093 | loss=1.7096 | ce=1.7096 | kd=0.0000 | acc=0.4906 | binary=0.559 | condition=0.850 | count=0.075 | density=0.000 | time=1.2s
Epoch 004 | step 0015/0093 | loss=1.7210 | ce=1.7210 | kd=0.0000 | acc=0.4813 | binary=0.551 | condition=0.853 | count=0.070 | density=0.000 | time=1.9s
Epoch 004 | step 0020/0093 | loss=1.7001 | ce=1.7001 | kd=0.0000 | acc=0.4805 | binary=0.541 | condition=0.852 | count=0.084 | density=0.000 | time=2.4s
Epoch 004 | step 0025/0093 | loss=1.7065 | ce=1.7065 | kd=0.0000 | acc=0.4769 | binary=0.547 | condition=0.838 | count=0.100 | density=0.000 | time=3.0s
Epoch 004 | step 0030/0093 | loss=1.6979 | ce=1.6979 | kd=0.0000 | acc=0.4823 | binary=0.557 | condition=0.834 | count=0.102 | density=0.000 | time=3.6s
Epoch 004 | step 0035/0093 | loss=1.7083 | ce=1.7083 | kd=0.0000 | acc=0.4862 | binary=0.573 | condition=0.826 | count=0.099 | density=0.000 | time=4.3s
Epoch 004 | step 0040/0093 | loss=1.6761 | ce=1.6761 | kd=0.0000 | acc=0.5102 | binary=0.601 | condition=0.836 | count=0.112 | density=0.000 | time=4.8s
Epoch 004 | step 0045/0093 | loss=1.6820 | ce=1.6820 | kd=0.0000 | acc=0.5163 | binary=0.618 | condition=0.844 | count=0.116 | density=0.000 | time=5.4s
Epoch 004 | step 0050/0093 | loss=1.6760 | ce=1.6760 | kd=0.0000 | acc=0.5222 | binary=0.632 | condition=0.841 | count=0.125 | density=0.000 | time=6.1s
Epoch 004 | step 0055/0093 | loss=1.6636 | ce=1.6636 | kd=0.0000 | acc=0.5295 | binary=0.642 | condition=0.845 | count=0.128 | density=0.000 | time=7.1s
Epoch 004 | step 0060/0093 | loss=1.6647 | ce=1.6647 | kd=0.0000 | acc=0.5253 | binary=0.640 | condition=0.842 | count=0.123 | density=0.000 | time=8.0s
Epoch 004 | step 0065/0093 | loss=1.6572 | ce=1.6572 | kd=0.0000 | acc=0.5272 | binary=0.648 | condition=0.838 | count=0.123 | density=0.000 | time=9.0s
Epoch 004 | step 0070/0093 | loss=1.6489 | ce=1.6489 | kd=0.0000 | acc=0.5290 | binary=0.651 | condition=0.839 | count=0.123 | density=0.000 | time=10.1s
Epoch 004 | step 0075/0093 | loss=1.6405 | ce=1.6405 | kd=0.0000 | acc=0.5337 | binary=0.662 | condition=0.837 | count=0.125 | density=0.000 | time=11.0s
Epoch 004 | step 0080/0093 | loss=1.6329 | ce=1.6329 | kd=0.0000 | acc=0.5350 | binary=0.666 | condition=0.836 | count=0.126 | density=0.000 | time=11.5s
Epoch 004 | step 0085/0093 | loss=1.6312 | ce=1.6312 | kd=0.0000 | acc=0.5336 | binary=0.668 | condition=0.836 | count=0.124 | density=0.000 | time=12.2s
Epoch 004 | step 0090/0093 | loss=1.6243 | ce=1.6243 | kd=0.0000 | acc=0.5358 | binary=0.668 | condition=0.841 | count=0.129 | density=0.000 | time=12.7s
Epoch 004 | step 0093/0093 | loss=1.6228 | ce=1.6228 | kd=0.0000 | acc=0.5368 | binary=0.669 | condition=0.843 | count=0.129 | density=0.000 | time=12.9s

train overall: acc=0.5368 (3166/5898)
train macro acc: 0.1955
train count exact: acc=0.1287 (155/1204)
train count ±1: acc=0.1287 (155/1204)
train by edge head:
  binary       acc=0.6693 (1763/2634)
  condition    acc=0.8432 (1248/1480)
  count        acc=0.1287 (155/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.6690 (388/580)
  Complex_Counting                         acc=0.1106 (69/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.7991 (1090/1364)
  Risk_Assessment                          acc=0.7638 (443/580)

In [ ]:
%cd /content/TinyDisasterVQA
%env PYTHONPATH=/content/TinyDisasterVQA/src
%env PYTHONUNBUFFERED=1

!python -u scripts/06_train_student.py \
  --dataset-root dataset \
  --runs-dir /content/drive/MyDrive/TinyDisasterVQA/StudentResolutionAblation_R1_R3 \
  --train-csv outputs/training_data_cap5/train.csv \
  --valid-csv outputs/training_data_cap5/valid.csv \
  --test-csv outputs/training_data_cap5/test.csv \
  --metadata outputs/training_data_cap5/metadata.json \
  --class-weights outputs/answer_space_cap5/class_weights_edge_global_by_label.json \
  --student-variant tdm_xs \
  --mode ce \
  --image-size 128 \
  --epochs 50 \
  --batch-size 64 \
  --eval-batch-size 64 \
  --num-workers 2 \
  --device auto \
  --patience 8 \
  --min-delta 0.001 \
  --log-interval 5 \
  --run-name R3_tdm_xs_128_ce_$(date +%Y%m%d_%H%M%S)

/content/TinyDisasterVQA
env: PYTHONPATH=/content/TinyDisasterVQA/src
env: PYTHONUNBUFFERED=1
================================================================================
TinyDisasterVQA / Train TDM Student
================================================================================
Run dir:              /content/drive/MyDrive/TinyDisasterVQA/StudentResolutionAblation_R1_R3/R3_tdm_xs_128_ce_20260610_113433
Device:               cuda
Student variant:      tdm_xs
Mode:                 ce
Count cap:            5
Num classes:          14
Question templates:   31
AMP:                  True
Image size:           128
Batch size:           64
Eval batch:           64
Epochs:               50
LR:                   0.0003
Weight decay:         0.0001
Patience:             8
Min delta:            0.001
KD alpha:             0.0
KD temp:              0.0

Model summary
================================================================================
Class:             TDMXSVQA
Total params:      8,982
Trainable params:  8,982
FP32 param size:   0.03 MB
Int8 param size:   8.8 KB
Student variant:   tdm_xs
Image block type:  dsconv
Image channels:    (8, 16, 24, 32, 48)
Image feature dim: 48
Template encoder:  one_hot + Linear
Template input dim:31
Template emb dim:  8
Fusion hidden dim: 64
Fusion layers:     1
Num classes:       14
Head type:         single edge_global


================================================================================
Epoch 1/50
================================================================================
Epoch 001 | step 0001/0093 | loss=2.6905 | ce=2.6905 | kd=0.0000 | acc=0.0156 | binary=0.000 | condition=0.000 | count=0.000 | density=0.500 | time=9.8s
Epoch 001 | step 0005/0093 | loss=2.6727 | ce=2.6727 | kd=0.0000 | acc=0.0312 | binary=0.000 | condition=0.000 | count=0.056 | density=0.207 | time=10.0s
Epoch 001 | step 0010/0093 | loss=2.6574 | ce=2.6574 | kd=0.0000 | acc=0.0422 | binary=0.000 | condition=0.000 | count=0.078 | density=0.276 | time=11.1s
Epoch 001 | step 0015/0093 | loss=2.6441 | ce=2.6441 | kd=0.0000 | acc=0.0531 | binary=0.034 | condition=0.000 | count=0.068 | density=0.277 | time=11.9s
Epoch 001 | step 0020/0093 | loss=2.6312 | ce=2.6312 | kd=0.0000 | acc=0.0773 | binary=0.098 | condition=0.000 | count=0.065 | density=0.233 | time=12.7s
Epoch 001 | step 0025/0093 | loss=2.6207 | ce=2.6207 | kd=0.0000 | acc=0.0975 | binary=0.159 | condition=0.000 | count=0.053 | density=0.192 | time=13.3s
Epoch 001 | step 0030/0093 | loss=2.6072 | ce=2.6072 | kd=0.0000 | acc=0.1250 | binary=0.229 | condition=0.000 | count=0.048 | density=0.166 | time=14.0s
Epoch 001 | step 0035/0093 | loss=2.5940 | ce=2.5940 | kd=0.0000 | acc=0.1424 | binary=0.275 | condition=0.000 | count=0.042 | density=0.139 | time=14.5s
Epoch 001 | step 0040/0093 | loss=2.5822 | ce=2.5822 | kd=0.0000 | acc=0.1539 | binary=0.305 | condition=0.000 | count=0.037 | density=0.122 | time=15.2s
Epoch 001 | step 0045/0093 | loss=2.5685 | ce=2.5685 | kd=0.0000 | acc=0.1656 | binary=0.333 | condition=0.000 | count=0.032 | density=0.109 | time=15.8s
Epoch 001 | step 0050/0093 | loss=2.5573 | ce=2.5573 | kd=0.0000 | acc=0.1688 | binary=0.346 | condition=0.000 | count=0.029 | density=0.096 | time=16.4s
Epoch 001 | step 0055/0093 | loss=2.5434 | ce=2.5434 | kd=0.0000 | acc=0.1756 | binary=0.366 | condition=0.000 | count=0.026 | density=0.087 | time=16.9s
Epoch 001 | step 0060/0093 | loss=2.5306 | ce=2.5306 | kd=0.0000 | acc=0.1797 | binary=0.379 | condition=0.000 | count=0.024 | density=0.080 | time=17.6s
Epoch 001 | step 0065/0093 | loss=2.5166 | ce=2.5166 | kd=0.0000 | acc=0.1839 | binary=0.390 | condition=0.000 | count=0.022 | density=0.072 | time=18.2s
Epoch 001 | step 0070/0093 | loss=2.5028 | ce=2.5028 | kd=0.0000 | acc=0.1862 | binary=0.396 | condition=0.000 | count=0.021 | density=0.068 | time=18.9s
Epoch 001 | step 0075/0093 | loss=2.4868 | ce=2.4868 | kd=0.0000 | acc=0.1904 | binary=0.408 | condition=0.000 | count=0.019 | density=0.063 | time=19.4s
Epoch 001 | step 0080/0093 | loss=2.4704 | ce=2.4704 | kd=0.0000 | acc=0.1941 | binary=0.415 | condition=0.000 | count=0.018 | density=0.060 | time=20.0s
Epoch 001 | step 0085/0093 | loss=2.4565 | ce=2.4565 | kd=0.0000 | acc=0.1956 | binary=0.418 | condition=0.000 | count=0.017 | density=0.056 | time=20.5s
Epoch 001 | step 0090/0093 | loss=2.4439 | ce=2.4439 | kd=0.0000 | acc=0.1970 | binary=0.422 | condition=0.000 | count=0.016 | density=0.053 | time=21.1s
Epoch 001 | step 0093/0093 | loss=2.4385 | ce=2.4385 | kd=0.0000 | acc=0.1980 | binary=0.424 | condition=0.001 | count=0.016 | density=0.052 | time=28.6s

train overall: acc=0.1980 (1168/5898)
train macro acc: 0.0743
train count exact: acc=0.0158 (19/1204)
train count ±1: acc=0.0382 (46/1204)
train by edge head:
  binary       acc=0.4244 (1118/2634)
  condition    acc=0.0007 (1/1480)
  count        acc=0.0158 (19/1204)
  density      acc=0.0517 (30/580)
train by question type:
  Building_Condition_Recognition           acc=0.3655 (212/580)
  Complex_Counting                         acc=0.0160 (10/624)
  Density_Estimation                       acc=0.0517 (30/580)
  Entire_Image_Condition_Recognition       acc=0.2023 (276/1364)
  Risk_Assessment                          acc=0.6431 (373/580)
  Road_Condition_Recognition               acc=0.1623 (258/1590)
  Simple_Counting                          acc=0.0155 (9/580)

valid overall: acc=0.2481 (448/1806)
valid macro acc: 0.0714
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.5504 (448/814)
  condition    acc=0.0000 (0/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.4489 (79/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.2906 (120/413)
  Risk_Assessment                          acc=0.7784 (137/176)
  Road_Condition_Recognition               acc=0.2249 (112/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 1 done | train_acc=0.1980 | valid_acc=0.2481 | best_valid_acc=0.2481 at epoch 1 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 2/50
================================================================================
Epoch 002 | step 0001/0093 | loss=2.1190 | ce=2.1190 | kd=0.0000 | acc=0.2656 | binary=0.567 | condition=0.000 | count=0.000 | density=0.000 | time=0.3s
Epoch 002 | step 0005/0093 | loss=2.0975 | ce=2.0975 | kd=0.0000 | acc=0.2562 | binary=0.491 | condition=0.013 | count=0.000 | density=0.000 | time=0.8s
Epoch 002 | step 0010/0093 | loss=2.1521 | ce=2.1521 | kd=0.0000 | acc=0.2297 | binary=0.475 | condition=0.020 | count=0.000 | density=0.000 | time=1.3s
Epoch 002 | step 0015/0093 | loss=2.1429 | ce=2.1429 | kd=0.0000 | acc=0.2344 | binary=0.486 | condition=0.028 | count=0.000 | density=0.000 | time=2.0s
Epoch 002 | step 0020/0093 | loss=2.1378 | ce=2.1378 | kd=0.0000 | acc=0.2375 | binary=0.496 | condition=0.042 | count=0.000 | density=0.000 | time=2.6s
Epoch 002 | step 0025/0093 | loss=2.1377 | ce=2.1377 | kd=0.0000 | acc=0.2469 | binary=0.510 | condition=0.059 | count=0.000 | density=0.000 | time=3.2s
Epoch 002 | step 0030/0093 | loss=2.1353 | ce=2.1353 | kd=0.0000 | acc=0.2526 | binary=0.511 | condition=0.072 | count=0.000 | density=0.000 | time=3.8s
Epoch 002 | step 0035/0093 | loss=2.1359 | ce=2.1359 | kd=0.0000 | acc=0.2518 | binary=0.512 | condition=0.082 | count=0.000 | density=0.000 | time=4.4s
Epoch 002 | step 0040/0093 | loss=2.1308 | ce=2.1308 | kd=0.0000 | acc=0.2539 | binary=0.509 | condition=0.101 | count=0.000 | density=0.000 | time=5.1s
Epoch 002 | step 0045/0093 | loss=2.1238 | ce=2.1238 | kd=0.0000 | acc=0.2590 | binary=0.508 | condition=0.119 | count=0.000 | density=0.000 | time=6.0s
Epoch 002 | step 0050/0093 | loss=2.1124 | ce=2.1124 | kd=0.0000 | acc=0.2656 | binary=0.506 | condition=0.142 | count=0.000 | density=0.000 | time=6.9s
Epoch 002 | step 0055/0093 | loss=2.1111 | ce=2.1111 | kd=0.0000 | acc=0.2699 | binary=0.503 | condition=0.163 | count=0.000 | density=0.000 | time=8.0s
Epoch 002 | step 0060/0093 | loss=2.1071 | ce=2.1071 | kd=0.0000 | acc=0.2786 | binary=0.509 | condition=0.188 | count=0.000 | density=0.000 | time=9.0s
Epoch 002 | step 0065/0093 | loss=2.1060 | ce=2.1060 | kd=0.0000 | acc=0.2812 | binary=0.506 | condition=0.208 | count=0.000 | density=0.000 | time=9.9s
Epoch 002 | step 0070/0093 | loss=2.1061 | ce=2.1061 | kd=0.0000 | acc=0.2857 | binary=0.505 | condition=0.230 | count=0.000 | density=0.000 | time=10.4s
Epoch 002 | step 0075/0093 | loss=2.1093 | ce=2.1093 | kd=0.0000 | acc=0.2873 | binary=0.503 | condition=0.246 | count=0.000 | density=0.000 | time=11.1s
Epoch 002 | step 0080/0093 | loss=2.1104 | ce=2.1104 | kd=0.0000 | acc=0.2906 | binary=0.499 | condition=0.269 | count=0.000 | density=0.000 | time=11.7s
Epoch 002 | step 0085/0093 | loss=2.1091 | ce=2.1091 | kd=0.0000 | acc=0.2947 | binary=0.497 | condition=0.291 | count=0.000 | density=0.000 | time=12.3s
Epoch 002 | step 0090/0093 | loss=2.1049 | ce=2.1049 | kd=0.0000 | acc=0.2972 | binary=0.490 | condition=0.312 | count=0.000 | density=0.000 | time=12.9s
Epoch 002 | step 0093/0093 | loss=2.1033 | ce=2.1033 | kd=0.0000 | acc=0.2976 | binary=0.487 | condition=0.320 | count=0.000 | density=0.000 | time=13.1s

train overall: acc=0.2976 (1755/5898)
train macro acc: 0.0940
train count exact: acc=0.0000 (0/1204)
train count ±1: acc=0.0000 (0/1204)
train by edge head:
  binary       acc=0.4867 (1282/2634)
  condition    acc=0.3196 (473/1480)
  count        acc=0.0000 (0/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.4552 (264/580)
  Complex_Counting                         acc=0.0000 (0/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.4208 (574/1364)
  Risk_Assessment                          acc=0.7379 (428/580)
  Road_Condition_Recognition               acc=0.3075 (489/1590)
  Simple_Counting                          acc=0.0000 (0/580)

valid overall: acc=0.3671 (663/1806)
valid macro acc: 0.1182
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.4128 (336/814)
  condition    acc=0.7283 (327/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.4659 (82/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.5424 (224/413)
  Risk_Assessment                          acc=0.7159 (126/176)
  Road_Condition_Recognition               acc=0.4639 (231/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 2 done | train_acc=0.2976 | valid_acc=0.3671 | best_valid_acc=0.3671 at epoch 2 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 3/50
================================================================================
Epoch 003 | step 0001/0093 | loss=1.9725 | ce=1.9725 | kd=0.0000 | acc=0.4375 | binary=0.483 | condition=0.875 | count=0.000 | density=0.000 | time=0.3s
Epoch 003 | step 0005/0093 | loss=1.9602 | ce=1.9602 | kd=0.0000 | acc=0.3719 | binary=0.406 | condition=0.794 | count=0.000 | density=0.000 | time=0.8s
Epoch 003 | step 0010/0093 | loss=1.9445 | ce=1.9445 | kd=0.0000 | acc=0.3937 | binary=0.423 | condition=0.741 | count=0.000 | density=0.000 | time=1.3s
Epoch 003 | step 0015/0093 | loss=2.0032 | ce=2.0032 | kd=0.0000 | acc=0.3708 | binary=0.415 | condition=0.703 | count=0.000 | density=0.000 | time=2.0s
Epoch 003 | step 0020/0093 | loss=2.0389 | ce=2.0389 | kd=0.0000 | acc=0.3672 | binary=0.437 | condition=0.678 | count=0.000 | density=0.000 | time=2.5s
Epoch 003 | step 0025/0093 | loss=2.0142 | ce=2.0142 | kd=0.0000 | acc=0.3731 | binary=0.436 | condition=0.686 | count=0.000 | density=0.000 | time=3.1s
Epoch 003 | step 0030/0093 | loss=2.0115 | ce=2.0115 | kd=0.0000 | acc=0.3771 | binary=0.438 | condition=0.690 | count=0.000 | density=0.000 | time=3.9s
Epoch 003 | step 0035/0093 | loss=2.0206 | ce=2.0206 | kd=0.0000 | acc=0.3741 | binary=0.433 | condition=0.692 | count=0.000 | density=0.000 | time=5.0s
Epoch 003 | step 0040/0093 | loss=2.0255 | ce=2.0255 | kd=0.0000 | acc=0.3727 | binary=0.430 | condition=0.698 | count=0.000 | density=0.000 | time=5.8s
Epoch 003 | step 0045/0093 | loss=2.0219 | ce=2.0219 | kd=0.0000 | acc=0.3712 | binary=0.428 | condition=0.705 | count=0.000 | density=0.000 | time=6.8s
Epoch 003 | step 0050/0093 | loss=2.0197 | ce=2.0197 | kd=0.0000 | acc=0.3700 | binary=0.430 | condition=0.698 | count=0.000 | density=0.000 | time=7.9s
Epoch 003 | step 0055/0093 | loss=2.0218 | ce=2.0218 | kd=0.0000 | acc=0.3716 | binary=0.434 | condition=0.701 | count=0.000 | density=0.000 | time=8.6s
Epoch 003 | step 0060/0093 | loss=2.0246 | ce=2.0246 | kd=0.0000 | acc=0.3716 | binary=0.439 | condition=0.696 | count=0.000 | density=0.000 | time=9.3s
Epoch 003 | step 0065/0093 | loss=2.0164 | ce=2.0164 | kd=0.0000 | acc=0.3700 | binary=0.435 | condition=0.687 | count=0.000 | density=0.000 | time=9.8s
Epoch 003 | step 0070/0093 | loss=2.0202 | ce=2.0202 | kd=0.0000 | acc=0.3679 | binary=0.439 | condition=0.683 | count=0.000 | density=0.000 | time=10.5s
Epoch 003 | step 0075/0093 | loss=2.0142 | ce=2.0142 | kd=0.0000 | acc=0.3692 | binary=0.441 | condition=0.683 | count=0.000 | density=0.000 | time=11.1s
Epoch 003 | step 0080/0093 | loss=2.0116 | ce=2.0116 | kd=0.0000 | acc=0.3719 | binary=0.446 | condition=0.686 | count=0.000 | density=0.000 | time=11.8s
Epoch 003 | step 0085/0093 | loss=2.0074 | ce=2.0074 | kd=0.0000 | acc=0.3732 | binary=0.446 | condition=0.689 | count=0.000 | density=0.000 | time=12.3s
Epoch 003 | step 0090/0093 | loss=2.0060 | ce=2.0060 | kd=0.0000 | acc=0.3727 | binary=0.444 | condition=0.692 | count=0.000 | density=0.000 | time=12.9s
Epoch 003 | step 0093/0093 | loss=2.0082 | ce=2.0082 | kd=0.0000 | acc=0.3723 | binary=0.445 | condition=0.692 | count=0.000 | density=0.000 | time=13.1s

train overall: acc=0.3723 (2196/5898)
train macro acc: 0.1198
train count exact: acc=0.0000 (0/1204)
train count ±1: acc=0.0000 (0/1204)
train by edge head:
  binary       acc=0.4450 (1172/2634)
  condition    acc=0.6919 (1024/1480)
  count        acc=0.0000 (0/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.5017 (291/580)
  Complex_Counting                         acc=0.0000 (0/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.5587 (762/1364)
  Risk_Assessment                          acc=0.6414 (372/580)
  Road_Condition_Recognition               acc=0.4849 (771/1590)
  Simple_Counting                          acc=0.0000 (0/580)

valid overall: acc=0.4131 (746/1806)
valid macro acc: 0.1324
valid count exact: acc=0.0000 (0/367)
valid count ±1: acc=0.0000 (0/367)
valid by edge head:
  binary       acc=0.4914 (400/814)
  condition    acc=0.7706 (346/449)
  count        acc=0.0000 (0/367)
  density      acc=0.0000 (0/176)
valid by question type:
  Building_Condition_Recognition           acc=0.5739 (101/176)
  Complex_Counting                         acc=0.0000 (0/191)
  Density_Estimation                       acc=0.0000 (0/176)
  Entire_Image_Condition_Recognition       acc=0.5981 (247/413)
  Risk_Assessment                          acc=0.7102 (125/176)
  Road_Condition_Recognition               acc=0.5482 (273/498)
  Simple_Counting                          acc=0.0000 (0/176)

Epoch 3 done | train_acc=0.3723 | valid_acc=0.4131 | best_valid_acc=0.4131 at epoch 3 | no_improve=0/8 | IMPROVED

================================================================================
Epoch 4/50
================================================================================
Epoch 004 | step 0001/0093 | loss=1.8374 | ce=1.8374 | kd=0.0000 | acc=0.4375 | binary=0.516 | condition=0.706 | count=0.000 | density=0.000 | time=0.3s
Epoch 004 | step 0005/0093 | loss=1.9472 | ce=1.9472 | kd=0.0000 | acc=0.3969 | binary=0.465 | condition=0.735 | count=0.000 | density=0.000 | time=0.7s
Epoch 004 | step 0010/0093 | loss=1.9492 | ce=1.9492 | kd=0.0000 | acc=0.4047 | binary=0.486 | condition=0.739 | count=0.000 | density=0.000 | time=1.3s
Epoch 004 | step 0015/0093 | loss=1.9139 | ce=1.9139 | kd=0.0000 | acc=0.4104 | binary=0.476 | condition=0.756 | count=0.000 | density=0.000 | time=1.9s
Epoch 004 | step 0020/0093 | loss=1.9107 | ce=1.9107 | kd=0.0000 | acc=0.4156 | binary=0.482 | condition=0.766 | count=0.000 | density=0.000 | time=2.7s
Epoch 004 | step 0025/0093 | loss=1.9148 | ce=1.9148 | kd=0.0000 | acc=0.4113 | binary=0.484 | condition=0.752 | count=0.000 | density=0.000 | time=3.7s
Epoch 004 | step 0030/0093 | loss=1.9143 | ce=1.9143 | kd=0.0000 | acc=0.4135 | binary=0.489 | condition=0.757 | count=0.000 | density=0.000 | time=4.6s
Epoch 004 | step 0035/0093 | loss=1.9174 | ce=1.9174 | kd=0.0000 | acc=0.4188 | binary=0.500 | condition=0.765 | count=0.000 | density=0.000 | time=5.7s
Epoch 004 | step 0040/0093 | loss=1.9271 | ce=1.9271 | kd=0.0000 | acc=0.4230 | binary=0.517 | condition=0.763 | count=0.000 | density=0.000 | time=6.8s
Epoch 004 | step 0045/0093 | loss=1.9221 | ce=1.9221 | kd=0.0000 | acc=0.4281 | binary=0.529 | condition=0.757 | count=0.000 | density=0.000 | time=7.5s
Epoch 004 | step 0050/0093 | loss=1.9136 | ce=1.9136 | kd=0.0000 | acc=0.4331 | binary=0.534 | condition=0.765 | count=0.002 | density=0.000 | time=8.2s
Epoch 004 | step 0055/0093 | loss=1.9071 | ce=1.9071 | kd=0.0000 | acc=0.4372 | binary=0.538 | condition=0.775 | count=0.001 | density=0.000 | time=8.7s
Epoch 004 | step 0060/0093 | loss=1.9060 | ce=1.9060 | kd=0.0000 | acc=0.4396 | binary=0.539 | condition=0.782 | count=0.004 | density=0.000 | time=9.4s
Epoch 004 | step 0065/0093 | loss=1.9030 | ce=1.9030 | kd=0.0000 | acc=0.4377 | binary=0.535 | condition=0.777 | count=0.007 | density=0.000 | time=9.9s
Epoch 004 | step 0070/0093 | loss=1.8995 | ce=1.8995 | kd=0.0000 | acc=0.4382 | binary=0.534 | condition=0.784 | count=0.008 | density=0.000 | time=10.6s
Epoch 004 | step 0075/0093 | loss=1.8928 | ce=1.8928 | kd=0.0000 | acc=0.4387 | binary=0.534 | condition=0.787 | count=0.010 | density=0.000 | time=11.1s
Epoch 004 | step 0080/0093 | loss=1.8920 | ce=1.8920 | kd=0.0000 | acc=0.4381 | binary=0.533 | condition=0.784 | count=0.012 | density=0.000 | time=11.8s
Epoch 004 | step 0085/0093 | loss=1.8870 | ce=1.8870 | kd=0.0000 | acc=0.4408 | binary=0.538 | condition=0.782 | count=0.016 | density=0.000 | time=12.3s
Epoch 004 | step 0090/0093 | loss=1.8797 | ce=1.8797 | kd=0.0000 | acc=0.4448 | binary=0.544 | condition=0.785 | count=0.018 | density=0.000 | time=13.0s
Epoch 004 | step 0093/0093 | loss=1.8805 | ce=1.8805 | kd=0.0000 | acc=0.4442 | binary=0.545 | condition=0.786 | count=0.018 | density=0.000 | time=13.1s

train overall: acc=0.4442 (2620/5898)
train macro acc: 0.1462
train count exact: acc=0.0183 (22/1204)
train count ±1: acc=0.0183 (22/1204)
train by edge head:
  binary       acc=0.5448 (1435/2634)
  condition    acc=0.7858 (1163/1480)
  count        acc=0.0183 (22/1204)
  density      acc=0.0000 (0/580)
train by question type:
  Building_Condition_Recognition           acc=0.6034 (350/580)
  Complex_Counting                         acc=0.0144 (9/624)
  Density_Estimation                       acc=0.0000 (0/580)
  Entire_Image_Condition_Recognition       acc=0.6518 (889/1364)
  Risk_Assessment                          acc=0.7552 (438/580)

In [ ]:
%cd /content/TinyDisasterVQA

import json
import pandas as pd
from pathlib import Path

R_DIR = Path("/content/drive/MyDrive/TinyDisasterVQA/StudentResolutionAblation_R1_R3")
BASELINE_DIR = Path("/content/drive/MyDrive/TinyDisasterVQA/StudentAblation_S1_S10")

summary_paths = list(R_DIR.glob("*/final_summary.json"))

# Optional: include 224 baselines for direct comparison
baseline_keep = ["S1_tdm_s_ce", "S4_tdm_fast_ce"]
for p in BASELINE_DIR.glob("*/final_summary.json"):
    if any(p.parent.name.startswith(prefix) for prefix in baseline_keep):
        summary_paths.append(p)

rows = []

for path in summary_paths:
    with open(path, "r") as f:
        s = json.load(f)

    rows.append({
        "run_name": path.parent.name,
        "student_variant": s.get("student_variant"),
        "image_size": s.get("image_size"),
        "mode": s.get("mode"),
        "best_valid_acc": s.get("best_valid_acc"),
        "test_acc": s.get("test_acc"),
        "test_macro_acc": s.get("test_macro_accuracy"),
        "test_count_acc": s.get("test_count_exact"),
        "test_count_pm1": s.get("test_count_pm1"),
        "test_binary_acc": s.get("test_binary_acc"),
        "test_condition_acc": s.get("test_condition_acc"),
        "test_density_acc": s.get("test_density_acc"),
        "total_params": s.get("total_params"),
        "best_epoch": s.get("best_epoch"),
    })

df = pd.DataFrame(rows)

df = df.sort_values(
    by=["test_acc", "test_macro_acc", "test_count_acc"],
    ascending=False,
).reset_index(drop=True)

display(df)

out_path = R_DIR / "resolution_ablation_summary_with_224_baselines.csv"
df.to_csv(out_path, index=False)
print(f"Saved: {out_path}")

/content/TinyDisasterVQA

,run_name,student_variant,image_size,mode,best_valid_acc,test_acc,test_macro_acc,test_count_acc,test_count_pm1,test_binary_acc,test_condition_acc,test_density_acc,total_params,best_epoch
0,S4_tdm_fast_ce_20260610_092129,tdm_fast,224,ce,0.879291,0.852155,0.603659,0.543081,0.762402,0.962195,0.973154,0.710383,91902,41
1,R1_tdm_fast_128_ce_20260610_111228,tdm_fast,128,ce,0.865449,0.850518,0.591509,0.530026,0.751958,0.964634,0.975391,0.704918,91902,28
2,S1_tdm_s_ce_20260610_085317,tdm_s,224,ce,0.855482,0.845608,0.584631,0.503916,0.741514,0.965854,0.977629,0.699454,25814,26
3,R2_tdm_s_128_ce_20260610_112222,tdm_s,128,ce,0.839424,0.826514,0.549457,0.443864,0.684073,0.963415,0.979866,0.639344,25814,36
4,R3_tdm_xs_128_ce_20260610_113433,tdm_xs,128,ce,0.827796,0.806328,0.516657,0.415144,0.629243,0.954878,0.961969,0.579235,8982,27

Saved: /content/drive/MyDrive/TinyDisasterVQA/StudentResolutionAblation_R1_R3/resolution_ablation_summary_with_224_baselines.csv